import { BarChart3, CheckSquare, Gauge, Sparkles, Table2 } from 'lucide-react';
import React, { useMemo, useState } from 'react';
import { StandardArtifactShell } from '@/components/standard/StandardArtifactShell';
import type { StandardSekcjaDef } from '@/components/standard/StandardArtifactShell.types';
import { resolveBusinessDisplayLabel } from '@/components/shared/PreviewPane/businessDisplayLabel';

type Range={knowledgeState:string;base:number|null};
export interface CapacityCardScenario {scenarioId:string;name?:string|null;status:'DRAFT'|'PUBLISHED'|'SUPERSEDED';scenarioVersion:number;planScenarioId:string;planScenarioVersion:number;periods:Array<{periodId:string;demand:Range;supply:Range}>;proposedAssignments:Array<{resourceOrRoleId:string;periodIds:string[];rationale:string}>;constraints:Array<{detail:string;state:string}>;publishedAt:string|null}
export const countCapacityGaps=(scenario:CapacityCardScenario)=>scenario.periods.filter(p=>p.demand.base!==null&&p.supply.base!==null&&p.demand.base>p.supply.base).length;

export function CapacityAnalysisCard({scenario,noPressure=false,onBack,onAnalyze,onPublish}:{scenario:CapacityCardScenario;noPressure?:boolean;onBack:()=>void;onAnalyze:()=>void;onPublish:()=>void}){
 const [section,setSection]=useState('source'); const title=resolveBusinessDisplayLabel({displayName:scenario.name,rawId:scenario.scenarioId,fallback:'Analiza bez nazwy'}); const gaps=countCapacityGaps(scenario); const roles=useMemo(()=>[...new Set(scenario.proposedAssignments.map(a=>a.resourceOrRoleId))],[scenario]); const box='rounded-xl border border-c-border-subtle bg-c-surface p-4';
 const sections:StandardSekcjaDef[]=[
  {id:'source',icon:CheckSquare,label:{pl:'Plan źródłowy',en:'Source plan'},component:<div className={box}>Plan źródłowy · v{scenario.planScenarioVersion}</div>,aiContract:{none:true,reason:'Źródłem jest opublikowany plan.'}},
  {id:'worksheet',icon:Table2,label:{pl:'Arkusz obciążenia',en:'Load worksheet'},component:<div className={box}>{scenario.periods.map(p=><div key={p.periodId} className="grid grid-cols-3 border-b border-c-border-subtle py-2"><b>{p.periodId}</b><span>Popyt: {p.demand.base??'Nieznane'}</span><span>Podaż: {p.supply.base??'Nieznane'}</span></div>)}</div>,aiContract:{none:true,reason:'Arkusz pokazuje zapisane dane.'}},
  {id:'pressure',icon:Gauge,label:{pl:'Luki i presja',en:'Gaps and pressure'},component:<div className={box}>{gaps?`Okresy z luką: ${gaps}`:'Brak wykrytych luk'} · Role: {roles.length||'Nieznane'}</div>,aiContract:{none:true,reason:'Luki liczy ta sama reguła co doradca.'}},
  {id:'proposals',icon:Sparkles,label:{pl:'Propozycje zmian',en:'Change proposals'},component:<div className={box}>{noPressure?'Brak przeciążeń do rozwiązania':'Uruchom „Pracuj z AI”, aby otrzymać warianty: przesuń kolejność, podziel zakres lub dołóż moce.'}</div>,aiContract:{none:true,reason:'Propozycje tworzy istniejący capacityOptionsAdvisor.'}},
  {id:'decisions',icon:BarChart3,label:{pl:'Decyzje',en:'Decisions'},component:<div className={box}>{scenario.status==='DRAFT'?<button className="rounded-lg border border-c-border px-3 py-2 focus-visible:ring-2 focus-visible:ring-c-focus" onClick={onPublish}>Opublikuj analizę</button>:`Opublikowano ${scenario.publishedAt??''}`}</div>,aiContract:{none:true,reason:'Decyzję podejmuje człowiek.'}},
 ];
 const right={actions:{label:'Akcje',children:<button className="rounded-lg border border-c-border px-3 py-2" onClick={onBack}>Wróć do listy</button>,actionIds:['back']},properties:{label:'Właściwości',children:<div className="text-sm">Okresy: {scenario.periods.length} · Role: {roles.length} · Luki: {gaps}</div>},relations:{pominieta:true as const,reason:'Plan źródłowy jest osobną sekcją.'},comments:{pominieta:true as const,reason:'Brak mechanizmu komentarzy dla analizy.'},history:{label:'Historia',children:<div>Wersja {scenario.scenarioVersion}</div>}};
 const ai=[{id:'analyze',label:{pl:'Analizuj',en:'Analyze'},icon:Sparkles,variant:'ai' as const,onClick:onAnalyze},{id:'fill-section',label:{pl:'Uzupełnij tę sekcję',en:'Complete this section'},icon:Sparkles,variant:'ai' as const,onClick:onAnalyze},{id:'fill-document',label:{pl:'Uzupełnij cały dokument',en:'Complete document'},icon:Sparkles,variant:'ai' as const,onClick:onAnalyze}];
 return <StandardArtifactShell karta="capacity_analysis" klasa="L" header={{title,onTitleChange:()=>undefined,titleReadOnly:true,artifactType:'document' as any,artifactId:scenario.scenarioId,onSave:()=>undefined,saveState:'saved',onClose:onBack,statusLabel:scenario.status==='DRAFT'?'Szkic':scenario.status==='PUBLISHED'?'Opublikowany':'Zastąpiony',statusTone:scenario.status==='PUBLISHED'?'approved':'draft'}} primaryAction={{intentionallyNone:true,reason:'Publikacja jest w sekcji Decyzje.'}} sections={sections} rightPanel={right} activeSection={section} onSectionChange={setSection} densityMode="n" onDensityModeChange={()=>undefined} toolAIActions={ai} panelAriaLabel="Szczegóły analizy obciążenia"/>;
}
