import React, { useMemo, useState } from 'react';
import { ArtifactPropertiesTable } from '@/components/standard/ArtifactPropertiesTable';
import { DocumentCardMenu5 } from '@/components/standard/DocumentCardMenu5';
import { StandardArtifactShell } from '@/components/standard/StandardArtifactShell';
import type { StandardSekcjaDef } from '@/components/standard/StandardArtifactShell.types';
import { CAPACITY_ANALYSIS_CARD_CONTRACT } from '@/components/standard/documentCardContracts';
import { resolveBusinessDisplayLabel } from '@/components/shared/PreviewPane/businessDisplayLabel';

type Range={knowledgeState:string;base:number|null};
export interface CapacityCardScenario {scenarioId:string;name?:string|null;status:'DRAFT'|'PUBLISHED'|'SUPERSEDED';scenarioVersion:number;planScenarioId:string;planScenarioVersion:number;periods:Array<{periodId:string;demand:Range;supply:Range}>;proposedAssignments:Array<{resourceOrRoleId:string;periodIds:string[];rationale:string}>;constraints:Array<{detail:string;state:string}>;publishedAt:string|null}
export const countCapacityGaps=(scenario:CapacityCardScenario)=>scenario.periods.filter(p=>p.demand.base!==null&&p.supply.base!==null&&p.demand.base>p.supply.base).length;

export function CapacityAnalysisCard({scenario,noPressure=false,onBack,onAnalyze,onPublish}:{scenario:CapacityCardScenario;noPressure?:boolean;onBack:()=>void;onAnalyze:()=>void;onPublish:()=>void}){
 const [section,setSection]=useState('source'); const [readMode,setReadMode]=useState(false); const title=resolveBusinessDisplayLabel({displayName:scenario.name,rawId:scenario.scenarioId,fallback:'Analiza bez nazwy'}); const gaps=countCapacityGaps(scenario); const roles=useMemo(()=>[...new Set(scenario.proposedAssignments.map(a=>a.resourceOrRoleId))],[scenario]); const box='rounded-xl border border-c-border-subtle bg-c-surface p-4';
 const content:Record<string,React.ReactNode>={
  source:<div className={box}>Plan źródłowy · v{scenario.planScenarioVersion}</div>,
  worksheet:scenario.periods.length?<div className={box}>{scenario.periods.map(p=><div key={p.periodId} className="grid grid-cols-3 border-b border-c-border-subtle py-2"><b>{p.periodId}</b><span>Popyt: {p.demand.base??'Nieznane'}</span><span>Podaż: {p.supply.base??'Nieznane'}</span></div>)}</div>:null,
  pressure:<div className={box}>{gaps?`Okresy z luką: ${gaps}`:'Brak wykrytych luk'} · Role: {roles.length||'Nieznane'}</div>,
  proposals:<div className={box}>{noPressure?'Brak przeciążeń do rozwiązania':'Uruchom „Pracuj z AI”, aby otrzymać warianty: przesuń kolejność, podziel zakres lub dołóż moce.'}</div>,
  decisions:<div className={box}>{scenario.status==='DRAFT'?<button className="rounded-lg border border-c-border px-3 py-2 focus-visible:ring-2 focus-visible:ring-c-focus" onClick={onPublish}>Opublikuj analizę</button>:`Opublikowano ${scenario.publishedAt?new Intl.DateTimeFormat('pl-PL').format(new Date(scenario.publishedAt)):'—'}`}</div>,
 };
 const sections:StandardSekcjaDef[]=CAPACITY_ANALYSIS_CARD_CONTRACT.flatMap(item=>content[item.id]?[{...item,component:content[item.id],aiContract:{none:true as const,reason:item.aiReason}}]:[]);
 const right={actions:{label:'Akcje',children:<button className="rounded-lg border border-c-border px-3 py-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-c-focus" onClick={onBack}>Wróć do listy</button>,actionIds:['back']},properties:{label:'Właściwości',children:<ArtifactPropertiesTable propertyLabel="Właściwość" valueLabel="Wartość" rows={[{id:'status',label:'Status',value:scenario.status==='DRAFT'?'Szkic':scenario.status==='PUBLISHED'?'Opublikowany':'Zastąpiony'},{id:'periods',label:'Okresy',value:scenario.periods.length,mono:true},{id:'roles',label:'Role',value:roles.length,mono:true},{id:'gaps',label:'Luki',value:gaps,mono:true}]}/>},relations:{label:'Powiązania',children:<p className="text-sm">Plan źródłowy · wersja {scenario.planScenarioVersion}</p>},evidence:scenario.constraints.length?{label:'Źródła i założenia',children:<ul className="list-disc pl-4 text-sm">{scenario.constraints.map(item=><li key={item.detail}>{item.detail}</li>)}</ul>}:{pominieta:true as const,reason:'Brak zapisanych ograniczeń.'},comments:{pominieta:true as const,reason:'Brak mechanizmu komentarzy dla analizy.'},history:{label:'Historia',children:<div>Wersja {scenario.scenarioVersion}</div>}};
 return <StandardArtifactShell karta="capacity_analysis" klasa="L" header={{title,onTitleChange:()=>undefined,titleReadOnly:true,artifactType:'document' as any,artifactId:scenario.scenarioId,onSave:()=>undefined,saveState:'saved',onClose:onBack,statusLabel:scenario.status==='DRAFT'?'Szkic':scenario.status==='PUBLISHED'?'Opublikowany':'Zastąpiony',statusTone:scenario.status==='PUBLISHED'?'approved':'draft'}} primaryAction={{intentionallyNone:true,reason:'Publikacja jest w sekcji Decyzje.'}} sections={sections} rightPanel={right} activeSection={section} onSectionChange={setSection} densityMode="n" onDensityModeChange={()=>undefined} toolbar={<DocumentCardMenu5 sections={sections} activeSection={section} onSectionChange={setSection} readMode={readMode} onReadModeChange={scenario.status==='DRAFT'?setReadMode:undefined} ai={{onAnalizuj:onAnalyze,analizaWToku:false,kontekstArtefaktu:{title,status:scenario.status,type:'capacity_analysis'},moznaEdytowac:scenario.status==='DRAFT'&&!readMode,uzupelnijSekcje:{rodzaj:'wlasnaPropozycja',uruchom:onAnalyze,opis:'Doradca przygotuje propozycje zmian do oceny.'},uzupelnijDokument:{rodzaj:'wlasnaPropozycja',uruchom:onAnalyze,opis:'Doradca przygotuje wariant całej analizy do oceny.'}}}/>} panelAriaLabel="Szczegóły analizy obciążenia"/>;
}
