import { BarChart3, CalendarRange, CheckSquare, GitBranch, ListOrdered, Sparkles, Users } from 'lucide-react';
import React, { useMemo, useState } from 'react';
import { StandardArtifactShell } from '@/components/standard/StandardArtifactShell';
import type { StandardSekcjaDef } from '@/components/standard/StandardArtifactShell.types';
import { resolveBusinessDisplayLabel } from '@/components/shared/PreviewPane/businessDisplayLabel';
import { GeneratorPlanuModal, type PlanGenerationMode } from '../Generator/GeneratorPlanuModal';

export interface PlanCardScenario { scenarioId: string; name?: string|null; status: 'DRAFT'|'PUBLISHED'|'SUPERSEDED'; scenarioVersion:number; portfolioScenarioId:string; portfolioScenarioVersion:number; windowUnit:string; timezone:string; periods:Array<{periodId:string;start:string;end:string}>; windows:Array<{initiativeId:string;target:string|null;rationale:string;dependencySnapshot:string[];constraintSnapshot:Array<{detail:string}>}>; assumptions:string[]; updatedBy:string; publishedBy:string|null; publishedAt:string|null }

export function PlanCard({ scenario, initiatives, proposal, busy, onBack, onAnalyze, onReview, onPublish }: { scenario: PlanCardScenario; initiatives:Array<{id:string;name:string;lifecycle?:string}>; proposal?:{conflicts:string[];changes:unknown[];status:string}|null; busy?:boolean; onBack:()=>void; onAnalyze:(mode:PlanGenerationMode)=>void; onReview:(outcome:'ACCEPT'|'REJECT')=>void; onPublish:()=>void }) {
  const [section, setSection] = useState('horizon'); const [generator, setGenerator] = useState(false);
  const title = resolveBusinessDisplayLabel({displayName:scenario.name,rawId:scenario.scenarioId,fallback:'Plan bez nazwy'});
  const names = useMemo(() => new Map(initiatives.map((item)=>[item.id,item.name])),[initiatives]);
  const capacityConstraints = useMemo(
    () => [...new Set(scenario.windows.flatMap((window) => window.constraintSnapshot.map((constraint) => constraint.detail)).filter((detail) => detail.trim()))],
    [scenario.windows]
  );
  const box='rounded-xl border border-c-border-subtle bg-c-surface p-4';
  const sections: StandardSekcjaDef[] = [
    {id:'horizon',icon:CalendarRange,label:{pl:'Horyzont',en:'Horizon'},component:<div className={box}><p>{scenario.windowUnit} · {scenario.timezone}</p><ul>{scenario.periods.map(p=><li key={p.periodId}>{p.periodId}: {p.start.slice(0,10)} – {p.end.slice(0,10)}</li>)}</ul></div>,aiContract:{none:true,reason:'Horyzont jest edytowany przez człowieka w generatorze.'}},
    {id:'scope',icon:CheckSquare,label:{pl:'Zakres inicjatyw',en:'Initiative scope'},component:<div className={box}>{initiatives.map(i=><p key={i.id}>{i.name} · {i.lifecycle==='EXECUTING'?'W realizacji':i.lifecycle==='SCHEDULED'?'Zaplanowana':i.lifecycle==='DRAFT'?'Szkic':'Nieznane'}</p>)}</div>,aiContract:{none:true,reason:'Zakres wybiera człowiek.'}},
    {id:'windows',icon:ListOrdered,label:{pl:'Kolejność i okna',en:'Sequence and windows'},component:<div className={box}>{scenario.windows.map((w,index)=><div key={w.initiativeId} className="border-b border-c-border-subtle py-2"><b>{index+1}. {names.get(w.initiativeId)??'Inicjatywa'}</b><p>{w.target?.slice(0,10)??'Nieznane'} · {w.rationale}</p></div>)}</div>,aiContract:{none:true,reason:'Propozycję tworzy istniejący solver planu.'}},
    {id:'dependencies',icon:GitBranch,label:{pl:'Zależności i konflikty',en:'Dependencies and conflicts'},component:<div className={box}>{proposal?.conflicts.length?proposal.conflicts.map(c=><p key={c}>{c}</p>):'Brak wykrytych konfliktów'}</div>,aiContract:{none:true,reason:'Konflikty są wynikiem deterministycznego solvera.'}},
    {id:'capacity',icon:Users,label:{pl:'Obciążenie ról',en:'Role load'},component:<div className={box}>{capacityConstraints.length?<ul>{capacityConstraints.map((detail)=><li key={detail}>{detail}</li>)}</ul>:'Nieznane — brak zapisanych ograniczeń obciążenia'}</div>,aiContract:{none:true,reason:'Podaż jest ręczna i pochodzi z analizy obciążenia.'}},
    {id:'decisions',icon:BarChart3,label:{pl:'Decyzje',en:'Decisions'},component:<div className={box}><p>{scenario.publishedAt?`Opublikowano ${scenario.publishedAt}`:'Plan pozostaje szkicem.'}</p>{scenario.status==='DRAFT'&&<button className="mt-2 rounded-lg border border-c-border px-3 py-2 focus-visible:ring-2 focus-visible:ring-c-focus" onClick={onPublish}>Opublikuj plan</button>}</div>,aiContract:{none:true,reason:'Decyzję publikacji podejmuje człowiek.'}},
  ];
  const rightPanel={actions:{label:'Akcje',children:<button className="rounded-lg border border-c-border px-3 py-2" onClick={onBack}>Wróć do listy</button>,actionIds:['back']},properties:{label:'Właściwości',children:<div className="text-sm">Portfel źródłowy · v{scenario.portfolioScenarioVersion}</div>},relations:{pominieta:true as const,reason:'Powiązania są opisane w sekcjach karty.'},comments:{pominieta:true as const,reason:'Plan nie ma osobnego wątku komentarzy.'},history:{label:'Historia',children:<div className="text-sm">Wersja {scenario.scenarioVersion}</div>}};
  const ai=[{id:'analyze',label:{pl:'Analizuj',en:'Analyze'},icon:Sparkles,variant:'ai' as const,onClick:()=>onAnalyze('DEPENDENCIES')},{id:'fill-section',label:{pl:'Uzupełnij tę sekcję',en:'Complete this section'},icon:Sparkles,variant:'ai' as const,onClick:()=>onAnalyze('MIXED')},{id:'fill-document',label:{pl:'Uzupełnij cały dokument',en:'Complete document'},icon:Sparkles,variant:'ai' as const,onClick:()=>setGenerator(true)}];
  return <StandardArtifactShell karta="plan" klasa="L" header={{title,onTitleChange:()=>undefined,titleReadOnly:true,artifactType:'document' as any,artifactId:scenario.scenarioId,onSave:()=>undefined,saveState:'saved',onClose:onBack,statusLabel:scenario.status==='DRAFT'?'Szkic':scenario.status==='PUBLISHED'?'Opublikowany':'Zastąpiony',statusTone:scenario.status==='PUBLISHED'?'approved':'draft'}} primaryAction={{intentionallyNone:true,reason:'Publikacja jest decyzją w sekcji Decyzje.'}} sections={sections} rightPanel={rightPanel} activeSection={section} onSectionChange={setSection} densityMode="n" onDensityModeChange={()=>undefined} toolAIActions={ai} panelAriaLabel="Szczegóły planu" nakladki={<GeneratorPlanuModal open={generator} initiatives={initiatives} busy={busy} hasProposal={Boolean(proposal)} onClose={()=>setGenerator(false)} onGenerate={(input)=>onAnalyze(input.mode)} onReview={onReview}/>}/>;
}
