/**
 * Mock data for Reports & Presentations module
 * Will be replaced with API calls when backend is ready
 */

import type { PresentationItem, ReportItem, TemplateItem } from './types';

export const MOCK_TEMPLATES: TemplateItem[] = [
  {
    id: 'tmpl-1',
    title: 'Raport R1 — Tygodniowy przegląd realizacji',
    description: 'Standardowy raport tygodniowy z postępem inicjatyw, blokerami i KPI.',
    type: 'report',
    category: 'R1',
    scope: 'application',
    status: 'active',
    updatedAt: '2026-02-26T10:00:00Z',
    createdBy: 'System',
    sectionCount: 6,
  },
  {
    id: 'tmpl-2',
    title: 'Raport R2 — Komitet sterujący',
    description: 'Raport dla komitetu sterującego z podsumowaniem portfela i decyzjami.',
    type: 'report',
    category: 'R2',
    scope: 'application',
    status: 'active',
    updatedAt: '2026-02-25T14:30:00Z',
    createdBy: 'System',
    sectionCount: 8,
  },
  {
    id: 'tmpl-3',
    title: 'Raport R3 — Śledzenie korzyści',
    description: 'Raport ROI i korzyści z wdrożeń dla sponsorów biznesowych.',
    type: 'report',
    category: 'R3',
    scope: 'application',
    status: 'active',
    updatedAt: '2026-02-24T09:00:00Z',
    createdBy: 'System',
    sectionCount: 5,
  },
  {
    id: 'tmpl-4',
    title: 'Raport R4 — Przegląd portfela',
    description: 'Strategiczny przegląd całego portfela inicjatyw z analizą trendów.',
    type: 'report',
    category: 'R4',
    scope: 'application',
    status: 'active',
    updatedAt: '2026-02-23T16:00:00Z',
    createdBy: 'System',
    sectionCount: 10,
  },
  {
    id: 'tmpl-5',
    title: 'Executive Update — Prezentacja dla zarządu',
    description: 'Prezentacja slajdowa z kluczowymi metrykami i decyzjami do podjęcia.',
    type: 'presentation',
    category: 'executive_update',
    scope: 'application',
    status: 'active',
    updatedAt: '2026-02-22T11:00:00Z',
    createdBy: 'System',
    slideCount: 12,
  },
  {
    id: 'tmpl-6',
    title: 'Assessment Results — Prezentacja wyników oceny',
    description: 'Szablon prezentacji wyników oceny dojrzałości DRD/SIRI/ADMA.',
    type: 'presentation',
    category: 'assessment_results',
    scope: 'application',
    status: 'active',
    updatedAt: '2026-02-20T08:00:00Z',
    createdBy: 'System',
    slideCount: 18,
  },
  {
    id: 'tmpl-7',
    title: 'Project Kickoff — Rozpoczęcie projektu',
    description: 'Szablon prezentacji kickoff z celami, zakresem i harmonogramem.',
    type: 'presentation',
    category: 'project_kickoff',
    scope: 'organization',
    status: 'active',
    updatedAt: '2026-02-18T13:00:00Z',
    createdBy: 'Anna Kowalska',
    slideCount: 10,
  },
  {
    id: 'tmpl-8',
    title: 'Financial Review Template',
    description: 'Szablon raportu finansowego z analizą budżetową i prognozami.',
    type: 'report',
    category: 'financial_review',
    scope: 'organization',
    status: 'draft',
    updatedAt: '2026-02-15T10:00:00Z',
    createdBy: 'Jan Nowak',
    sectionCount: 7,
  },
];

export const MOCK_REPORTS: ReportItem[] = [
  {
    id: 'rpt-1',
    title: 'R1 — Sprint 24 Review (17-23 Feb 2026)',
    reportType: 'R1',
    status: 'exported',
    owner: 'Piotr Wiśniewski',
    periodFrom: '2026-02-17',
    periodTo: '2026-02-23',
    createdAt: '2026-02-23T18:00:00Z',
    updatedAt: '2026-02-24T09:00:00Z',
    exportFormats: ['PDF', 'DOCX'],
  },
  {
    id: 'rpt-2',
    title: 'R1 — Sprint 25 Review (24 Feb - 2 Mar 2026)',
    reportType: 'R1',
    status: 'draft',
    owner: 'Piotr Wiśniewski',
    periodFrom: '2026-02-24',
    periodTo: '2026-03-02',
    createdAt: '2026-02-27T10:00:00Z',
    updatedAt: '2026-02-28T08:00:00Z',
    exportFormats: [],
  },
  {
    id: 'rpt-3',
    title: 'R2 — Steering Committee Q1 2026',
    reportType: 'R2',
    status: 'ready',
    owner: 'Anna Kowalska',
    periodFrom: '2026-01-01',
    periodTo: '2026-03-31',
    createdAt: '2026-02-20T14:00:00Z',
    updatedAt: '2026-02-26T16:00:00Z',
    exportFormats: ['PDF', 'PPTX'],
  },
  {
    id: 'rpt-4',
    title: 'R3 — Benefits Tracking H1 2026',
    reportType: 'R3',
    status: 'draft',
    owner: 'Marek Zieliński',
    periodFrom: '2026-01-01',
    periodTo: '2026-06-30',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-02-22T11:00:00Z',
    exportFormats: [],
  },
  {
    id: 'rpt-5',
    title: 'R4 — Portfolio Overview 2026',
    reportType: 'R4',
    status: 'exported',
    owner: 'Anna Kowalska',
    periodFrom: '2026-01-01',
    periodTo: '2026-12-31',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-02-20T14:00:00Z',
    exportFormats: ['PDF', 'DOCX', 'PPTX'],
  },
  {
    id: 'rpt-6',
    title: 'R1 — Sprint 23 Review (10-16 Feb 2026)',
    reportType: 'R1',
    status: 'exported',
    owner: 'Piotr Wiśniewski',
    periodFrom: '2026-02-10',
    periodTo: '2026-02-16',
    createdAt: '2026-02-16T18:00:00Z',
    updatedAt: '2026-02-17T09:00:00Z',
    exportFormats: ['PDF'],
  },
  {
    id: 'rpt-7',
    title: 'Custom — Digital Transformation Progress',
    reportType: 'custom',
    status: 'ready',
    owner: 'Jan Nowak',
    periodFrom: '2025-06-01',
    periodTo: '2026-02-28',
    createdAt: '2026-02-25T10:00:00Z',
    updatedAt: '2026-02-27T15:00:00Z',
    exportFormats: ['PDF'],
  },
];

export const MOCK_PRESENTATIONS: PresentationItem[] = [
  {
    id: 'pres-1',
    title: 'DRD Assessment Results — Board Presentation',
    sourceType: 'assessment',
    owner: 'Piotr Wiśniewski',
    status: 'ready',
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-25T14:00:00Z',
    slideCount: 24,
    exportFormats: ['PPTX', 'PDF'],
  },
  {
    id: 'pres-2',
    title: 'SWOT Analysis — Strategic Planning Workshop',
    sourceType: 'tool',
    owner: 'Anna Kowalska',
    status: 'shared',
    createdAt: '2026-02-18T09:00:00Z',
    updatedAt: '2026-02-22T11:00:00Z',
    slideCount: 16,
    exportFormats: ['PPTX', 'PDF', 'PNG'],
  },
  {
    id: 'pres-3',
    title: 'Financial Outlook Q2 2026',
    sourceType: 'finance',
    owner: 'Marek Zieliński',
    status: 'editing',
    createdAt: '2026-02-24T14:00:00Z',
    updatedAt: '2026-02-27T16:00:00Z',
    slideCount: 12,
    exportFormats: [],
  },
  {
    id: 'pres-4',
    title: 'Value Stream Map — Process Optimization',
    sourceType: 'tool',
    owner: 'Jan Nowak',
    status: 'generated',
    createdAt: '2026-02-26T08:00:00Z',
    updatedAt: '2026-02-26T08:30:00Z',
    slideCount: 8,
    exportFormats: [],
  },
  {
    id: 'pres-5',
    title: 'Project Kickoff — Automation Initiative',
    sourceType: 'upload',
    owner: 'Piotr Wiśniewski',
    status: 'draft',
    createdAt: '2026-02-27T10:00:00Z',
    updatedAt: '2026-02-28T09:00:00Z',
    slideCount: 10,
    exportFormats: [],
  },
  {
    id: 'pres-6',
    title: 'BCG Matrix — Portfolio Prioritization',
    sourceType: 'tool',
    owner: 'Anna Kowalska',
    status: 'ready',
    createdAt: '2026-02-15T13:00:00Z',
    updatedAt: '2026-02-19T10:00:00Z',
    slideCount: 14,
    exportFormats: ['PPTX'],
  },
];
