ALTER TABLE tp_views ADD COLUMN IF NOT EXISTS share_token TEXT UNIQUE;
ALTER TABLE tp_views ADD COLUMN IF NOT EXISTS is_shared BOOLEAN DEFAULT false;
ALTER TABLE tp_views ADD COLUMN IF NOT EXISTS share_password TEXT;
ALTER TABLE tp_views ADD COLUMN IF NOT EXISTS share_expires_at TIMESTAMPTZ;
