import { MoreVertical, Plus, Search, Sparkles } from 'lucide-react';
import React from 'react';

import { StandardTable, type TableColumn, type TableRow } from '../../src/components/standard';

type View = 'kpi-l1' | 'kpi-l2' | 'kpi-l3' | 'okr-l1' | 'okr-l2' | 'okr-l3' | 'roi-l1' | 'roi-l2';
const view = (new URLSearchParams(window.location.search).get('view') || 'kpi-l1') as View;

const menu = [
  ['KPI', 'kpi'],
  ['OKR', 'okr'],
  ['ROI', 'roi'],
] as const;
const domain = view.split('-')[0];

const status = (label: string, tone: 'ok' | 'warn' | 'bad' | 'neutral' = 'neutral') => (
  <span className={`inline-flex rounded-full border px-2 py-0.5 text-[11px] font-medium ${tone === 'bad' ? 'border-c-danger/40 bg-c-danger/10 text-c-danger' : tone === 'warn' ? 'border-c-warning/40 bg-c-warning/10 text-c-warning' : tone === 'ok' ? 'border-c-success/40 text-c-success' : 'border-c-border-subtle text-c-text-secondary'}`}>{label}</span>
);

const Pair = ({ target, actual, tone = 'neutral' }: { target: string; actual: string; tone?: 'neutral' | 'warn' | 'bad' }) => (
  <div className="min-w-[82px] text-right tabular-nums"><div className="text-[10px] text-c-text-muted">CEL&nbsp; {target}</div><div className={tone === 'bad' ? 'font-semibold text-c-danger' : tone === 'warn' ? 'font-semibold text-c-warning' : 'font-medium text-c-text'}>Rezultat&nbsp; {actual}</div></div>
);

const reportsKpi = [
  { id: '1', name: 'Plant Balanced Scorecard — Zakład DBR77', scope: 'Zakład Tychy', period: '2026 · edycja 03', count: 138, state: '93 / 21 / 8 / 16', actions: 8, owner: 'Anna Kowalska', updated: '05.09.2026' },
  { id: '2', name: 'KPI produkcji — Q3 2026', scope: 'Produkcja', period: 'Q3 2026', count: 24, state: '17 / 4 / 2 / 1', actions: 2, owner: 'Marek Zieliński', updated: '04.09.2026' },
  { id: '3', name: 'KPI jakości — sierpień', scope: 'Jakość', period: 'VIII 2026', count: 18, state: '13 / 3 / 1 / 1', actions: 1, owner: 'Joanna Lis', updated: '03.09.2026' },
];
const reportsOkr = [
  { id: '1', name: 'OKR zakładu — Q4 2026', scope: 'Zakład DBR77', cycle: 'Q4 2026', objectives: 4, results: 11, state: '7 / 3 / 1 / —', owners: 7, checkin: '04.09.2026' },
  { id: '2', name: 'OKR automatyzacji — Q4 2026', scope: 'Program automatyzacji', cycle: 'Q4 2026', objectives: 3, results: 8, state: '6 / 2 / — / —', owners: 5, checkin: '03.09.2026' },
  { id: '3', name: 'OKR sprzedaży — H2 2026', scope: 'Sprzedaż', cycle: 'H2 2026', objectives: 3, results: 9, state: '5 / 2 / 1 / 1', owners: 6, checkin: '01.09.2026' },
];
const roiRows = [
  { id: '1', name: 'Robotyzacja gniazda spawalniczego', subject: 'Robotyzacja', option: '2 · pełna automatyzacja', capex: '1 000 000 zł', benefit: '400 000 zł', roi: 'ROI 5Y 100%', payback: '2,5 roku', npv: '516 315 zł', irr: '28,7%', recommendation: 'CONDITIONAL GO', phase: 'Wyliczenia', owner: 'Piotr Wiśniewski' },
  { id: '2', name: 'System wizyjny kontroli jakości', subject: 'IT / jakość', option: '1 · modernizacja', capex: '620 000 zł', benefit: '238 000 zł', roi: 'ROI 3Y 15%', payback: '2,6 roku', npv: '—', irr: '—', recommendation: 'GO', phase: 'Założenia', owner: 'Joanna Lis' },
  { id: '3', name: 'Automatyzacja magazynu WIP', subject: 'Magazyn', option: '3 · RaaS', capex: '—', benefit: '—', roi: '—', payback: '—', npv: '—', irr: '—', recommendation: '—', phase: 'Założenia', owner: 'Marek Zieliński' },
];

const col = (id: string, label: string, width = '140px', render?: (row: any) => React.ReactNode): TableColumn => ({ id, label, width, render: render || ((r: any) => <span className="text-sm text-c-text-secondary">{r[id] ?? '—'}</span>) });
const table = (data: any[], columns: TableColumn[], key: string, rowClassName?: (row: TableRow) => string) => <StandardTable data={data} columns={columns} persistKey={`p7k.prototype.${key}`} minTableWidth="columns" density="compact" rowClassName={rowClassName} rowMenu={() => ({ primary: [{ id: 'open', label: 'Otwórz', onClick: () => {} }] })} />;

const kpiItems = [
  { id: 'group-sales', group: true, name: 'SPRZEDAŻ · właściciel nadrzędny: Dyrektor Sprzedaży', area: 'Sprzedaż' },
  { id: 'k1', area: 'Sprzedaż', name: 'Wielkość sprzedaży netto', contract: '↑ min. · LC/1000', cadence: 'Miesiąc', type: 'Rozliczeniowy', owner: 'Tomasz Nowak', benchmark: '12 400', limit: '5%', jul: <Pair target="12 000" actual="12 180" />, aug: <Pair target="12 400" actual="11 620" tone="bad" />, sep: <Pair target="12 800" actual="—" />, ytd: <Pair target="98 200" actual="94 810" tone="warn" />, state: status('Krytyczne · działanie otwarte', 'bad') },
  { id: 'k2', area: 'Sprzedaż', name: 'Poziom przyjętych zamówień', contract: '↑ min. · LC/1000', cadence: 'Miesiąc', type: 'Rozliczeniowy', owner: 'Ewa Maj', benchmark: '10 900', limit: '4%', jul: <Pair target="10 500" actual="10 720" />, aug: <Pair target="10 900" actual="10 540" tone="warn" />, sep: <Pair target="11 100" actual="—" />, ytd: <Pair target="86 000" actual="85 440" />, state: status('Ostrzeżenie', 'warn') },
  { id: 'group-production', group: true, name: 'PRODUKCJA · właściciel nadrzędny: Dyrektor Operacyjny', area: 'Produkcja' },
  { id: 'k3', area: 'Produkcja', name: 'OEE linii montażowej', contract: '↑ min. · %', cadence: 'Miesiąc', type: 'Rozliczeniowy', owner: 'Marek Zieliński', benchmark: '78%', limit: '3%', jul: <Pair target="76%" actual="77%" />, aug: <Pair target="78%" actual="79%" />, sep: <Pair target="79%" actual="—" />, ytd: <Pair target="76%" actual="77%" />, state: status('W normie', 'ok') },
];

const okrItems = [
  { id: 'theme1', group: true, result: 'EFEKTYWNOŚĆ OPERACYJNA' },
  { id: 'kr1', objective: 'Skrócić przezbrojenia bez utraty jakości', ambition: 'Zobowiązanie', result: 'Skrócić średni czas przezbrojenia z 42 do 28 min', owner: 'Marek Zieliński', team: 'Produkcja L3', values: '42 / 28 / 31 min', progress: '79%', confidence: 'Średnia', deadline: '30.11.2026', checkin: '04.09.2026', state: status('Zagrożony', 'warn') },
  { id: 'kr2', objective: 'Skrócić przezbrojenia bez utraty jakości', ambition: 'Zobowiązanie', result: 'Utrzymać FPY podczas zmian na poziomie min. 98%', owner: 'Joanna Lis', team: 'Jakość', values: '97,2 / 98 / 96,8%', progress: '—', confidence: 'Niska', deadline: '30.11.2026', checkin: '03.09.2026', state: status('Krytyczny · działanie otwarte', 'bad') },
  { id: 'theme2', group: true, result: 'WZROST PRZYCHODÓW' },
  { id: 'kr3', objective: 'Uruchomić sprzedaż nowej usługi', ambition: 'Aspiracja', result: 'Pozyskać 12 klientów pilotażowych', owner: 'Ewa Maj', team: 'Sprzedaż', values: '0 / 12 / 9', progress: '75%', confidence: 'Wysoka', deadline: '15.12.2026', checkin: '05.09.2026', state: status('Na dobrej drodze', 'ok') },
];

function Frame({ title, subtitle, children, action }: { title: string; subtitle: string; children: React.ReactNode; action?: string }) {
  return <div className="min-h-screen bg-c-app text-c-text"><header className="border-b border-c-border bg-c-surface px-6 py-3"><div className="flex items-center justify-between"><div><div className="text-[11px] text-c-text-muted">Wyniki › {domain.toUpperCase()}</div><h1 className="text-lg font-semibold">{title}</h1><p className="text-xs text-c-text-secondary">{subtitle}</p></div><div className="flex items-center gap-2">{action && <button className="inline-flex h-9 items-center gap-2 rounded-lg border border-c-border bg-c-surface-raised px-3 text-sm"><Plus size={15}/>{action}</button>}<button aria-label="Więcej" className="p-2"><MoreVertical size={18}/></button></div></div></header><nav className="flex h-12 items-center gap-2 border-b border-c-border bg-c-surface px-6">{menu.map(([label,id]) => <button key={id} className={`rounded-full px-4 py-1.5 text-sm ${domain === id ? 'bg-c-accent-soft text-c-accent font-semibold' : 'text-c-text-secondary'}`}>{label}</button>)}<div className="ml-auto flex items-center gap-2 rounded-lg border border-c-border px-3 py-1.5 text-xs text-c-text-muted"><Search size={14}/>Szukaj w Wynikach</div></nav>{view === 'okr-l2' && <div className="flex h-11 items-center gap-2 border-b border-c-border bg-c-surface px-6 text-xs"><span className="text-c-text-muted">Filtry:</span><button className="rounded-full border border-c-accent/40 bg-c-accent-soft px-3 py-1 font-medium text-c-accent">Właściciel: wszyscy</button><button className="rounded-full border border-c-border px-3 py-1 text-c-text-secondary">Wszystkie</button><button className="rounded-full border border-c-border px-3 py-1 text-c-text-secondary">Zagrożone</button><button className="rounded-full border border-c-border px-3 py-1 text-c-text-secondary">Bez check-inu</button></div>}<main className="p-4">{children}</main></div>;
}

const CardShell = ({ sections, active, children }: { sections: string[]; active: string; children: React.ReactNode }) => <div className="grid grid-cols-[190px_minmax(0,1fr)_280px] gap-4"><nav className="rounded-xl border border-c-border bg-c-surface p-2">{sections.map(s => <div key={s} className={`rounded-lg px-3 py-2 text-sm ${s === active ? 'bg-c-accent-soft font-medium text-c-accent' : 'text-c-text-secondary'}`}>{s}</div>)}</nav><section className="space-y-4">{children}</section><aside className="rounded-xl border border-c-border bg-c-surface p-4"><div className="flex items-center gap-2 font-medium"><Sparkles size={16}/>Panel analizy</div><div className="mt-4 space-y-3 text-xs text-c-text-secondary"><p>Akcje</p><p>Właściwości</p><p>Powiązania</p><p>Źródła i założenia</p><p>Komentarze</p><p>Historia</p><hr className="border-c-border"/><p>Teresa wyjaśnia dane, ale nie tworzy pomiarów.</p></div></aside></div>;
const Block = ({ title, children }: { title: string; children: React.ReactNode }) => <div className="rounded-xl border border-c-border bg-c-surface p-4"><h2 className="mb-3 text-sm font-semibold">{title}</h2>{children}</div>;

function Content() {
  if (view === 'kpi-l1') return <Frame title="Raporty KPI" subtitle="Proces · zestawienia okresowe zakładów, projektów i działów" action="Nowy raport">{table(reportsKpi, [col('name','NAZWA RAPORTU','260px'),col('scope','ZAKRES'),col('period','OKRES'),col('count','MIERNIKI','90px'),col('state','STAN · norma / ostrz. / kryt. / brak','220px'),col('actions','OTWARTE DZIAŁANIA'),col('owner','PRZYGOTOWAŁ'),col('updated','AKTUALIZACJA')],view)}</Frame>;
  if (view === 'kpi-l2') return <Frame title="Plant Balanced Scorecard — Zakład DBR77" subtitle="Zakład Tychy · 2026 · edycja 03 · rewizja 05.09.2026 · przygotowała Anna Kowalska · 93 w normie · 21 ostrzeżeń · 8 krytycznych · 16 braków" action="Dodaj miernik"><div style={{ zoom: 0.74 }}>{table(kpiItems, [col('name','MIERNIK','260px'),col('contract','KIERUNEK / JEDNOSTKA','160px'),col('cadence','CZĘSTOTLIWOŚĆ'),col('type','TYP'),col('owner','ODPOWIEDZIALNOŚĆ'),col('benchmark','BENCHMARK'),col('limit','LIMIT %','90px'),col('jul','LIP 2026','120px',r=>r.jul),col('aug','SIE 2026','120px',r=>r.aug),col('sep','WRZ 2026','120px',r=>r.sep),col('ytd','YTD','120px',r=>r.ytd),col('state','STAN','190px',r=>r.state)],view,r=>(r as any).group?'bg-c-surface-raised font-semibold':'')}</div></Frame>;
  if (view === 'kpi-l3') return <Frame title="Wielkość sprzedaży netto" subtitle="Wyniki › KPI › Plant Balanced Scorecard — Zakład DBR77 › Wielkość sprzedaży netto · LC/1000 · Krytyczne"><CardShell sections={['Wyniki','Kontrakt','Pomiary','Odchylenia','Działania','Raporty','Historia']} active="Odchylenia"><Block title="Wyniki · sierpień 2026"><div className="grid grid-cols-4 gap-3 text-sm"><div>CEL<br/><b>12 400</b></div><div>Rezultat<br/><b className="text-c-danger">11 620</b></div><div>Odchylenie<br/><b className="text-c-danger">−6,3%</b></div><div>YTD<br/><b>94 810 / 98 200</b></div></div></Block><Block title="Kontrakt miernika"><p className="text-xs text-c-text-secondary">Sprzedaż · ↑ min. · LC/1000 · miesiąc · rozliczeniowy · Tomasz Nowak · benchmark 12 400 · limit 5% · metoda: przychody brutto − rabaty − zwroty − skonta.</p></Block><Block title="Odchylenia i karty działania">{table([{id:'a1',month:'Sierpień 2026',goal:'Nie',required:'Tak',problem:'Sprzedaż krajowa poniżej planu',cause:'Opóźnienie dwóch uruchomień',action:'Plan odbiorów i wsparcie wdrożeń',owner:'Tomasz Nowak',due:'18.09.2026',comment:'Powiązano z planem sprzedaży',state:'OTWARTY'}],[col('month','MIESIĄC'),col('goal','CEL OSIĄGNIĘTY?'),col('required','DZIAŁANIA?'),col('problem','PROBLEM','210px'),col('cause','GŁÓWNA PRZYCZYNA','210px'),col('action','DZIAŁANIA','220px'),col('owner','ODPOWIEDZIALNOŚĆ'),col('due','TERMIN'),col('comment','KOMENTARZ','200px'),col('state','STATUS','110px',r=>status(r.state,'bad'))],'kpi-actions')}</Block></CardShell></Frame>;
  if (view === 'okr-l1') return <Frame title="Raporty OKR" subtitle="Człowiek · zakres i cykl" action="Nowy raport">{table(reportsOkr,[col('name','NAZWA','250px'),col('scope','ZAKRES'),col('cycle','CYKL'),col('objectives','CELE'),col('results','REZULTATY'),col('state','STAN · droga / zagroż. / kryt. / brak','230px'),col('owners','WŁAŚCICIELE'),col('checkin','OSTATNI CHECK-IN')],view)}</Frame>;
  if (view === 'okr-l2') return <Frame title="OKR zakładu — Q4 2026" subtitle="Zakład DBR77 · Q4 2026 · Skupić zespoły na mierzalnej zmianie operacyjnej · filtr domyślny: Właściciel" action="Dodaj cel">{table(okrItems,[col('objective','CEL','220px',r=>r.group?<b>{r.result}</b>:<div><b>{r.objective}</b><div className="text-[10px] text-c-text-muted">{r.ambition}</div></div>),col('result','KLUCZOWY REZULTAT','280px'),col('owner','WŁAŚCICIEL'),col('team','ZESPÓŁ'),col('values','START / CEL / BIEŻĄCA','170px'),col('progress','POSTĘP'),col('confidence','PEWNOŚĆ'),col('deadline','TERMIN'),col('checkin','OSTATNI CHECK-IN'),col('state','STAN','180px',r=>r.state)],view,r=>(r as any).group?'bg-c-surface-raised font-semibold':'')}</Frame>;
  if (view === 'okr-l3') return <Frame title="Skrócić przezbrojenia bez utraty jakości" subtitle="Wyniki › OKR › OKR zakładu — Q4 2026 › Skrócić przezbrojenia"><CardShell sections={['Cel','Kluczowe rezultaty','Check-iny','Powiązania','Refleksja']} active="Kluczowe rezultaty"><Block title="Cel"><p className="text-sm">Skrócić przezbrojenia bez utraty jakości</p><p className="mt-1 text-xs text-c-text-secondary">Właściciel: Marek Zieliński · Zakład DBR77 · Q4 2026 · Zobowiązanie · pewność średnia</p></Block><Block title="Kluczowe rezultaty"><div className="space-y-3">{okrItems.filter(r=>!r.group&&r.objective?.startsWith('Skrócić')).map(r=><div key={r.id} className={`rounded-lg border border-c-border border-l-4 p-3 ${r.id==='kr2'?'border-l-c-danger':'border-l-c-warning'}`}><div className="flex justify-between"><b className="text-sm">{r.result}</b>{r.state}</div><div className="mt-2 text-xs text-c-text-secondary">{r.owner} · {r.team} · termin {r.deadline} · START / CEL / BIEŻĄCA: {r.values} · postęp {r.progress} · pewność {r.confidence}</div><button className="mt-3 rounded-lg border border-c-border px-3 py-1 text-xs">Check-in</button></div>)}</div></Block></CardShell></Frame>;
  if (view === 'roi-l1') return <Frame title="Analizy ROI" subtitle="Inwestycje · ekonomika, ryzyko i rekomendacja" action="Nowa analiza">{table(roiRows,[col('name','NAZWA','250px'),col('subject','PRZEDMIOT'),col('option','WARIANT','180px'),col('capex','CAPEX'),col('benefit','ROCZNA KORZYŚĆ'),col('roi','ROI'),col('payback','PAYBACK'),col('npv','NPV'),col('irr','IRR'),col('recommendation','REKOMENDACJA','180px',r=>status(r.recommendation)),col('phase','FAZA'),col('owner','WŁAŚCICIEL')],view)}</Frame>;
  return <Frame title="Robotyzacja gniazda spawalniczego" subtitle="Wyniki › ROI › Robotyzacja gniazda spawalniczego · wariant 2 · 5 lat · CONDITIONAL GO"><CardShell sections={['Założenia','Wyliczenia','Realizacja']} active="Realizacja"><Block title="Założenia"><p className="text-xs text-c-text-secondary">Problem: niestabilna wydajność i brak operatorów · BAU: 10 dodatkowych FTE w 2 lata · CAPEX 1 000 000 zł z contingency 10% · ΔNWC 80 000 zł · korzyści Hard/Avoided oddzielnie · OEE 62→72% → przepustowość → marża → cash flow.</p></Block><Block title="Wyliczenia"><div className="grid grid-cols-5 gap-3 text-xs"><div>ROI 5Y<br/><b>100%</b></div><div>PP<br/><b>2,5 roku</b></div><div>NPV<br/><b>516 315 zł</b></div><div>IRR<br/><b>28,7%</b></div><div>PI / BCR<br/><b>1,52 / 1,39</b></div></div><p className="mt-3 text-xs text-c-text-secondary">Scenariusze: Conservative / Base / Upside · wrażliwość ±20% · rekomendacja CONDITIONAL GO.</p></Block><Block title="Realizacja · przegląd po 6 miesiącach">{table([{id:'r1',metric:'CAPEX',expected:'1 000 000 zł',actual:'1 080 000 zł',variance:'+80 000 zł'},{id:'r2',metric:'Output',expected:'+15%',actual:'+11%',variance:'−4 pp'},{id:'r3',metric:'FTE saving',expected:'10 FTE',actual:'7 FTE',variance:'−3 FTE'},{id:'r4',metric:'Roczna korzyść',expected:'400 000 zł',actual:'312 000 zł',variance:'−88 000 zł'},{id:'r5',metric:'Payback',expected:'2,5 roku',actual:'3,46 roku',variance:'+0,96 roku'}],[col('metric','KPI / KORZYŚĆ','180px'),col('expected','EXPECTED'),col('actual','ACTUAL'),col('variance','WARIANCJA','160px',r=><span className="font-semibold text-c-danger">{r.variance}</span>)],'roi-pir')}</Block><Block title="Prawdziwość założeń i ROI po realizacji"><p className="text-xs text-c-text-secondary">Popyt: potwierdzone · redukcja FTE: częściowo potwierdzona — przesunięto 7 z 10 etatów · ramp-up: obalone — trwał 14 zamiast 8 tygodni. ROI po realizacji 5Y: 44% · NPV: 118 400 zł · rekomendacja: korekta planu korzyści.</p></Block></CardShell></Frame>;
}

export default Content;
