/**
 * Route Configuration for React Router v7
 *
 * This file defines the URL structure and route mappings for the application.
 * Migration Strategy: Gradual replacement of ViewRenderer with standard routing.
 */

import { AppView } from '@/types';

/**
 * Route path definitions
 * Maps AppView enum values to URL paths
 */
export const ROUTES = {
  // Public Routes
  WELCOME: '/',
  AUTH: '/auth',
  BECOME_PARTNER: '/become-partner',

  // Main App Routes
  AI_CHAT: '/chat',
  INTERVIEW: '/interview',
  DISCOVERY_CONSULTANT: '/discovery', // Legacy alias for Interview

  // Discovery Tools Module
  DISCOVERY_TOOLS: {
    ROOT: '/discovery-tools',
    STRATEGIC: '/discovery-tools/strategic',
    OPERATIONAL: '/discovery-tools/operational',
    DIGITAL: '/discovery-tools/digital',
    PROCESS_AUTOMATION: '/discovery-tools/process-automation',
  },

  MY_WORK: '/my-work',
  DASHBOARD: '/dashboard',

  // Assessment Module
  ASSESSMENT: {
    ROOT: '/assessment',
    DRD: '/assessment/drd',
    SIRI: '/assessment/siri',
    ADMA: '/assessment/adma',
    CMMI: '/assessment/cmmi',
    LEAN: '/assessment/lean',
    OVERVIEW: '/assessment/overview',
    SUMMARY: '/assessment/summary',
    AUDITS: '/assessment/audits',
  },

  // Context Builder
  CONTEXT_BUILDER: {
    ROOT: '/context',
    PROFILE: '/context/profile',
    GOALS: '/context/goals',
    CHALLENGES: '/context/challenges',
    MEGATRENDS: '/context/megatrends',
    STRATEGY: '/context/strategy',
  },

  // Transformation Modules
  INITIATIVES: '/initiatives',
  ROADMAP: '/roadmap',
  PORTFOLIO: '/portfolio',
  ROI: '/roi',
  ECONOMICS: '/economics',
  EXECUTION: '/execution',
  IMPLEMENTATION: '/implementation',
  ROLLOUT: '/rollout',
  REPORTS: '/reports',
  KPI_OKR: '/kpi-okr',
  BENEFITS: '/benefits',

  // Project Intelligence
  PROJECT_INTELLIGENCE: '/project-intelligence',

  // Studio
  STUDIO: '/studio',

  // Admin
  ADMIN: {
    ROOT: '/admin',
    OVERVIEW: '/admin/overview',
    ORGANIZATION: '/admin/organization',
    TEAM: '/admin/team',
    WORKSPACE: '/admin/workspace',
    AI: '/admin/ai',
    BILLING: '/admin/billing',
    SECURITY: '/admin/security',
    COMPLIANCE: '/admin/compliance',
  },

  // Settings
  SETTINGS: {
    ROOT: '/settings',
    PROFILE: '/settings/profile',
    BILLING: '/settings/billing',
    AI: '/settings/ai',
    NOTIFICATIONS: '/settings/notifications',
    INTEGRATIONS: '/settings/integrations',
    ORGANIZATION: '/settings/organization',
    SECURITY: '/settings/security',
  },

  // SuperAdmin
  SUPERADMIN: {
    ROOT: '/superadmin',
    OVERVIEW: '/superadmin/overview',
    CUSTOMERS: '/superadmin/customers',
    AI_PLATFORM: '/superadmin/ai-platform',
    SYSTEM: '/superadmin/system',
    REVENUE: '/superadmin/revenue',
    ANALYTICS: '/superadmin/analytics',
  },

  // Partner Portal
  PARTNER: {
    LANDING: '/partner',
    PRICING: '/partner/pricing',
    DASHBOARD: '/partner/dashboard',
    CLIENTS: '/partner/clients',
    COMMISSION: '/partner/commission',
    DIRECTORY: '/partner/directory',
    RESOURCES: '/partner/resources',
  },

  // Consultant
  CONSULTANT: {
    PANEL: '/consultant/panel',
    INVITES: '/consultant/invites',
  },

  // Wizards
  ORG_SETUP: '/setup/organization',
  ONBOARDING: '/setup/onboarding',
  TRIAL_ENTRY: '/trial',

  // Affiliate
  AFFILIATE: '/affiliate',

  // AI Actions
  AI_ACTIONS: '/ai-actions',

  // Legal
  LEGAL: {
    ABOUT: '/about',
    CONTACT: '/contact',
    TERMS: '/terms',
    PRIVACY: '/privacy',
    COOKIES: '/cookies',
    SECURITY: '/security',
  },

  // Status & Changelog
  STATUS: '/status',
  CHANGELOG: '/changelog',

  // Knowledge & Pricing
  KNOWLEDGE_BASE: '/knowledge',
  PRICING: '/pricing',
  EXECUTIVE: '/executive',
} as const;

/**
 * Maps AppView enum to route paths
 * Used for backward compatibility during migration
 */
export const APP_VIEW_TO_ROUTE: Record<AppView, string> = {
  // Public
  [AppView.WELCOME]: ROUTES.WELCOME,
  [AppView.AUTH]: ROUTES.AUTH,

  // Main
  [AppView.AI_CHAT]: ROUTES.AI_CHAT,
  [AppView.MY_WORK]: ROUTES.MY_WORK,
  [AppView.DASHBOARD]: ROUTES.DASHBOARD,
  [AppView.USER_DASHBOARD]: ROUTES.DASHBOARD,
  [AppView.DASHBOARD_OVERVIEW]: ROUTES.DASHBOARD,
  [AppView.DASHBOARD_SNAPSHOT]: ROUTES.DASHBOARD,

  // Assessment
  [AppView.ASSESSMENT_DRD]: ROUTES.ASSESSMENT.DRD,
  [AppView.ASSESSMENT_SIRI]: ROUTES.ASSESSMENT.SIRI,
  [AppView.ASSESSMENT_ADMA]: ROUTES.ASSESSMENT.ADMA,
  [AppView.ASSESSMENT_CMMI]: ROUTES.ASSESSMENT.CMMI,
  [AppView.ASSESSMENT_LEAN]: ROUTES.ASSESSMENT.LEAN,
  [AppView.ASSESSMENT_LEAN_EXTERNAL]: ROUTES.ASSESSMENT.LEAN,
  [AppView.ASSESSMENT_OVERVIEW]: ROUTES.ASSESSMENT.OVERVIEW,
  [AppView.ASSESSMENT_SUMMARY]: ROUTES.ASSESSMENT.SUMMARY,
  [AppView.ASSESSMENT_AUDITS]: ROUTES.ASSESSMENT.AUDITS,
  [AppView.ASSESSMENT_DIGITAL_EXTERNAL]: ROUTES.ASSESSMENT.DRD,
  [AppView.ASSESSMENT_OTHER]: ROUTES.ASSESSMENT.ROOT,
  [AppView.MY_ASSESSMENTS]: ROUTES.ASSESSMENT.ROOT,
  [AppView.REVIEWER_DASHBOARD]: ROUTES.ASSESSMENT.ROOT,
  [AppView.ASSESSMENT_DASHBOARD]: ROUTES.ASSESSMENT.ROOT,
  [AppView.GAP_MAP]: ROUTES.ASSESSMENT.ROOT,
  [AppView.ASSESSMENT_REPORTS]: ROUTES.ASSESSMENT.ROOT,
  [AppView.INITIATIVE_GENERATOR]: ROUTES.INITIATIVES,

  // Context Builder
  [AppView.CONTEXT_BUILDER]: ROUTES.CONTEXT_BUILDER.ROOT,
  [AppView.CONTEXT_BUILDER_PROFILE]: ROUTES.CONTEXT_BUILDER.PROFILE,
  [AppView.CONTEXT_BUILDER_GOALS]: ROUTES.CONTEXT_BUILDER.GOALS,
  [AppView.CONTEXT_BUILDER_CHALLENGES]: ROUTES.CONTEXT_BUILDER.CHALLENGES,
  [AppView.CONTEXT_BUILDER_MEGATRENDS]: ROUTES.CONTEXT_BUILDER.MEGATRENDS,
  [AppView.CONTEXT_BUILDER_STRATEGY]: ROUTES.CONTEXT_BUILDER.STRATEGY,

  // Transformation
  [AppView.FULL_STEP1_CONTEXT]: ROUTES.CONTEXT_BUILDER.ROOT,
  [AppView.FULL_STEP1_ASSESSMENT]: ROUTES.ASSESSMENT.DRD,
  [AppView.FULL_STEP1_PROCESSES]: ROUTES.ASSESSMENT.DRD,
  [AppView.FULL_STEP1_DIGITAL]: ROUTES.ASSESSMENT.DRD,
  [AppView.FULL_STEP1_MODELS]: ROUTES.ASSESSMENT.DRD,
  [AppView.FULL_STEP1_DATA]: ROUTES.ASSESSMENT.DRD,
  [AppView.FULL_STEP1_CULTURE]: ROUTES.ASSESSMENT.DRD,
  [AppView.FULL_STEP1_CYBERSECURITY]: ROUTES.ASSESSMENT.DRD,
  [AppView.FULL_STEP1_AI]: ROUTES.ASSESSMENT.DRD,
  [AppView.FULL_STEP2_INITIATIVES]: ROUTES.INITIATIVES,
  [AppView.FULL_STEP3_ROADMAP]: ROUTES.ROADMAP,
  [AppView.FULL_STEP4_ROI]: ROUTES.ROI,
  [AppView.ECONOMICS]: ROUTES.ECONOMICS,
  [AppView.FULL_STEP5_EXECUTION]: ROUTES.EXECUTION,
  [AppView.IMPLEMENTATION]: ROUTES.IMPLEMENTATION,
  [AppView.FULL_PILOT_EXECUTION]: ROUTES.IMPLEMENTATION,
  [AppView.FULL_ROLLOUT]: ROUTES.ROLLOUT,
  [AppView.FULL_STEP6_REPORTS]: ROUTES.REPORTS,
  [AppView.DRD_AUDIT_REPORT]: ROUTES.REPORTS,
  [AppView.KPI_OKR_DASHBOARD]: ROUTES.KPI_OKR,
  [AppView.PORTFOLIO_ROADMAP]: ROUTES.PORTFOLIO,
  [AppView.INITIATIVE_MANAGEMENT]: ROUTES.PORTFOLIO,
  [AppView.BENEFITS_REALIZATION]: ROUTES.BENEFITS,

  // Interview (was Project Intelligence)
  [AppView.PROJECT_INTELLIGENCE]: ROUTES.PROJECT_INTELLIGENCE,
  [AppView.INTERVIEW]: ROUTES.INTERVIEW,
  [AppView.DISCOVERY_CONSULTANT]: ROUTES.DISCOVERY_CONSULTANT,

  // Discovery Tools Module
  [AppView.DISCOVERY_TOOLS]: ROUTES.DISCOVERY_TOOLS.ROOT,
  [AppView.DISCOVERY_TOOLS_STRATEGIC]: ROUTES.DISCOVERY_TOOLS.STRATEGIC,
  [AppView.DISCOVERY_TOOLS_OPERATIONAL]: ROUTES.DISCOVERY_TOOLS.OPERATIONAL,
  [AppView.DISCOVERY_TOOLS_DIGITAL]: ROUTES.DISCOVERY_TOOLS.DIGITAL,
  [AppView.DISCOVERY_TOOLS_PROCESS_AUTOMATION]: ROUTES.DISCOVERY_TOOLS.PROCESS_AUTOMATION,

  // Studio
  [AppView.STUDIO]: ROUTES.STUDIO,

  // Admin
  [AppView.ADMIN_DASHBOARD]: ROUTES.ADMIN.ROOT,
  [AppView.ADMIN_OVERVIEW]: ROUTES.ADMIN.OVERVIEW,
  [AppView.ADMIN_ORGANIZATION]: ROUTES.ADMIN.ORGANIZATION,
  [AppView.ADMIN_ORGANIZATION_SETTINGS]: ROUTES.ADMIN.ORGANIZATION,
  [AppView.ADMIN_TEAM]: ROUTES.ADMIN.TEAM,
  [AppView.ADMIN_WORKSPACE]: ROUTES.ADMIN.WORKSPACE,
  [AppView.ADMIN_PROJECT_DETAILS]: ROUTES.ADMIN.WORKSPACE,
  [AppView.ADMIN_AI]: ROUTES.ADMIN.AI,
  [AppView.ADMIN_BILLING]: ROUTES.ADMIN.BILLING,
  [AppView.ADMIN_SECURITY]: ROUTES.ADMIN.SECURITY,
  [AppView.ADMIN_SETTINGS]: ROUTES.ADMIN.SECURITY,
  [AppView.ADMIN_USERS]: ROUTES.ADMIN.TEAM,
  [AppView.ADMIN_PROJECTS]: ROUTES.ADMIN.WORKSPACE,
  [AppView.ADMIN_LLM]: ROUTES.ADMIN.AI,
  [AppView.ADMIN_AI_HEALTH]: ROUTES.ADMIN.AI,
  [AppView.ADMIN_KNOWLEDGE]: ROUTES.ADMIN.AI,
  [AppView.ADMIN_TEAMS]: ROUTES.ADMIN.TEAM,
  [AppView.ADMIN_ANALYTICS]: ROUTES.ADMIN.ROOT,
  [AppView.ADMIN_FEEDBACK]: ROUTES.ADMIN.ROOT,
  [AppView.ADMIN_METRICS]: ROUTES.ADMIN.ROOT,
  [AppView.ADMIN_API_KEYS]: ROUTES.ADMIN.SECURITY,
  [AppView.ADMIN_BILLING_MANAGEMENT]: ROUTES.ADMIN.BILLING,
  [AppView.ADMIN_BULK_OPERATIONS]: ROUTES.ADMIN.ROOT,
  [AppView.ADMIN_WORK_MODE]: ROUTES.ADMIN.ROOT,
  [AppView.ADMIN_SETTINGS_CONSULTANTS]: ROUTES.ADMIN.TEAM,
  [AppView.ADMIN_INVITATIONS]: ROUTES.ADMIN.TEAM,
  [AppView.ADMIN_TOKEN_MANAGEMENT]: ROUTES.ADMIN.SECURITY,

  // Settings
  [AppView.SETTINGS_PROFILE]: ROUTES.SETTINGS.PROFILE,
  [AppView.SETTINGS_BILLING]: ROUTES.SETTINGS.BILLING,
  [AppView.SETTINGS_AI]: ROUTES.SETTINGS.AI,
  [AppView.SETTINGS_NOTIFICATIONS]: ROUTES.SETTINGS.NOTIFICATIONS,
  [AppView.SETTINGS_INTEGRATIONS]: ROUTES.SETTINGS.INTEGRATIONS,
  [AppView.SETTINGS_ORGANIZATION]: ROUTES.SETTINGS.ORGANIZATION,
  [AppView.SETTINGS_MFA]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_ACTIVE_SESSIONS]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_LOGIN_HISTORY]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_DATA_CONTROLS]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_API_KEYS]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_WEBHOOKS]: ROUTES.SETTINGS.INTEGRATIONS,
  [AppView.SETTINGS_CALENDAR_SYNC]: ROUTES.SETTINGS.INTEGRATIONS,
  [AppView.SETTINGS_APPEARANCE]: ROUTES.SETTINGS.PROFILE,
  [AppView.SETTINGS_AI_MEMORY]: ROUTES.SETTINGS.AI,
  [AppView.SETTINGS_AI_RESPONSE_STYLE]: ROUTES.SETTINGS.AI,
  [AppView.SETTINGS_AI_CHAT_HISTORY]: ROUTES.SETTINGS.AI,
  [AppView.SETTINGS_AI_VOICE]: ROUTES.SETTINGS.AI,
  [AppView.SETTINGS_SECURITY]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_API_ACCESS]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_PRIVACY]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_SSO]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_LEGAL]: ROUTES.SETTINGS.PROFILE,
  [AppView.SETTINGS_WORK_PREFERENCES]: ROUTES.SETTINGS.PROFILE,
  [AppView.SETTINGS_DASHBOARD_PREFERENCES]: ROUTES.SETTINGS.PROFILE,
  [AppView.SETTINGS_ACCESSIBILITY]: ROUTES.SETTINGS.PROFILE,
  [AppView.SETTINGS_PROFILE_MODULE]: ROUTES.SETTINGS.PROFILE,
  [AppView.SETTINGS_AI_MODULE]: ROUTES.SETTINGS.AI,
  [AppView.SETTINGS_NOTIFICATIONS_MODULE]: ROUTES.SETTINGS.NOTIFICATIONS,
  [AppView.SETTINGS_SECURITY_MODULE]: ROUTES.SETTINGS.SECURITY,
  [AppView.SETTINGS_INTEGRATIONS_MODULE]: ROUTES.SETTINGS.INTEGRATIONS,
  [AppView.SETTINGS_APPEARANCE_MODULE]: ROUTES.SETTINGS.PROFILE,
  [AppView.SETTINGS_REGIONALIZATION]: ROUTES.SETTINGS.PROFILE,

  // SuperAdmin
  [AppView.SUPERADMIN_OVERVIEW]: ROUTES.SUPERADMIN.OVERVIEW,
  [AppView.SUPERADMIN_CUSTOMERS]: ROUTES.SUPERADMIN.CUSTOMERS,
  [AppView.SUPERADMIN_AI_PLATFORM]: ROUTES.SUPERADMIN.AI_PLATFORM,
  [AppView.SUPERADMIN_AI_INFRASTRUCTURE]: ROUTES.SUPERADMIN.AI_PLATFORM,
  [AppView.SUPERADMIN_AI_DEVELOPMENT]: ROUTES.SUPERADMIN.AI_PLATFORM,
  [AppView.SUPERADMIN_AI_OPERATIONS]: ROUTES.SUPERADMIN.AI_PLATFORM,
  [AppView.SUPERADMIN_SYSTEM]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_CONTENT]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_REVENUE]: ROUTES.SUPERADMIN.REVENUE,
  [AppView.SUPERADMIN_SECURITY]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_CONFIGURATION]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_ANALYTICS]: ROUTES.SUPERADMIN.ANALYTICS,
  [AppView.SUPERADMIN_DASHBOARD]: ROUTES.SUPERADMIN.ROOT,
  [AppView.SUPERADMIN_ORGANIZATIONS]: ROUTES.SUPERADMIN.CUSTOMERS,
  [AppView.SUPERADMIN_USERS]: ROUTES.SUPERADMIN.CUSTOMERS,
  [AppView.SUPERADMIN_BILLING]: ROUTES.SUPERADMIN.REVENUE,
  [AppView.SUPERADMIN_AI_CONFIG]: ROUTES.SUPERADMIN.AI_PLATFORM,
  [AppView.SUPERADMIN_LLM_MANAGEMENT]: ROUTES.SUPERADMIN.AI_PLATFORM,
  [AppView.SUPERADMIN_AI_INTELLIGENCE]: ROUTES.SUPERADMIN.AI_PLATFORM,
  [AppView.SUPERADMIN_KNOWLEDGE]: ROUTES.SUPERADMIN.AI_PLATFORM,
  [AppView.SUPERADMIN_SETTINGS]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_SSO]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_SECURITY_POLICIES]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_API_MANAGEMENT]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_WHITELABEL]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_COMPLIANCE]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_INVOICES]: ROUTES.SUPERADMIN.REVENUE,
  [AppView.SUPERADMIN_FEEDBACK]: ROUTES.SUPERADMIN.ANALYTICS,
  [AppView.SUPERADMIN_BULK_OPERATIONS]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_PLAYBOOK_TEMPLATES]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.SUPERADMIN_PLAYBOOK_EDITOR]: ROUTES.SUPERADMIN.SYSTEM,
  [AppView.ADMIN_PLAYBOOK_RUNS]: ROUTES.ADMIN.ROOT,

  // Partner
  [AppView.PARTNER_LANDING]: ROUTES.PARTNER.LANDING,
  [AppView.PARTNER_PRICING]: ROUTES.PARTNER.PRICING,
  [AppView.APP_PRICING]: ROUTES.PRICING,
  [AppView.PARTNER_PROVIDER_HOME]: ROUTES.PARTNER.DASHBOARD,
  [AppView.PARTNER_DASHBOARD]: ROUTES.PARTNER.DASHBOARD,
  [AppView.PARTNER_CLIENT_ACCESS]: ROUTES.PARTNER.CLIENTS,
  [AppView.PARTNER_COMMISSION]: ROUTES.PARTNER.COMMISSION,
  [AppView.PARTNER_DIRECTORY]: ROUTES.PARTNER.DIRECTORY,
  [AppView.PARTNER_RESOURCES]: ROUTES.PARTNER.RESOURCES,

  // Consultant
  [AppView.CONSULTANT_PANEL]: ROUTES.CONSULTANT.PANEL,
  [AppView.CONSULTANT_INVITES]: ROUTES.CONSULTANT.INVITES,

  // Wizards
  [AppView.ORG_SETUP_WIZARD]: ROUTES.ORG_SETUP,
  [AppView.ONBOARDING_WIZARD]: ROUTES.ONBOARDING,
  [AppView.TRIAL_ENTRY]: ROUTES.TRIAL_ENTRY,

  // Quick Assessment
  [AppView.FREE_ASSESSMENT_CHAT]: ROUTES.ASSESSMENT.ROOT,
  [AppView.QUICK_STEP1_PROFILE]: ROUTES.CONTEXT_BUILDER.PROFILE,
  [AppView.QUICK_STEP2_USER_CONTEXT]: ROUTES.CONTEXT_BUILDER.GOALS,
  [AppView.QUICK_STEP3_EXPECTATIONS]: ROUTES.CONTEXT_BUILDER.STRATEGY,

  // Affiliate
  [AppView.AFFILIATE_DASHBOARD]: ROUTES.AFFILIATE,

  // AI Actions
  [AppView.AI_ACTION_PROPOSALS]: ROUTES.AI_ACTIONS,

  // Legacy/Fallback
  [AppView.FULL_TRANSFORMATION_CHAT]: ROUTES.AI_CHAT,
  [AppView.MASTERCLASS]: ROUTES.DASHBOARD,
  [AppView.RESOURCES]: ROUTES.DASHBOARD,
  [AppView.EXECUTIVE_VIEW]: ROUTES.EXECUTIVE,
  [AppView.KNOWLEDGE_BASE]: ROUTES.KNOWLEDGE_BASE,
  [AppView.KNOWLEDGE_BASE_ARTICLE]: ROUTES.KNOWLEDGE_BASE,
  [AppView.STATUS_PAGE]: ROUTES.DASHBOARD,
  [AppView.CHANGELOG]: ROUTES.DASHBOARD,
  [AppView.HELP_ANALYTICS]: ROUTES.DASHBOARD,
};

/**
 * Helper function to get route path from AppView
 * Enhanced with diagnostic logging for navigation debugging
 */
export function getRouteFromAppView(view: AppView): string {
  const route = APP_VIEW_TO_ROUTE[view];

  if (!route) {
    console.warn(
      `[routeConfig] WARNING: No route mapping for view "${view}", falling back to dashboard`
    );
    console.warn('[routeConfig] This may indicate a missing entry in APP_VIEW_TO_ROUTE');
    return ROUTES.DASHBOARD;
  }

  return route;
}

/**
 * Helper function to get AppView from route path
 * Used for backward compatibility
 */
export function getAppViewFromRoute(path: string): AppView | null {
  const entry = Object.entries(APP_VIEW_TO_ROUTE).find(([_, route]) => route === path);
  return entry ? (entry[0] as AppView) : null;
}

/**
 * Validates that all AppView enum values have corresponding route mappings
 * Call this during development to catch missing mappings early
 */
export function validateRouteCompleteness(): { valid: boolean; missing: string[] } {
  const allViews = Object.values(AppView);
  const mappedViews = Object.keys(APP_VIEW_TO_ROUTE);

  const missing = allViews.filter((view) => !mappedViews.includes(view));

  if (missing.length > 0) {
    console.error('[routeConfig] VALIDATION ERROR: Missing route mappings for views:', missing);
  } else {
    console.log('[routeConfig] Route validation passed: All AppView values have mappings');
  }

  return {
    valid: missing.length === 0,
    missing,
  };
}

// Run validation in development mode
if (process.env.NODE_ENV === 'development') {
  // Defer validation to avoid blocking initial load
  setTimeout(() => {
    validateRouteCompleteness();
  }, 1000);
}
