#!/usr/bin/env node
import { chromium } from 'playwright';
const BASE = process.argv[2] || 'http://localhost:3150';
const AUTH = process.argv[3] || '/private/tmp/wt-zapisy/.auth-zapisy.json';
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, colorScheme: 'light', storageState: AUTH, locale: 'pl-PL' });
const page = await context.newPage();
const api = [];
page.on('response', (r) => { if (/\/api\/.*raid/i.test(r.url())) api.push(`${r.request().method()} ${r.status()} ${r.url().replace(BASE,'')}`); });
await page.goto(`${BASE}/initiatives`, { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(4000);
await page.locator('table tbody tr').first().dblclick();
await page.waitForTimeout(5000);
await page.getByRole('button', { name: 'Ryzyko i RAID', exact: true }).click();
await page.waitForTimeout(3500);
await page.screenshot({ path: '/tmp/rozpoznanie-raid.png', fullPage: false });
const btns = await page.$$eval('button', (els) => els.map((e) => (e.textContent || '').trim()).filter((s) => s && s.length < 40));
console.log('PRZYCISKI:', JSON.stringify([...new Set(btns)].slice(-45)));
console.log('API RAID:', api.join('\n'));
await browser.close();
