export type FunnelEventName =
  | 'auth_login_success'
  | 'demo_session_started'
  | 'trial_org_setup_completed'
  | 'billing_payment_method_added'
  | 'interview_conversational_started'
  | 'interview_transcript_message_added'
  | 'interview_ai_parse_requested'
  | 'interview_ai_parse_applied'
  | 'interview_question_marked_answered'
  | 'interview_question_needs_follow_up'
  | 'survey_started'
  | 'survey_resumed'
  | 'survey_completed'
  | 'survey_abandoned'
  | 'external_assessment_opened'
  | 'external_assessment_started'
  | 'external_assessment_completed'
  | 'external_assessment_result_viewed'
  | 'external_assessment_cta_clicked'
  | 'inference_run_started'
  | 'inference_run_completed'
  | 'inference_run_failed'
  | 'insight_generated'
  | 'insight_approved'
  | 'insight_regenerated'
  | 'insight_exported'
  | 'insight_used_in_ai_context'
  | 'sponsor_report_created'
  | 'sponsor_report_generated'
  | 'sponsor_report_section_edited'
  | 'sponsor_report_approved'
  | 'sponsor_report_rejected'
  | 'sponsor_report_exported'
  | 'sponsor_report_utilized'
  | 'ai_access_blocked'
  | 'upgrade_cta_clicked'
  | 'upgrade_viewed'
  | 'plan_selected'
  | 'checkout_started'
  | 'checkout_completed'
  | 'checkout_failed'
  | 'subscription_cancelled'
  | 'cloud_source_connected'
  | 'dataset_import_started'
  | 'dataset_import_succeeded'
  | 'dataset_import_failed'
  | 'deep_thinking_started'
  | 'deep_thinking_report_generated'
  | 'deep_thinking_exported'
  | 'market_research_started'
  | 'market_research_report_generated'
  | 'market_research_exported'
  | 'cothinker_mode_selected'
  | 'cothinker_response_generated'
  | 'oauth_login_started'
  | 'oauth_login_succeeded'
  | 'oauth_login_failed'
  | 'oauth_linked'
  | 'oauth_unlinked'
  | 'linkedin_connect_cta_shown'
  | 'linkedin_connect_cta_clicked'
  | 'linkedin_connect_cta_dismissed'
  | 'personal_task_created'
  | 'personal_task_completed'
  | 'personal_task_due_date_set'
  | 'my_idea_saved'
  | 'my_idea_edited'
  | 'my_idea_suggested'
  | 'my_idea_used'
  | 'tools_hub_opened'
  | 'known_tools_opened'
  | 'known_tool_viewed'
  | 'tool_filtered'
  | 'tool_preview_opened'
  | 'tool_session_started_from_library'
  | 'tool_kb_opened'
  | 'help_video_watched'
  | 'help_video_skipped'
  | 'help_video_dont_show'
  | 'ai_authoring_used'
  | 'ai_authoring_applied'
  | 'ai_authoring_undone'
  | 'ai_card_generated'
  | 'initiative_gate_readiness_viewed'
  | 'initiative_gate_readiness_ai_requested'
  | 'skills_gap_viewed'
  | 'licensed_tool_framework_opened'
  | 'licensed_tool_assessment_completed'
  | 'licensed_tool_assessment_approved'
  | 'licensed_tools_report_generated'
  | 'licensed_tools_deck_exported'
  | 'licensed_tool_roadmap_generated'
  | 'licensed_tool_initiatives_created_from_roadmap'
  | 'licensed_tool_locked_viewed'
  | 'licensed_tool_unlock_cta_clicked'
  | 'pdf_import_started'
  | 'pdf_import_extracted'
  | 'pdf_import_mapping_confirmed'
  | 'execution_timeline_viewed'
  | 'execution_timeline_initiative_updated'
  | 'execution_timeline_filtered'
  | 'execution_risk_signal_viewed'
  | 'execution_risk_signal_dismissed'
  | 'execution_risk_mitigation_updated'
  | 'execution_warning_clicked'
  | 'delay_detection_viewed'
  | 'delay_signal_detected'
  | 'delay_signal_dismissed'
  | 'delay_alert_sent'
  | 'delay_alert_clicked'
  | 'budget_dashboard_viewed'
  | 'budget_plan_updated'
  | 'budget_actual_updated'
  | 'budget_overspend_signal_detected'
  | 'budget_recommendation_applied'
  | 'roi_assumptions_updated'
  | 'roi_realized_value_updated'
  | 'roi_variance_viewed'
  | 'kpi_created'
  | 'kpi_value_updated'
  | 'kpi_mapping_updated'
  | 'kpi_viewed'
  | 'kpi_attribution_viewed'
  | 'kpi_attribution_parameters_updated'
  | 'kpi_attribution_exported'
  | 'kpi_financial_mapping_created'
  | 'kpi_financial_mapping_updated'
  | 'kpi_financial_impact_viewed'
  | 'integration_sync_hub_viewed'
  | 'integration_connected'
  | 'integration_disconnected'
  | 'integration_reauth_required'
  | 'integration_reauth_completed'
  | 'integration_sync_run_started'
  | 'integration_sync_run_completed'
  | 'integration_error_resolved'
  | 'financial_statement_import_started'
  | 'financial_statement_import_completed'
  | 'financial_statement_import_failed'
  | 'financial_statement_mapping_corrected'
  | 'financial_ratios_viewed'
  | 'financial_benchmark_updated'
  | 'financial_ratio_exported'
  | 'presentation_generator_opened'
  | 'presentation_outline_generated'
  | 'presentation_exported'
  | 'presentation_shared'
  | 'template_selected'
  | 'brand_kit_updated'
  | 'template_cloned'
  | 'template_published'
  | 'report_builder_opened'
  | 'report_section_added'
  | 'report_section_reordered'
  | 'report_section_generated'
  | 'report_section_regenerated'
  | 'report_exported'
  | 'report_shared'
  | 'report_agent_message_sent'
  | 'report_quality_check_run'
  | 'report_template_selected'
  | 'report_template_applied'
  | 'portfolio_ai_analysis_requested'
  | 'portfolio_ai_analysis_succeeded'
  | 'portfolio_ai_analysis_failed'
  | 'portfolio_ai_suggestion_applied'
  | 'portfolio_timeline_optimization_requested'
  | 'portfolio_timeline_scenario_applied'
  | 'portfolio_nonhuman_resources_viewed'
  | 'portfolio_nonhuman_conflict_detected'
  | 'portfolio_scenario_optimization_requested'
  | 'portfolio_scenario_selected'
  | 'portfolio_scenario_applied'
  | 'finance_analysis_generated'
  | 'finance_analysis_approved'
  | 'finance_insight_converted_to_initiative'
  | 'budget_created'
  | 'budget_scenario_updated'
  | 'budget_approved'
  | 'budget_exported'
  | 'financial_model_created'
  | 'financial_model_event_added'
  | 'financial_model_event_updated'
  | 'financial_model_validation_failed'
  | 'financial_model_approved'
  | 'report_schedule_created'
  | 'report_schedule_updated'
  | 'report_schedule_paused'
  | 'report_schedule_trigger_fired'
  | 'report_schedule_run_completed'
  | 'report_schedule_delivery_sent'
  | 'report_schedule_delivery_failed'
  | 'landing_docs_section_viewed'
  | 'landing_docs_cta_clicked'
  | 'landing_docs_search_used'
  | 'landing_viewed'
  | 'landing_primary_cta_clicked'
  | 'pricing_viewed'
  | 'pricing_cta_clicked'
  | 'valuation_created'
  | 'valuation_assumption_updated'
  | 'valuation_approved'
  | 'valuation_exported'
  | 'valuation_advisory_generated'
  | 'valuation_advisory_recommendation_converted'
  | 'valuation_advisory_exported'
  | 'valuation_negotiation_pack_generated'
  | 'valuation_negotiation_pack_exported'
  // T063 — Organization UX
  | 'org_workspace_opened'
  | 'org_admin_cta_clicked'
  | 'org_member_invite_sent'
  // T064 — Megatrend relocation
  | 'megatrends_opened'
  | 'megatrends_redirect_used'
  // T043 — Capability Management
  | 'capability_profile_updated'
  | 'capability_match_viewed'
  | 'capability_assignment_suggestion_generated'
  | 'capability_assignment_applied'
  // T065 — Competency Taxonomy
  | 'competency_created'
  | 'competency_updated'
  | 'competency_deleted'
  | 'initiative_requirement_added'
  | 'initiative_requirement_removed'
  // T066 — Skills Gap Analysis
  | 'skills_gap_viewed'
  | 'skills_gap_action_created'
  // T044 — Change Sentiment
  | 'change_pulse_submitted'
  | 'change_sentiment_trend_changed'
  | 'change_resistance_alert_sent'
  | 'change_resistance_alert_clicked'
  // T045 — Stakeholder Communication
  | 'change_comm_plan_created'
  | 'change_comm_plan_updated'
  | 'change_comm_sent'
  | 'change_comm_overdue_detected'
  // T090 — Demo-to-Trial Conversion
  | 'demo_started'
  | 'demo_value_moment_reached'
  | 'demo_cta_clicked'
  | 'signup_started'
  | 'signup_completed'
  | 'trial_activated'
  // T099 — C-Type Table View
  | 'table_view_mode_changed'
  | 'table_row_quick_action_used'
  // T102 — Sidebar Design System
  | 'sidebar_item_clicked'
  | 'sidebar_collapsed_toggled'
  | 'sidebar_flyout_opened'
  // T104/T105 — Chat UI Polish
  | 'chat_business_button_clicked'
  | 'ai_actions_view_opened'
  // T108 — SuperAdmin Control & System Testing
  | 'superadmin_action_executed'
  | 'superadmin_impersonation_started'
  | 'superadmin_impersonation_ended'
  | 'test_support_bootstrap_called'
  | 'test_support_cleanup_called'
  // T116 — AI Prompt Management & Learning
  | 'prompt_version_published'
  | 'prompt_version_rolled_back'
  | 'prompt_ab_experiment_started'
  | 'prompt_ab_experiment_winner_promoted'
  | 'ai_feedback_submitted'
  | 'ai_learning_instruction_applied'
  // T117 — Core Documentation Layer
  | 'core_docs_reindexed'
  | 'core_docs_drift_detected'
  | 'ai_citation_verification_score'
  // T118 — Web Search Governance
  | 'ai_web_search_used'
  | 'ai_web_search_blocked'
  // T119 — Org Context Governance
  | 'ai_context_category_used'
  | 'ai_context_blocked'
  // T120 — User Privacy
  | 'ai_private_mode_enabled'
  | 'ai_private_mode_disabled'
  | 'ai_memory_write_blocked'
  // T121 — Document Governance
  | 'ai_doc_used'
  | 'ai_doc_blocked'
  // T014 — Survey Shell (additional granularity)
  | 'survey_question_answered'
  | 'survey_section_completed'
  // T067 — CV-Based Matching Engine
  | 'cv_uploaded'
  | 'cv_extracted'
  | 'cv_competencies_approved'
  | 'cv_match_viewed'
  | 'cv_match_applied';

export function trackFunnelEvent(eventName: FunnelEventName, data: Record<string, unknown> = {}) {
  try {
    // Persist last events for debugging/support
    const existing = JSON.parse(sessionStorage.getItem('funnel_events') || '[]');
    existing.push({ eventName, data, timestamp: Date.now() });
    sessionStorage.setItem('funnel_events', JSON.stringify(existing.slice(-100)));
  } catch {
    // ignore
  }

  try {
    if (typeof window !== 'undefined' && (window as any).gtag) {
      (window as any).gtag('event', eventName, data);
    }
  } catch {
    // ignore
  }

  try {
    if (typeof window !== 'undefined' && (window as any).journeyAnalytics) {
      (window as any).journeyAnalytics.trackMilestone?.(eventName, data);
    }
  } catch {
    // ignore
  }
}
