/**
 * AICardDraftModal
 *
 * Whole-card AI generation for initiatives, tasks, and decisions.
 * Accepts a brief, calls the backend to generate a structured draft,
 * and allows selective field application with preview.
 */

import { Check, Loader2, Sparkles, X } from 'lucide-react';
import React, { useCallback, useState } from 'react';
import toast from 'react-hot-toast';
import { useTranslation } from 'react-i18next';

import { Api } from '@/services/api';
import { trackFunnelEvent } from '@/services/funnelAnalytics';

export type ArtifactType = 'initiative' | 'task' | 'decision';

interface AICardDraftModalProps {
  artifactType: ArtifactType;
  projectId: string;
  open: boolean;
  onClose: () => void;
  onApplyFields: (fields: Record<string, string>) => void;
}

const FIELD_LABELS: Record<string, { en: string; pl: string }> = {
  name: { en: 'Name', pl: 'Nazwa' },
  title: { en: 'Title', pl: 'Tytuł' },
  summary: { en: 'Summary', pl: 'Podsumowanie' },
  problem_statement: { en: 'Problem Statement', pl: 'Opis problemu' },
  objectives: { en: 'Objectives', pl: 'Cele' },
  scope: { en: 'Scope', pl: 'Zakres' },
  expected_benefits: { en: 'Expected Benefits', pl: 'Oczekiwane korzyści' },
  success_criteria: { en: 'Success Criteria', pl: 'Kryteria sukcesu' },
  risks_overview: { en: 'Risks Overview', pl: 'Przegląd ryzyk' },
  description: { en: 'Description', pl: 'Opis' },
  acceptance_criteria: { en: 'Acceptance Criteria', pl: 'Kryteria akceptacji' },
  definition_of_done: { en: 'Definition of Done', pl: 'Definicja ukończenia' },
  context: { en: 'Context', pl: 'Kontekst' },
  options_considered: { en: 'Options Considered', pl: 'Rozważane opcje' },
  recommendation: { en: 'Recommendation', pl: 'Rekomendacja' },
  rationale: { en: 'Rationale', pl: 'Uzasadnienie' },
};

export const AICardDraftModal: React.FC<AICardDraftModalProps> = ({
  artifactType,
  projectId,
  open,
  onClose,
  onApplyFields,
}) => {
  const { t, i18n } = useTranslation();
  const isPolish = i18n.language === 'pl';

  const [brief, setBrief] = useState('');
  const [loading, setLoading] = useState(false);
  const [draft, setDraft] = useState<Record<string, string> | null>(null);
  const [selectedFields, setSelectedFields] = useState<Record<string, boolean>>({});

  const handleGenerate = useCallback(async () => {
    if (brief.trim().length < 10) {
      toast.error(
        isPolish ? 'Opis musi mieć min. 10 znaków' : 'Brief must be at least 10 characters'
      );
      return;
    }

    setLoading(true);
    setDraft(null);
    try {
      const res = await Api.post('/ai/generate-card-draft', {
        artifactType,
        brief: brief.trim(),
        projectId,
        language: isPolish ? 'pl' : 'en',
      });

      const generatedDraft = (res as any)?.draft;
      if (!generatedDraft || typeof generatedDraft !== 'object') {
        throw new Error('Invalid draft response');
      }

      setDraft(generatedDraft);
      setSelectedFields(Object.fromEntries(Object.keys(generatedDraft).map((k) => [k, true])));
      trackFunnelEvent('ai_card_generated', {
        artifactType,
        fieldCount: Object.keys(generatedDraft).length,
      });
    } catch (err: any) {
      toast.error(err?.message || t('aiAuthoring.draftFailed', 'Failed to generate draft'));
    } finally {
      setLoading(false);
    }
  }, [brief, artifactType, projectId, isPolish, t]);

  const handleApply = useCallback(() => {
    if (!draft) return;
    const applied: Record<string, string> = {};
    for (const [key, val] of Object.entries(draft)) {
      if (selectedFields[key]) {
        applied[key] = val;
      }
    }
    if (Object.keys(applied).length === 0) {
      toast.error(isPolish ? 'Zaznacz pola do zastosowania' : 'Select fields to apply');
      return;
    }

    onApplyFields(applied);
    trackFunnelEvent('ai_authoring_applied', {
      artifactType,
      fieldCount: Object.keys(applied).length,
      source: 'card_draft',
    });

    Api.post('/ai/authoring-audit', {
      artifactType,
      actionType: 'card_generate',
      inputText: brief,
      outputText: JSON.stringify(applied),
      wasApplied: true,
    }).catch(() => {});

    toast.success(t('aiAuthoring.draftGenerated', 'Draft generated by AI'));
    onClose();
  }, [draft, selectedFields, artifactType, brief, onApplyFields, onClose, isPolish, t]);

  if (!open) return null;

  const titleKey = `aiAuthoring.generate${artifactType.charAt(0).toUpperCase() + artifactType.slice(1)}`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40">
      <div className="w-full max-w-2xl rounded-2xl bg-white/95 dark:bg-navy-900/95 backdrop-blur-xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200/60 dark:border-navy-700/60 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-primary-500/10 to-primary-500/10 dark:from-primary-500/20 dark:to-primary-500/20 flex items-center justify-center">
              <Sparkles size={16} className="text-primary-600 dark:text-primary-400" />
            </div>
            <div>
              <div className="text-sm font-semibold text-slate-700 dark:text-slate-200">
                {t(titleKey, `Generate ${artifactType} draft`)}
              </div>
              <div className="text-xs text-slate-500 dark:text-slate-400">
                {t('aiAuthoring.previewSubtitle', 'Review each section and apply selectively.')}
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-navy-800 text-slate-500 dark:text-slate-400"
          >
            <X size={16} />
          </button>
        </div>

        <div className="p-6 space-y-4 max-h-[70vh] overflow-y-auto">
          {/* Brief input */}
          {!draft && (
            <div className="space-y-3">
              <label className="block text-xs font-semibold text-slate-600 dark:text-slate-300">
                {t('aiAuthoring.briefLabel', 'Brief description')}
              </label>
              <textarea
                value={brief}
                onChange={(e) => setBrief(e.target.value)}
                rows={5}
                placeholder={t(
                  'aiAuthoring.briefPlaceholder',
                  'Describe the initiative/task/decision in 3-8 bullet points...'
                )}
                className="w-full px-3 py-2.5 rounded-xl border border-slate-200/70 dark:border-navy-700/70 bg-white/50 dark:bg-navy-800/50 text-sm text-slate-700 dark:text-slate-200 placeholder-slate-400 dark:placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-primary-500/30 resize-none"
              />
              <button
                onClick={handleGenerate}
                disabled={loading || brief.trim().length < 10}
                className="w-full py-2.5 rounded-xl bg-navy-900 hover:bg-navy-800 dark:bg-[#F4F7FB] dark:text-navy-950 dark:hover:bg-[#DDE5EF] disabled:opacity-40 text-white text-sm font-semibold transition-colors inline-flex items-center justify-center gap-2"
              >
                {loading ? (
                  <>
                    <Loader2 size={16} className="animate-spin" />
                    {t('aiAuthoring.generating', 'Generating draft...')}
                  </>
                ) : (
                  <>
                    <Sparkles size={16} />
                    {t('aiAuthoring.generateCardDraft', 'Generate Card Draft')}
                  </>
                )}
              </button>
            </div>
          )}

          {/* Draft preview */}
          {draft && (
            <div className="space-y-2">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-semibold text-slate-600 dark:text-slate-300">
                  {t('aiAuthoring.previewTitle', 'AI Draft Preview')}
                </span>
                <button
                  onClick={() => {
                    setDraft(null);
                    setSelectedFields({});
                  }}
                  className="text-[11px] text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"
                >
                  {t('aiAuthoring.discardAll', 'Discard')}
                </button>
              </div>

              {Object.entries(draft).map(([key, value]) => {
                const label = FIELD_LABELS[key]
                  ? isPolish
                    ? FIELD_LABELS[key].pl
                    : FIELD_LABELS[key].en
                  : key;
                return (
                  <label
                    key={key}
                    className="flex items-start gap-3 p-3 rounded-xl bg-slate-50/60 dark:bg-navy-800/40 border border-slate-200/60 dark:border-navy-700/60 cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      checked={!!selectedFields[key]}
                      onChange={(e) =>
                        setSelectedFields((p) => ({ ...p, [key]: e.target.checked }))
                      }
                      className="mt-1 shrink-0"
                    />
                    <div className="min-w-0 flex-1">
                      <div className="text-xs font-semibold text-slate-700 dark:text-slate-200 mb-1">
                        {label}
                      </div>
                      <div className="text-xs text-slate-600 dark:text-slate-300 whitespace-pre-wrap leading-relaxed">
                        {value}
                      </div>
                    </div>
                  </label>
                );
              })}
            </div>
          )}
        </div>

        {/* Footer */}
        {draft && (
          <div className="px-6 py-4 border-t border-slate-200/60 dark:border-navy-700/60 flex items-center justify-between bg-slate-50/60 dark:bg-navy-900/40">
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-sm font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-navy-800 transition-colors"
            >
              {isPolish ? 'Zamknij' : 'Close'}
            </button>
            <button
              onClick={handleApply}
              className="px-5 py-2 rounded-xl bg-navy-900 hover:bg-navy-800 dark:bg-[#F4F7FB] dark:text-navy-950 dark:hover:bg-[#DDE5EF] disabled:opacity-40 text-white text-sm font-semibold transition-colors inline-flex items-center gap-2"
            >
              <Check size={16} />
              <span>{t('aiAuthoring.applySelected', 'Apply Selected')}</span>
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default AICardDraftModal;
