/**
 * Canonical Icon Mapping (T101)
 *
 * Single source of truth for icon-to-concept mapping.
 * Used instead of ad-hoc icon choices per screen.
 */

import {
  AlertTriangle,
  Archive,
  BarChart3,
  Bell,
  Briefcase,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Clock,
  Copy,
  CreditCard,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  Flag,
  FolderOpen,
  Globe,
  Grid3x3,
  History,
  Home,
  Info,
  LayoutDashboard,
  LayoutList,
  Link2,
  Loader2,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  MessageSquare,
  MoreVertical,
  Paperclip,
  PenLine,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Sparkles,
  Star,
  Target,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react';

export const ACTION_ICONS: Record<string, LucideIcon> = {
  add: Plus,
  edit: Edit3,
  delete: Trash2,
  download: Download,
  upload: Upload,
  search: Search,
  filter: Filter,
  copy: Copy,
  refresh: RefreshCw,
  close: X,
  more: MoreVertical,
  expand: ChevronDown,
  navigate: ChevronRight,
  link: Link2,
  externalLink: ExternalLink,
  play: Play,
  lock: Lock,
  view: Eye,
  write: PenLine,
  attach: Paperclip,
  send: Mail,
};

export const STATUS_ICONS: Record<string, LucideIcon> = {
  success: CheckCircle2,
  warning: AlertTriangle,
  danger: AlertTriangle,
  info: Info,
  loading: Loader2,
  check: Check,
  star: Star,
  flag: Flag,
};

export const MODULE_ICONS: Record<string, LucideIcon> = {
  chat: MessageSquare,
  myWork: ClipboardList,
  assessment: Shield,
  initiatives: Target,
  execution: Zap,
  benefits: TrendingUp,
  economics: BarChart3,
  reports: FileText,
  tools: Sparkles,
  settings: Settings,
  organization: Briefcase,
  users: Users,
  user: User,
  calendar: Calendar,
  history: History,
  notifications: Bell,
  home: Home,
  dashboard: LayoutDashboard,
  grid: Grid3x3,
  list: LayoutList,
  archive: Archive,
  folder: FolderOpen,
  billing: CreditCard,
  clock: Clock,
  globe: Globe,
  logout: LogOut,
};
