import fs from 'node:fs';
import path from 'node:path';

import type { APIRequestContext, Browser, BrowserContext } from '@playwright/test';

export type MywIdentity = {
  runId: string;
  organizationId: string;
  userId: string;
  token: string;
  role: 'MANAGER' | 'USER';
};

export async function createMember(
  request: APIRequestContext,
  runId: string,
  role: MywIdentity['role']
): Promise<MywIdentity> {
  const response = await request.post('/api/test-support/member', { data: { runId, role } });
  if (response.status() !== 201) {
    throw new Error(
      `member ${role} bootstrap failed: ${response.status()} ${await response.text()}`
    );
  }
  return { ...(await response.json()), role } as MywIdentity;
}

export async function createIdentityContext(
  browser: Browser,
  baseURL: string,
  identity: MywIdentity,
  viewport = { width: 1440, height: 960 }
): Promise<BrowserContext> {
  const context = await browser.newContext({ baseURL, viewport });
  await context.addInitScript(
    ({ auth, origin }) => {
      if (window.location.origin !== origin) return;
      const user = {
        id: auth.userId,
        email: `${auth.role.toLowerCase()}@local.test`,
        role: auth.role,
        organizationId: auth.organizationId,
        organizationName: 'MYW technical tenant',
        firstName: 'E2E',
        lastName: auth.role,
        isAuthenticated: true,
        accessLevel: 'full',
        isDemo: false,
      };
      localStorage.setItem('token', auth.token);
      localStorage.setItem('user', JSON.stringify(user));
      localStorage.setItem(`consultify_onboarding_done:${auth.userId}`, 'true');
      localStorage.setItem(
        'consultify-storage',
        JSON.stringify({
          state: {
            sessionMode: 'FULL',
            isDemoMode: false,
            isDemoSession: false,
            currentUser: user,
            currentOrganization: { id: auth.organizationId, name: 'MYW technical tenant' },
          },
          version: 0,
        })
      );
    },
    { auth: identity, origin: new URL(baseURL).origin }
  );
  return context;
}

export function writeTechnicalResult(filePath: string, value: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

/**
 * Titles seeded for the non-empty success journeys. Deliberately carry the
 * runId so the cleanup query can find them by exact name and so two parallel
 * runs never read each other's rows.
 */
export type MywSeedTitles = {
  taskTitle: string;
  decisionTitle: string;
  planTitle: string;
};

export type MywSeed = MywSeedTitles & {
  taskId: string;
  decisionId: string;
  planId: string;
  /** Rows the canonical inbox materializer actually produced (read back, not assumed). */
  inboxItemCount: number;
  inboxTitles: string[];
};

export function mywSeedTitles(runId: string, role: string): MywSeedTitles {
  const tag = `${runId}-${role}`;
  return {
    taskTitle: `MYW seeded task ${tag}`,
    decisionTitle: `MYW seeded decision ${tag}`,
    planTitle: `MYW seeded plan ${tag}`,
  };
}

async function expectCreated(
  label: string,
  response: Awaited<ReturnType<APIRequestContext['post']>>,
  expected: number[]
): Promise<any> {
  if (!expected.includes(response.status())) {
    throw new Error(`${label} failed: ${response.status()} ${await response.text()}`);
  }
  return response.json();
}

/**
 * Seed a NON-EMPTY My Work state through the REAL, MOUNTED product write
 * endpoints, using the identity's OWN signed token — never a direct INSERT and
 * never a test-only shortcut. Every row below therefore passes the same
 * validation, authorization and persistence path a real user's write does:
 *
 *   · POST /api/my-work/personal-tasks       → Inbox `assigned_tasks` section
 *   · POST /api/decisions                    → Decisions surface + Inbox
 *                                              `decisions_required` section.
 *                                              `sourceType`+`sourceId` is the
 *                                              product's own generic decision
 *                                              context (OKR-E006), so no
 *                                              project/initiative is invented.
 *   · POST /api/ai/agent-plan                → Agent surface ("Moje procesy"),
 *                                              steps generated by the product's
 *                                              own ProcessLibrary (`classic-5`).
 *   · POST /api/v8/my-work/inbox/canonical/materialize
 *                                            → the real materializer, then the
 *                                              canonical table is READ BACK so
 *                                              the caller asserts against rows
 *                                              that genuinely exist in
 *                                              PostgreSQL before any UI claim.
 */
export async function seedMywSurfaces(
  api: APIRequestContext,
  titles: MywSeedTitles
): Promise<MywSeed> {
  const task = await expectCreated(
    'seed personal task',
    await api.post('/api/my-work/personal-tasks', {
      data: { title: titles.taskTitle, status: 'todo', priority: 'high' },
    }),
    [201]
  );

  const decision = await expectCreated(
    'seed decision',
    await api.post('/api/decisions', {
      data: {
        title: titles.decisionTitle,
        description: 'MYW non-empty success journey',
        priority: 'high',
        sourceType: 'my_work_personal_task',
        sourceId: String(task.id),
      },
    }),
    [201]
  );

  const plan = await expectCreated(
    'seed agent plan',
    await api.post('/api/ai/agent-plan', {
      data: {
        title: titles.planTitle,
        description: 'MYW non-empty success journey',
        processId: 'classic-5',
      },
    }),
    [201]
  );

  const materialized = await api.post('/api/v8/my-work/inbox/canonical/materialize');
  if (![200, 201].includes(materialized.status())) {
    throw new Error(
      `canonical inbox materialize failed: ${materialized.status()} ${await materialized.text()}`
    );
  }

  const table = await api.get('/api/v8/my-work/inbox/canonical?limit=200');
  if (table.status() !== 200) {
    throw new Error(`canonical inbox read failed: ${table.status()} ${await table.text()}`);
  }
  const items = (((await table.json())?.data?.items ?? []) as Array<{ title?: string }>) || [];
  const inboxTitles = items.map((item) => String(item?.title ?? ''));

  return {
    ...titles,
    taskId: String(task.id),
    decisionId: String(decision.id),
    planId: String(plan?.plan?.id ?? plan?.id ?? ''),
    inboxItemCount: items.length,
    inboxTitles,
  };
}

/**
 * Guard against this repo's known false-green: an onboarding/consent modal can
 * cover every screen while the surface DOM underneath still "contains" the row,
 * so `toBeVisible()` alone reports a rendered surface that no human could read.
 *
 * Resolve what the browser would actually hit at the row's own centre point and
 * require it to be the row (or inside it). Anything else — an overlay, a
 * backdrop, a dialog — fails here instead of being screenshotted as success.
 */
export async function assertVisibleAndUncovered(locator: any, label: string): Promise<void> {
  await locator.first().waitFor({ state: 'visible', timeout: 30_000 });
  // The Decisions surface stacks ~13 queue panels above its own list, so a real
  // row can sit far below the fold. Being below the fold is not a presentation
  // failure — being covered is. Scroll first, then test what the user would hit.
  await locator.first().scrollIntoViewIfNeeded();
  const covered = await locator.first().evaluate((el: Element) => {
    const rect = el.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0) return 'zero-sized';
    const x = rect.left + rect.width / 2;
    const y = rect.top + rect.height / 2;
    if (x < 0 || y < 0 || x > window.innerWidth || y > window.innerHeight) return 'off-screen';
    const hit = document.elementFromPoint(x, y);
    if (!hit) return 'no-hit';
    if (hit === el || el.contains(hit) || hit.contains(el)) return null;
    const describe = (node: Element) =>
      `${node.tagName.toLowerCase()}${node.id ? `#${node.id}` : ''}` +
      `${node.getAttribute('role') ? `[role=${node.getAttribute('role')}]` : ''}` +
      `${node.className && typeof node.className === 'string' ? `.${node.className.split(/\s+/).filter(Boolean).slice(0, 3).join('.')}` : ''}`;
    return `covered-by:${describe(hit)}`;
  });
  if (covered) {
    throw new Error(`${label} is not genuinely presented to the user (${covered})`);
  }
}
