import fs from 'node:fs';
import path from 'node:path';

import type { APIRequestContext, Browser, BrowserContext } from '@playwright/test';

export type MywIdentity = {
  runId: string;
  organizationId: string;
  userId: string;
  token: string;
  role: 'MANAGER' | 'USER';
};

export async function createMember(
  request: APIRequestContext,
  runId: string,
  role: MywIdentity['role']
): Promise<MywIdentity> {
  const response = await request.post('/api/test-support/member', { data: { runId, role } });
  if (response.status() !== 201) {
    throw new Error(
      `member ${role} bootstrap failed: ${response.status()} ${await response.text()}`
    );
  }
  return { ...(await response.json()), role } as MywIdentity;
}

export async function createIdentityContext(
  browser: Browser,
  baseURL: string,
  identity: MywIdentity,
  viewport = { width: 1440, height: 960 }
): Promise<BrowserContext> {
  const context = await browser.newContext({ baseURL, viewport });
  await context.addInitScript(
    ({ auth, origin }) => {
      if (window.location.origin !== origin) return;
      const user = {
        id: auth.userId,
        email: `${auth.role.toLowerCase()}@local.test`,
        role: auth.role,
        organizationId: auth.organizationId,
        organizationName: 'MYW technical tenant',
        firstName: 'E2E',
        lastName: auth.role,
        isAuthenticated: true,
        accessLevel: 'full',
        isDemo: false,
      };
      localStorage.setItem('token', auth.token);
      localStorage.setItem('user', JSON.stringify(user));
      localStorage.setItem(`consultify_onboarding_done:${auth.userId}`, 'true');
      localStorage.setItem(
        'consultify-storage',
        JSON.stringify({
          state: {
            sessionMode: 'FULL',
            isDemoMode: false,
            isDemoSession: false,
            currentUser: user,
            currentOrganization: { id: auth.organizationId, name: 'MYW technical tenant' },
          },
          version: 0,
        })
      );
    },
    { auth: identity, origin: new URL(baseURL).origin }
  );
  return context;
}

export function writeTechnicalResult(filePath: string, value: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

/**
 * Titles seeded for the non-empty success journeys. Deliberately carry the
 * runId so the cleanup query can find them by exact name and so two parallel
 * runs never read each other's rows.
 */
export type MywSeedTitles = {
  taskTitle: string;
  decisionTitle: string;
  planTitle: string;
};

export type MywSeed = MywSeedTitles & {
  taskId: string;
  decisionId: string;
  planId: string;
  /** Rows the canonical inbox materializer actually produced (read back, not assumed). */
  inboxItemCount: number;
  inboxTitles: string[];
};

export function mywSeedTitles(runId: string, role: string): MywSeedTitles {
  const tag = `${runId}-${role}`;
  return {
    taskTitle: `MYW seeded task ${tag}`,
    decisionTitle: `MYW seeded decision ${tag}`,
    planTitle: `MYW seeded plan ${tag}`,
  };
}

async function expectCreated(
  label: string,
  response: Awaited<ReturnType<APIRequestContext['post']>>,
  expected: number[]
): Promise<any> {
  if (!expected.includes(response.status())) {
    throw new Error(`${label} failed: ${response.status()} ${await response.text()}`);
  }
  return response.json();
}

/**
 * Seed a NON-EMPTY My Work state through the REAL, MOUNTED product write
 * endpoints, using the identity's OWN signed token — never a direct INSERT and
 * never a test-only shortcut. Every row below therefore passes the same
 * validation, authorization and persistence path a real user's write does:
 *
 *   · POST /api/my-work/personal-tasks       → Inbox `assigned_tasks` section
 *   · POST /api/decisions                    → Decisions surface + Inbox
 *                                              `decisions_required` section.
 *                                              `sourceType`+`sourceId` is the
 *                                              product's own generic decision
 *                                              context (OKR-E006), so no
 *                                              project/initiative is invented.
 *   · POST /api/ai/agent-plan                → Agent surface ("Moje procesy"),
 *                                              steps generated by the product's
 *                                              own ProcessLibrary (`classic-5`).
 *   · POST /api/v8/my-work/inbox/canonical/materialize
 *                                            → the real materializer, then the
 *                                              canonical table is READ BACK so
 *                                              the caller asserts against rows
 *                                              that genuinely exist in
 *                                              PostgreSQL before any UI claim.
 */
export async function seedMywSurfaces(
  api: APIRequestContext,
  titles: MywSeedTitles
): Promise<MywSeed> {
  const task = await expectCreated(
    'seed personal task',
    await api.post('/api/my-work/personal-tasks', {
      data: { title: titles.taskTitle, status: 'todo', priority: 'high' },
    }),
    [201]
  );

  const decision = await expectCreated(
    'seed decision',
    await api.post('/api/decisions', {
      data: {
        title: titles.decisionTitle,
        description: 'MYW non-empty success journey',
        priority: 'high',
        sourceType: 'my_work_personal_task',
        sourceId: String(task.id),
      },
    }),
    [201]
  );

  const plan = await expectCreated(
    'seed agent plan',
    await api.post('/api/ai/agent-plan', {
      data: {
        title: titles.planTitle,
        description: 'MYW non-empty success journey',
        processId: 'classic-5',
      },
    }),
    [201]
  );

  const materialized = await api.post('/api/v8/my-work/inbox/canonical/materialize');
  if (![200, 201].includes(materialized.status())) {
    throw new Error(
      `canonical inbox materialize failed: ${materialized.status()} ${await materialized.text()}`
    );
  }

  const table = await api.get('/api/v8/my-work/inbox/canonical?limit=200');
  if (table.status() !== 200) {
    throw new Error(`canonical inbox read failed: ${table.status()} ${await table.text()}`);
  }
  const items = (((await table.json())?.data?.items ?? []) as Array<{ title?: string }>) || [];
  const inboxTitles = items.map((item) => String(item?.title ?? ''));

  return {
    ...titles,
    taskId: String(task.id),
    decisionId: String(decision.id),
    planId: String(plan?.plan?.id ?? plan?.id ?? ''),
    inboxItemCount: items.length,
    inboxTitles,
  };
}

/**
 * Guard against this repo's known false-green: an onboarding/consent modal can
 * cover every screen while the surface DOM underneath still "contains" the row,
 * so `toBeVisible()` alone reports a rendered surface that no human could read.
 *
 * Resolve what the browser would actually hit at the row's own centre point and
 * require it to be the row (or inside it). Anything else — an overlay, a
 * backdrop, a dialog — fails here instead of being screenshotted as success.
 */
export async function assertVisibleAndUncovered(locator: any, label: string): Promise<void> {
  await locator.first().waitFor({ state: 'visible', timeout: 30_000 });
  // The Decisions surface stacks ~13 queue panels above its own list, so a real
  // row can sit far below the fold. Being below the fold is not a presentation
  // failure — being covered is. Scroll first, then test what the user would hit.
  await locator.first().scrollIntoViewIfNeeded();
  const covered = await locator.first().evaluate((el: Element) => {
    const rect = el.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0) return 'zero-sized';
    const x = rect.left + rect.width / 2;
    const y = rect.top + rect.height / 2;
    if (x < 0 || y < 0 || x > window.innerWidth || y > window.innerHeight) return 'off-screen';
    const hit = document.elementFromPoint(x, y);
    if (!hit) return 'no-hit';
    if (hit === el || el.contains(hit) || hit.contains(el)) return null;
    const describe = (node: Element) =>
      `${node.tagName.toLowerCase()}${node.id ? `#${node.id}` : ''}` +
      `${node.getAttribute('role') ? `[role=${node.getAttribute('role')}]` : ''}` +
      `${node.className && typeof node.className === 'string' ? `.${node.className.split(/\s+/).filter(Boolean).slice(0, 3).join('.')}` : ''}`;
    return `covered-by:${describe(hit)}`;
  });
  if (covered) {
    throw new Error(`${label} is not genuinely presented to the user (${covered})`);
  }
}

// ---------------------------------------------------------------------------
// Per-test isolation, asserted cleanup, and residue verified against the
// database itself.
//
// Why this exists: sharing one bootstrap run across tests lets one test's
// residue become another test's phantom pass, and `purgeByOrganizationId`
// swallows every per-table DELETE failure (testSupport.routes.ts:553-559
// catch + logger.warn + continue). A cleanup whose response nobody reads, and
// whose effect nobody re-measures, is not a cleanup that can be claimed.
// ---------------------------------------------------------------------------

/** Bounded on purpose: a real cleanup here measured 87s against 1634 tables. */
export const MYW_CLEANUP_TIMEOUT_MS = 180_000;

export type MywRun = {
  runId: string;
  organizationId: string;
  userId: string;
  token: string;
};

/**
 * A bootstrap run owned by exactly ONE test. The suffix carries the test label
 * plus time and randomness, so two tests — and two concurrent runs of this
 * file — can never collide or clean up each other's rows.
 */
export async function createIsolatedRun(
  support: APIRequestContext,
  baseRunId: string,
  label: string
): Promise<MywRun> {
  const runId = `${baseRunId}-${label}-${Date.now().toString(36)}-${Math.random()
    .toString(36)
    .slice(2, 8)}`;
  const response = await support.post('/api/test-support/bootstrap', { data: { runId } });
  if (!response.ok()) {
    throw new Error(`bootstrap ${runId} failed: ${response.status()} ${await response.text()}`);
  }
  return { ...(await response.json()), runId } as MywRun;
}

export type MywCleanupResult = {
  runId: string;
  status: number;
  body: unknown;
};

/**
 * Cleanup whose RESPONSE IS READ AND ASSERTED. `deleted: false` is the silent
 * no-op path — a run that was never registered, or was already purged — and it
 * must fail loudly rather than be mistaken for a successful clean.
 */
export async function cleanupRunAsserted(
  support: APIRequestContext,
  runId: string
): Promise<MywCleanupResult> {
  const response = await support.post('/api/test-support/cleanup', {
    data: { runId },
    timeout: MYW_CLEANUP_TIMEOUT_MS,
  });
  const status = response.status();
  const body = await response.json().catch(() => null);
  if (status !== 200) {
    throw new Error(`cleanup ${runId} returned ${status}: ${JSON.stringify(body)}`);
  }
  if (!body || (body as any).ok !== true || (body as any).deleted !== true) {
    throw new Error(
      `cleanup ${runId} did not report a real delete (silent no-op?): ${JSON.stringify(body)}`
    );
  }
  return { runId, status, body };
}

/**
 * ---------------------------------------------------------------------------
 * GUARDED CLEANUP + RESIDUE PROVEN BY CAPTURED IDS
 * ---------------------------------------------------------------------------
 *
 * The previous residue check counted ai_agent_plan_steps by JOINING through
 * ai_agent_plans. Cleanup deletes the parent, so after cleanup that inner join
 * matches no parent rows and returns 0 WHETHER OR NOT THE CHILDREN SURVIVED.
 * It reported 0 by construction and could never fail — the same shape of
 * false-green that made the historical evidence wrong.
 *
 * ai_agent_plan_steps carries neither organization_id nor org_id, so
 * purgeByOrganizationId skips it outright; it survives only via
 * ai_agent_plan_steps_plan_id_fkey ON DELETE CASCADE. A lost cascade is exactly
 * what a parent-join can never see. The same applies to decision_history
 * (cascade from decisions) and user_preferences (cascade from users).
 *
 * So: capture the child IDs BEFORE cleanup, then after cleanup query each child
 * table DIRECTLY by those captured IDs — no join, no parent dependency.
 */

/** Fixed, deterministic — NOT random: two harness runs must serialize. */
export const MYW_FIXTURE_ADVISORY_LOCK_KEY = 774811001;

/** Exact names known disposable. */
const DISPOSABLE_DB_EXACT = new Set(['cb_myw']);
/** Prefix used by this program's disposable lanes. */
const DISPOSABLE_DB_PREFIX = 'cb_';

function parseDatabaseName(databaseUrl: string): string {
  return new URL(databaseUrl).pathname.replace(/^\//, '');
}

/**
 * EXACT equality, or EXACT PREFIX equality via startsWith.
 *
 * Deliberately never `includes`/substring: a contains-test would happily accept
 * a production database whose name merely EMBEDS the prefix, e.g.
 * "prod_cb_myw_live" contains "cb_" but must never be cleaned.
 */
export function assertDisposableDatabaseName(dbName: string): void {
  const exact = DISPOSABLE_DB_EXACT.has(dbName);
  const prefixed = dbName.startsWith(DISPOSABLE_DB_PREFIX);
  if (!exact && !prefixed) {
    throw new Error(
      `refusing to mutate "${dbName}": not an exact disposable name (${[...DISPOSABLE_DB_EXACT].join(', ')}) ` +
        `and does not start with "${DISPOSABLE_DB_PREFIX}"`
    );
  }
}

export type FixtureCleanupSession = {
  query: (text: string, values?: unknown[]) => Promise<{ rows: any[] }>;
  release: () => Promise<void>;
};

/**
 * Everything below runs BEFORE any mutation: opt-in, disposable-namespace
 * check, caller-vs-server database EQUALITY check, then a retained
 * deterministic advisory lock held for the whole cleanup.
 */
export async function openGuardedCleanupSession(
  databaseUrl: string
): Promise<FixtureCleanupSession> {
  if (process.env.MYW_ALLOW_FIXTURE_CLEANUP !== '1') {
    throw new Error(
      'refusing to clean: set MYW_ALLOW_FIXTURE_CLEANUP=1 to opt in explicitly. Cleanup deletes rows and is never implicit.'
    );
  }
  const declared = parseDatabaseName(databaseUrl);
  assertDisposableDatabaseName(declared);

  const { Client } = await import('pg');
  const client = new Client({ connectionString: databaseUrl });
  await client.connect();
  try {
    const current = String((await client.query('SELECT current_database() AS db')).rows[0]?.db);
    // EQUALITY, not containment: the database the caller NAMED must be the
    // database the server actually served, or the URL is pointing somewhere else.
    if (current !== declared) {
      throw new Error(
        `database identity mismatch: caller URL names "${declared}" but the server reports "${current}"`
      );
    }
    assertDisposableDatabaseName(current);
    const locked = (
      await client.query('SELECT pg_advisory_lock($1) IS NOT NULL AS ok', [
        MYW_FIXTURE_ADVISORY_LOCK_KEY,
      ])
    ).rows[0]?.ok;
    if (locked !== true) throw new Error('failed to acquire the fixture advisory lock');
  } catch (error) {
    await client.end();
    throw error;
  }

  return {
    query: (text, values) => client.query(text, values as any),
    release: async () => {
      try {
        const released = (
          await client.query('SELECT pg_advisory_unlock($1) AS released', [
            MYW_FIXTURE_ADVISORY_LOCK_KEY,
          ])
        ).rows[0]?.released;
        if (released !== true) {
          throw new Error(`advisory unlock did not return true (got ${JSON.stringify(released)})`);
        }
        const held = Number(
          (
            await client.query(
              "SELECT count(*)::int AS c FROM pg_locks WHERE locktype='advisory' AND pid = pg_backend_pid()"
            )
          ).rows[0]?.c
        );
        if (held !== 0) {
          throw new Error(`session still holds ${held} advisory lock(s) after unlock`);
        }
      } finally {
        await client.end();
      }
    },
  };
}

/**
 * Tables written by this lane that ARE org-scoped, so purgeByOrganizationId can
 * reach them. Enumerated by name — business, audit and telemetry alike.
 * (`audit_events` is scoped by `org_id`, not `organization_id`.)
 */
export const MYW_ORG_SCOPED_TABLES = [
  { table: 'organizations', column: 'id' },
  { table: 'users', column: 'organization_id' },
  { table: 'organization_members', column: 'organization_id' },
  { table: 'tasks', column: 'organization_id' },
  { table: 'decisions', column: 'organization_id' },
  { table: 'ai_agent_plans', column: 'organization_id' },
  { table: 'canonical_inbox_items', column: 'organization_id' },
  { table: 'test_support_runs', column: 'organization_id' },
  { table: 'audit_events', column: 'org_id' },
  { table: 'api_logs', column: 'organization_id' },
] as const;

export type CapturedFixtureIds = {
  agentPlanIds: string[];
  agentPlanStepIds: string[];
  decisionHistoryIds: string[];
  preferenceUserIds: string[];
};

/**
 * Capture the identities of CASCADE-ONLY children BEFORE cleanup. After
 * cleanup their parents are gone, so this is the only moment they can be named.
 */
export async function captureFixtureIds(
  session: FixtureCleanupSession,
  organizationIds: string[]
): Promise<CapturedFixtureIds> {
  const ids = async (sql: string) =>
    (await session.query(sql, [organizationIds])).rows.map((r: any) => String(r.id));
  return {
    agentPlanIds: await ids(
      `SELECT id FROM ai_agent_plans WHERE organization_id = ANY($1::text[])`
    ),
    agentPlanStepIds: await ids(
      `SELECT s.id FROM ai_agent_plan_steps s
       JOIN ai_agent_plans p ON p.id = s.plan_id
       WHERE p.organization_id = ANY($1::text[])`
    ),
    decisionHistoryIds: await ids(
      `SELECT h.id FROM decision_history h
       JOIN decisions d ON d.id = h.decision_id
       WHERE d.organization_id = ANY($1::text[])`
    ),
    preferenceUserIds: await ids(
      `SELECT u.id FROM user_preferences up
       JOIN users u ON u.id = up.user_id
       WHERE u.organization_id = ANY($1::text[])`
    ),
  };
}

export type MywResidue = Record<string, number>;

/**
 * Post-cleanup inventory taken DIRECTLY from PostgreSQL.
 *
 * The cleanup endpoint's own success response proves nothing here:
 * purgeByOrganizationId swallows every per-table DELETE failure
 * (testSupport.routes.ts:553-559 catch + logger.warn + continue), so it can
 * report ok/deleted while rows survive. Only this inventory is evidence.
 *
 * Cascade-only children are counted BY CAPTURED ID — never through a parent
 * join, which after cleanup would return 0 unconditionally.
 */
export async function measureResidueStrict(
  session: FixtureCleanupSession,
  organizationIds: string[],
  captured: CapturedFixtureIds
): Promise<MywResidue> {
  const residue: MywResidue = {};
  for (const { table, column } of MYW_ORG_SCOPED_TABLES) {
    const { rows } = await session.query(
      `SELECT COUNT(*)::int AS count FROM ${table} WHERE ${column} = ANY($1::text[])`,
      [organizationIds]
    );
    residue[table] = Number(rows[0]?.count ?? 0);
  }
  const byId = async (label: string, sql: string, values: string[]) => {
    if (values.length === 0) {
      residue[label] = 0;
      return;
    }
    const { rows } = await session.query(sql, [values]);
    residue[label] = Number(rows[0]?.count ?? 0);
  };
  await byId(
    'ai_agent_plan_steps__by_captured_id',
    `SELECT COUNT(*)::int AS count FROM ai_agent_plan_steps WHERE id = ANY($1::text[])`,
    captured.agentPlanStepIds
  );
  await byId(
    'ai_agent_plans__by_captured_id',
    `SELECT COUNT(*)::int AS count FROM ai_agent_plans WHERE id = ANY($1::text[])`,
    captured.agentPlanIds
  );
  await byId(
    'decision_history__by_captured_id',
    `SELECT COUNT(*)::int AS count FROM decision_history WHERE id = ANY($1::text[])`,
    captured.decisionHistoryIds
  );
  await byId(
    'user_preferences__by_captured_user_id',
    `SELECT COUNT(*)::int AS count FROM user_preferences WHERE user_id = ANY($1::text[])`,
    captured.preferenceUserIds
  );
  return residue;
}

/**
 * Require an exact zero for every enumerated entry, naming each offender.
 *
 * If an append-only table ever lands here its trigger will reject the DELETE,
 * purgeByOrganizationId will swallow that failure, and the count will stay
 * non-zero. Report that number honestly — for such a table zero is reachable
 * only by destroying the database, not by cleaning it.
 */
export function expectNoResidue(residue: MywResidue): void {
  const offenders = Object.entries(residue).filter(([, count]) => count !== 0);
  if (offenders.length > 0) {
    throw new Error(
      `fixture residue not zero: ${offenders.map(([t, c]) => `${t}=${c}`).join(', ')} ` +
        `(full inventory: ${JSON.stringify(residue)})`
    );
  }
}

/** Tables a denied request must not write to. */
export const MYW_WRITE_DELTA_TABLES = ['tasks', 'decisions', 'ai_agent_plans'] as const;

export type WriteSnapshot = Record<string, number>;

/** Row counts scoped to the given organizations, for zero-write deltas. */
export async function snapshotWrites(
  session: FixtureCleanupSession,
  organizationIds: string[]
): Promise<WriteSnapshot> {
  const snapshot: WriteSnapshot = {};
  for (const table of MYW_WRITE_DELTA_TABLES) {
    const { rows } = await session.query(
      `SELECT COUNT(*)::int AS count FROM ${table} WHERE organization_id = ANY($1::text[])`,
      [organizationIds]
    );
    snapshot[table] = Number(rows[0]?.count ?? 0);
  }
  return snapshot;
}

/** A denied request must leave every counted table byte-identical. */
export function expectZeroWriteDelta(
  before: WriteSnapshot,
  after: WriteSnapshot,
  label: string
): void {
  const moved = Object.keys(before).filter((t) => before[t] !== after[t]);
  if (moved.length > 0) {
    throw new Error(
      `${label} was expected to write nothing, but ${moved
        .map((t) => `${t}: ${before[t]} -> ${after[t]}`)
        .join(', ')}`
    );
  }
}

/**
 * The whole teardown, in the only order that proves anything:
 *   guard -> lock -> CAPTURE cascade-only child IDs -> cleanup (response
 *   asserted) -> direct PostgreSQL inventory -> unlock asserted.
 *
 * Capture must precede cleanup: afterwards the parents are gone and the
 * children can no longer be named.
 *
 * NOTE ON ATOMICITY: this is NOT atomic and is never claimed to be.
 * purgeByOrganizationId iterates tables one DELETE at a time and swallows
 * per-table failures, so a partial purge is possible by construction. What is
 * demonstrated here is DETECTION and honest reporting of a partial purge —
 * see the forced-failure test — not atomic cleanup.
 */
export async function guardedCleanupAndAssertNoResidue(
  support: APIRequestContext,
  databaseUrl: string,
  runIds: string[],
  organizationIds: string[]
): Promise<{ residue: MywResidue; captured: CapturedFixtureIds }> {
  const session = await openGuardedCleanupSession(databaseUrl);
  try {
    const captured = await captureFixtureIds(session, organizationIds);
    for (const runId of runIds) {
      await cleanupRunAsserted(support, runId);
    }
    const residue = await measureResidueStrict(session, organizationIds, captured);
    expectNoResidue(residue);
    return { residue, captured };
  } finally {
    await session.release();
  }
}
