
import React from 'react';
import { Zap, Layers, ArrowRight, CheckCircle2, Lock } from 'lucide-react';
import { SessionMode } from '../types';

interface WelcomeViewProps {
  onStartSession: (mode: SessionMode) => void;
  onLoginClick?: () => void;
}

export const WelcomeView: React.FC<WelcomeViewProps> = ({
  onStartSession,
  onLoginClick
}) => {

  // North Star positioning
  const northStar = "The first open consulting ecosystem that teaches leaders to think like Harvard and act in real business — with AI as a partner, not an authority.";

  const text = {
    logIn: 'Log In',
    register: 'Register',
    titleStart: 'Think Strategically.',
    titleEnd: 'Act Decisively.',
    subtitle: 'Learn how to lead transformation with AI as your cognitive partner.',
    northStarLabel: 'What makes this different?',

    // Primary CTA - low pressure demo path
    demoTitle: 'See How It Works',
    demoDesc: 'Watch the system in action. No registration, no pressure. Understand the approach before committing.',
    demoBtn: 'Explore Demo',
    demoTime: '~10 minutes',

    // Secondary paths (de-emphasized)
    quickTitle: 'Quick Assessment',
    quickSteps: '3 Steps',
    quickTime: '~5 minutes',
    quickDesc: 'Instant auto-analysis of your firm. Get personalized recommendations and quick-win ideas generated by AI immediately.',
    quickBtn: 'Start Quick Assessment',

    fullTitle: 'Full Transformation Project',
    fullSteps: '5 Steps',
    fullTime: 'Complete Consulting Flow',
    fullDesc: 'Deep strategic assessment, financial analysis (ROI), roadmap creation, and execution monitoring.',
    fullFeatures: [
      'Full maturity assessment (DRD)',
      'Financial analysis & Roadmap',
      'AI Strategic Advisor'
    ],
    fullBtn: 'Unlock Full Version',

    masterclassTitle: 'Want to deepen your knowledge?',
    masterclassDesc: 'Join our Masterclass program and learn proven tools from transformation leaders.',
    masterclassLink: 'View Masterclass Details',

    videoTitle: 'See how CONSULTIFY works',
    videoPerson: 'Dr. Piotr Wiśniewski',
    videoRole: 'Your guide to digital transformation'
  };

  return (
    <div className="flex flex-col h-full w-full bg-gray-50 dark:bg-navy-950 text-navy-900 dark:text-white overflow-hidden transition-colors duration-300">

      {/* GLOBAL HEADER (Only for Welcome View) */}
      <header className="h-20 border-b border-slate-200 dark:border-elegant flex items-center justify-between px-8 lg:px-12 bg-white dark:bg-navy-950 shrink-0 relative z-50 transition-colors duration-300">
        <div className="flex items-center gap-3 font-bold text-xl tracking-tight text-navy-950 dark:text-white">
          <div className="h-8 px-2 rounded-sm bg-purple-600 flex items-center justify-center shadow-glow">
            <span className="text-white font-bold text-xs tracking-tighter">DBR77</span>
          </div>
          <span className="tracking-widest text-sm">CONSULTIFY</span>
        </div>

        <div className="flex items-center gap-6">

          <div className="h-4 w-px bg-slate-200 dark:bg-white/15"></div>
          <button
            onClick={onLoginClick}
            className="text-sm font-medium text-navy-700 hover:text-purple-600 dark:text-white dark:hover:text-purple-400 transition-colors"
          >
            {text.logIn}
          </button>

          {/* Admin Login Button - Added per request */}

          <button
            onClick={() => onStartSession(SessionMode.FREE)}
            className="px-5 py-2 bg-navy-900 text-white dark:bg-white dark:text-navy-950 hover:bg-navy-800 dark:hover:bg-slate-200 font-semibold text-sm rounded-sm transition-colors"
          >
            {text.register}
          </button>
        </div>
      </header>

      {/* MAIN CONTENT SPLIT */}
      <div className="flex flex-1 overflow-hidden" dir="ltr">

        {/* LEFT COLUMN - PATH SELECTION */}
        <div className="w-1/2 p-8 lg:p-12 flex flex-col justify-center border-r border-slate-200 dark:border-elegant overflow-y-auto">
          <div className="max-w-xl mx-auto w-full space-y-8">

            <div>
              <h1 className="text-3xl lg:text-4xl font-bold mb-2 tracking-tight text-navy-950 dark:text-white">
                {text.titleStart} <span className="text-purple-600 dark:text-purple-500">{text.titleEnd}</span>
              </h1>
              <p className="text-slate-500 dark:text-slate-400 text-lg mb-4">
                {text.subtitle}
              </p>
              {/* North Star Statement */}
              <div className="bg-purple-50 dark:bg-purple-900/20 border border-purple-100 dark:border-purple-500/20 rounded-lg p-4">
                <p className="text-xs font-medium text-purple-600 dark:text-purple-400 mb-1">{text.northStarLabel}</p>
                <p className="text-sm text-slate-700 dark:text-slate-300 italic leading-relaxed">{northStar}</p>
              </div>
            </div>

            <div className="space-y-4">

              {/* PRIMARY CTA: EXPLORE DEMO (Low Pressure Entry) */}
              <div className="group relative bg-gradient-to-br from-purple-600 to-indigo-700 border border-purple-500 rounded-lg p-6 transition-all duration-300 hover:shadow-xl hover:shadow-purple-500/20 cursor-pointer"
                onClick={() => onStartSession(SessionMode.DEMO)}>
                <div className="absolute top-0 right-0 p-4 opacity-50 group-hover:opacity-100 transition-opacity">
                  <ArrowRight className="text-white" size={24} />
                </div>

                <div className="flex items-start gap-4 mb-4">
                  <div className="w-12 h-12 rounded bg-white/10 flex items-center justify-center border border-white/20">
                    <Zap className="text-white" size={24} />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-white">{text.demoTitle}</h3>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-xs font-medium px-2 py-0.5 rounded bg-white/20 text-white">{text.demoTime}</span>
                      <span className="text-xs text-white/70">No registration required</span>
                    </div>
                  </div>
                </div>

                <p className="text-white/80 text-sm mb-6 leading-relaxed">
                  {text.demoDesc}
                </p>

                <button className="w-full py-3 bg-white text-purple-700 font-semibold rounded transition-colors hover:bg-white/90 flex items-center justify-center gap-2">
                  {text.demoBtn}
                </button>
              </div>

              {/* SECONDARY: Quick Assessment */}
              <div className="group relative bg-white dark:bg-navy-900 border border-slate-200 dark:border-white/10 hover:border-purple-500/50 rounded-lg p-5 transition-all duration-300 hover:shadow-md cursor-pointer"
                onClick={() => onStartSession(SessionMode.FREE)}>
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 rounded bg-purple-50 dark:bg-purple-900/30 flex items-center justify-center border border-purple-100 dark:border-purple-500/30">
                    <Zap className="text-purple-600 dark:text-purple-300" size={20} />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold text-navy-900 dark:text-white group-hover:text-purple-600 dark:group-hover:text-purple-400 transition-colors">{text.quickTitle}</h3>
                    <p className="text-xs text-slate-500">{text.quickTime} · {text.quickSteps}</p>
                  </div>
                  <ArrowRight className="text-slate-400 group-hover:text-purple-500 transition-colors" size={20} />
                </div>
              </div>

              {/* OPTION 2: FULL TRANSFORMATION */}
              <div className="group relative bg-white dark:bg-navy-900 border border-slate-200 dark:border-white/10 hover:border-blue-500/50 rounded-lg p-6 transition-all duration-300 cursor-pointer hover:shadow-lg"
                onClick={() => onStartSession(SessionMode.FULL)}>

                <div className="flex items-start gap-4 mb-4">
                  <div className="w-12 h-12 rounded bg-slate-100 dark:bg-navy-800 flex items-center justify-center border border-slate-200 dark:border-white/10 group-hover:border-blue-500/50 transition-colors">
                    <Layers className="text-slate-500 dark:text-slate-300 group-hover:text-blue-500 dark:group-hover:text-blue-400" size={24} />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-navy-900 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">{text.fullTitle}</h3>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-xs font-medium px-2 py-0.5 rounded bg-blue-100 text-blue-700 dark:bg-blue-500/10 dark:text-blue-400 border border-blue-200 dark:border-blue-500/20">{text.fullSteps}</span>
                      <span className="text-xs text-slate-500">{text.fullTime}</span>
                    </div>
                  </div>
                </div>

                <p className="text-slate-500 dark:text-slate-400 text-sm mb-6 leading-relaxed">
                  {text.fullDesc}
                </p>

                <div className="space-y-2 mb-6">
                  {text.fullFeatures.map((feature, idx) => (
                    <div key={idx} className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">
                      <CheckCircle2 size={14} className="text-blue-500" /> <span>{feature}</span>
                    </div>
                  ))}
                </div>

                <button className="w-full py-3 bg-purple-600 hover:bg-purple-500 text-white font-medium rounded transition-colors flex items-center justify-center gap-2">
                  <Lock size={16} />
                  {text.fullBtn}
                </button>
              </div>



              {/* OPTION 3: CONSULTING (New) */}
              <div className="group relative bg-white dark:bg-navy-900 border border-slate-200 dark:border-white/10 hover:border-emerald-500/50 rounded-lg p-6 transition-all duration-300 cursor-pointer hover:shadow-lg"
                onClick={() => window.location.href = '/consulting'}>

                <div className="flex items-start gap-4 mb-4">
                  <div className="w-12 h-12 rounded bg-emerald-50 dark:bg-emerald-900/30 flex items-center justify-center border border-emerald-100 dark:border-emerald-500/30 group-hover:border-emerald-600 transition-colors">
                    <CheckCircle2 className="text-emerald-600 dark:text-emerald-300 group-hover:text-emerald-500" size={24} />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-navy-900 dark:text-white group-hover:text-emerald-600 dark:group-hover:text-emerald-400 transition-colors">Talk to Consulting</h3>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-xs text-slate-500">Custom Engagement</span>
                    </div>
                  </div>
                </div>

                <p className="text-slate-500 dark:text-slate-400 text-sm mb-6 leading-relaxed">
                  Need a bespoke approach? Schedule a call with our senior consultants to discuss your specific transformation needs.
                </p>

                <button className="w-full py-3 bg-white dark:bg-navy-800 border border-slate-200 dark:border-white/20 text-navy-900 dark:text-white font-medium rounded hover:bg-slate-50 dark:hover:bg-navy-700 transition-colors flex items-center justify-center gap-2">
                  Contact Us
                </button>
              </div>

            </div>

          </div>
        </div>

        {/* RIGHT COLUMN - VIDEO INTRO */}
        <div className="w-1/2 relative bg-gray-50 dark:bg-navy-950 flex flex-col items-center justify-center p-12 transition-colors duration-300">
          {/* Decorative background elements */}
          <div className="absolute top-0 right-0 w-full h-full bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-purple-100/50 dark:from-purple-900/20 via-gray-50 dark:via-navy-950 to-gray-50 dark:to-navy-950 pointer-events-none transition-colors duration-300"></div>
          <div className="absolute bottom-0 left-0 w-full h-full bg-[radial-gradient(ellipse_at_bottom_left,_var(--tw-gradient-stops))] from-blue-100/50 dark:from-blue-900/10 via-gray-50 dark:via-navy-950 to-gray-50 dark:to-navy-950 pointer-events-none transition-colors duration-300"></div>

          <div className="relative z-10 w-full max-w-2xl">
            <div className="mb-8 text-center">
              <h2 className="text-2xl font-light tracking-wide text-navy-900 dark:text-white mb-2">{text.videoTitle}</h2>
              <div className="h-0.5 w-16 bg-purple-600 mx-auto"></div>
            </div>

            {/* Video Player Placeholder */}
            <video
              className="aspect-video w-full rounded-xl overflow-hidden shadow-2xl"
              controls
            >
              <source src={`/videos/en.mp4`} type="video/mp4" />
              Your browser does not support the video tag.
            </video>

            <div className="mt-6 text-center">
              <p className="text-lg font-medium text-navy-900 dark:text-white">{text.videoPerson}</p>
              <p className="text-sm text-purple-600 dark:text-purple-400">{text.videoRole}</p>
            </div>

            <div className="mt-12 pt-8 border-t border-slate-200 dark:border-white/10 text-center">
              <h4 className="text-sm font-semibold text-navy-900 dark:text-white mb-2">{text.masterclassTitle}</h4>
              <p className="text-xs text-slate-500 dark:text-slate-400 mb-4 max-w-sm mx-auto">{text.masterclassDesc}</p>
              <a href="#" className="text-xs text-purple-600 dark:text-purple-400 hover:text-purple-500 dark:hover:text-purple-300 underline inline-flex items-center gap-1">
                {text.masterclassLink} →
              </a>
            </div>
          </div>
        </div>
      </div>

    </div >
  );
};
