/**
 * Chat V9 / TRUST T-TR2 — unit tests for the pure reasoning
 * snippet builder.
 *
 * Contract pinned:
 *   - Output length is always [2, 3]; caller can trust the array
 *     never being empty.
 *   - Observation ids are closed-enum tokens (safe React keys).
 *   - Retrieval buckets use strict thresholds: 0 → `none`, 1-3 →
 *     `some`, 4+ → `strong`. Matches TrustBadge's
 *     `bucketSourceCount` so the disclosure can never contradict
 *     the trigger pill.
 *   - `modelLabel` treats empty / whitespace / null / undefined
 *     identically (all → `model-unknown`).
 *   - Priority order is `retrieval → model → verify`.
 *   - The retrieval body for 1 citation is grammatically correct
 *     (no "cites 1 sources" typo).
 */

import { describe, expect, it } from 'vitest';

import {
  buildTrustBadgeReasoning,
  TRUST_REASONING_OBSERVATION_IDS,
} from '../buildTrustBadgeReasoning';

describe('TRUST_REASONING_OBSERVATION_IDS (closed-enum contract)', () => {
  it('freezes the exact list of valid ids', () => {
    expect([...TRUST_REASONING_OBSERVATION_IDS]).toEqual([
      'retrieval-strong',
      'retrieval-some',
      'retrieval-none',
      'model-known',
      'model-unknown',
      'verify',
    ]);
  });
});

describe('buildTrustBadgeReasoning — retrieval bucket', () => {
  it('emits retrieval-none for zero sources', () => {
    const out = buildTrustBadgeReasoning({ citationCount: 0, modelLabel: null });
    expect(out[0].id).toBe('retrieval-none');
    expect(out[0].body).toMatch(/model.*own reasoning/i);
  });

  it('emits retrieval-none for negative / non-finite counts', () => {
    expect(buildTrustBadgeReasoning({ citationCount: -5, modelLabel: null })[0].id).toBe(
      'retrieval-none'
    );
    expect(buildTrustBadgeReasoning({ citationCount: Number.NaN, modelLabel: null })[0].id).toBe(
      'retrieval-none'
    );
  });

  it('emits retrieval-some for 1 source with a singular grammar', () => {
    const out = buildTrustBadgeReasoning({ citationCount: 1, modelLabel: null });
    expect(out[0].id).toBe('retrieval-some');
    expect(out[0].body).toContain('1 retrieved source;');
    expect(out[0].body).not.toContain('1 retrieved sources');
  });

  it('emits retrieval-some for 3 sources', () => {
    expect(buildTrustBadgeReasoning({ citationCount: 3, modelLabel: null })[0].id).toBe(
      'retrieval-some'
    );
  });

  it('emits retrieval-strong at the 4-source threshold (matches TrustBadge bucket)', () => {
    expect(buildTrustBadgeReasoning({ citationCount: 4, modelLabel: null })[0].id).toBe(
      'retrieval-strong'
    );
  });

  it('embeds the raw count in the retrieval-strong body', () => {
    const out = buildTrustBadgeReasoning({ citationCount: 12, modelLabel: null });
    expect(out[0].id).toBe('retrieval-strong');
    expect(out[0].body).toContain('12 retrieved sources');
  });
});

describe('buildTrustBadgeReasoning — model observation', () => {
  it('emits model-known when a non-empty label is provided', () => {
    const out = buildTrustBadgeReasoning({
      citationCount: 0,
      modelLabel: 'GPT-4o',
    });
    expect(out[1].id).toBe('model-known');
    expect(out[1].body).toContain('GPT-4o');
  });

  it('trims surrounding whitespace from the model label', () => {
    const out = buildTrustBadgeReasoning({
      citationCount: 0,
      modelLabel: '   GPT-4o   ',
    });
    expect(out[1].body).toContain('Generated by GPT-4o.');
  });

  it.each([null, undefined, '', '   '])('emits model-unknown for degraded label %p', (label) => {
    const out = buildTrustBadgeReasoning({
      citationCount: 0,
      modelLabel: label as string | null | undefined,
    });
    expect(out[1].id).toBe('model-unknown');
  });
});

describe('buildTrustBadgeReasoning — invariants', () => {
  it('always has exactly 3 observations in priority order', () => {
    const out = buildTrustBadgeReasoning({ citationCount: 2, modelLabel: 'x' });
    expect(out).toHaveLength(3);
    expect(out[0].id.startsWith('retrieval-')).toBe(true);
    expect(out[1].id.startsWith('model-')).toBe(true);
    expect(out[2].id).toBe('verify');
  });

  it('ids remain a subset of the exported closed-enum', () => {
    const out = buildTrustBadgeReasoning({
      citationCount: 100,
      modelLabel: 'claude',
    });
    for (const obs of out) {
      expect(TRUST_REASONING_OBSERVATION_IDS).toContain(obs.id);
    }
  });

  it('every observation has non-empty headline + body', () => {
    const matrix = [
      { citationCount: 0, modelLabel: null },
      { citationCount: 1, modelLabel: 'Claude' },
      { citationCount: 8, modelLabel: undefined },
    ];
    for (const input of matrix) {
      const out = buildTrustBadgeReasoning(input);
      for (const obs of out) {
        expect(obs.headline.length).toBeGreaterThan(0);
        expect(obs.body.length).toBeGreaterThan(0);
      }
    }
  });
});
