/**
 * Chat V9 / TRUST T-TR1.4 — unit tests for
 * `buildTrustBadgeReasoningText`.
 *
 * The formatter is deterministic and dependency-free; these
 * tests pin the exact clipboard payload so accidental format
 * drift is caught at CI time before it reaches users pasting
 * observations into tickets.
 */

import { describe, expect, it } from 'vitest';

import type { TrustReasoningObservation } from '../buildTrustBadgeReasoning';
import { buildTrustBadgeReasoningText } from '../buildTrustBadgeReasoningText';

function obs(
  id: TrustReasoningObservation['id'],
  headline: string,
  body: string
): TrustReasoningObservation {
  return { id, headline, body };
}

describe('buildTrustBadgeReasoningText', () => {
  it('renders a numbered Markdown block with the default header', () => {
    const text = buildTrustBadgeReasoningText([
      obs(
        'retrieval-strong',
        'Grounded in retrieved sources',
        'The reply is grounded in 4 retrieved sources (see list above).'
      ),
      obs('model-known', 'Model used', 'Generated by GPT-4o.'),
      obs(
        'verify',
        'Always verify',
        'Retrieval tells you what the model saw, not whether it is correct. Double-check anything that affects a decision.'
      ),
    ]);

    expect(text).toBe(
      [
        'Why this answer?:',
        '',
        '1. Grounded in retrieved sources — The reply is grounded in 4 retrieved sources (see list above).',
        '2. Model used — Generated by GPT-4o.',
        '3. Always verify — Retrieval tells you what the model saw, not whether it is correct. Double-check anything that affects a decision.',
      ].join('\n')
    );
  });

  it('embeds the humanised model label in the header when provided', () => {
    const text = buildTrustBadgeReasoningText(
      [obs('model-known', 'Model used', 'Generated by GPT-4o.')],
      { modelLabel: 'GPT-4o' }
    );

    expect(text.startsWith('Why this answer? (answered by GPT-4o):')).toBe(true);
  });

  it('ignores empty / whitespace / non-string modelLabel values', () => {
    const valid = [obs('model-unknown', 'Model not recorded', 'None.')];
    expect(buildTrustBadgeReasoningText(valid, { modelLabel: '   ' })).toContain(
      'Why this answer?:'
    );
    expect(buildTrustBadgeReasoningText(valid, { modelLabel: '' })).toContain('Why this answer?:');
    expect(
      buildTrustBadgeReasoningText(valid, {
        modelLabel: undefined as unknown as string,
      })
    ).toContain('Why this answer?:');
    expect(
      buildTrustBadgeReasoningText(valid, {
        modelLabel: 42 as unknown as string,
      })
    ).toContain('Why this answer?:');
  });

  it('returns a graceful stub when the list is empty', () => {
    expect(buildTrustBadgeReasoningText([])).toBe('Why this answer?:\n\nNo reasoning recorded.');
  });

  it('returns the same stub for null / undefined / non-array input', () => {
    const stub = 'Why this answer?:\n\nNo reasoning recorded.';
    expect(buildTrustBadgeReasoningText(null)).toBe(stub);
    expect(buildTrustBadgeReasoningText(undefined)).toBe(stub);
    expect(buildTrustBadgeReasoningText('nope' as unknown as TrustReasoningObservation[])).toBe(
      stub
    );
  });

  it('skips observations with empty or whitespace headline / body', () => {
    const text = buildTrustBadgeReasoningText([
      obs('retrieval-strong', '', 'non-empty body'),
      obs('model-known', 'Model used', '   '),
      obs('verify', 'Always verify', 'verify body'),
    ]);

    expect(text).toBe('Why this answer?:\n\n1. Always verify — verify body');
  });

  it('renumbers by output position so a skipped row does not leave a gap', () => {
    const text = buildTrustBadgeReasoningText([
      obs('retrieval-strong', 'Grounded', 'A.'),
      obs('model-known', '', 'B.'),
      obs('verify', 'Always verify', 'C.'),
    ]);

    expect(text).toContain('1. Grounded — A.');
    expect(text).toContain('2. Always verify — C.');
    expect(text).not.toContain('3.');
  });

  it('skips non-object entries defensively', () => {
    const text = buildTrustBadgeReasoningText([
      null as unknown as TrustReasoningObservation,
      obs('verify', 'Always verify', 'still works'),
      undefined as unknown as TrustReasoningObservation,
      'nope' as unknown as TrustReasoningObservation,
    ]);

    expect(text).toBe('Why this answer?:\n\n1. Always verify — still works');
  });

  it('returns the stub when every observation is filtered out', () => {
    const text = buildTrustBadgeReasoningText([
      obs('retrieval-strong', '  ', 'body'),
      obs('model-known', 'headline', '   '),
    ]);

    expect(text).toBe('Why this answer?:\n\nNo reasoning recorded.');
  });
});
