#!/usr/bin/env tsx
import type { PoolClient } from 'pg';
import { readManifest, restore, runMain, writeManifest, type Manifest, type ManifestEntry, type Mode } from './wspolne.js';

async function plan(c:PoolClient,orgId:string){
  const rows=(await c.query(`SELECT fs.*,coalesce(u.display_name,u.email,fs.created_by,'—') author FROM financial_statements fs LEFT JOIN users u ON u.id=fs.created_by WHERE fs.organization_id=$1 AND fs.period_start>=date '2023-01-01' AND fs.period_end<date '2026-01-01' AND lower(coalesce(fs.status,''))<>'archived' AND coalesce(fs.entity_name,'') !~* 'CD[ -]?PROJEKT' ORDER BY fs.period_start,fs.statement_type`,[orgId])).rows;
  const out=[];for(const r of rows){const mismatch=Number((await c.query(`SELECT count(*)::int n FROM financial_statement_values v JOIN financial_statement_lines l ON l.id=v.canonical_line_id WHERE v.statement_id=$1 AND upper(coalesce(l.statement_type,''))<>upper(coalesce($2,''))`,[r.id,r.statement_type])).rows[0].n);let balance:'OK'|'NIESPINA'|'NIEMIERZALNE'='OK';if(String(r.statement_type).toUpperCase()==='BS'){const totals=await c.query(`SELECT lower(coalesce(l.line_code,'')||' '||coalesce(l.line_name,'')||' '||coalesce(l.line_name_pl,'')) label,v.value::numeric value FROM financial_statement_values v JOIN financial_statement_lines l ON l.id=v.canonical_line_id WHERE v.statement_id=$1 AND (lower(coalesce(l.line_code,'')||' '||coalesce(l.line_name,'')||' '||coalesce(l.line_name_pl,'')) ~ '(total assets|aktywa razem|suma aktyw)' OR lower(coalesce(l.line_code,'')||' '||coalesce(l.line_name,'')||' '||coalesce(l.line_name_pl,'')) ~ '(total liabil|pasywa razem|suma pasyw)')`,[r.id]);if(totals.rows.length<2)balance='NIEMIERZALNE';else if(Number(totals.rows[0].value)!==Number(totals.rows[1].value))balance='NIESPINA';}out.push({r,mismatch,balance,inconsistent:mismatch>0||balance==='NIESPINA'});}return out;
}
async function main(c:PoolClient,org:{id:string;name:string},mode:Mode){if(mode.kind==='rollback'){const m=readManifest(mode.manifest!,'legacy-finanse-2024');await c.query('BEGIN');try{const n=await restore(c,m);await c.query('COMMIT');console.log(`PRZYWRÓCONE: ${n}`)}catch(e){await c.query('ROLLBACK');throw e}return}const p=await plan(c,org.id);for(const x of p)console.log(`${x.r.id} · ${x.r.entity_name??'—'} · ${x.r.statement_type} · ${x.r.period_start}–${x.r.period_end} · bilans=${x.balance} · pozycje w złym typie=${x.mismatch} · ${x.inconsistent?'ARCHIWIZUJ':'ZOSTAW'}`);const bad=p.filter(x=>x.inconsistent);console.log(`PAKIETY: ${p.length}; NIESPÓJNE: ${bad.length}; CD PROJEKT: nietknięty`);if(mode.kind==='dry-run')return;const entries:ManifestEntry[]=[];await c.query('BEGIN');try{for(const x of bad){const q=await c.query(`UPDATE financial_statements SET status='archived',notes=concat_ws(E'\n',nullif(notes,''),'niespójne — decyzja właściciela 06.09'),updated_at=now() WHERE organization_id=$1 AND id=$2 AND lower(coalesce(status,''))<>'archived' RETURNING *`,[org.id,x.r.id]);if(q.rowCount)entries.push({table:'financial_statements',idColumn:'id',id:x.r.id,action:'archive',before:x.r});}await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}const m:Manifest={version:1,script:'legacy-finanse-2024',organizationId:org.id,organizationName:org.name,createdAt:new Date().toISOString(),entries};console.log(`ZMIENIONE: ${entries.length}; manifest: ${writeManifest('legacy-finanse-2024',m)}`)}
runMain('legacy-finanse-2024',main).catch(e=>{console.error(e);process.exitCode=1});
