import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const routesDir = path.resolve(__dirname, '../server/src/routes');

async function fixRoutes() {
  console.log(`Scanning ${routesDir}...`);
  try {
    const files = fs.readdirSync(routesDir);
    for (const file of files) {
      if (file.endsWith('.routes.ts')) {
        const filePath = path.join(routesDir, file);
        let content = fs.readFileSync(filePath, 'utf-8');

        // Check for local JS import OR existing stub
        const match = content.match(/await import\(['"]\.\/([^'"]+)\.js['"]\)/);
        const isStub = content.includes('Autogenerated stub for missing legacy implementation');

        if (match || isStub) {
          const jsFileName = match ? match[1] + '.js' : file.replace('.routes.ts', '.js');
          const jsFilePath = path.join(routesDir, jsFileName);

          if (!fs.existsSync(jsFilePath)) {
            console.log(`Fixing ${file} (references missing ${jsFileName})...`);

            // Create stub content
            const stubContent = `/**
 * ${file.replace('.routes.ts', '')} Routes (Stub)
 * Autogenerated stub for missing legacy implementation
 */
import { Router } from 'express';
// import { aiRateLimiter } from '../middleware/rateLimiting.middleware.js'; // Optional
import logger from '../utils/Logger.js';

const router = Router();

// Stub for missing JS routes
router.use((req, res) => {
    logger.warn(\`[${file.replace('.routes.ts', '')}] Route not implemented (stubbed)\`);
    res.status(501).json({ error: 'Not implemented: Route handler missing' });
});

export default router;
`;
            fs.writeFileSync(filePath, stubContent);
          }
        }
      }
    }
  } catch (error) {
    console.error('Error fixing routes:', error);
  }
}

fixRoutes();
