#!/usr/bin/env python3
"""Generate the exact runtime contract from the reviewed E1 classification."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

TENANT_COLUMNS = ("organization_id", "org_id", "tenant_id")


def ts(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inventory", type=Path, required=True)
    parser.add_argument("--classification", type=Path, required=True)
    parser.add_argument("--baseline-policy", type=Path, required=True)
    parser.add_argument("--foreign-key-contracts", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    inventory = json.loads(args.inventory.read_text(encoding="utf-8"))
    classification = json.loads(args.classification.read_text(encoding="utf-8"))
    baseline = json.loads(args.baseline_policy.read_text(encoding="utf-8"))
    rows = {f"{row['schema']}.{row['table']}": row for row in inventory["tables"]}
    baseline_ids = {f"{row['schema']}.{row['table']}" for row in baseline["tables"]}

    foreign_keys = defaultdict(list)
    with args.foreign_key_contracts.open(encoding="utf-8", newline="") as handle:
        for values in csv.reader(handle, delimiter="\t"):
            if len(values) != 7:
                raise SystemExit(f"invalid FK contract row: {values!r}")
            schema, table, parent_schema, parent_table, columns, parent_columns, delete_action = values
            foreign_keys[f"{schema}.{table}"].append(
                {
                    "columns": columns.split(","),
                    "parentSchema": parent_schema,
                    "parentTable": parent_table,
                    "parentColumns": parent_columns.split(","),
                    "deleteAction": delete_action,
                }
            )

    contracts = []
    for decision in classification["tables"]:
        table_id = f"{decision['schema']}.{decision['table']}"
        row = rows[table_id]
        contract = {
            "schema": decision["schema"],
            "table": decision["table"],
            "category": decision["category"],
            "columnTypes": {column["name"]: column["type"] for column in row["columns"]},
            "primaryKey": row["primaryKey"],
            "foreignKeys": foreign_keys[table_id],
            "counterpartyColumns": [],
            "projection": [],
            "excludedColumns": [],
            "source": decision["sourceEvidence"],
        }
        if decision["category"] == "EXPORT":
            contract["projection"] = decision["projection"]
            contract["excludedColumns"] = decision["excludedColumns"]
            ownership = decision["ownership"]
            if ownership["kind"] in ("ORGANIZATION_ROOT", "DIRECT_COLUMN"):
                contract["ownerColumn"] = ownership["column"]
            else:
                contract["ownerPath"] = ownership["path"]
                terminal_id = table_id
                for edge in ownership["path"]:
                    terminal_id = f"{edge['parentSchema']}.{edge['parentTable']}"
                terminal = rows[terminal_id]
                terminal_columns = {column["name"] for column in terminal["columns"]}
                if terminal_id == "public.organizations":
                    contract["ownerPathTerminalColumn"] = "id"
                else:
                    terminal_column = next((name for name in TENANT_COLUMNS if name in terminal_columns), None)
                    if not terminal_column:
                        raise SystemExit(f"ownership terminal lacks tenant column: {table_id} -> {terminal_id}")
                    contract["ownerPathTerminalColumn"] = terminal_column
        if decision["category"] == "DERIVED":
            contract["derivedFrom"] = decision["derivedFrom"]
        contracts.append(contract)

    header = """// Generated by scripts/enterprise/generate-organization-export-enterprise-contract.py.\n// Exact identities only; do not edit by hand.\nimport type { OrganizationExportTableContract } from './organizationExportContract.js';\n\n"""
    serialized = ts(contracts)
    body = f"export const ORGANIZATION_EXPORT_ENTERPRISE_TABLES = JSON.parse({ts(serialized)}) as readonly OrganizationExportTableContract[];\n"
    args.out.write_text(header + body, encoding="utf-8")
    print(json.dumps({"contracts": len(contracts), "baselineOverlays": len(baseline_ids)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
