/**
 * RoiCaseDecisionWorkspace — the DECISION phase of the ROI Case FULL TOOL.
 * Two Menu 2 sub-views: Approval snapshots (read-only history — system-
 * generated by `approveRoiCase`, no write route exists,
 * `roiCaseApprovalCommands.ts:441-484`) and Compare (the approved/forecast/
 * actual comparison, `GET .../compare`, `roi.routes.ts:2078-2098`).
 *
 * Lifecycle TRANSITIONS themselves (submit/approve/reject/request-changes/
 * reopen-for-revision) are deliberately NOT duplicated here — they already
 * have a real, working UI in `ResultsRoiHub.tsx`'s row-menu kebab
 * (`RoiTransitionDialog`), one implementation, not two. This phase surfaces
 * the DECISION EVIDENCE (approval snapshots, compare view), not a second
 * copy of the transition buttons.
 *
 * Same phase-chip header as the other three phase workspaces —
 * `RoiCasePhaseNav.tsx`.
 */
import React, { useCallback, useEffect, useState } from 'react';

import type { StandardModuleTab, TableRow } from '@/components/standard';

import { ResultsVNextRegistryShell } from '../ResultsVNextRegistryShell';
import type { RoiCaseListItem } from './roiApi';
import { getRoiCaseCompareView, listRoiApprovalSnapshots, type RoiApprovalSnapshot, type RoiCompareView } from './roiCaseFullToolApi';
import {
  buildRoiApprovalSnapshotColumns,
  buildRoiApprovalSnapshotPreview,
  buildRoiApprovalSnapshotRowMenu,
  buildRoiCaseViewsColumns,
  buildRoiCaseViewsPreview,
  buildRoiCaseViewsRowMenu,
  buildRoiCaseViewsRows,
  withRoiFullToolId,
} from './roiCaseFullToolPresenters';
import { buildRoiCasePhaseChips, type RoiCasePhase } from './RoiCasePhaseNav';
import { toUserFacingErrorMessage } from '../shared/errorMessage';

type DecisionTab = 'approval-snapshots' | 'compare';

export interface RoiCaseDecisionWorkspaceProps {
  roiCase: RoiCaseListItem;
  isPolish: boolean;
  onBack: () => void;
  phase: RoiCasePhase;
  onPhaseChange: (phase: RoiCasePhase) => void;
}

export const RoiCaseDecisionWorkspace: React.FC<RoiCaseDecisionWorkspaceProps> = ({ roiCase, isPolish, onBack, phase, onPhaseChange }) => {
  const [tab, setTab] = useState<DecisionTab>('approval-snapshots');
  const phaseChips = buildRoiCasePhaseChips(isPolish);

  const [snapshots, setSnapshots] = useState<RoiApprovalSnapshot[] | null>(null);
  const [snapshotsError, setSnapshotsError] = useState<string | null>(null);
  const [snapshotsLoading, setSnapshotsLoading] = useState(false);
  const [selectedSnapshotId, setSelectedSnapshotId] = useState<string | null>(null);

  const loadSnapshots = useCallback(() => {
    setSnapshotsLoading(true);
    setSnapshotsError(null);
    listRoiApprovalSnapshots(roiCase.caseId)
      .then((rows) => setSnapshots(rows))
      .catch((err) => setSnapshotsError(toUserFacingErrorMessage(err, isPolish)))
      .finally(() => setSnapshotsLoading(false));
  }, [roiCase.caseId]);

  const [compare, setCompare] = useState<RoiCompareView | null | undefined>(undefined);
  const [compareError, setCompareError] = useState<string | null>(null);
  const [compareLoading, setCompareLoading] = useState(false);
  const [compareSelected, setCompareSelected] = useState(false);

  const loadCompare = useCallback(() => {
    setCompareLoading(true);
    setCompareError(null);
    getRoiCaseCompareView(roiCase.caseId)
      .then((v) => setCompare(v))
      .catch((err) => setCompareError(toUserFacingErrorMessage(err, isPolish)))
      .finally(() => setCompareLoading(false));
  }, [roiCase.caseId]);

  useEffect(() => {
    if (tab === 'approval-snapshots' && snapshots === null && !snapshotsLoading) loadSnapshots();
    if (tab === 'compare' && compare === undefined && !compareLoading) loadCompare();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab]);

  const breadcrumbs = [
    { label: isPolish ? 'Rejestr ROI' : 'ROI registry', onClick: onBack },
    { label: roiCase.title },
  ];
  const tabs: StandardModuleTab[] = [
    { id: 'approval-snapshots', label: isPolish ? 'Migawki zatwierdzenia' : 'Approval snapshots' },
    { id: 'compare', label: isPolish ? 'Porównanie' : 'Compare' },
  ];

  if (tab === 'compare') {
    const rows: TableRow[] = compare === undefined ? [] : buildRoiCaseViewsRows(compare, null).filter((r) => r.id === 'compare').map((r) => withRoiFullToolId(r, 'id'));
    const selected = compareSelected ? (rows[0] as any) : null;
    return (
      <ResultsVNextRegistryShell
        domain="roi"
        moduleBar={{
          breadcrumbs, tabs, activeTab: tab, onTabChange: (id) => setTab(id as DecisionTab),
          showTabCounts: false, viewModes: ['table'], viewMode: 'table',
          chips: phaseChips, activeChip: phase, onChipChange: (id) => onPhaseChange(id as RoiCasePhase),
        }}
        table={{
          columns: buildRoiCaseViewsColumns(isPolish),
          data: rows,
          persistKey: 'results-vnext.roi-decision.compare',
          loading: compareLoading,
          error: compareError,
          onRetry: loadCompare,
          selectedRowId: compareSelected ? 'compare' : null,
          onRowClick: () => setCompareSelected(true),
          rowMenu: (row) => buildRoiCaseViewsRowMenu(row as any, isPolish, () => setCompareSelected(true)),
        }}
        preview={selected ? buildRoiCaseViewsPreview(selected, isPolish, () => setCompareSelected(false)) : null}
      />
    );
  }

  const rows: TableRow[] = (snapshots ?? []).map((s) => withRoiFullToolId(s, 'snapshotId'));
  const selected = (snapshots ?? []).find((s) => s.snapshotId === selectedSnapshotId) ?? null;
  return (
    <ResultsVNextRegistryShell
      domain="roi"
      moduleBar={{
        breadcrumbs, tabs, activeTab: tab, onTabChange: (id) => setTab(id as DecisionTab),
        showTabCounts: false, viewModes: ['table'], viewMode: 'table',
        chips: phaseChips, activeChip: phase, onChipChange: (id) => onPhaseChange(id as RoiCasePhase),
      }}
      table={{
        columns: buildRoiApprovalSnapshotColumns(isPolish),
        data: rows,
        persistKey: 'results-vnext.roi-decision.approval-snapshots',
        loading: snapshotsLoading,
        error: snapshotsError,
        onRetry: loadSnapshots,
        empty:
          !snapshotsLoading && !snapshotsError && rows.length === 0
            ? {
                title: isPolish ? 'Brak migawek zatwierdzenia' : 'No approval snapshots yet',
                description: isPolish
                  ? 'Migawka powstaje automatycznie w momencie akceptacji sprawy.'
                  : 'A snapshot is created automatically the moment the case is approved.',
              }
            : undefined,
        selectedRowId: selectedSnapshotId,
        onRowClick: (row) => setSelectedSnapshotId(String(row.snapshotId)),
        rowMenu: (row) => buildRoiApprovalSnapshotRowMenu(row as unknown as RoiApprovalSnapshot, isPolish, (r) => setSelectedSnapshotId(r.snapshotId)),
        defaultSort: { columnId: 'approvedAt', direction: 'desc' },
      }}
      preview={selected ? buildRoiApprovalSnapshotPreview(selected, isPolish, () => setSelectedSnapshotId(null)) : null}
    />
  );
};

export default RoiCaseDecisionWorkspace;
