import type { Deck, DeckCard } from '../wizard/types';

const mockCards: DeckCard[] = [
  {
    card_id: 'card-001',
    deck_id: 'demo-deck',
    order_index: 0,
    intent: 'cover',
    layout_id: 'cover_centered',
    title: 'Q1 2026 Strategic Review',
    blocks: [
      {
        block_id: 'b-001',
        card_id: 'card-001',
        type: 'heading',
        content: { text: 'Q1 2026 Strategic Review', level: 1 },
        is_refreshable: false,
        position: { area: 'full', order: 0 },
        ai_editable: true,
      },
      {
        block_id: 'b-002',
        card_id: 'card-001',
        type: 'paragraph',
        content: { text: 'Steering Committee Update — March 2026' },
        is_refreshable: false,
        position: { area: 'full', order: 1 },
        ai_editable: true,
      },
    ],
    source_refs: [],
    has_refreshable_data: false,
    background: { type: 'gradient', value: 'linear-gradient(135deg, #0B3D91, #1A8A8A)' },
    animations: { entrance: 'fade', block_stagger: false },
    is_locked: false,
  },
  {
    card_id: 'card-002',
    deck_id: 'demo-deck',
    order_index: 1,
    intent: 'executive_summary',
    layout_id: 'content_full',
    title: 'Executive Summary',
    blocks: [
      {
        block_id: 'b-003',
        card_id: 'card-002',
        type: 'heading',
        content: { text: 'Executive Summary', level: 2 },
        is_refreshable: false,
        position: { area: 'full', order: 0 },
        ai_editable: true,
      },
      {
        block_id: 'b-004',
        card_id: 'card-002',
        type: 'bullet_list',
        content: {
          items: [
            'Revenue grew 12% YoY, exceeding targets by 3pp',
            'Three new strategic initiatives launched successfully',
            'Client satisfaction score reached 4.7/5.0',
            'Key risk: supply chain disruption in APAC region',
          ],
        },
        is_refreshable: false,
        position: { area: 'full', order: 1 },
        ai_editable: true,
      },
    ],
    source_refs: [{ artifact_id: 'init-001', artifact_type: 'initiative', artifact_name: 'Digital Transformation' }],
    has_refreshable_data: false,
    background: { type: 'theme' },
    animations: { entrance: 'slide_up', block_stagger: true },
    is_locked: false,
  },
  {
    card_id: 'card-003',
    deck_id: 'demo-deck',
    order_index: 2,
    intent: 'kpi_dashboard',
    layout_id: 'data_grid',
    title: 'Key Performance Indicators',
    blocks: [
      {
        block_id: 'b-005',
        card_id: 'card-003',
        type: 'heading',
        content: { text: 'Key Performance Indicators', level: 2 },
        is_refreshable: false,
        position: { area: 'full', order: 0 },
        ai_editable: true,
      },
      {
        block_id: 'b-006',
        card_id: 'card-003',
        type: 'metric_strip',
        content: {
          metrics: [
            { label: 'Revenue', value: '$2.4M', unit: '' },
            { label: 'Growth', value: '+12%', unit: '' },
            { label: 'NPS', value: '72', unit: '' },
            { label: 'Clients', value: '148', unit: '' },
          ],
        },
        is_refreshable: true,
        position: { area: 'full', order: 1 },
        ai_editable: true,
      },
      {
        block_id: 'b-007',
        card_id: 'card-003',
        type: 'chart',
        content: {
          chartType: 'bar',
          title: 'Quarterly Revenue',
          data: [
            { label: 'Q1', value: 480 },
            { label: 'Q2', value: 620 },
            { label: 'Q3', value: 550 },
            { label: 'Q4', value: 750 },
          ],
        },
        is_refreshable: true,
        position: { area: 'full', order: 2 },
        ai_editable: true,
      },
    ],
    source_refs: [{ artifact_id: 'fa-001', artifact_type: 'financial_analysis', artifact_name: 'Q1 Financial Model' }],
    has_refreshable_data: true,
    background: { type: 'theme' },
    animations: { entrance: 'fade', block_stagger: true },
    is_locked: false,
  },
  {
    card_id: 'card-004',
    deck_id: 'demo-deck',
    order_index: 3,
    intent: 'content',
    layout_id: 'content_full',
    title: 'Strategic Initiatives Progress',
    blocks: [
      {
        block_id: 'b-008',
        card_id: 'card-004',
        type: 'heading',
        content: { text: 'Strategic Initiatives Progress', level: 2 },
        is_refreshable: false,
        position: { area: 'full', order: 0 },
        ai_editable: true,
      },
      {
        block_id: 'b-009',
        card_id: 'card-004',
        type: 'smart_layout',
        content: {
          layoutType: '3col',
          items: [
            { title: 'Digital Transformation', description: 'On track — 72% complete. Cloud migration ahead of schedule.' },
            { title: 'Market Expansion', description: 'At risk — regulatory delays in APAC. Mitigation plan in place.' },
            { title: 'Operational Excellence', description: 'Complete — cost reduction targets exceeded by 15%.' },
          ],
        },
        is_refreshable: false,
        position: { area: 'full', order: 1 },
        ai_editable: true,
      },
    ],
    source_refs: [],
    has_refreshable_data: false,
    background: { type: 'theme' },
    animations: { entrance: 'slide_up', block_stagger: false },
    is_locked: false,
  },
  {
    card_id: 'card-005',
    deck_id: 'demo-deck',
    order_index: 4,
    intent: 'risk_overview',
    layout_id: 'content_full',
    title: 'Risk Overview',
    blocks: [
      {
        block_id: 'b-010',
        card_id: 'card-005',
        type: 'heading',
        content: { text: 'Risk Overview', level: 2 },
        is_refreshable: false,
        position: { area: 'full', order: 0 },
        ai_editable: true,
      },
      {
        block_id: 'b-011',
        card_id: 'card-005',
        type: 'smart_diagram',
        content: {
          diagram_kind: 'matrix_2x2',
          items: [
            { label: 'High Impact / High Probability', description: 'Supply chain disruption in APAC' },
            { label: 'High Impact / Low Probability', description: 'Key talent attrition' },
            { label: 'Low Impact / High Probability', description: 'Minor budget overruns' },
            { label: 'Low Impact / Low Probability', description: 'Technology stack changes' },
          ],
        },
        is_refreshable: false,
        position: { area: 'full', order: 1 },
        ai_editable: true,
      },
    ],
    source_refs: [],
    has_refreshable_data: false,
    background: { type: 'theme' },
    animations: { entrance: 'fade', block_stagger: false },
    is_locked: false,
  },
  {
    card_id: 'card-006',
    deck_id: 'demo-deck',
    order_index: 5,
    intent: 'timeline',
    layout_id: 'timeline_horizontal',
    title: 'Roadmap Q2-Q4 2026',
    blocks: [
      {
        block_id: 'b-012',
        card_id: 'card-006',
        type: 'heading',
        content: { text: 'Roadmap Q2-Q4 2026', level: 2 },
        is_refreshable: false,
        position: { area: 'full', order: 0 },
        ai_editable: true,
      },
      {
        block_id: 'b-013',
        card_id: 'card-006',
        type: 'timeline_block',
        content: {
          items: [
            { date: 'Apr', title: 'Phase 2 Launch' },
            { date: 'Jun', title: 'APAC Market Entry' },
            { date: 'Sep', title: 'Platform v3 Release' },
            { date: 'Dec', title: 'Year-End Review' },
          ],
        },
        is_refreshable: false,
        position: { area: 'full', order: 1 },
        ai_editable: true,
      },
    ],
    source_refs: [],
    has_refreshable_data: false,
    background: { type: 'theme' },
    animations: { entrance: 'slide_up', block_stagger: false },
    is_locked: false,
  },
  {
    card_id: 'card-007',
    deck_id: 'demo-deck',
    order_index: 6,
    intent: 'next_steps',
    layout_id: 'content_full',
    title: 'Next Steps & Decisions',
    blocks: [
      {
        block_id: 'b-014',
        card_id: 'card-007',
        type: 'heading',
        content: { text: 'Next Steps & Decisions Required', level: 2 },
        is_refreshable: false,
        position: { area: 'full', order: 0 },
        ai_editable: true,
      },
      {
        block_id: 'b-015',
        card_id: 'card-007',
        type: 'bullet_list',
        content: {
          items: [
            'Approve Phase 2 budget allocation ($1.2M)',
            'Decide on APAC market entry strategy by April 15',
            'Review and approve revised risk mitigation plan',
            'Schedule deep-dive session on Platform v3 architecture',
          ],
        },
        is_refreshable: false,
        position: { area: 'full', order: 1 },
        ai_editable: true,
      },
      {
        block_id: 'b-016',
        card_id: 'card-007',
        type: 'callout',
        content: { variant: 'info', text: 'Decision deadline: Board meeting April 22, 2026' },
        is_refreshable: false,
        position: { area: 'full', order: 2 },
        ai_editable: true,
      },
    ],
    source_refs: [],
    has_refreshable_data: false,
    background: { type: 'theme' },
    animations: { entrance: 'fade', block_stagger: true },
    is_locked: false,
  },
  {
    card_id: 'card-008',
    deck_id: 'demo-deck',
    order_index: 7,
    intent: 'thank_you',
    layout_id: 'cover_centered',
    title: 'Thank You',
    blocks: [
      {
        block_id: 'b-017',
        card_id: 'card-008',
        type: 'heading',
        content: { text: 'Thank You', level: 1 },
        is_refreshable: false,
        position: { area: 'full', order: 0 },
        ai_editable: true,
      },
      {
        block_id: 'b-018',
        card_id: 'card-008',
        type: 'paragraph',
        content: { text: 'Questions? Contact the Strategy Team at strategy@example.com' },
        is_refreshable: false,
        position: { area: 'full', order: 1 },
        ai_editable: true,
      },
    ],
    source_refs: [],
    has_refreshable_data: false,
    background: { type: 'gradient', value: 'linear-gradient(135deg, #0B3D91, #1A8A8A)' },
    animations: { entrance: 'fade', block_stagger: false },
    is_locked: false,
  },
];

export const MOCK_DECK: Deck = {
  deck_id: 'demo-deck',
  organization_id: 'org-001',
  title: 'Q1 2026 Strategic Review',
  description: 'Steering Committee Update for Q1 2026',
  template_id: 'tmpl-exec-update',
  theme_id: 'ocean',
  presentation_mode: 'briefing',
  communication_register: 'executive',
  image_style_preset: 'abstract_geometric',
  color_set_id: 'ocean',
  status: 'editing',
  card_size: '16:9',
  cards: mockCards,
  source_refs: [
    { artifact_id: 'init-001', artifact_type: 'initiative', artifact_name: 'Digital Transformation' },
    { artifact_id: 'fa-001', artifact_type: 'financial_analysis', artifact_name: 'Q1 Financial Model' },
  ],
  generation_settings: {
    text_mode: 'generate',
    content_depth: 'concise',
    audience: 'executive',
    tone: 'executive',
    language: 'en',
    image_source: 'smart',
  },
  animations_enabled: true,
  share_settings: { is_shared: false, permissions: 'view' },
  speaker_notes_generated: false,
  created_by: 'user-001',
  created_at: '2026-02-28T10:00:00Z',
  updated_at: '2026-02-28T10:00:00Z',
};
