/**
 * Country list for the first-login "work location" selector.
 * Country-level only (not specific plants) — VTS has more sites than we can enumerate.
 * Relevant VTS regions (Poland, Hungary, Lithuania, Latvia, Estonia) are included among
 * the main countries; "Other" is the catch-all fallback.
 */
export const WORK_LOCATION_COUNTRIES: string[] = [
  'Poland',
  'Hungary',
  'Lithuania',
  'Latvia',
  'Estonia',
  'Germany',
  'France',
  'United Kingdom',
  'Ireland',
  'Spain',
  'Portugal',
  'Italy',
  'Netherlands',
  'Belgium',
  'Luxembourg',
  'Switzerland',
  'Austria',
  'Czech Republic',
  'Slovakia',
  'Slovenia',
  'Croatia',
  'Romania',
  'Bulgaria',
  'Greece',
  'Serbia',
  'Ukraine',
  'Moldova',
  'Belarus',
  'Denmark',
  'Sweden',
  'Norway',
  'Finland',
  'Iceland',
  'Turkey',
  'Russia',
  'United States',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'China',
  'India',
  'Japan',
  'South Korea',
  'Singapore',
  'United Arab Emirates',
  'Saudi Arabia',
  'Australia',
  'South Africa',
  'Other',
];
