/**
 * backup Routes (Stub)
 * Autogenerated stub for missing legacy implementation
 */
import { Router } from 'express';

// import { aiRateLimiter } from '../middleware/rateLimiting.middleware.js'; // Optional
import logger from '../utils/Logger.js';

const router = Router();

// Stub for missing JS routes
router.use((req, res) => {
  logger.warn(`[backup] Route not implemented (stubbed)`);
  // Degraded mode: route exists in gateway but feature is unavailable.
  // Avoid 5xx in public deploy smoke checks.
  res.status(404).json({ error: 'Not available' });
});

export default router;
