/**
 * Report Builder Public Routes
 *
 * Public endpoints for accessing shared reports (no authentication required).
 */

import bcrypt from 'bcryptjs';
import { NextFunction, Request, Response, Router } from 'express';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';

import ReportBuilderService from '../services/reportBuilderService.js';
import logger from '../utils/Logger.js';

const router = Router();

// ==========================================
// TYPES
// ==========================================

interface AssessmentMatrixData {
  type: 'assessment_matrix';
  scaleMax: number;
  axes: Array<{
    axisId: string;
    axisName: string;
    score: number;
    maxScore: number;
    gap?: number;
  }>;
}

// ==========================================
// HELPER FUNCTIONS
// ==========================================

const ensureExportDir = async (): Promise<string> => {
  const exportDir = path.resolve(process.cwd(), 'exports', 'report-builder-public');
  await fs.promises.mkdir(exportDir, { recursive: true });
  return exportDir;
};

/**
 * Write PDF for public report
 */
const writePublicReportPdf = async (
  report: any,
  sections: any[],
  branding: { showCompanyLogo: boolean; showConsultinityBranding: boolean; customMessage?: string },
  filePath: string
): Promise<void> => {
  const doc = new PDFDocument({ margin: 48, size: 'A4' });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // Title page
  doc
    .fontSize(24)
    .fillColor('#1e293b')
    .text(report.title || 'Report', { align: 'center' });
  doc.moveDown(0.5);

  if (report.sourceName) {
    doc.fontSize(12).fillColor('#64748b').text(`Source: ${report.sourceName}`, { align: 'center' });
  }
  doc.fontSize(10).fillColor('#94a3b8').text(`Generated: ${new Date().toLocaleDateString()}`, {
    align: 'center',
  });

  if (branding.customMessage) {
    doc.moveDown(1);
    doc.fontSize(11).fillColor('#475569').text(branding.customMessage, { align: 'center' });
  }

  doc.moveDown(2);

  // Sections
  const enabledSections = sections
    .filter((s) => s.enabled !== false)
    .sort((a, b) => (a.orderIndex || 0) - (b.orderIndex || 0));

  for (const section of enabledSections) {
    const content = section.content || section.editedContent || section.generatedContent || '';
    if (!content) continue;

    // Section title
    doc.fontSize(16).fillColor('#1e293b').text(section.title);
    doc.moveDown(0.3);

    // Check if it's a matrix section
    const isMatrix = section.sectionType === 'matrix' || section.renderKind === 'matrix';
    if (isMatrix) {
      try {
        const matrixData = JSON.parse(content) as AssessmentMatrixData;
        if (matrixData.type === 'assessment_matrix' && matrixData.axes) {
          // Render matrix as table
          doc.fontSize(10).fillColor('#64748b').text('Assessment Matrix', { underline: true });
          doc.moveDown(0.3);

          const tableTop = doc.y;
          const startX = 48;

          // Header
          doc.fontSize(9).fillColor('#475569');
          doc.text('Axis', startX, tableTop);
          doc.text('Score', startX + 200, tableTop);
          doc.text('Max', startX + 260, tableTop);

          let currentY = tableTop + 20;

          for (const axis of matrixData.axes) {
            doc.fontSize(9).fillColor('#1e293b');
            doc.text(axis.axisName || axis.axisId, startX, currentY, { width: 190 });
            doc.text(axis.score?.toFixed(1) || '—', startX + 200, currentY);
            doc.text(String(axis.maxScore || matrixData.scaleMax), startX + 260, currentY);
            currentY += 20;

            // Page break if needed
            if (currentY > doc.page.height - 100) {
              doc.addPage();
              currentY = 48;
            }
          }

          doc.y = currentY + 10;
        }
      } catch {
        // If parsing fails, render as text
        doc.fontSize(11).fillColor('#334155').text(content);
      }
    } else {
      // Regular markdown content - render as plain text
      const plainText = content
        .replace(/#{1,6}\s/g, '')
        .replace(/\*\*(.*?)\*\*/g, '$1')
        .replace(/\*(.*?)\*/g, '$1')
        .replace(/`(.*?)`/g, '$1')
        .replace(/\[(.*?)\]\(.*?\)/g, '$1')
        .replace(/^[-*]\s/gm, '• ');

      doc.fontSize(11).fillColor('#334155').text(plainText, {
        align: 'justify',
        lineGap: 2,
      });
    }

    doc.moveDown(1.5);

    // Page break if needed
    if (doc.y > doc.page.height - 150) {
      doc.addPage();
    }
  }

  // Footer with branding
  if (branding.showConsultinityBranding) {
    doc.fontSize(8).fillColor('#94a3b8');
    doc.text('Generated by Consultify', 48, doc.page.height - 40);
  }

  doc.end();
  await new Promise<void>((resolve, reject) => {
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
};

// ==========================================
// PUBLIC ENDPOINTS
// ==========================================

/**
 * GET /api/public/report/:token
 * Access a shared report via public link (no auth required)
 */
router.get('/:token', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { token } = req.params;
    const { password } = req.query;

    const result = await ReportBuilderService.getPublicLinkByToken(token);

    if (!result) {
      return res.status(404).json({ error: 'Link not found or expired' });
    }

    // Check password if required
    if (result.link.passwordHash) {
      if (!password || typeof password !== 'string') {
        return res.status(401).json({ error: 'Password required', requiresPassword: true });
      }

      const passwordValid = await bcrypt.compare(password, result.link.passwordHash);
      if (!passwordValid) {
        return res.status(401).json({ error: 'Invalid password', requiresPassword: true });
      }
    }

    // Return report data for public view
    res.json({
      report: {
        id: result.report.id,
        title: result.report.title,
        sourceName: result.report.sourceName,
        status: result.report.status,
        createdAt: result.report.createdAt,
      },
      sections: result.sections
        .filter((s) => s.enabled)
        .sort((a, b) => a.orderIndex - b.orderIndex)
        .map((s) => ({
          sectionKey: s.sectionKey,
          sectionType: s.sectionType,
          title: s.title,
          content: s.editedContent || s.generatedContent || '',
          renderKind: s.renderKind,
        })),
      branding: {
        showCompanyLogo: result.link.showCompanyLogo,
        showConsultinityBranding: result.link.showConsultinityBranding,
        customMessage: result.link.customMessage,
      },
    });
  } catch (err) {
    logger.error('[ReportBuilderPublic] Error accessing public link:', err);
    next(err);
  }
});

/**
 * GET /api/public/report/:token/pdf
 * Download PDF of a shared report (no auth required)
 */
router.get('/:token/pdf', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { token } = req.params;
    const { password } = req.query;

    const result = await ReportBuilderService.getPublicLinkByToken(token);

    if (!result) {
      return res.status(404).json({ error: 'Link not found or expired' });
    }

    // Check password if required
    if (result.link.passwordHash) {
      if (!password || typeof password !== 'string') {
        return res.status(401).json({ error: 'Password required', requiresPassword: true });
      }

      const passwordValid = await bcrypt.compare(password, result.link.passwordHash);
      if (!passwordValid) {
        return res.status(401).json({ error: 'Invalid password', requiresPassword: true });
      }
    }

    // Generate PDF
    const exportDir = await ensureExportDir();
    const fileName = `public-${token}-${Date.now()}.pdf`;
    const filePath = path.join(exportDir, fileName);

    const enabledSections = result.sections
      .filter((s) => s.enabled)
      .sort((a, b) => a.orderIndex - b.orderIndex);

    await writePublicReportPdf(
      result.report,
      enabledSections,
      {
        showCompanyLogo: result.link.showCompanyLogo,
        showConsultinityBranding: result.link.showConsultinityBranding,
        customMessage: result.link.customMessage,
      },
      filePath
    );

    logger.info('[ReportBuilderPublic] PDF downloaded via public link', {
      reportId: result.report.id,
      token,
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="${result.report.title || 'report'}.pdf"`
    );
    return res.sendFile(filePath);
  } catch (err: any) {
    logger.error('[ReportBuilderPublic] Error downloading public PDF:', err);
    return res.status(500).json({ error: 'Failed to generate PDF', message: err.message });
  }
});

/**
 * POST /api/public/report/:token/verify-password
 * Verify password for a protected shared report
 */
router.post('/:token/verify-password', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { token } = req.params;
    const { password } = req.body;

    // Get link without incrementing view count
    const { getDatabase } = await import('../database/index.js');
    const db = getDatabase();

    const linkRow = await new Promise<any>((resolve, reject) => {
      db.get(
        `SELECT * FROM report_public_links WHERE link_token = ? AND revoked_at IS NULL`,
        [token],
        (err: Error | null, row: any) => {
          if (err) reject(err);
          else resolve(row);
        }
      );
    });

    if (!linkRow) {
      return res.status(404).json({ error: 'Link not found' });
    }

    // Check expiration
    if (linkRow.expires_at && new Date(linkRow.expires_at) < new Date()) {
      return res.status(404).json({ error: 'Link expired' });
    }

    // If no password required
    if (!linkRow.password_hash) {
      return res.json({ valid: true, requiresPassword: false });
    }

    // Verify password
    if (!password || typeof password !== 'string') {
      return res.json({ valid: false, requiresPassword: true });
    }

    const passwordValid = await bcrypt.compare(password, linkRow.password_hash);
    res.json({ valid: passwordValid, requiresPassword: true });
  } catch (err) {
    logger.error('[ReportBuilderPublic] Error verifying password:', err);
    next(err);
  }
});

export default router;
