/**
 * Report PDF + Cadence Routes (M14 / ExecutionHub)
 *
 * Slice F8 (8.4) — server-side status-report PDF download. The report bytes are
 * generated by the pure `reportPdfService.renderReportPdf` (no browser needed),
 * so this route only handles auth, org-scoped fetch, and streaming the Buffer.
 *
 * Slice F6 (6.3) — cadence due-detection. `reportCadenceService.findDueReports`
 * decides which (initiative, periodType) pairs are due for a fresh report. This
 * route exposes that list read-only; it does NOT trigger generation.
 *
 * Auth mirrors `status-reports.routes.ts`: verifyToken + isAuthenticated, org
 * taken from `req.user.organizationId`, handlers wrapped in `asyncHandler`.
 *
 * Mounted in Gateway.ts at `/api/report-pdf` (see `app.use('/api/report-pdf',
 * reportPdfRoutes)`).
 */
import { Request, Response, Router } from 'express';

import { isAuthenticated, verifyToken } from '../middleware/auth.middleware.js';
// Default-import both services: the repo-wide ambient `declare module '*.js'`
// (src/types/custom.d.ts) only surfaces the `default` named export for `.js`
// specifiers, so destructuring named exports (findDueReports/renderReportPdf)
// would fail to type-check. The default objects expose the same functions.
import reportCadenceService from '../services/reportCadenceService.js';
import reportPdfService from '../services/reportPdfService.js';
import statusReportService from '../services/statusReportService.js';
import { asyncHandler } from '../utils/asyncHandler.js';

const { findDueReports } = reportCadenceService;
const { renderReportPdf } = reportPdfService;

const router = Router();

interface AuthRequest extends Request {
  user?: { id: string; organizationId: string };
}

function paramStr(value: string | string[] | undefined): string {
  return Array.isArray(value) ? String(value[0] || '') : String(value || '');
}

// ─── F6 · 6.3 — Cadence: which reports are due ─────────────────────────────
// Registered before the `/:reportId/pdf` route so the literal `cadence`
// segment is never captured as a reportId.
router.get(
  '/cadence/due',
  verifyToken,
  isAuthenticated,
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const orgId = req.user?.organizationId;
    if (!orgId) return res.status(401).json({ error: 'Unauthorized' });
    // Date.now() at request time is intentional — cadence is evaluated "now".
    const due = await findDueReports(orgId, Date.now());
    return res.json({ due });
  })
);

// ─── F8 · 8.4 — Server-side PDF download ───────────────────────────────────
router.get(
  '/:reportId/pdf',
  verifyToken,
  isAuthenticated,
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const orgId = req.user?.organizationId;
    if (!orgId) return res.status(401).json({ error: 'Unauthorized' });

    const reportId = paramStr(req.params.reportId);
    const report = await statusReportService.getReport(reportId, orgId);
    if (!report) return res.status(404).json({ error: 'Report not found' });

    const pdf = await renderReportPdf(report);

    const safeName = String(report.initiativeName || 'status-report')
      .replace(/[^a-zA-Z0-9._-]+/g, '_')
      .slice(0, 80);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}-${reportId}.pdf"`);
    res.setHeader('Content-Length', String(pdf.length));
    return res.send(pdf);
  })
);

export default router;
