/**
 * report-comments Routes (Stub)
 * Autogenerated stub for missing legacy implementation
 */
import { Router } from 'express';

// import { aiRateLimiter } from '../middleware/rateLimiting.middleware.js'; // Optional
import logger from '../utils/Logger.js';

const router = Router();

// Stub for missing JS routes
router.use((req, res) => {
  logger.warn(`[report-comments] Route unavailable (no real implementation)`);
  res.status(503).json({
    success: false,
    error: 'Report comments are not available (no real implementation)',
  });
});

export default router;
