/**
 * Report Builder Public Routes
 *
 * Public endpoints for accessing shared reports (no authentication required).
 */

import bcrypt from 'bcryptjs';
import { Document, HeadingLevel, Packer, Paragraph, TextRun } from 'docx';
import { NextFunction, Request, Response, Router } from 'express';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';

import config from '../config/Config.js';
import ReportBuilderService from '../services/reportBuilderService.js';
import logger from '../utils/Logger.js';
import { exportsDir } from '../utils/storagePaths.js';

const router = Router();

// ==========================================
// TYPES
// ==========================================

interface AssessmentMatrixData {
  type: 'assessment_matrix';
  scaleMax: number;
  axes: Array<{
    axisId: string;
    axisName: string;
    score: number;
    maxScore: number;
    gap?: number;
  }>;
}

// ==========================================
// HELPER FUNCTIONS
// ==========================================

const ensureExportDir = async (): Promise<string> => {
  return exportsDir('report-builder-public');
};

/**
 * Write PDF for public report
 */
const writePublicReportPdf = async (
  report: any,
  sections: any[],
  branding: { showCompanyLogo: boolean; showConsultifyBranding: boolean; customMessage?: string },
  filePath: string
): Promise<void> => {
  const doc = new PDFDocument({ margin: 48, size: 'A4' });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // Title page
  doc
    .fontSize(24)
    .fillColor('#1e293b')
    .text(report.title || 'Report', { align: 'center' });
  doc.moveDown(0.5);

  if (report.sourceName) {
    doc.fontSize(12).fillColor('#64748b').text(`Source: ${report.sourceName}`, { align: 'center' });
  }
  doc.fontSize(10).fillColor('#94a3b8').text(`Generated: ${new Date().toLocaleDateString()}`, {
    align: 'center',
  });

  if (branding.customMessage) {
    doc.moveDown(1);
    doc.fontSize(11).fillColor('#475569').text(branding.customMessage, { align: 'center' });
  }

  doc.moveDown(2);

  // Sections
  const enabledSections = sections
    .filter((s) => s.enabled !== false)
    .sort((a, b) => (a.orderIndex || 0) - (b.orderIndex || 0));

  for (const section of enabledSections) {
    const content = section.content || section.editedContent || section.generatedContent || '';
    if (!content) continue;

    // Section title
    doc.fontSize(16).fillColor('#1e293b').text(section.title);
    doc.moveDown(0.3);

    // Check if it's a matrix section
    const isMatrix = section.sectionType === 'matrix' || section.renderKind === 'matrix';
    if (isMatrix) {
      try {
        const matrixData = JSON.parse(content) as AssessmentMatrixData;
        if (matrixData.type === 'assessment_matrix' && matrixData.axes) {
          // Render matrix as table
          doc.fontSize(10).fillColor('#64748b').text('Assessment Matrix', { underline: true });
          doc.moveDown(0.3);

          const tableTop = doc.y;
          const startX = 48;

          // Header
          doc.fontSize(9).fillColor('#475569');
          doc.text('Axis', startX, tableTop);
          doc.text('Score', startX + 200, tableTop);
          doc.text('Max', startX + 260, tableTop);

          let currentY = tableTop + 20;

          for (const axis of matrixData.axes) {
            doc.fontSize(9).fillColor('#1e293b');
            doc.text(axis.axisName || axis.axisId, startX, currentY, { width: 190 });
            doc.text(axis.score?.toFixed(1) || '—', startX + 200, currentY);
            doc.text(String(axis.maxScore || matrixData.scaleMax), startX + 260, currentY);
            currentY += 20;

            // Page break if needed
            if (currentY > doc.page.height - 100) {
              doc.addPage();
              currentY = 48;
            }
          }

          doc.y = currentY + 10;
        }
      } catch {
        // If parsing fails, render as text
        doc.fontSize(11).fillColor('#334155').text(content);
      }
    } else {
      // Regular markdown content - render as plain text
      const plainText = content
        .replace(/#{1,6}\s/g, '')
        .replace(/\*\*(.*?)\*\*/g, '$1')
        .replace(/\*(.*?)\*/g, '$1')
        .replace(/`(.*?)`/g, '$1')
        .replace(/\[(.*?)\]\(.*?\)/g, '$1')
        .replace(/^[-*]\s/gm, '• ');

      doc.fontSize(11).fillColor('#334155').text(plainText, {
        align: 'justify',
        lineGap: 2,
      });
    }

    doc.moveDown(1.5);

    // Page break if needed
    if (doc.y > doc.page.height - 150) {
      doc.addPage();
    }
  }

  // Footer with branding
  if (branding.showConsultifyBranding) {
    doc.fontSize(8).fillColor('#94a3b8');
    doc.text('Generated by Consultify', 48, doc.page.height - 40);
  }

  doc.end();
  await new Promise<void>((resolve, reject) => {
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
};

function markdownToPlainText(content: string): string {
  return String(content || '')
    .replace(/#{1,6}\s/g, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`(.*?)`/g, '$1')
    .replace(/\[(.*?)\]\(.*?\)/g, '$1')
    .replace(/^[-*]\s/gm, '• ')
    .trim();
}

/**
 * Write DOCX for public report
 */
const writePublicReportDocx = async (
  report: any,
  sections: any[],
  branding: { showCompanyLogo: boolean; showConsultifyBranding: boolean; customMessage?: string },
  filePath: string
): Promise<void> => {
  const children: Paragraph[] = [];

  // Title page-ish header
  children.push(
    new Paragraph({
      text: String(report.title || 'Report'),
      heading: HeadingLevel.TITLE,
    })
  );
  if (report.sourceName) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: `Source: ${String(report.sourceName)}`, color: '64748B' })],
      })
    );
  }
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: `Generated: ${new Date().toLocaleDateString()}`, color: '94A3B8' }),
      ],
    })
  );
  if (branding.customMessage) {
    children.push(new Paragraph({ text: String(branding.customMessage) }));
  }
  children.push(new Paragraph({ text: '' }));

  const enabledSections = sections
    .filter((s) => s.enabled !== false)
    .sort((a, b) => (a.orderIndex || 0) - (b.orderIndex || 0));

  for (const section of enabledSections) {
    const raw = section.content || section.editedContent || section.generatedContent || '';
    if (!raw) continue;

    children.push(
      new Paragraph({
        text: String(section.title || section.sectionKey || 'Section'),
        heading: HeadingLevel.HEADING_1,
      })
    );

    const isMatrix = section.sectionType === 'matrix' || section.renderKind === 'matrix';
    if (isMatrix) {
      try {
        const matrixData = JSON.parse(String(raw)) as AssessmentMatrixData;
        if (matrixData?.type === 'assessment_matrix' && Array.isArray(matrixData.axes)) {
          for (const axis of matrixData.axes) {
            children.push(
              new Paragraph({
                text: `${axis.axisName || axis.axisId}: ${axis.score?.toFixed?.(1) ?? axis.score} / ${
                  axis.maxScore || matrixData.scaleMax
                }`,
              })
            );
          }
        } else {
          children.push(new Paragraph({ text: markdownToPlainText(raw) }));
        }
      } catch {
        children.push(new Paragraph({ text: markdownToPlainText(raw) }));
      }
    } else {
      const plain = markdownToPlainText(raw);
      const parts = plain
        .split(/\n{2,}|\n/)
        .map((p) => p.trim())
        .filter(Boolean);
      if (parts.length === 0) {
        children.push(new Paragraph({ text: '' }));
      } else {
        for (const p of parts) {
          children.push(new Paragraph({ text: p }));
        }
      }
    }

    children.push(new Paragraph({ text: '' }));
  }

  if (branding.showConsultifyBranding) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: 'Generated by Consultify', color: '94A3B8' })],
      })
    );
  }

  const doc = new Document({ sections: [{ children }] });
  const buffer = await Packer.toBuffer(doc);
  await fs.promises.writeFile(filePath, buffer);
};

// ==========================================
// PUBLIC ENDPOINTS
// ==========================================

/**
 * GET /api/public/report/:token
 * Access a shared report via public link (no auth required)
 */
router.get('/:token', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const tokenParam = req.params.token;
    const token = Array.isArray(tokenParam) ? tokenParam[0] : tokenParam;
    const { password } = req.query;

    const result = await ReportBuilderService.getPublicLinkByToken(token);

    if (!result) {
      return res.status(404).json({ error: 'Link not found or expired' });
    }

    // Check password if required
    if (result.link.passwordHash) {
      if (!password || typeof password !== 'string') {
        return res.status(401).json({ error: 'Password required', requiresPassword: true });
      }

      const passwordValid = await bcrypt.compare(password, result.link.passwordHash);
      if (!passwordValid) {
        return res.status(401).json({ error: 'Invalid password', requiresPassword: true });
      }
    }

    // Return enriched report data for public view
    const reportConfig =
      typeof result.report.config === 'string'
        ? JSON.parse(result.report.config)
        : result.report.config || {};

    res.json({
      report: {
        id: result.report.id,
        title: result.report.title,
        description: (result.report as any).description,
        sourceName: result.report.sourceName,
        sourceFramework: result.report.sourceFramework,
        status: result.report.status,
        createdAt: result.report.createdAt,
        config: {
          intent: reportConfig.intent || {},
          styling: reportConfig.styling || {},
          language: reportConfig.language,
          chapters: reportConfig.chapters || [],
        },
      },
      sections: result.sections
        .filter((s) => s.enabled)
        .sort((a, b) => a.orderIndex - b.orderIndex)
        .map((s) => ({
          sectionKey: s.sectionKey,
          sectionType: s.sectionType,
          title: s.title,
          content: s.editedContent || s.generatedContent || '',
          renderKind: s.renderKind,
          blockTypeId: (s as any).blockTypeId,
          blockConfig:
            typeof (s as any).blockConfig === 'string'
              ? JSON.parse((s as any).blockConfig || '{}')
              : (s as any).blockConfig || {},
          contentFormat: (s as any).contentFormat,
          orderIndex: s.orderIndex,
          chapter: (s as any).chapter,
        })),
      branding: {
        showCompanyLogo: result.link.showCompanyLogo,
        showConsultifyBranding: result.link.showConsultifyBranding,
        customMessage: result.link.customMessage,
      },
    });
  } catch (err) {
    logger.error('[ReportBuilderPublic] Error accessing public link:', err);
    next(err);
  }
});

/**
 * GET /api/public/report/:token/pdf
 * Download PDF of a shared report (no auth required)
 */
router.get('/:token/pdf', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const tokenParam = req.params.token;
    const token = Array.isArray(tokenParam) ? tokenParam[0] : tokenParam;
    const { password } = req.query;

    const result = await ReportBuilderService.getPublicLinkByToken(token);

    if (!result) {
      return res.status(404).json({ error: 'Link not found or expired' });
    }

    // Check password if required
    if (result.link.passwordHash) {
      if (!password || typeof password !== 'string') {
        return res.status(401).json({ error: 'Password required', requiresPassword: true });
      }

      const passwordValid = await bcrypt.compare(password, result.link.passwordHash);
      if (!passwordValid) {
        return res.status(401).json({ error: 'Invalid password', requiresPassword: true });
      }
    }

    // Generate PDF
    const exportDir = await ensureExportDir();
    const fileName = `public-${token}-${Date.now()}.pdf`;
    const filePath = path.join(exportDir, fileName);

    const enabledSections = result.sections
      .filter((s) => s.enabled)
      .sort((a, b) => a.orderIndex - b.orderIndex);

    await writePublicReportPdf(
      result.report,
      enabledSections,
      {
        showCompanyLogo: result.link.showCompanyLogo,
        showConsultifyBranding: result.link.showConsultifyBranding,
        customMessage: result.link.customMessage,
      },
      filePath
    );

    logger.info('[ReportBuilderPublic] PDF downloaded via public link', {
      reportId: result.report.id,
      token,
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="${result.report.title || 'report'}.pdf"`
    );
    return res.sendFile(filePath);
  } catch (err: any) {
    logger.error('[ReportBuilderPublic] Error downloading public PDF', {
      err: err,
      correlationId: (req as any).correlationId,
    });
    res.status(500).json({
      error: 'Nie udało się wygenerować PDF',
      code: 'REPORT_BUILDER_PUBLIC_GENERATE_PDF_FAILED',
    });
  }
});

/**
 * GET /api/public/report/:token/pptx
 * Download PPTX of a shared report (requires authentication).
 */
router.get('/:token/pptx', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const tokenParam = req.params.token;
    const linkToken = Array.isArray(tokenParam) ? tokenParam[0] : tokenParam;
    const { password: pwd } = req.query;

    // Verify authentication
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ error: 'Authentication required for PPTX download' });
    }

    const result = await ReportBuilderService.getPublicLinkByToken(linkToken);
    if (!result) {
      return res.status(404).json({ error: 'Link not found or expired' });
    }

    // Check password if required
    if (result.link.passwordHash) {
      if (!pwd || typeof pwd !== 'string') {
        return res.status(401).json({ error: 'Password required', requiresPassword: true });
      }
      const passwordValid = await bcrypt.compare(pwd, result.link.passwordHash);
      if (!passwordValid) {
        return res.status(401).json({ error: 'Invalid password', requiresPassword: true });
      }
    }

    // Generate PPTX using the pipeline
    const { PptxPipelineService } = await import('../services/report/pptx/PptxPipelineService.js');
    const pipeline = new PptxPipelineService();

    const enabledSections = result.sections
      .filter((s) => s.enabled)
      .sort((a, b) => a.orderIndex - b.orderIndex);

    const reportConfig =
      typeof result.report.config === 'string'
        ? JSON.parse(result.report.config)
        : result.report.config || {};

    const pptxResult = await pipeline.generateFromLegacyReport(
      {
        report: result.report,
        sections: enabledSections,
        scoreSummary: undefined,
        organizationName: reportConfig.organizationName,
        projectName: result.report.title,
      },
      {
        language: reportConfig.language || 'pl',
        template: reportConfig.styling?.template || 'corporate',
        brandColor: reportConfig.styling?.primaryColor,
        confidentiality: 'confidential',
        addCover: true,
      }
    );

    logger.info('[ReportBuilderPublic] PPTX downloaded via public link', {
      reportId: result.report.id,
      token: linkToken,
      slides: pptxResult.slideCount,
    });

    res.setHeader(
      'Content-Type',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    );
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="${result.report.title || 'report'}.pptx"`
    );
    return res.send(pptxResult.buffer);
  } catch (err: any) {
    logger.error('[ReportBuilderPublic] Error downloading public PPTX', {
      err: err,
      correlationId: (req as any).correlationId,
    });
    res.status(500).json({
      error: 'Nie udało się wygenerować PPTX',
      code: 'REPORT_BUILDER_PUBLIC_GENERATE_PPTX_FAILED',
    });
  }
});

/**
 * GET /api/public/report/:token/docx
 * Download DOCX of a shared report (requires authentication).
 */
router.get('/:token/docx', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const tokenParam = req.params.token;
    const linkToken = Array.isArray(tokenParam) ? tokenParam[0] : tokenParam;
    const { password: pwd } = req.query;

    // Verify authentication
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ error: 'Authentication required for DOCX download' });
    }

    const result = await ReportBuilderService.getPublicLinkByToken(linkToken);
    if (!result) {
      return res.status(404).json({ error: 'Link not found or expired' });
    }

    // Check password if required
    if (result.link.passwordHash) {
      if (!pwd || typeof pwd !== 'string') {
        return res.status(401).json({ error: 'Password required', requiresPassword: true });
      }
      const passwordValid = await bcrypt.compare(pwd, result.link.passwordHash);
      if (!passwordValid) {
        return res.status(401).json({ error: 'Invalid password', requiresPassword: true });
      }
    }

    // For now, generate a basic DOCX using the same PDF approach but as DOCX
    // We delegate to the authenticated export endpoint pattern
    const enabledSections = result.sections
      .filter((s) => s.enabled)
      .sort((a, b) => a.orderIndex - b.orderIndex);

    // Generate DOCX (real .docx)
    const exportDir = await ensureExportDir();
    const fileName = `public-${linkToken}-${Date.now()}.docx`;
    const filePath = path.join(exportDir, fileName);

    await writePublicReportDocx(
      result.report,
      enabledSections,
      {
        showCompanyLogo: result.link.showCompanyLogo,
        showConsultifyBranding: result.link.showConsultifyBranding,
        customMessage: result.link.customMessage,
      },
      filePath
    );

    logger.info('[ReportBuilderPublic] DOCX downloaded via public link', {
      reportId: result.report.id,
      token: linkToken,
    });

    res.setHeader(
      'Content-Type',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    );
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="${result.report.title || 'report'}.docx"`
    );
    return res.sendFile(filePath);
  } catch (err: any) {
    logger.error('[ReportBuilderPublic] Error downloading public DOCX', {
      err: err,
      correlationId: (req as any).correlationId,
    });
    res.status(500).json({
      error: 'Nie udało się wygenerować DOCX',
      code: 'REPORT_BUILDER_PUBLIC_GENERATE_DOCX_FAILED',
    });
  }
});

/**
 * GET /api/public/report/:token/check-auth
 * Check if the current request has a valid auth token.
 * Used by the public view to conditionally show download buttons.
 */
router.get('/:token/check-auth', async (req: Request, res: Response) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.json({ authenticated: false });
    }

    // Dynamically import verifyToken logic
    const jwt = await import('jsonwebtoken');
    const token = authHeader.split(' ')[1];
    try {
      const decoded = jwt.default.verify(token, config.JWT_SECRET) as any;
      return res.json({
        authenticated: true,
        userId: decoded.userId || decoded.id,
        userName: decoded.name || decoded.email,
      });
    } catch {
      return res.json({ authenticated: false });
    }
  } catch {
    return res.json({ authenticated: false });
  }
});

/**
 * POST /api/public/report/:token/verify-password
 * Verify password for a protected shared report
 */
router.post('/:token/verify-password', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const tokenParam = req.params.token;
    const token = Array.isArray(tokenParam) ? tokenParam[0] : tokenParam;
    const { password } = req.body;

    // Get link without incrementing view count
    const { getDatabase } = await import('../database/index.js');
    const db = getDatabase();

    const linkRow = await new Promise<any>((resolve, reject) => {
      db.get(
        `SELECT * FROM report_public_links WHERE link_token = ? AND revoked_at IS NULL`,
        [token],
        (err: Error | null, row: any) => {
          if (err) reject(err);
          else resolve(row);
        }
      );
    });

    if (!linkRow) {
      return res.status(404).json({ error: 'Link not found' });
    }

    // Check expiration
    if (linkRow.expires_at && new Date(linkRow.expires_at) < new Date()) {
      return res.status(404).json({ error: 'Link expired' });
    }

    // If no password required
    if (!linkRow.password_hash) {
      return res.json({ valid: true, requiresPassword: false });
    }

    // Verify password
    if (!password || typeof password !== 'string') {
      return res.json({ valid: false, requiresPassword: true });
    }

    const passwordValid = await bcrypt.compare(password, linkRow.password_hash);
    res.json({ valid: passwordValid, requiresPassword: true });
  } catch (err) {
    logger.error('[ReportBuilderPublic] Error verifying password:', err);
    next(err);
  }
});

export default router;
