export enum AppView {
  AI_CHAT = 'AI_CHAT', // Main welcome screen with AI Chat
  DISCOVERY_CONSULTANT = 'DISCOVERY_CONSULTANT', // AI Discovery with Canvas
  WELCOME = 'WELCOME',
  AUTH = 'AUTH',
  DASHBOARD = 'DASHBOARD',
  USER_DASHBOARD = 'USER_DASHBOARD',
  DASHBOARD_OVERVIEW = 'DASHBOARD_OVERVIEW',
  DASHBOARD_SNAPSHOT = 'DASHBOARD_SNAPSHOT',

  // Quick Assessment
  QUICK_STEP1_PROFILE = 'QUICK_STEP1_PROFILE',
  QUICK_STEP2_USER_CONTEXT = 'QUICK_STEP2_USER_CONTEXT',
  QUICK_STEP3_EXPECTATIONS = 'QUICK_STEP3_EXPECTATIONS',
  TRIAL_ENTRY = 'TRIAL_ENTRY', // Phase C: Controlled Trial Selection

  // Full Transformation Views
  ONBOARDING_WIZARD = 'ONBOARDING_WIZARD', // Phase E: Guided First Value
  ORG_SETUP_WIZARD = 'ORG_SETUP_WIZARD', // Phase D: Organization Setup
  FULL_STEP1_CONTEXT = 'FULL_STEP1_CONTEXT', // NEW: Senior Consultant Context Gathering
  FULL_STEP1_ASSESSMENT = 'FULL_STEP1_ASSESSMENT', // Parent (legacy)

  // Assessment views (Multi-framework)
  ASSESSMENT_OVERVIEW = 'ASSESSMENT_OVERVIEW', // Assessment landing page
  ASSESSMENT_DRD = 'ASSESSMENT_DRD', // DRD with axis selector
  ASSESSMENT_SIRI = 'ASSESSMENT_SIRI', // SIRI framework
  ASSESSMENT_ADMA = 'ASSESSMENT_ADMA', // ADMA framework
  ASSESSMENT_CMMI = 'ASSESSMENT_CMMI', // CMMI-DMM framework
  ASSESSMENT_LEAN = 'ASSESSMENT_LEAN', // Lean 4.0 (RapidLean)
  ASSESSMENT_DIGITAL_EXTERNAL = 'ASSESSMENT_DIGITAL_EXTERNAL', // Legacy - kept for backward compat
  ASSESSMENT_LEAN_EXTERNAL = 'ASSESSMENT_LEAN_EXTERNAL', // Legacy - kept for backward compat
  ASSESSMENT_OTHER = 'ASSESSMENT_OTHER', // Other assessments
  ASSESSMENT_SUMMARY = 'ASSESSMENT_SUMMARY', // Assessment Hub dashboard
  ASSESSMENT_AUDITS = 'ASSESSMENT_AUDITS', // Generic reports/audits
  MY_ASSESSMENTS = 'MY_ASSESSMENTS', // User's assessments list
  REVIEWER_DASHBOARD = 'REVIEWER_DASHBOARD', // Reviewer pending reviews
  ASSESSMENT_DASHBOARD = 'ASSESSMENT_DASHBOARD', // Assessment module dashboard
  GAP_MAP = 'GAP_MAP', // Gap analysis dashboard
  ASSESSMENT_REPORTS = 'ASSESSMENT_REPORTS', // Assessment reports archive
  INITIATIVE_GENERATOR = 'INITIATIVE_GENERATOR', // Initiative generator wizard

  // DRD Axis Views (kept for backward compatibility)
  FULL_STEP1_PROCESSES = 'FULL_STEP1_PROCESSES',
  FULL_STEP1_DIGITAL = 'FULL_STEP1_DIGITAL',
  FULL_STEP1_MODELS = 'FULL_STEP1_MODELS',
  FULL_STEP1_DATA = 'FULL_STEP1_DATA',
  FULL_STEP1_CULTURE = 'FULL_STEP1_CULTURE',
  FULL_STEP1_CYBERSECURITY = 'FULL_STEP1_CYBERSECURITY',
  FULL_STEP1_AI = 'FULL_STEP1_AI',

  FULL_STEP2_INITIATIVES = 'FULL_STEP2_INITIATIVES',
  FULL_STEP3_ROADMAP = 'FULL_STEP3_ROADMAP',
  FULL_STEP4_ROI = 'FULL_STEP4_ROI',
  ECONOMICS = 'ECONOMICS', // Module: Economics & Value Realization (Digitization Maturity)
  FULL_STEP5_EXECUTION = 'FULL_STEP5_EXECUTION', // Keeping for backward compat
  IMPLEMENTATION = 'IMPLEMENTATION', // Module 4: Wdrożenie
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  FULL_PILOT_EXECUTION = 'IMPLEMENTATION', // @deprecated - use IMPLEMENTATION
  FULL_ROLLOUT = 'FULL_ROLLOUT', // Module 5
  FULL_STEP6_REPORTS = 'FULL_STEP6_REPORTS',
  DRD_AUDIT_REPORT = 'DRD_AUDIT_REPORT', // DRD Audit Report Builder
  KPI_OKR_DASHBOARD = 'KPI_OKR_DASHBOARD', // Module: KPI/OKR post-implementation tracking

  MASTERCLASS = 'MASTERCLASS',
  RESOURCES = 'RESOURCES',

  // Legacy/Fallback
  FREE_ASSESSMENT_CHAT = 'FREE_ASSESSMENT_CHAT',
  FULL_TRANSFORMATION_CHAT = 'FULL_TRANSFORMATION_CHAT',

  // SaaS / Admin
  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  ADMIN_USERS = 'ADMIN_USERS',
  ADMIN_PROJECTS = 'ADMIN_PROJECTS',
  ADMIN_LLM = 'ADMIN_LLM',
  ADMIN_AI_HEALTH = 'ADMIN_AI_HEALTH',
  ADMIN_KNOWLEDGE = 'ADMIN_KNOWLEDGE',
  ADMIN_TEAMS = 'ADMIN_TEAMS',
  ADMIN_ANALYTICS = 'ADMIN_ANALYTICS',
  ADMIN_FEEDBACK = 'ADMIN_FEEDBACK',
  ADMIN_METRICS = 'ADMIN_METRICS',
  SETTINGS_PROFILE = 'SETTINGS_PROFILE',
  SETTINGS_BILLING = 'SETTINGS_BILLING',
  SETTINGS_AI = 'SETTINGS_AI',
  SETTINGS_NOTIFICATIONS = 'SETTINGS_NOTIFICATIONS',
  SETTINGS_INTEGRATIONS = 'SETTINGS_INTEGRATIONS',
  SETTINGS_REGIONALIZATION = 'SETTINGS_REGIONALIZATION',
  SETTINGS_ORGANIZATION = 'SETTINGS_ORGANIZATION', // NEW
  SETTINGS_MFA = 'SETTINGS_MFA',
  SETTINGS_ACTIVE_SESSIONS = 'SETTINGS_ACTIVE_SESSIONS',
  SETTINGS_LOGIN_HISTORY = 'SETTINGS_LOGIN_HISTORY',
  SETTINGS_DATA_CONTROLS = 'SETTINGS_DATA_CONTROLS',

  SETTINGS_API_KEYS = 'ADMIN_API_KEYS', // Mapping to existing key
  SETTINGS_WEBHOOKS = 'SETTINGS_WEBHOOKS',
  SETTINGS_CALENDAR_SYNC = 'SETTINGS_CALENDAR_SYNC',
  SETTINGS_APPEARANCE = 'SETTINGS_APPEARANCE',
  SETTINGS_AI_MEMORY = 'SETTINGS_AI_MEMORY',
  SETTINGS_AI_RESPONSE_STYLE = 'SETTINGS_AI_RESPONSE_STYLE',
  SETTINGS_AI_CHAT_HISTORY = 'SETTINGS_AI_CHAT_HISTORY',
  SETTINGS_AI_VOICE = 'SETTINGS_AI_VOICE',

  // Context Builder (Renamed directly or used as parent)
  CONTEXT_BUILDER = 'CONTEXT_BUILDER',
  CONTEXT_BUILDER_PROFILE = 'CONTEXT_BUILDER_PROFILE',
  CONTEXT_BUILDER_GOALS = 'CONTEXT_BUILDER_GOALS',
  CONTEXT_BUILDER_CHALLENGES = 'CONTEXT_BUILDER_CHALLENGES',
  CONTEXT_BUILDER_MEGATRENDS = 'CONTEXT_BUILDER_MEGATRENDS',
  CONTEXT_BUILDER_STRATEGY = 'CONTEXT_BUILDER_STRATEGY',

  // Teamwork Views
  MY_WORK = 'MY_WORK', // New Module 7 (Tasks & Workflow)
  PROJECT_INTELLIGENCE = 'PROJECT_INTELLIGENCE', // AI-powered project knowledge capture

  // Initiative Lifecycle Management
  INITIATIVE_MANAGEMENT = 'INITIATIVE_MANAGEMENT', // @deprecated - use PORTFOLIO_ROADMAP
  PORTFOLIO_ROADMAP = 'PORTFOLIO_ROADMAP', // Unified Portfolio & Roadmap view (replaces INITIATIVE_MANAGEMENT + FULL_STEP3_ROADMAP)
  BENEFITS_REALIZATION = 'BENEFITS_REALIZATION', // DONE, BLOCKED, CANCELLED, ARCHIVED + KPIs

  // Step D: Executive View (Read-only reporting for executives)
  EXECUTIVE_VIEW = 'EXECUTIVE_VIEW',

  // AI Action Proposals Review
  AI_ACTION_PROPOSALS = 'AI_ACTION_PROPOSALS',

  // Consultinity Studio - Visual AI Workspace
  STUDIO = 'STUDIO',

  // Step 13: Visual Playbook Editor
  SUPERADMIN_PLAYBOOK_TEMPLATES = 'SUPERADMIN_PLAYBOOK_TEMPLATES',
  SUPERADMIN_PLAYBOOK_EDITOR = 'SUPERADMIN_PLAYBOOK_EDITOR',
  ADMIN_PLAYBOOK_RUNS = 'ADMIN_PLAYBOOK_RUNS',

  // Org Admin Consultant Views
  ADMIN_SETTINGS_CONSULTANTS = 'ADMIN_SETTINGS_CONSULTANTS',
  ADMIN_INVITATIONS = 'ADMIN_INVITATIONS',
  ADMIN_TOKEN_MANAGEMENT = 'ADMIN_TOKEN_MANAGEMENT',

  // Ecosystem (Phase G)
  AFFILIATE_DASHBOARD = 'AFFILIATE_DASHBOARD',

  // SuperAdmin Module Views (New modular structure)
  SUPERADMIN_OVERVIEW = 'SUPERADMIN_OVERVIEW',
  SUPERADMIN_CUSTOMERS = 'SUPERADMIN_CUSTOMERS',
  SUPERADMIN_AI_PLATFORM = 'SUPERADMIN_AI_PLATFORM', // Legacy - kept for backward compatibility
  // AI Platform - Variant A (3 Modules)
  SUPERADMIN_AI_INFRASTRUCTURE = 'SUPERADMIN_AI_INFRASTRUCTURE', // LLM Providers, Tiers, Settings, Health
  SUPERADMIN_AI_DEVELOPMENT = 'SUPERADMIN_AI_DEVELOPMENT', // Prompts, Intelligence, Experiments, Knowledge
  SUPERADMIN_AI_OPERATIONS = 'SUPERADMIN_AI_OPERATIONS', // Mission Control, Performance, Costs, SLA, Analytics
  SUPERADMIN_SYSTEM = 'SUPERADMIN_SYSTEM',
  SUPERADMIN_CONTENT = 'SUPERADMIN_CONTENT',
  SUPERADMIN_REVENUE = 'SUPERADMIN_REVENUE',
  SUPERADMIN_SECURITY = 'SUPERADMIN_SECURITY',
  SUPERADMIN_CONFIGURATION = 'SUPERADMIN_CONFIGURATION',
  SUPERADMIN_ANALYTICS = 'SUPERADMIN_ANALYTICS', // Custom Dashboards, Reports, Metrics, Predictive

  // SuperAdmin Legacy Views (kept for backward compatibility - used as tab identifiers)
  SUPERADMIN_DASHBOARD = 'SUPERADMIN_DASHBOARD',
  SUPERADMIN_ORGANIZATIONS = 'SUPERADMIN_ORGANIZATIONS',
  SUPERADMIN_USERS = 'SUPERADMIN_USERS',
  SUPERADMIN_BILLING = 'SUPERADMIN_BILLING',
  SUPERADMIN_AI_CONFIG = 'SUPERADMIN_AI_CONFIG',
  SUPERADMIN_LLM_MANAGEMENT = 'SUPERADMIN_LLM_MANAGEMENT',
  SUPERADMIN_AI_INTELLIGENCE = 'SUPERADMIN_AI_INTELLIGENCE',
  SUPERADMIN_KNOWLEDGE = 'SUPERADMIN_KNOWLEDGE',
  SUPERADMIN_SETTINGS = 'SUPERADMIN_SETTINGS',

  // SuperAdmin Enterprise Views (used as tab identifiers)
  SUPERADMIN_SSO = 'SUPERADMIN_SSO',
  SUPERADMIN_SECURITY_POLICIES = 'SUPERADMIN_SECURITY_POLICIES',
  SUPERADMIN_API_MANAGEMENT = 'SUPERADMIN_API_MANAGEMENT',
  SUPERADMIN_WHITELABEL = 'SUPERADMIN_WHITELABEL',
  SUPERADMIN_COMPLIANCE = 'SUPERADMIN_COMPLIANCE',
  SUPERADMIN_INVOICES = 'SUPERADMIN_INVOICES',
  SUPERADMIN_FEEDBACK = 'SUPERADMIN_FEEDBACK',
  SUPERADMIN_BULK_OPERATIONS = 'SUPERADMIN_BULK_OPERATIONS',

  // Admin Module Views (7-module structure - Best practices from ClickUp/HubSpot/Replit)
  ADMIN_OVERVIEW = 'ADMIN_OVERVIEW', // Dashboard, Metrics, Analytics
  ADMIN_ORGANIZATION = 'ADMIN_ORGANIZATION', // Profile, Branding, Ownership
  ADMIN_ORGANIZATION_SETTINGS = 'ADMIN_ORGANIZATION_SETTINGS',
  ADMIN_TEAM = 'ADMIN_TEAM', // Users, Groups, Invitations, Roles
  ADMIN_WORKSPACE = 'ADMIN_WORKSPACE', // Projects, Knowledge, Playbooks
  ADMIN_PROJECT_DETAILS = 'ADMIN_PROJECT_DETAILS', // Specific project management
  ADMIN_AI = 'ADMIN_AI', // LLM, Health, Analytics, Tokens
  ADMIN_BILLING = 'ADMIN_BILLING', // Plans, Payments, Invoices, Alerts
  ADMIN_SECURITY = 'ADMIN_SECURITY', // Auth, Access, Audit, Data
  ADMIN_SETTINGS = 'ADMIN_SETTINGS', // Legacy - redirects to ADMIN_SECURITY

  // Admin Enterprise Views (legacy - used as tab identifiers)
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  ADMIN_API_KEYS = 'ADMIN_API_KEYS',
  ADMIN_BILLING_MANAGEMENT = 'ADMIN_BILLING_MANAGEMENT',
  ADMIN_BULK_OPERATIONS = 'ADMIN_BULK_OPERATIONS',
  ADMIN_WORK_MODE = 'ADMIN_WORK_MODE',

  // Settings Enterprise Views
  SETTINGS_SECURITY = 'SETTINGS_SECURITY',
  SETTINGS_API_ACCESS = 'SETTINGS_API_ACCESS',
  SETTINGS_PRIVACY = 'SETTINGS_PRIVACY',
  SETTINGS_SSO = 'SETTINGS_SSO',

  // Settings (additional)
  SETTINGS_LEGAL = 'SETTINGS_LEGAL',

  // Extended User Settings
  SETTINGS_WORK_PREFERENCES = 'SETTINGS_WORK_PREFERENCES',
  SETTINGS_DASHBOARD_PREFERENCES = 'SETTINGS_DASHBOARD_PREFERENCES',
  SETTINGS_ACCESSIBILITY = 'SETTINGS_ACCESSIBILITY',

  // Settings Module Views (6-module structure)
  SETTINGS_PROFILE_MODULE = 'SETTINGS_PROFILE_MODULE',
  SETTINGS_AI_MODULE = 'SETTINGS_AI_MODULE',
  SETTINGS_NOTIFICATIONS_MODULE = 'SETTINGS_NOTIFICATIONS_MODULE',
  SETTINGS_SECURITY_MODULE = 'SETTINGS_SECURITY_MODULE',
  SETTINGS_INTEGRATIONS_MODULE = 'SETTINGS_INTEGRATIONS_MODULE',
  SETTINGS_APPEARANCE_MODULE = 'SETTINGS_APPEARANCE_MODULE',

  // Help & Documentation
  KNOWLEDGE_BASE = 'KNOWLEDGE_BASE',
  KNOWLEDGE_BASE_ARTICLE = 'KNOWLEDGE_BASE_ARTICLE',
  STATUS_PAGE = 'STATUS_PAGE',
  CHANGELOG = 'CHANGELOG',
  HELP_ANALYTICS = 'HELP_ANALYTICS',
}
