CREATE TABLE v8_output_artifacts (artifact_id TEXT PRIMARY KEY, artifact_family TEXT, title_snapshot TEXT, origin_summary_json TEXT);
CREATE TABLE report_builder_templates (id TEXT PRIMARY KEY, organization_id TEXT, name TEXT, description TEXT, updated_at TIMESTAMPTZ);
CREATE TABLE presentation_templates (id TEXT PRIMARY KEY, organization_id TEXT, name TEXT, description TEXT, updated_at TIMESTAMPTZ);
CREATE TABLE document_studio_templates (template_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, name TEXT, purpose TEXT, language TEXT);
CREATE TABLE tp_base_templates (id SERIAL PRIMARY KEY, name TEXT, description TEXT, created_by TEXT);
INSERT INTO v8_output_artifacts VALUES ('c0','template','PMO Weekly','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c1','template','Raport Steering','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c2','template','Sponsor One-Pager','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c3','template','Cotygodniowy status PMO (PMO Weekly Status)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c4','template','Streszczenie wykonawcze (Executive Summary)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c5','template','Uzasadnienie biznesowe (Business Case)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c6','template','Raport diagnostyczny DRD (Diagnostic Report)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c7','template','Aktualizacja dla komitetu sterującego (Steering Committee Update)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c8','template','Jednostronicowy raport dla sponsora (Sponsor One-Pager)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c9','template','Deck raportu końcowego (Final Report Deck)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c10','template','Przegląd komitetu sterującego (Steering Review)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c11','template','Deck rekomendacji Minto (Recommendation Deck)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c12','template','Prezentacja ustaleń SCR (Findings Readout)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c13','template','Deck otwarcia projektu (Kickoff Deck)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c14','template','Finance — Sekcja finansowa raportu','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c15','template','Program — Raport 3 osi (czas × zadania × wartość)','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c16','template','Raport statusowy','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c17','template','Investor pitch','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c18','template','Executive memo','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c19','template','Raport audytowy','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c20','template','Board deck','{"template":{"description":"PL-przed"}}');
INSERT INTO v8_output_artifacts VALUES ('c21','template','Diagnostic deck','{"template":{"description":"PL-przed"}}');