import { Download, FileText, Loader2 } from 'lucide-react';
import React, { useCallback, useState } from 'react';
import { useTranslation } from 'react-i18next';

import { ArtifactPropertiesTable } from '@/components/standard/ArtifactPropertiesTable';
import { DocumentCardMenu5 } from '@/components/standard/DocumentCardMenu5';
import { StandardArtifactShell } from '@/components/standard/StandardArtifactShell';
import type { StandardSekcjaDef } from '@/components/standard/StandardArtifactShell.types';
import { EXECUTION_REPORT_CARD_CONTRACT } from '@/components/standard/documentCardContracts';
import { downloadExecutionReportFile, publishExecutionReportRun, type ExecutionReportRunDto } from '@/services/executionReports/executionReportsApi';
import { formatListDate } from '@/utils/listDateFormat';

interface Props { run: ExecutionReportRunDto; onBack: () => void; onChanged?: (run: ExecutionReportRunDto) => void }
const formatDate = (value: string | null | undefined) => { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : formatListDate(date); };

export const ExecutionReportDocument = ({ run, onBack, onChanged }: Props) => {
  const { t } = useTranslation();
  const [busy, setBusy] = useState<'docx' | 'pdf' | 'publish' | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeSection, setActiveSection] = useState('metrics');
  const [readMode, setReadMode] = useState(run.status === 'PUBLISHED');
  const payload = run.payload;
  const download = useCallback(async (format: 'docx' | 'pdf') => { setBusy(format); setError(null); try { await downloadExecutionReportFile(run.id, format, run.title.replace(/[\\/:*?"<>|]/g, '-')); } catch (cause) { setError(cause instanceof Error ? cause.message : t('executionReports.doc.downloadFailed', 'The file could not be downloaded.')); } finally { setBusy(null); } }, [run.id, run.title]);
  const publish = useCallback(async () => { setBusy('publish'); setError(null); try { const updated = await publishExecutionReportRun(run.id); onChanged?.({ ...run, ...updated, payload: run.payload }); } catch (cause) { setError(cause instanceof Error ? cause.message : t('executionReports.doc.publishFailed', 'The report could not be published.')); } finally { setBusy(null); } }, [onChanged, run]);
  const content: Record<string, React.ReactNode> = {
    metrics: payload?.metrics?.length ? <div className="grid grid-cols-2 gap-3 md:grid-cols-3">{payload.metrics.map(metric=><div key={metric.id} className="rounded-xl border border-c-border bg-c-surface-raised p-3"><p className="text-xs text-c-text-muted">{metric.label}</p><p className="mt-1 text-xl font-semibold">{metric.value}</p>{metric.hint?<p className="text-xs text-c-text-muted">{metric.hint}</p>:null}</div>)}</div> : null,
    content: payload?.sections?.length ? <div className="space-y-4">{payload.sections.map(section=><section key={section.id} className="rounded-xl border border-c-border bg-c-surface-raised p-4"><h2 className="font-semibold">{section.title}</h2>{section.narrative?<p className="mt-2 text-sm leading-relaxed">{section.narrative}</p>:null}{section.bullets?.length?<ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{section.bullets.map((bullet,index)=><li key={index}>{bullet}</li>)}</ul>:null}{section.table?.rows.length?<div className="mt-3 overflow-x-auto"><table data-canon="§27-exempt" className="w-full min-w-[560px] text-sm"><thead><tr className="border-b border-c-border text-left">{section.table.columns.map(column=><th key={column.id} className="px-2 py-2 text-xs text-c-text-muted">{column.label}</th>)}</tr></thead><tbody>{section.table.rows.map((row,index)=><tr key={index} className="border-b border-c-border/60">{section.table!.columns.map(column=><td key={column.id} className="px-2 py-2">{row[column.id]??'—'}</td>)}</tr>)}</tbody></table></div>:null}</section>)}</div> : null,
  };
  const sections: StandardSekcjaDef[] = EXECUTION_REPORT_CARD_CONTRACT.flatMap(item => content[item.id] ? [{ ...item, component: content[item.id], aiContract: { none: true as const, reason: item.aiReason } }] : []);
  const safeActiveSection = sections.some(item=>item.id===activeSection) ? activeSection : sections[0]?.id ?? 'content';
  const actions = <div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary inline-flex items-center gap-2 focus-visible:ring-2 focus-visible:ring-c-focus" onClick={()=>void download('docx')} disabled={busy!==null}>{busy==='docx'?<Loader2 className="h-4 w-4 animate-spin"/>:<FileText className="h-4 w-4"/>}{t('executionReports.doc.downloadDocx', 'Download DOCX')}</button><button type="button" className="btn-secondary inline-flex items-center gap-2 focus-visible:ring-2 focus-visible:ring-c-focus" onClick={()=>void download('pdf')} disabled={busy!==null}>{busy==='pdf'?<Loader2 className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}{t('executionReports.doc.downloadPdf', 'Download PDF')}</button>{run.status==='DRAFT'?<button type="button" className="btn-secondary focus-visible:ring-2 focus-visible:ring-c-focus" onClick={()=>void publish()} disabled={busy!==null}>{t('executionReports.doc.publish', 'Publish')}</button>:null}</div>;
  const rightPanel={actions:{label:t('executionReports.doc.actions', 'Actions'),children:actions,actionIds:['download-docx','download-pdf','publish']},properties:{label:t('executionReports.doc.properties', 'Properties'),children:<ArtifactPropertiesTable propertyLabel={t('executionReports.doc.property', 'Property')} valueLabel={t('executionReports.doc.value', 'Value')} rows={[{id:'level',label:t('executionReports.columns.level', 'Level'),value:t(`executionReports.level.${run.level}`,run.level)},{id:'status',label:'Status',value:run.status==='PUBLISHED'?t('executionReports.status.published', 'Published'):t('executionReports.status.draft', 'Draft')},{id:'asOf',label:t('executionReports.columns.asOf', 'Data as of'),value:formatDate(run.asOf),mono:true},{id:'period',label:t('executionReports.columns.period', 'Period'),value:`${formatDate(run.period.start)} – ${formatDate(run.period.end)}`,mono:true},{id:'author',label:t('executionReports.columns.author', 'Author'),value:run.createdByName||'—'}]}/>},relations:{pominieta:true as const,reason:t('executionReports.doc.noRelations', 'The snapshot declares no separate relations.')},evidence:payload?.ragReason?{label:t('executionReports.doc.sourcesAssumptions', 'Sources and assumptions'),children:<p className="text-sm">{payload.ragReason}</p>}:{pominieta:true as const,reason:t('executionReports.doc.noSources', 'No sources or assumptions recorded.')},comments:{pominieta:true as const,reason:t('executionReports.doc.noComments', 'A report snapshot has no comment thread.')},history:{label:t('executionReports.doc.history', 'History'),children:<p className="text-sm">{t('executionReports.doc.createdAt', 'Created')} {formatDate(run.createdAt)}{run.publishedAt?` · ${t('executionReports.doc.publishedAt', 'published')} ${formatDate(run.publishedAt)}`:''}</p>}};
  return <div data-testid="execution-report-document" className="h-full min-h-0">{error?<p role="alert" className="m-3 rounded-lg border border-c-danger/50 bg-c-danger/10 p-3 text-sm">{error}</p>:null}<StandardArtifactShell karta="execution-report" klasa="L" header={{title:run.title,onTitleChange:()=>undefined,titleReadOnly:true,artifactType:'document' as any,artifactId:run.id,onSave:()=>undefined,saveState:'saved',onClose:onBack,statusLabel:run.status==='PUBLISHED'?t('executionReports.status.published', 'Published'):t('executionReports.status.draft', 'Draft'),statusTone:run.status==='PUBLISHED'?'approved':'draft'}} primaryAction={{intentionallyNone:true,reason:t('executionReports.doc.publishInActions', 'Publishing is available in the Actions section.')}} sections={sections} rightPanel={rightPanel} activeSection={safeActiveSection} onSectionChange={setActiveSection} densityMode="n" onDensityModeChange={()=>undefined} toolbar={<DocumentCardMenu5 sections={sections} activeSection={safeActiveSection} onSectionChange={setActiveSection} readMode={readMode} onReadModeChange={run.status==='DRAFT'?setReadMode:undefined} ai={{onAnalizuj:()=>setError(t('executionReports.doc.aiUnavailable', 'AI analysis is not available for a frozen report snapshot.')),kontekstArtefaktu:{title:run.title,status:run.status,type:'execution-report'},moznaEdytowac:false,powodTylkoOdczyt:t('executionReports.doc.readOnlyReason', 'the report is a frozen snapshot; AI cannot add to its content')}}/>} panelAriaLabel={t('executionReports.doc.panelAria', 'Execution report details')}/></div>;
};
export default ExecutionReportDocument;
