/**
 * ReportCompactPanel
 *
 * Side panel (menu 3) for execution report quick view.
 * Shows RAG status header, report contract, live highlights,
 * and export actions (PDF report / PPTX presentation).
 */

import { AnimatePresence, motion } from 'framer-motion';
import {
  AlertTriangle,
  CheckCircle2,
  ChevronRight,
  Clock,
  Copy,
  Download,
  FileText,
  Loader2,
  Maximize2,
  Presentation,
  Sparkles,
  X,
} from 'lucide-react';
import React, { useCallback, useMemo, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import { useTranslation } from 'react-i18next';
import jsPDF from 'jspdf';

// ---------------------------------------------------------------------------
// TYPES
// ---------------------------------------------------------------------------

export interface ReportHighlight {
  label: string;
  value: string | number;
  variant?: 'default' | 'warn' | 'critical';
}

export interface ReportDef {
  id: string;
  title: string;
  audience: string;
  cadence: string;
  scope: string;
  dataSources: string[];
  sections: string[];
  ragLogic: string;
  followUpActions: string[];
  icon: React.ReactNode;
  highlights: ReportHighlight[];
}

interface ReportCompactPanelProps {
  report: ReportDef | null;
  isOpen: boolean;
  onClose: () => void;
  onGenerate?: (report: ReportDef) => void;
  mode?: 'overlay' | 'embedded';
}

type PanelTab = 'contract' | 'data' | 'export';

// ---------------------------------------------------------------------------
// RAG LOGIC
// ---------------------------------------------------------------------------

function computeRAG(report: ReportDef): 'green' | 'amber' | 'red' {
  const crits = report.highlights.filter((h) => h.variant === 'critical');
  const warns = report.highlights.filter((h) => h.variant === 'warn');
  if (crits.length >= 2) return 'red';
  if (crits.length >= 1 || warns.length >= 2) return 'amber';
  return 'green';
}

const RAG_CONFIG = {
  green: {
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    text: 'text-emerald-600 dark:text-emerald-400',
    label: 'On Track',
    icon: CheckCircle2,
  },
  amber: {
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/30',
    text: 'text-amber-600 dark:text-amber-400',
    label: 'Needs Attention',
    icon: AlertTriangle,
  },
  red: {
    bg: 'bg-rose-500/10',
    border: 'border-rose-500/30',
    text: 'text-rose-600 dark:text-rose-400',
    label: 'At Risk',
    icon: AlertTriangle,
  },
} as const;

const PANEL_TABS: { id: PanelTab; labelKey: string; icon: React.ElementType }[] = [
  { id: 'contract', labelKey: 'execution.reportPanel.contract', icon: FileText },
  { id: 'data', labelKey: 'execution.reportPanel.data', icon: Sparkles },
  { id: 'export', labelKey: 'execution.reportPanel.export', icon: Download },
];

// ---------------------------------------------------------------------------
// EXPORT HELPERS
// ---------------------------------------------------------------------------

function buildReportMarkdown(report: ReportDef, rag: 'green' | 'amber' | 'red'): string {
  const ragLabel = RAG_CONFIG[rag].label;
  const now = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  return [
    `# ${report.title}`,
    `**Status: ${ragLabel.toUpperCase()}** · Generated: ${now}`,
    `**Audience:** ${report.audience} · **Cadence:** ${report.cadence}`,
    '',
    `## Scope`,
    report.scope,
    '',
    `## Live Data`,
    ...report.highlights.map((h) => `- **${h.label}:** ${h.value}${h.variant === 'critical' ? ' ⚠️' : h.variant === 'warn' ? ' ⚡' : ''}`),
    '',
    `## Data Sources`,
    ...report.dataSources.map((d) => `- ${d}`),
    '',
    `## Report Sections`,
    ...report.sections.map((s, i) => `${i + 1}. ${s}`),
    '',
    `## RAG / Confidence Logic`,
    report.ragLogic,
    '',
    `## Expected Follow-up Actions`,
    ...report.followUpActions.map((a) => `- [ ] ${a}`),
    '',
    `---`,
    `_Generated by Consultify Execution Reports_`,
  ].join('\n');
}

function exportReportPDF(report: ReportDef, rag: 'green' | 'amber' | 'red') {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const m = 15;
  const maxW = pageW - m * 2;
  let y = m;

  const addPage = (need: number) => {
    if (y + need > pageH - m) { pdf.addPage(); y = m; }
  };

  const ragConf = RAG_CONFIG[rag];
  const ragColors: Record<string, [number, number, number]> = {
    green: [16, 185, 129],
    amber: [245, 158, 11],
    red: [239, 68, 68],
  };

  // Header bar
  const barColor = ragColors[rag];
  pdf.setFillColor(...barColor);
  pdf.rect(0, 0, pageW, 12, 'F');
  pdf.setFontSize(9);
  pdf.setTextColor(255, 255, 255);
  pdf.text(ragConf.label.toUpperCase(), m, 8);
  pdf.text(new Date().toLocaleDateString(), pageW - m, 8, { align: 'right' });
  y = 20;

  // Title
  pdf.setFontSize(18);
  pdf.setTextColor(20, 30, 70);
  pdf.text(report.title, m, y);
  y += 8;

  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`${report.audience} · ${report.cadence}`, m, y);
  y += 10;

  // Live data highlights
  pdf.setFontSize(11);
  pdf.setTextColor(30, 30, 30);
  pdf.text('Live Data', m, y);
  y += 6;
  for (const h of report.highlights) {
    addPage(6);
    const isAlert = h.variant === 'critical' || h.variant === 'warn';
    pdf.setFontSize(9);
    pdf.setTextColor(isAlert ? ragColors[h.variant === 'critical' ? 'red' : 'amber'][0] : 80,
      isAlert ? ragColors[h.variant === 'critical' ? 'red' : 'amber'][1] : 80,
      isAlert ? ragColors[h.variant === 'critical' ? 'red' : 'amber'][2] : 80);
    pdf.text(`${h.label}: ${h.value}`, m + 2, y);
    y += 5;
  }
  y += 4;

  // Scope
  addPage(12);
  pdf.setFontSize(11);
  pdf.setTextColor(30, 30, 30);
  pdf.text('Scope', m, y);
  y += 5;
  pdf.setFontSize(9);
  pdf.setTextColor(60, 60, 60);
  const scopeLines = pdf.splitTextToSize(report.scope, maxW);
  for (const line of scopeLines) { addPage(5); pdf.text(line, m + 2, y); y += 4.5; }
  y += 4;

  // Sections
  addPage(12);
  pdf.setFontSize(11);
  pdf.setTextColor(30, 30, 30);
  pdf.text('Report Sections', m, y);
  y += 5;
  pdf.setFontSize(9);
  pdf.setTextColor(60, 60, 60);
  report.sections.forEach((s, i) => { addPage(5); pdf.text(`${i + 1}. ${s}`, m + 2, y); y += 4.5; });
  y += 4;

  // RAG logic
  addPage(12);
  pdf.setFontSize(11);
  pdf.setTextColor(30, 30, 30);
  pdf.text('RAG / Confidence Logic', m, y);
  y += 5;
  pdf.setFontSize(9);
  pdf.setTextColor(60, 60, 60);
  const ragLines = pdf.splitTextToSize(report.ragLogic, maxW);
  for (const line of ragLines) { addPage(5); pdf.text(line, m + 2, y); y += 4.5; }
  y += 4;

  // Follow-up actions
  addPage(12);
  pdf.setFontSize(11);
  pdf.setTextColor(30, 30, 30);
  pdf.text('Expected Follow-up Actions', m, y);
  y += 5;
  pdf.setFontSize(9);
  pdf.setTextColor(60, 60, 60);
  report.followUpActions.forEach((a) => { addPage(5); pdf.text(`☐ ${a}`, m + 2, y); y += 4.5; });

  // Footer
  const totalPages = pdf.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Page ${i}/${totalPages} · Consultify Execution Reports`, pageW - m, pageH - 5, { align: 'right' });
  }

  const slug = report.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
  pdf.save(`${slug}-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ---------------------------------------------------------------------------
// COMPONENT
// ---------------------------------------------------------------------------

export const ReportCompactPanel: React.FC<ReportCompactPanelProps> = ({
  report,
  isOpen,
  onClose,
  onGenerate,
  mode = 'overlay',
}) => {
  const { t } = useTranslation();
  const [activeTab, setActiveTab] = useState<PanelTab>('contract');
  const [isExporting, setIsExporting] = useState(false);
  const panelRef = useRef<HTMLDivElement>(null);

  const rag = useMemo(() => (report ? computeRAG(report) : 'green'), [report]);
  const ragConf = RAG_CONFIG[rag];

  const handleCopyMarkdown = useCallback(() => {
    if (!report) return;
    const md = buildReportMarkdown(report, rag);
    navigator.clipboard.writeText(md).then(
      () => toast.success(t('execution.reportPanel.copied', 'Report copied to clipboard')),
      () => toast.error(t('execution.reportPanel.copyFailed', 'Copy failed'))
    );
  }, [report, rag, t]);

  const handleExportPDF = useCallback(() => {
    if (!report) return;
    setIsExporting(true);
    try {
      exportReportPDF(report, rag);
      toast.success(t('execution.reportPanel.pdfExported', 'PDF downloaded'));
    } catch {
      toast.error(t('execution.reportPanel.pdfFailed', 'PDF export failed'));
    } finally {
      setIsExporting(false);
    }
  }, [report, rag, t]);

  const handleExportPresentation = useCallback(() => {
    if (!report) return;
    const md = buildReportMarkdown(report, rag);
    const encoded = encodeURIComponent(md);
    const title = encodeURIComponent(report.title);
    window.open(`/prezentacje?sourceType=execution_report&sourceName=${title}&content=${encoded}`, '_blank');
    toast.success(t('execution.reportPanel.presentationOpened', 'Opening presentation generator…'));
  }, [report, rag, t]);

  if (!isOpen || !report) return null;

  const RagIcon = ragConf.icon;

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {mode === 'overlay' && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 bg-black/20 dark:bg-black/40 z-40"
              onClick={onClose}
            />
          )}
          <motion.div
            ref={panelRef}
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'spring', damping: 30, stiffness: 300 }}
            className="fixed right-0 top-0 bottom-0 w-[440px] max-w-full z-50 flex flex-col bg-white dark:bg-navy-950 border-l border-slate-200 dark:border-navy-700 shadow-2xl"
          >
            {/* RAG status bar */}
            <div className={`h-1.5 w-full ${rag === 'green' ? 'bg-emerald-500' : rag === 'amber' ? 'bg-amber-500' : 'bg-rose-500'}`} />

            {/* Header */}
            <div className="px-4 pt-3 pb-2 border-b border-slate-100 dark:border-navy-800">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <div className={`px-2 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wide ${ragConf.bg} ${ragConf.text} ${ragConf.border} border`}>
                      <RagIcon size={10} className="inline mr-1 -mt-0.5" />
                      {ragConf.label}
                    </div>
                    <span className="text-[10px] font-medium uppercase tracking-wide text-slate-400 dark:text-slate-500">
                      {report.cadence}
                    </span>
                  </div>
                  <h3 className="text-sm font-semibold text-slate-900 dark:text-white truncate">
                    {report.title}
                  </h3>
                  <p className="text-[11px] text-slate-500 dark:text-slate-400 truncate mt-0.5">
                    {report.audience}
                  </p>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  {onGenerate && (
                    <button
                      type="button"
                      onClick={() => onGenerate(report)}
                      className="p-1.5 rounded-lg text-slate-400 hover:text-cyan-500 hover:bg-slate-100 dark:hover:bg-navy-800 transition-colors"
                      title={t('execution.reportPanel.generate', 'Generate with AI')}
                    >
                      <Maximize2 size={14} />
                    </button>
                  )}
                  <button
                    type="button"
                    onClick={onClose}
                    className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 dark:hover:bg-navy-800 transition-colors"
                  >
                    <X size={14} />
                  </button>
                </div>
              </div>

              {/* Live highlights */}
              <div className="flex flex-wrap gap-1.5 mt-2.5">
                {report.highlights.map((h) => (
                  <span
                    key={h.label}
                    className={`inline-flex items-center gap-0.5 px-2 py-0.5 rounded text-[10px] font-medium ${
                      h.variant === 'critical'
                        ? 'bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400'
                        : h.variant === 'warn'
                          ? 'bg-amber-50 dark:bg-amber-900/20 text-amber-600 dark:text-amber-400'
                          : 'bg-slate-100 dark:bg-navy-800 text-slate-600 dark:text-slate-400'
                    }`}
                  >
                    {h.label}: {h.value}
                  </span>
                ))}
              </div>

              {/* Tabs */}
              <div className="flex gap-0.5 mt-3 -mb-px">
                {PANEL_TABS.map((tab) => {
                  const Icon = tab.icon;
                  const isActive = activeTab === tab.id;
                  return (
                    <button
                      key={tab.id}
                      type="button"
                      onClick={() => setActiveTab(tab.id)}
                      className={`flex items-center gap-1 px-2.5 py-1.5 text-[11px] font-medium rounded-t-lg border-b-2 transition-colors ${
                        isActive
                          ? 'border-cyan-500 text-cyan-600 dark:text-cyan-400 bg-cyan-50/50 dark:bg-cyan-900/10'
                          : 'border-transparent text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300'
                      }`}
                    >
                      <Icon size={12} />
                      {t(tab.labelKey, tab.id)}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Body */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {activeTab === 'contract' && (
                <>
                  <Section label="Scope">
                    <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">{report.scope}</p>
                  </Section>

                  <Section label="Data Sources">
                    <div className="flex flex-wrap gap-1">
                      {report.dataSources.map((ds) => (
                        <span key={ds} className="inline-block px-1.5 py-0.5 rounded bg-slate-100 dark:bg-navy-800 text-[10px] text-slate-600 dark:text-slate-400">{ds}</span>
                      ))}
                    </div>
                  </Section>

                  <Section label="Mandatory Sections">
                    <ol className="space-y-1 list-decimal list-inside">
                      {report.sections.map((s) => (
                        <li key={s} className="text-[11px] text-slate-600 dark:text-slate-400">{s}</li>
                      ))}
                    </ol>
                  </Section>

                  <Section label="RAG / Confidence Logic">
                    <p className="text-[11px] text-slate-600 dark:text-slate-400 leading-relaxed">{report.ragLogic}</p>
                  </Section>

                  <Section label="Expected Follow-up Actions">
                    <div className="flex flex-wrap gap-1.5">
                      {report.followUpActions.map((a) => (
                        <span key={a} className="inline-block px-2 py-0.5 rounded-full bg-cyan-50 dark:bg-cyan-900/20 text-[10px] font-medium text-cyan-700 dark:text-cyan-300">{a}</span>
                      ))}
                    </div>
                  </Section>
                </>
              )}

              {activeTab === 'data' && (
                <>
                  <div className={`rounded-xl p-4 ${ragConf.bg} ${ragConf.border} border`}>
                    <div className="flex items-center gap-2 mb-2">
                      <RagIcon size={16} className={ragConf.text} />
                      <span className={`text-sm font-semibold ${ragConf.text}`}>{ragConf.label}</span>
                    </div>
                    <p className="text-[11px] text-slate-600 dark:text-slate-400 leading-relaxed">{report.ragLogic}</p>
                  </div>

                  <Section label="Live Metrics">
                    <div className="space-y-2">
                      {report.highlights.map((h) => (
                        <div key={h.label} className="flex items-center justify-between py-1.5 border-b border-slate-100 dark:border-navy-800 last:border-0">
                          <span className="text-xs text-slate-500 dark:text-slate-400">{h.label}</span>
                          <span className={`text-sm font-semibold tabular-nums ${
                            h.variant === 'critical' ? 'text-rose-600 dark:text-rose-400' :
                            h.variant === 'warn' ? 'text-amber-600 dark:text-amber-400' :
                            'text-slate-900 dark:text-white'
                          }`}>
                            {h.value}
                          </span>
                        </div>
                      ))}
                    </div>
                  </Section>

                  <Section label="Data Sources">
                    <div className="space-y-1">
                      {report.dataSources.map((ds) => (
                        <div key={ds} className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400">
                          <CheckCircle2 size={10} className="text-emerald-500 shrink-0" />
                          {ds}
                        </div>
                      ))}
                    </div>
                  </Section>
                </>
              )}

              {activeTab === 'export' && (
                <>
                  <ExportCard
                    icon={<FileText size={20} className="text-cyan-500" />}
                    title={t('execution.reportPanel.exportPdf', 'Export as PDF Report')}
                    description={t('execution.reportPanel.exportPdfDesc', 'A4 report with RAG header, live data, sections, and follow-up checklist. Ready for stakeholder distribution.')}
                    action={t('execution.reportPanel.downloadPdf', 'Download PDF')}
                    onAction={handleExportPDF}
                    loading={isExporting}
                  />

                  <ExportCard
                    icon={<Presentation size={20} className="text-purple-500" />}
                    title={t('execution.reportPanel.exportPresentation', 'Create Presentation')}
                    description={t('execution.reportPanel.exportPresentationDesc', 'Open in Presentation Generator to create a slide deck from this report definition and live data.')}
                    action={t('execution.reportPanel.openGenerator', 'Open Generator')}
                    onAction={handleExportPresentation}
                  />

                  <ExportCard
                    icon={<Copy size={20} className="text-slate-500 dark:text-slate-400" />}
                    title={t('execution.reportPanel.copyMarkdown', 'Copy as Markdown')}
                    description={t('execution.reportPanel.copyMarkdownDesc', 'Full report definition with live data in markdown format. Paste into documents, wikis, or chat.')}
                    action={t('execution.reportPanel.copy', 'Copy to Clipboard')}
                    onAction={handleCopyMarkdown}
                  />
                </>
              )}
            </div>

            {/* Footer */}
            <div className="px-4 py-3 border-t border-slate-100 dark:border-navy-800 flex items-center gap-2">
              {onGenerate && (
                <button
                  type="button"
                  onClick={() => onGenerate(report)}
                  className="h-8 px-4 rounded-lg text-xs font-medium bg-cyan-600 text-white hover:bg-cyan-700 transition-colors flex items-center gap-1.5"
                >
                  <Sparkles size={12} />
                  {t('execution.reportPanel.generateAI', 'Generate with AI')}
                </button>
              )}
              <button
                type="button"
                onClick={handleExportPDF}
                disabled={isExporting}
                className="h-8 px-3 rounded-lg text-xs font-medium border border-slate-200 dark:border-navy-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-navy-800 transition-colors flex items-center gap-1.5 disabled:opacity-50"
              >
                {isExporting ? <Loader2 size={12} className="animate-spin" /> : <Download size={12} />}
                PDF
              </button>
              <button
                type="button"
                onClick={handleCopyMarkdown}
                className="h-8 px-3 rounded-lg text-xs font-medium border border-slate-200 dark:border-navy-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-navy-800 transition-colors flex items-center gap-1.5"
              >
                <Copy size={12} />
                {t('execution.reportPanel.copy', 'Copy')}
              </button>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};

// ---------------------------------------------------------------------------
// SUB-COMPONENTS
// ---------------------------------------------------------------------------

const Section: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => (
  <div>
    <div className="text-[10px] uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-1.5 font-medium">{label}</div>
    {children}
  </div>
);

const ExportCard: React.FC<{
  icon: React.ReactNode;
  title: string;
  description: string;
  action: string;
  onAction: () => void;
  loading?: boolean;
}> = ({ icon, title, description, action, onAction, loading }) => (
  <div className="rounded-xl border border-slate-200 dark:border-navy-700 bg-white dark:bg-navy-900 p-4">
    <div className="flex items-start gap-3">
      <div className="shrink-0 w-10 h-10 flex items-center justify-center rounded-xl bg-slate-100 dark:bg-navy-800">
        {icon}
      </div>
      <div className="flex-1 min-w-0">
        <div className="text-sm font-medium text-slate-900 dark:text-white">{title}</div>
        <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">{description}</p>
        <button
          type="button"
          onClick={onAction}
          disabled={loading}
          className="mt-2.5 h-7 px-3 rounded-lg text-[11px] font-medium bg-slate-100 dark:bg-navy-800 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-navy-700 transition-colors flex items-center gap-1.5 disabled:opacity-50"
        >
          {loading ? <Loader2 size={10} className="animate-spin" /> : <ChevronRight size={10} />}
          {action}
        </button>
      </div>
    </div>
  </div>
);
