
import React from 'react';
import { FullSession, Language } from '../types';
import { translations } from '../translations';
import { Download, Copy, BarChart3, TrendingUp, CheckSquare } from 'lucide-react';

interface FullStep6WorkspaceProps {
  fullSession: FullSession;
  language: Language;
}

export const FullStep6Workspace: React.FC<FullStep6WorkspaceProps> = ({ 
  fullSession, 
  language 
}) => {
  const t = translations.fullReports;
  const ts = translations.sidebar;
  const report = fullSession.report;
  
  // 1. Maturity Calculations
  const scores = Object.entries(fullSession.assessment)
    .filter(([key]) => key !== 'completedAxes')
    .map(([key, val]: [string, any]) => ({ id: key, score: val.score }));
  
  const sortedScores = [...scores].sort((a, b) => b.score - a.score);
  const highest = sortedScores[0];
  const lowest = sortedScores[scores.length - 1];

  const getAxisLabel = (id: string) => {
      const key = `fullStep1_${id === 'digitalProducts' ? 'prod' : id.substring(0,4)}` as any;
      return ts[key]?.[language] || id;
  };

  // 2. Economics
  const econ = fullSession.economics || { totalCost: 0, totalAnnualBenefit: 0, overallROI: 0, paybackPeriodYears: 0 };

  // 3. Execution
  const initiatives = fullSession.initiatives || [];
  const total = initiatives.length;
  const done = initiatives.filter(i => i.status === 'Done').length;
  const inProg = initiatives.filter(i => i.status === 'In Progress').length;
  const blocked = initiatives.filter(i => i.status === 'Blocked').length;
  const completion = total > 0 ? (done / total) * 100 : 0;

  const handleExport = () => {
    if (!report) return;

    const content = `
# Digital Transformation Blueprint
Generated by CONSULTIFY AI
Date: ${new Date().toLocaleDateString()}

## EXECUTIVE SUMMARY
${report.executiveSummary}

## KEY FINDINGS
${report.keyFindings.map(f => `- ${f}`).join('\n')}

## RECOMMENDATIONS
${report.recommendations.map(r => `- ${r}`).join('\n')}

## ECONOMICS
Total Cost: $${econ.totalCost.toLocaleString()}k
Annual Benefit: $${econ.totalAnnualBenefit.toLocaleString()}k
ROI: ${econ.overallROI.toFixed(0)}%
Payback: ${econ.paybackPeriodYears.toFixed(1)} years

## MATURITY OVERVIEW
Strongest Axis: ${getAxisLabel(highest.id)} (${highest.score.toFixed(1)}/7)
Weakest Axis: ${getAxisLabel(lowest.id)} (${lowest.score.toFixed(1)}/7)
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `consultify_report_${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
     if (!report) return;
     navigator.clipboard.writeText(report.executiveSummary).then(() => {
        alert("Executive Summary copied to clipboard!");
     });
  };

  return (
    <div className="flex flex-col h-full bg-navy-900">
      {/* Header */}
      <div className="h-20 border-b border-white/5 flex flex-col justify-center px-8 bg-navy-900 shrink-0">
         <div className="flex justify-between items-center mb-1">
           <span className="text-sm font-semibold text-white tracking-wide">{t.header[language]}</span>
           <span className="text-xs text-slate-500">FINAL STEP</span>
         </div>
         <div className="w-full h-1 bg-navy-800 rounded-full overflow-hidden">
           <div className="h-full bg-green-500 w-full shadow-[0_0_10px_rgba(34,197,94,0.5)]"></div>
         </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-8 space-y-6">
         
         {/* Card 1: Maturity */}
         <div className="bg-navy-950/50 border border-white/10 rounded-xl p-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-5">
               <BarChart3 size={80} className="text-white"/>
            </div>
            <h4 className="text-sm font-semibold text-white mb-4 flex items-center gap-2 relative z-10">
                <BarChart3 size={16} className="text-blue-400"/>
                {t.cards.maturity[language]}
            </h4>
            
            <div className="grid grid-cols-2 gap-4 relative z-10">
               <div className="p-3 bg-navy-900 rounded border border-white/5">
                   <div className="text-xs text-slate-500 uppercase font-bold mb-1">Strongest</div>
                   <div className="text-white font-medium text-sm">{getAxisLabel(highest.id)}</div>
                   <div className="text-green-400 text-xs font-bold">{highest.score.toFixed(1)}/7</div>
               </div>
               <div className="p-3 bg-navy-900 rounded border border-white/5">
                   <div className="text-xs text-slate-500 uppercase font-bold mb-1">Weakest</div>
                   <div className="text-white font-medium text-sm">{getAxisLabel(lowest.id)}</div>
                   <div className="text-red-400 text-xs font-bold">{lowest.score.toFixed(1)}/7</div>
               </div>
            </div>
         </div>

         {/* Card 2: Economics */}
         <div className="bg-navy-950/50 border border-white/10 rounded-xl p-6 relative overflow-hidden">
             <div className="absolute top-0 right-0 p-4 opacity-5">
               <TrendingUp size={80} className="text-white"/>
            </div>
            <h4 className="text-sm font-semibold text-white mb-4 flex items-center gap-2 relative z-10">
                <TrendingUp size={16} className="text-green-400"/>
                {t.cards.economics[language]}
            </h4>
            
            <div className="space-y-3 relative z-10">
                <div className="flex justify-between items-center pb-2 border-b border-white/5">
                   <span className="text-slate-400 text-xs uppercase">Total Cost</span>
                   <span className="text-white font-bold">${econ.totalCost.toLocaleString()}k</span>
                </div>
                <div className="flex justify-between items-center pb-2 border-b border-white/5">
                   <span className="text-slate-400 text-xs uppercase">Annual Benefit</span>
                   <span className="text-green-400 font-bold">${econ.totalAnnualBenefit.toLocaleString()}k</span>
                </div>
                <div className="flex justify-between items-center">
                   <span className="text-slate-400 text-xs uppercase">ROI</span>
                   <span className="text-purple-400 font-bold">{econ.overallROI.toFixed(0)}%</span>
                </div>
            </div>
         </div>

         {/* Card 3: Execution */}
         <div className="bg-navy-950/50 border border-white/10 rounded-xl p-6 relative overflow-hidden">
             <div className="absolute top-0 right-0 p-4 opacity-5">
               <CheckSquare size={80} className="text-white"/>
            </div>
            <h4 className="text-sm font-semibold text-white mb-4 flex items-center gap-2 relative z-10">
                <CheckSquare size={16} className="text-purple-400"/>
                {t.cards.execution[language]}
            </h4>
            
            <div className="flex items-center gap-4 mb-4 relative z-10">
                <div className="flex-1">
                   <div className="text-2xl font-bold text-white">{completion.toFixed(0)}%</div>
                   <div className="text-xs text-slate-500">Completion Rate</div>
                </div>
                <div className="flex-1 text-right">
                   <div className="text-2xl font-bold text-white">{total}</div>
                   <div className="text-xs text-slate-500">Initiatives</div>
                </div>
            </div>
            
            <div className="flex gap-1 h-2 rounded-full overflow-hidden bg-navy-900 relative z-10">
                <div className="bg-green-500" style={{ width: `${(done/total)*100}%` }}></div>
                <div className="bg-blue-500" style={{ width: `${(inProg/total)*100}%` }}></div>
                <div className="bg-red-500" style={{ width: `${(blocked/total)*100}%` }}></div>
            </div>
            <div className="flex justify-between mt-2 text-[10px] text-slate-500 relative z-10">
               <span className="flex items-center gap-1"><div className="w-1.5 h-1.5 rounded-full bg-green-500"></div>Done</span>
               <span className="flex items-center gap-1"><div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div>In Prog</span>
               <span className="flex items-center gap-1"><div className="w-1.5 h-1.5 rounded-full bg-red-500"></div>Blocked</span>
            </div>
         </div>

      </div>

      {/* Footer */}
      <div className="p-6 border-t border-white/5 bg-navy-900 flex justify-between gap-4">
        <button 
          onClick={handleCopy}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg border border-white/10 text-slate-300 hover:text-white hover:bg-white/5 transition-all text-sm font-medium"
        >
           <Copy size={16} /> {t.buttons.copy[language]}
        </button>
        <button 
          onClick={handleExport}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg bg-purple-600 hover:bg-purple-500 text-white shadow-lg shadow-purple-900/20 transition-all text-sm font-bold"
        >
           <Download size={16} /> {t.buttons.export[language]}
        </button>
      </div>
    </div>
  );
};
