
import React from 'react';
import { FullReport, Language } from '../types';
import { translations } from '../translations';
import { FileText } from 'lucide-react';

interface FullReportDocumentProps {
  report: FullReport;
  language: Language;
}

export const FullReportDocument: React.FC<FullReportDocumentProps> = ({ 
  report, 
  language 
}) => {
  const t = translations.fullReports;

  const SectionHeader = ({ title }: { title: string }) => (
    <div className="mt-8 mb-4 border-b border-navy-800 pb-2">
      <h3 className="text-lg font-bold text-purple-400 uppercase tracking-wide">{title}</h3>
    </div>
  );

  return (
    <div className="h-full bg-navy-950 flex flex-col">
       {/* Document Header */}
       <div className="h-16 border-b border-navy-800 flex items-center px-8 bg-navy-950 shrink-0">
          <FileText className="text-purple-500 mr-3" size={20} />
          <span className="font-semibold text-white tracking-wide">{t.header[language]}</span>
          <span className="ml-auto text-xs text-slate-500 font-mono">
             Generated: {new Date(report.generatedAt).toLocaleDateString()}
          </span>
       </div>

       {/* Scrollable Document Area */}
       <div className="flex-1 overflow-y-auto p-8 lg:p-12">
          <div className="max-w-3xl mx-auto bg-navy-900/50 p-8 lg:p-12 rounded-xl border border-white/5 shadow-2xl">
             
             {/* Title */}
             <div className="text-center mb-12">
                <h1 className="text-3xl font-bold text-white mb-2">Digital Transformation Blueprint</h1>
                <p className="text-slate-400">Strategic Assessment & Execution Roadmap</p>
             </div>

             {/* Executive Summary */}
             <SectionHeader title={t.sections.exec[language]} />
             <div className="prose prose-invert prose-p:text-slate-300 prose-p:leading-relaxed max-w-none">
                {report.executiveSummary.split('\n\n').map((para, i) => (
                   <p key={i} className="mb-4">{para}</p>
                ))}
             </div>

             {/* Key Findings / Maturity */}
             <SectionHeader title={t.sections.maturity[language]} />
             <ul className="space-y-2">
                {report.keyFindings.map((finding, i) => (
                   <li key={i} className="flex gap-3 text-slate-300">
                      <span className="text-blue-500 mt-1.5">•</span>
                      <span>{finding}</span>
                   </li>
                ))}
             </ul>

             {/* Recommendations / Initiatives */}
             <SectionHeader title={t.sections.initiatives[language]} />
             <ul className="space-y-2">
                {report.recommendations.map((rec, i) => (
                   <li key={i} className="flex gap-3 text-slate-300">
                      <span className="text-green-500 mt-1.5">✓</span>
                      <span>{rec}</span>
                   </li>
                ))}
             </ul>

             {/* Footer */}
             <div className="mt-16 pt-8 border-t border-white/5 text-center text-xs text-slate-600">
                <p>CONFIDENTIAL - Generated by CONSULTIFY AI</p>
             </div>

          </div>
       </div>
    </div>
  );
};
