import { chromium } from 'playwright';
import fs from 'fs';
const BASE='http://127.0.0.1:3187';
const OUT='/private/tmp/wt-rev-real/evidence/przeglad-dbr77/realizacja';
const b=await chromium.launch();
const c=await b.newContext({storageState:'/private/tmp/wt-rev-real/auth-piotr.json',viewport:{width:1440,height:900}});
const p=await c.newPage();
const bledy=[], zapisy=[];
p.on('console',m=>{if(m.type()==='error')bledy.push(m.text().slice(0,300));});
p.on('response',r=>{const u=r.url();if(/\/api\/tasks/.test(u)&&r.request().method()!=='GET')zapisy.push({url:u.replace(BASE,''),method:r.request().method(),status:r.status()});});
const wybierz=async()=>{await p.getByRole('cell',{name:'Złożenie dokumentacji zgodności'}).first().click();await p.waitForTimeout(2500);};
await p.goto(`${BASE}/execution?tab=work`,{waitUntil:'domcontentloaded'});
await p.waitForTimeout(13000);
await wybierz();
await p.screenshot({path:`${OUT}/16-praca-podglad-przed-edycja.png`});
await p.getByRole('button',{name:/^Zmień termin$/}).first().click();
await p.waitForTimeout(1500);
const pole=p.locator('input[type="date"]:visible').first();
await pole.fill('2026-02-10');
await p.waitForTimeout(6000);
await p.screenshot({path:`${OUT}/17-praca-po-zapisie.png`});
console.log('zapisy:',JSON.stringify(zapisy));
await p.reload({waitUntil:'domcontentloaded'});
await p.waitForTimeout(13000);
await wybierz();
await p.screenshot({path:`${OUT}/18-praca-po-reload.png`});
const tekst=(await p.locator('body').innerText()).replace(/\n{2,}/g,'\n').slice(0,2200);
fs.writeFileSync(`${OUT}/18-praca-po-reload.png.json`,JSON.stringify({ekran:'praca-edycja-inline-i-reload',url:`${BASE}/execution?tab=work`,zmiana:'termin 09.02.2026 -> 10.02.2026, potem przywrocony',zapisy,bledyKonsoli:bledy,tekstEkranu:tekst},null,1));
console.log('bledy konsoli:',bledy.length);
await b.close();
