/**
 * Types Index
 * Master export file for all TypeScript types
 *
 * Enterprise SaaS Architecture - Consultinity
 */

// Core Enums and UI-specific types (Explicitly selected to avoid collisions)
export type {
  AdditionalAudit,
  Address,
  ADMAAssessmentData,
  ADMAPillarId,
  AICharterRequest,
  AIGeneratedCharter,
  AIMessageHistory,
  AIPreferences,
  AIProactivityMode,
  AIProviderType,
  AISettingsAuditEntry,
  ApiKey,
  ApprovalChainStatus,
  Artifact,
  AssessmentFrameworkId,
  AssessmentTab,
  AxisAssessment,
  AxisId,
  BenefitRange,
  BlockType,
  CalloutBlockContent,
  Certification,
  Challenge,
  ChatCitation,
  ChatMessage,
  // Additional missing types
  ChatOption,
  ChatResponseAction,
  CMMIAssessmentData,
  CMMICategoryId,
  CommsPlanItem,
  CompanyProfile,
  CompanySize,
  Constraint,
  ContactEmail,
  ContactPhone,
  ContentAnalyticsDashboard,
  ContentAnalyticsEvent,
  ContentCategory,
  ContentComment,
  ContentReview,
  ContentReviewPriority,
  ContentReviewStatus,
  ContentTag,
  CostRange,
  CustomRole,
  DaySchedule,
  DBR77AssessmentData,
  DBR77ProcessAssessment,
  DBR77WorkstationAssessment,
  Document,
  DoNotDisturbHours,
  DRDAxis,
  EconomicsSummary,
  Education,
  EffectiveAISettings,
  EmailPreferences,
  EmailTemplate,
  EmailTemplateStatus,
  EmergencyContact,
  ExtendedContactInfo,
  ExtendedSocialLinks,
  FocusMode,
  FreeSession,
  FullInitiative,
  FullReport,
  FullSession,
  GapForGeneration,
  GeneratedInitiative,
  GroupPermission,
  InitiativeComment,
  InitiativeGeneratorConstraints,
  InitiativeRiskLevel,
  InitiativeTeamMember,
  InitiativeTemplate,
  InitiativeVersion,
  Invitation,
  InvitationEvent,
  InvitationValidation,
  KeyboardShortcuts,
  KPITracking,
  Language,
  LegalDocType,
  LegalDocument,
  LinkedAccounts,
  LLMProvider,
  ManagementReport,
  ManagementReportScope,
  ManagementReportStatus,
  ManagementReportType,
  MaturityLevel,
  Notification,
  OrgAISettings,
  OrganizationOwnership,
  OrganizationProfile,
  OutOfOfficePeriod,
  OutOfOfficeSettings,
  OverallRAGStatus,
  OwnershipTransferRequest,
  PDFImportResult,
  PerformancePreferences,
  PermissionRequest,
  PermissionRequestPriority,
  PermissionRequestType,
  PlaybookEdge,
  PlaybookNode,
  PlaybookTemplateStats,
  PlaybookTemplateVersion,
  PlaybookTemplateVersionHistory,
  PMOProjectRole,
  PortfolioFilters,
  PortfolioInitiative,
  PortfolioSortConfig,
  PortfolioStats,
  PortfolioViewMode,
  PortfolioHealthReportContent,
  ProactivityBehavior,
  ProfileCompletion,
  ProfileVisibility,
  Quarter,
  QuietHoursSettings as QuietHoursSettingsType,
  RACIMatrix,
  RACIType,
  RAGStatus,
  RAGStatusItem,
  RelatedInitiative,
  Report,
  ReportApproval,
  ReportApprovalStatus,
  ReportBlock,
  ReportComment,
  ReportVersion,
  RaidReportContent,
  RiskRating,
  RolePermission,
  ShortcutAction,
  ShortcutCategory,
  ShortcutPreset,
  SIRIAssessmentData,
  SocialLinks,
  SpendingAlert,
  StakeholderImpact,
  StakeholderMapItem,
  StatusTransition,
  SteeringCommitteeReportContent,
  StrategicGoal,
  StrategicIntent,
  SuperAdminAISettings,
  TableBlockContent,
  TeamMeetingReportContent,
  TemplateCategory,
  TemplateGraph,
  TemplateValidationError,
  TextBlockContent,
  ThinkingStep,
  ToolCallInfo,
  UserAIProvider,
  UserAISettings,
  UserGroup,
  UserProfileExtended,
  UserSkill,
  VersionComparisonResult,
  Wave,
  WorkExperience,
  WorkflowState,
  Workstream,
  WorkstreamStatus,
} from './core';
export {
  ACCOUNT_TYPES,
  AppView,
  // Enum values
  AssessmentStep,
  AuthStep,
  InitiativeStatus,
  InvitationStatus,
  InvitationType,
  AccountType as LegacyAccountType,
  ProjectRole as LegacyProjectRole,
  UserRole as LegacyUserRole,
  PlaybookNodeType,
  PROJECT_ROLES,
  ProjectRole,
  SCMSPhase,
  SessionMode,
  TaskStatus,
  TemplateStatus,
  UserRole,
} from './core';

// Create Artifact alias
export type { Artifact as AIArtifact, WorkingHours } from './core';

// API Types (Categorized)
export * from './api/requests';
export * from './api/responses';

// Domain Types (Categorized)
export * from './domain/ai';
export * from './domain/billing';
export * from './domain/pmo';
export * from './domain/project';
export * from './domain/user';

// UI Types
export * from './ui/index';

// Specialized types
export * from './AIContract';
export * from './discovery';
export * from './myWork';
export * from './workspace';

// Re-export config types
export type { CardDocumentation } from '../config/cardDocumentation';
export type { FAQItem } from '../config/faqContent';
export type { VideoTutorial } from '../config/videoTutorialsContent';
