/**
 * Report Header Component
 * Header with title, period, and metadata
 */

import React from 'react';
import { Calendar, Clock, FileText, Building2 } from 'lucide-react';
import { ManagementReportType, ManagementReportScope, RAGStatus } from '../../../../types';
import { RAGIndicator } from './RAGIndicator';

interface ReportHeaderProps {
    title: string;
    reportType: ManagementReportType;
    scope: ManagementReportScope;
    periodStart: string;
    periodEnd: string;
    generatedAt: string;
    generatedBy?: string;
    projectName?: string;
    organizationName?: string;
    overallHealth?: RAGStatus;
    className?: string;
}

const reportTypeLabels = {
    TEAM_MEETING: { label: 'Team Meeting Report', icon: '📋', color: 'bg-blue-500' },
    STEERING_COMMITTEE: { label: 'Steering Committee Report', icon: '🏛️', color: 'bg-violet-500' }
};

const scopeLabels = {
    PROJECT: 'Single Project',
    PORTFOLIO: 'Portfolio'
};

export const ReportHeader: React.FC<ReportHeaderProps> = ({
    title,
    reportType,
    scope,
    periodStart,
    periodEnd,
    generatedAt,
    generatedBy,
    projectName,
    organizationName,
    overallHealth,
    className = ''
}) => {
    const typeConfig = reportTypeLabels[reportType] || reportTypeLabels.TEAM_MEETING;

    return (
        <div className={`bg-white dark:bg-navy-900 rounded-xl border border-slate-200 dark:border-white/10 p-6 ${className}`}>
            {/* Top row - type badge and health */}
            <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                    <span className={`px-3 py-1 rounded-full ${typeConfig.color} text-white text-sm font-medium`}>
                        {typeConfig.icon} {typeConfig.label}
                    </span>
                    <span className="px-2 py-1 rounded bg-slate-100 dark:bg-white/10 text-slate-600 dark:text-slate-300 text-xs font-medium">
                        {scopeLabels[scope]}
                    </span>
                </div>
                {overallHealth && (
                    <RAGIndicator status={overallHealth} size="lg" showLabel />
                )}
            </div>

            {/* Title */}
            <h1 className="text-2xl font-bold text-navy-900 dark:text-white mb-4">
                {title}
            </h1>

            {/* Metadata grid */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {/* Period */}
                <div className="flex items-center gap-2 text-sm">
                    <Calendar size={16} className="text-slate-400" />
                    <div>
                        <span className="text-slate-500 dark:text-slate-400">Period: </span>
                        <span className="font-medium text-navy-900 dark:text-white">
                            {periodStart} - {periodEnd}
                        </span>
                    </div>
                </div>

                {/* Generated */}
                <div className="flex items-center gap-2 text-sm">
                    <Clock size={16} className="text-slate-400" />
                    <div>
                        <span className="text-slate-500 dark:text-slate-400">Generated: </span>
                        <span className="font-medium text-navy-900 dark:text-white">
                            {new Date(generatedAt).toLocaleDateString()}
                        </span>
                    </div>
                </div>

                {/* Project/Organization */}
                {(projectName || organizationName) && (
                    <div className="flex items-center gap-2 text-sm">
                        <Building2 size={16} className="text-slate-400" />
                        <div>
                            <span className="text-slate-500 dark:text-slate-400">
                                {scope === 'PROJECT' ? 'Project: ' : 'Organization: '}
                            </span>
                            <span className="font-medium text-navy-900 dark:text-white">
                                {projectName || organizationName}
                            </span>
                        </div>
                    </div>
                )}

                {/* Generated by */}
                {generatedBy && (
                    <div className="flex items-center gap-2 text-sm">
                        <FileText size={16} className="text-slate-400" />
                        <div>
                            <span className="text-slate-500 dark:text-slate-400">By: </span>
                            <span className="font-medium text-navy-900 dark:text-white">
                                {generatedBy}
                            </span>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ReportHeader;


