/**
 * J17 (program JEZYK_EN_PL_20260908 §J17) — ANGIELSKIE zdania dla kodów błędów serwera.
 *
 * DLACZEGO TU, A NIE TYLKO W `public/locales/en`: `src/i18n.ts` ma
 * `react.useSuspense: false`, więc do czasu dojścia pliku tłumaczeń `t()` zwraca
 * defaultValue z kodu. Gdyby default był polski, użytkownik EN zobaczyłby polskie
 * zdanie przy KAŻDYM pierwszym malowaniu (zasada 3 planu). Dlatego tu jest wyłącznie
 * angielski; polski żyje wyłącznie w `public/locales/pl/translation.json`.
 *
 * Źródło listy: pomiar K5pl (258 polskich zdań z serwera) — 222 z nich serwer już
 * wysyłał z polem `code`, front go ignorował i renderował polskie `error`.
 * Lista NIE jest zamknięta: nieznany kod dostaje `API_ERROR_GENERIC`, nigdy zdania
 * z serwera.
 *
 * NIE dopisuj tu polskiego. NIE usuwaj kodu bez usunięcia go z serwera.
 */
export const API_ERROR_FALLBACKS_EN: Readonly<Record<string, string>> = Object.freeze({
  ADMIN_ACCESS_REQUIRED: 'Organization administrator permissions are required.',
  AI_BUDGET_EXHAUSTED: 'The assistant response could not be generated.',
  AI_CLARIFY_TIMEOUT: 'Generating clarifying questions timed out.',
  AI_NOTIFICATION_TRIGGER_FAILED: 'The AI notification could not be created.',
  ARTIFACT_APPROVALS_UNEXPECTED_FAILED: 'A server error occurred.',
  ASSESSMENT_AI_AUTOCOMPLETE_FAILED: 'Autocomplete could not be applied.',
  ASSESSMENT_AI_CORRECT_TEXT_FAILED: 'The text could not be corrected.',
  ASSESSMENT_AI_ESTIMATE_ROI_FAILED: 'ROI could not be estimated.',
  ASSESSMENT_AI_FILL_MISSING_FIELDS_FAILED: 'The missing fields could not be filled in.',
  ASSESSMENT_AI_GENERATE_BENCHMARK_COMMENTARY_FAILED: 'The benchmark commentary could not be generated.',
  ASSESSMENT_AI_GENERATE_BENCHMARK_REPORT_FAILED: 'The benchmark report could not be generated.',
  ASSESSMENT_AI_GENERATE_EVIDENCE_SUGGESTIONS_FAILED: 'Evidence suggestions could not be generated.',
  ASSESSMENT_AI_GENERATE_EXECUTIVE_SUMMARY_FAILED: 'The executive summary could not be generated.',
  ASSESSMENT_AI_GENERATE_FULL_REPORT_FAILED: 'The full report could not be generated.',
  ASSESSMENT_AI_GENERATE_GAP_ANALYSIS_FAILED: 'The gap analysis could not be generated.',
  ASSESSMENT_AI_GENERATE_INITIATIVES_FAILED: 'Initiatives could not be generated.',
  ASSESSMENT_AI_GENERATE_INITIATIVE_PLAN_FAILED: 'The initiative plan could not be generated.',
  ASSESSMENT_AI_GENERATE_INSIGHTS_FAILED: 'Insights could not be generated.',
  ASSESSMENT_AI_GENERATE_STAKEHOLDER_REPORT_FAILED: 'The stakeholder report could not be generated.',
  ASSESSMENT_AI_GENERATE_STAKEHOLDER_VIEW_FAILED: 'The stakeholder view could not be generated.',
  ASSESSMENT_AI_GENERATE_SUGGESTION_FAILED: 'The suggestion could not be generated.',
  ASSESSMENT_AI_GENERATE_TARGET_SUGGESTION_FAILED: 'The target suggestion could not be generated.',
  ASSESSMENT_AI_GET_CLARIFYING_QUESTION_FAILED: 'The clarifying question could not be loaded.',
  ASSESSMENT_AI_GET_CONTEXTUAL_HELP_FAILED: 'Contextual help could not be loaded.',
  ASSESSMENT_AI_GET_GUIDANCE_FAILED: 'Guidance could not be loaded.',
  ASSESSMENT_AI_GET_QUICK_ACTIONS_FAILED: 'Quick actions could not be loaded.',
  ASSESSMENT_AI_GET_REPORT_TYPES_FAILED: 'Report types could not be loaded.',
  ASSESSMENT_AI_PRIORITIZE_INITIATIVES_FAILED: 'Initiatives could not be prioritized.',
  ASSESSMENT_AI_REVIEW_JUSTIFICATIONS_FAILED: 'The justifications could not be reviewed.',
  ASSESSMENT_AI_VALIDATE_CONSISTENCY_FAILED: 'Consistency could not be validated.',
  ASSESSMENT_AI_VALIDATE_FIELD_FAILED: 'The field could not be validated.',
  ASSESSMENT_CONCLUSION_NO_EXECUTIVE_SUMMARY: 'This report has no executive summary yet, so there is nothing to build a conclusion from.',
  ASSESSMENT_CONCLUSION_PERSIST_FAILED: 'The conclusion could not be saved.',
  ASSESSMENT_EXPORT_FAILED: 'The assessment file could not be generated.',
  ASSESSMENT_HUB_CREATE_ASSESSMENT_FAILED: 'The assessment could not be created.',
  ASSESSMENT_HUB_DELETE_ASSESSMENT_FAILED: 'The assessment could not be deleted.',
  ASSESSMENT_HUB_FETCH_ASSESSMENTS_FAILED: 'Assessments could not be loaded.',
  ASSESSMENT_HUB_FETCH_ASSESSMENT_FAILED: 'The assessment could not be loaded.',
  ASSESSMENT_HUB_UPDATE_STATUS_FAILED: 'The status could not be updated.',
  ASSESSMENT_NOT_FOUND: 'No assessment was found for the given identifier.',
  ASSESSMENT_REPORTS_APPROVE_REPORT_FAILED: 'The report could not be approved.',
  ASSESSMENT_REPORTS_CREATE_REPORT_FAILED: 'The report could not be created.',
  ASSESSMENT_REPORTS_CREATE_SECTION_FAILED: 'The section could not be created.',
  ASSESSMENT_REPORTS_DELETE_REPORT_FAILED: 'The report could not be deleted.',
  ASSESSMENT_REPORTS_DELETE_SECTION_FAILED: 'The section could not be deleted.',
  ASSESSMENT_REPORTS_EXPORT_REPORT_FAILED: 'The report could not be exported.',
  ASSESSMENT_REPORTS_FETCH_HISTORY_FAILED: 'The history could not be loaded.',
  ASSESSMENT_REPORTS_FETCH_REPORTS_FAILED: 'Reports could not be loaded.',
  ASSESSMENT_REPORTS_FETCH_REPORT_FAILED: 'The report could not be loaded.',
  ASSESSMENT_REPORTS_FETCH_SECTIONS_FAILED: 'Sections could not be loaded.',
  ASSESSMENT_REPORTS_FETCH_TEMPLATES_FAILED: 'Templates could not be loaded.',
  ASSESSMENT_REPORTS_FINALIZE_REPORT_FAILED: 'The report could not be finalized.',
  ASSESSMENT_REPORTS_GENERATE_CONCLUSION_FAILED: 'The conclusion could not be generated from the assessment.',
  ASSESSMENT_REPORTS_GENERATE_DECK_FAILED: 'The presentation could not be generated.',
  ASSESSMENT_REPORTS_GENERATE_DRD_REPORT_FAILED: 'The DRD report could not be generated.',
  ASSESSMENT_REPORTS_REJECT_REPORT_FAILED: 'The report could not be rejected.',
  ASSESSMENT_REPORTS_REORDER_SECTIONS_FAILED: 'The sections could not be reordered.',
  ASSESSMENT_REPORTS_SEND_BACK_REPORT_FAILED: 'The report could not be sent back.',
  ASSESSMENT_REPORTS_START_GENERATION_FAILED: 'Generation could not be started.',
  ASSESSMENT_REPORTS_UPDATE_REPORT_FAILED: 'The report could not be updated.',
  ASSESSMENT_REPORTS_UPDATE_SECTION_FAILED: 'The section could not be updated.',
  ASSESSMENT_REPORTS_UTILIZE_REPORT_FAILED: 'The report could not be put to use.',
  ASSESSMENT_WORKFLOW_APPROVE_FAILED: 'The approval could not be recorded.',
  ASSESSMENT_WORKFLOW_CANCEL_ACCESS_REQUEST_FAILED: 'The access request could not be cancelled.',
  ASSESSMENT_WORKFLOW_CREATE_ASSESSMENT_VERSION_FAILED: 'The assessment version could not be created.',
  ASSESSMENT_WORKFLOW_DIFF_ASSESSMENT_VERSIONS_FAILED: 'The assessment versions could not be compared.',
  ASSESSMENT_WORKFLOW_GET_ACCESS_REQUESTS_FAILED: 'Access requests could not be loaded.',
  ASSESSMENT_WORKFLOW_GET_ACTIVITY_LOGS_FAILED: 'The activity log could not be loaded.',
  ASSESSMENT_WORKFLOW_GET_HISTORY_FAILED: 'The history could not be loaded.',
  ASSESSMENT_WORKFLOW_GET_PENDING_REVIEWS_FAILED: 'Pending reviews could not be loaded.',
  ASSESSMENT_WORKFLOW_GET_VERSIONS_FAILED: 'Versions could not be loaded.',
  ASSESSMENT_WORKFLOW_GET_WORKFLOW_STATUS_FAILED: 'The workflow status could not be loaded.',
  ASSESSMENT_WORKFLOW_INITIALIZE_WORKFLOW_FAILED: 'The workflow could not be initialized.',
  ASSESSMENT_WORKFLOW_LOG_ACTIVITY_FAILED: 'The activity could not be recorded.',
  ASSESSMENT_WORKFLOW_REJECT_FAILED: 'The rejection could not be recorded.',
  ASSESSMENT_WORKFLOW_RESTORE_VERSION_FAILED: 'The version could not be restored.',
  ASSESSMENT_WORKFLOW_START_REVIEW_FAILED: 'The review could not be started.',
  ASSESSMENT_WORKFLOW_SUBMIT_FOR_REVIEW_FAILED: 'The item could not be submitted for review.',
  ASSESSMENT_WORKFLOW_SUBMIT_REVIEW_FAILED: 'The review could not be submitted.',
  ASSESSMENT_WORKFLOW_V2_BUILD_ELIGIBILITY_FAILED: 'Eligibility could not be calculated.',
  ASSESSMENT_WORKFLOW_V2_EVALUATE_PERMISSIONS_FAILED: 'Permissions could not be evaluated.',
  ASSESSMENT_WORKFLOW_V2_FETCH_BENCHMARK_COMPARISON_FAILED: 'The benchmark comparison could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_FETCH_GATE_DECISIONS_FAILED: 'Gate decisions could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_FETCH_RUN_FAILED: 'The run could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_GET_ACCESS_REQUESTS_FAILED: 'Access requests could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_GET_ROLES_FAILED: 'Roles could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_GET_USER_ROLE_FAILED: 'The user role could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_LIST_BATCHES_FAILED: 'The batch list could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_LIST_REPORT_VERSIONS_FAILED: 'The report version list could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_LIST_RUNS_FAILED: 'The run list could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_LIST_RUN_INITIATIVES_FAILED: 'The initiatives of the run could not be loaded.',
  ASSESSMENT_WORKFLOW_V2_SEARCH_USERS_FAILED: 'The user search failed.',
  ASSESSMENT_WORKFLOW_V2_SUBMIT_DRAFTS_FAILED: 'The drafts could not be submitted.',
  ASSESSMENT_WORKFLOW_V2_UPDATE_GATE_DECISION_FAILED: 'The gate decision could not be updated.',
  AUDIT_COMPARE_PARAMS_INVALID: 'Numeric parameters ?a=<version>&b=<version> are required.',
  AUDIT_CONCLUSION_NO_SUMMARY: 'This report has neither an overall conclusion nor an executive summary, so there is nothing to build a conclusion from.',
  AUDIT_CONCLUSION_PERSIST_FAILED: 'The conclusion could not be saved.',
  AUDIT_CRITERIA_PAYLOAD_INVALID: 'An array of criteria was expected (body or body.criteria).',
  AUDIT_DIFF_PARAMS_MISSING: 'Parameters a and b are required.',
  AUDIT_INTERNAL_ERROR: 'An error occurred while processing the audit operation.',
  AUDIT_MATERIAL_ID_REQUIRED: 'materialId is required.',
  AUDIT_MISSING_ENTITY: 'entityType and entityId are required.',
  AUDIT_MISSING_PROGRAM: 'programId is required.',
  AUDIT_NEW_OUTPUT_ID_REQUIRED: 'newOutputId is required.',
  AUDIT_NOT_FOUND: 'The audit item was not found.',
  AUDIT_PROGRAM_ID_REQUIRED: 'The programId parameter is required.',
  AUDIT_PROPOSAL_INPUT_INVALID: 'programId and findingIds (a non-empty list) are required.',
  AUDIT_REPORT_INPUT_INVALID: 'programId, outputId and reportKind are required.',
  DATA_EXPORT_CANCEL_DELETION_FAILED: 'The data deletion request could not be cancelled.',
  DATA_EXPORT_CREATE_REQUEST_FAILED: 'The data export request could not be created.',
  DATA_EXPORT_DOWNLOAD_FAILED: 'The export could not be downloaded.',
  DATA_EXPORT_LIST_REQUESTS_FAILED: 'Export requests could not be loaded.',
  DATA_EXPORT_STATUS_FAILED: 'The export status could not be loaded.',
  GOVERNED_CONNECTOR_NOT_APPROVED: 'This integration is not available in this edition.',
  INITIATIVE_GENERATION_SCHEMA_MISSING: 'The run could not be created.',
  INVALID_ORGANIZATION_IDENTIFIER: 'The organization identifier is not a valid UUID, so this configuration cannot be saved.',
  KNOWLEDGE_CANDIDATES_APPROVED_FAILED: 'Approved ideas could not be loaded.',
  KNOWLEDGE_CANDIDATES_BY_CATEGORY_FAILED: 'Ideas by category could not be loaded.',
  KNOWLEDGE_CANDIDATES_BY_PROJECT_FAILED: 'Ideas by project could not be loaded.',
  KNOWLEDGE_CANDIDATES_LIST_FAILED: 'Knowledge candidates could not be loaded.',
  KNOWLEDGE_CANDIDATE_CREATE_FAILED: 'The candidate could not be submitted.',
  KNOWLEDGE_CANDIDATE_LINK_PROJECT_FAILED: 'The idea could not be linked to the project.',
  KNOWLEDGE_CANDIDATE_STATUS_UPDATE_FAILED: 'The candidate status could not be updated.',
  KNOWLEDGE_CANDIDATE_UPDATE_FAILED: 'The candidate could not be updated.',
  KNOWLEDGE_DOCUMENTS_LIST_FAILED: 'Knowledge documents could not be loaded.',
  KNOWLEDGE_DOCUMENT_UPLOAD_FAILED: 'The document could not be uploaded.',
  KNOWLEDGE_STRATEGIES_LIST_FAILED: 'Strategies could not be loaded.',
  KNOWLEDGE_STRATEGY_CREATE_FAILED: 'The strategy could not be created.',
  KNOWLEDGE_STRATEGY_LINK_DOCUMENT_FAILED: 'The document could not be linked to the strategy.',
  KNOWLEDGE_STRATEGY_LINK_IDEA_FAILED: 'The idea could not be linked to the strategy.',
  KNOWLEDGE_STRATEGY_PROGRESS_UPDATE_FAILED: 'The strategy progress could not be updated.',
  KNOWLEDGE_STRATEGY_RELATED_FAILED: 'Strategies with their links could not be loaded.',
  KNOWLEDGE_STRATEGY_TOGGLE_FAILED: 'The strategy could not be toggled.',
  KNOWLEDGE_STRATEGY_UNLINK_DOCUMENT_FAILED: 'The document could not be unlinked from the strategy.',
  KNOWLEDGE_STRATEGY_UNLINK_IDEA_FAILED: 'The idea could not be unlinked from the strategy.',
  KNOWLEDGE_STRATEGY_UPDATE_FAILED: 'The strategy could not be updated.',
  KNOWLEDGE_VAULT_FOLDERS_FAILED: 'Folders could not be loaded.',
  KNOWLEDGE_VAULT_FOLDER_CREATE_FAILED: 'The folder could not be created.',
  KNOWLEDGE_VAULT_FOLDER_DELETE_FAILED: 'The folder could not be deleted.',
  KNOWLEDGE_VAULT_FOLDER_UPDATE_FAILED: 'The folder could not be updated.',
  KNOWLEDGE_VAULT_SAFES_FAILED: 'The list of safes could not be loaded.',
  MANAGEMENT_REPORT_UPDATE_FAILED: 'The report could not be updated.',
  MEGATREND_BASELINE_FAILED: 'Megatrends could not be loaded.',
  MEGATREND_CUSTOM_CREATE_FAILED: 'The trend could not be created.',
  MEGATREND_CUSTOM_UPDATE_FAILED: 'The trend could not be updated.',
  MEGATREND_DETAIL_FAILED: 'The trend details could not be loaded.',
  MEGATREND_RADAR_FAILED: 'The radar data could not be loaded.',
  MFA_BACKUP_CODES_NOT_PERSISTED: 'New backup codes could not be generated.',
  MFA_BACKUP_CODE_NOT_CONSUMED: 'Verification failed.',
  MFA_DISABLE_FAILED: 'Multi-factor authentication could not be disabled.',
  MFA_DISABLE_NOT_PERSISTED: 'Multi-factor authentication could not be disabled.',
  MFA_ENABLE_NOT_PERSISTED: 'Multi-factor authentication could not be enabled.',
  MFA_REGENERATE_CODES_FAILED: 'New backup codes could not be generated.',
  MFA_SETUP_FAILED: 'Multi-factor authentication could not be set up.',
  MFA_SETUP_NOT_PERSISTED: 'Multi-factor authentication could not be set up.',
  MFA_STATUS_FAILED: 'The multi-factor authentication status could not be loaded.',
  MFA_VERIFY_FAILED: 'Verification failed.',
  MFA_VERIFY_SETUP_FAILED: 'The multi-factor authentication setup could not be verified.',
  ORG_POLICY_SNAPSHOT_FAILED: 'The organization access settings could not be loaded.',
  PRESENTATION_GENERATION_IN_PROGRESS: 'Generation is already running — poll the status instead of starting again.',
  REPORT_BUILDER_PUBLIC_GENERATE_DOCX_FAILED: 'The DOCX file could not be generated.',
  REPORT_BUILDER_PUBLIC_GENERATE_PDF_FAILED: 'The PDF file could not be generated.',
  REPORT_BUILDER_PUBLIC_GENERATE_PPTX_FAILED: 'The PPTX file could not be generated.',
  SETTINGS_AI_PROVIDERS_UPDATE_FAILED: 'The AI providers could not be saved.',
  SETTINGS_DASHBOARD_PREFERENCES_UPDATE_FAILED: 'The dashboard preferences could not be saved.',
  SETTINGS_DIGEST_PREFERENCES_UPDATE_FAILED: 'The notification digest could not be saved.',
  SETTINGS_DND_UPDATE_FAILED: 'Do not disturb could not be saved.',
  SETTINGS_EMAIL_NOTIFICATIONS_UPDATE_FAILED: 'The email notification preferences could not be saved.',
  SETTINGS_INBOX_AI_UPDATE_FAILED: 'The inbox AI preferences could not be saved.',
  SETTINGS_NOTIFICATIONS_SAVE_FAILED: 'The notification preferences could not be saved.',
  SETTINGS_NOTIFICATIONS_UPDATE_FAILED: 'The notification preferences could not be saved.',
  SETTINGS_QUIET_HOURS_UPDATE_FAILED: 'The quiet hours could not be saved.',
  SETTINGS_SCHEMA_NOT_MIGRATED: 'The database does not have the required settings schema.',
  SETTINGS_SIGNATURE_CREATE_FAILED: 'The signature could not be created.',
  SETTINGS_SIGNATURE_DELETE_FAILED: 'The signature could not be deleted.',
  SETTINGS_SIGNATURE_SET_DEFAULT_FAILED: 'The default signature could not be set.',
  SETTINGS_SIGNATURE_UPDATE_FAILED: 'The signature could not be saved.',
  SETTINGS_SOUND_PREFERENCES_UPDATE_FAILED: 'The notification sounds could not be saved.',
  SETTINGS_WORKING_HOURS_UPDATE_FAILED: 'The working hours could not be saved.',
  SETTINGS_WORK_PREFERENCES_UPDATE_FAILED: 'The work preferences could not be saved.',
  SUPERADMIN_CONTRACT_CREATE_FAILED: 'The contract could not be created.',
  SUPERADMIN_CONTRACT_DELETE_FAILED: 'The contract could not be deleted.',
  SUPERADMIN_CONTRACT_UPDATE_FAILED: 'The contract could not be updated.',
  SUPERADMIN_LIFECYCLE_STAGES_FETCH_FAILED: 'The customer lifecycle stages could not be loaded.',
  SUPERADMIN_LIFECYCLE_STAGE_CREATE_FAILED: 'The lifecycle stage could not be created.',
  SUPERADMIN_LIFECYCLE_STAGE_DELETE_FAILED: 'The lifecycle stage could not be deleted.',
  SUPERADMIN_LIFECYCLE_STAGE_UPDATE_FAILED: 'The lifecycle stage could not be updated.',
  SUPERADMIN_LIFECYCLE_TRANSITION_CREATE_FAILED: 'The lifecycle transition could not be created.',
  SUPERADMIN_PLAYBOOK_CREATE_FAILED: 'The playbook could not be created.',
  SUPERADMIN_PLAYBOOK_DELETE_FAILED: 'The playbook could not be deleted.',
  SUPERADMIN_PLAYBOOK_EXECUTE_FAILED: 'The playbook could not be executed.',
  SUPERADMIN_PLAYBOOK_UPDATE_FAILED: 'The playbook could not be updated.',
  VAULT_VERSION_CONFLICT: 'The document changed in the meantime — refresh and try again.',
  VAULT_VERSION_CREATE_FAILED: 'The new document version could not be saved.',
  VAULT_VERSION_RESTORE_FAILED: 'The document version could not be restored.',
  ANALYSES_READ_FAILED: 'The list of analyses could not be loaded. This is a read failure, not an empty list.',
  BENEFIT_ACTUAL_APPEND_ONLY: 'The recorded actual value changed in parallel — nothing was overwritten. Refresh the data and try again.',
  BILLING_ALERTS_UNAVAILABLE: 'The budget thresholds could not be saved permanently. The settings are unchanged.',
  BUSINESS_CASE_ENDPOINT_RETIRED: 'This endpoint was a stub and no longer produces an empty document. Use POST /api/v8/advisory/business-case instead.',
  FINANCE_STORAGE_UNAVAILABLE: 'This part of Finance has no storage in this database yet. Nothing was saved — try again once storage is available.',
  INITIATIVE_MATERIALIZE_EMPTY_PORTFOLIO: 'The portfolio is empty or the material could not be generated.',
  INITIATIVE_MATERIALIZE_FAILED: 'The material could not be generated (no initiative, or not enough data).',
  ORGANIZATION_CONTEXT_MISSING: 'No organization context.',
  PROJECT_ACCESS_FORBIDDEN: 'You do not have access to this project.',
  RESULTS_ACTUAL_SOURCE_REQUIRED: 'The actual value is unchanged. Publish an Actual snapshot in Results and open the reconciliation with its exact identifier.',
  ROI_RECONCILIATION_STORAGE_UNAVAILABLE: 'The linked ROI Case could not be checked — nothing was saved and the recorded actual value is unchanged.',
  TRIAL_ENTRY_ORGANIZATION_REQUIRED: 'This feature requires an organization. You are in the Trial Entry phase.',
  TRIAL_ENTRY_RESTRICTION: 'This feature is not available in Trial Entry. Create an organization to continue.',
  VAULT_DOCUMENT_DELETE_FORBIDDEN: 'You do not have permission to delete this document.',
  VAULT_DOCUMENT_EDIT_FORBIDDEN: 'You do not have permission to edit this document.',
  VAULT_EXPECTED_VERSION_INVALID: 'expectedVersion must be an integer.',
  VAULT_FOLDER_PROJECT_MISMATCH: 'The folder belongs to a different project.',
  VAULT_FOLDER_SCOPE_MISMATCH: 'The folder belongs to a different safe level.',
  VAULT_PROJECT_ID_REQUIRED: 'projectId is required for scope=project.',
  VAULT_SCOPE_INVALID: 'scope must be one of: user, project, organization.',
  VAULT_VERSION_NUMBER_INVALID: 'versionNumber must be a positive integer.',
});

/** Zdanie pokazywane, gdy kod jest nieznany albo go w ogóle nie ma. */
export const API_ERROR_GENERIC_EN = 'Something went wrong. Please try again.';
