/**
 * Chat V9 / TRUST T-TR2 — pure builder for the "Why this answer?"
 * reasoning snippet rendered inside the Trust Badge popover.
 *
 * What the builder produces
 * -------------------------
 * A deterministic, closed-enum list of observations the popover
 * renders as bullet points when the user expands "Why this
 * answer?". Each observation has:
 *
 *   - `id`      — closed-enum token; safe to use as a React key
 *                 and as a selector in tests.
 *   - `headline`— one-line title (e.g. "Retrieval signal").
 *   - `body`    — a single user-facing sentence. Template string
 *                 with a dictionary-fed token (`{n}`, `{model}`)
 *                 so the caller doesn't have to stitch strings.
 *
 * The list is always non-empty: even the worst-case "no sources,
 * no model" input yields at least the honest disclosure
 * observation. Callers must not assume a specific order beyond
 * the priority documented below.
 *
 * Priority order
 * --------------
 *   1. `retrieval-*`  — what the reply was grounded on.
 *   2. `model-*`      — which model actually generated it.
 *   3. `verify`       — always-present reminder so the expansion
 *                       never ends on a smug signal.
 *
 * PII / telemetry contract
 * ------------------------
 * Pure helper. No store access, no DOM, no telemetry hook. All
 * strings are template literals the caller renders directly; the
 * template variables (`{n}`, `{model}`) are the ONLY dynamic
 * content and the caller substitutes them with the already-
 * normalised `citationCount` and `modelLabel` it already passes
 * to `buildTrustBadgeCitationsText`.
 *
 * Design notes
 * ------------
 * - `citationCount` below 0 or non-finite falls through to the
 *   `retrieval-none` branch. The caller should not have to
 *   defensively clamp before calling us.
 * - `modelLabel` is only considered "known" when it is a
 *   non-empty trimmed string. Empty / whitespace / null / undef
 *   all resolve to `model-unknown`.
 * - "Few" vs "Many" thresholds mirror the existing
 *   `bucketSourceCount` buckets in `TrustBadge.tsx` so the
 *   badge-level source count and the reasoning snippet never
 *   contradict each other.
 */

export const TRUST_REASONING_OBSERVATION_IDS = [
  'retrieval-strong',
  'retrieval-some',
  'retrieval-none',
  'model-known',
  'model-unknown',
  'verify',
] as const;

export type TrustReasoningObservationId = (typeof TRUST_REASONING_OBSERVATION_IDS)[number];

export interface TrustReasoningObservation {
  id: TrustReasoningObservationId;
  headline: string;
  body: string;
}

export interface BuildTrustBadgeReasoningInput {
  citationCount: number;
  modelLabel: string | null | undefined;
}

function isCleanModel(label: string | null | undefined): label is string {
  return typeof label === 'string' && label.trim().length > 0;
}

function retrievalObservation(count: number): TrustReasoningObservation {
  if (!Number.isFinite(count) || count <= 0) {
    return {
      id: 'retrieval-none',
      headline: 'No retrieved sources',
      body: 'This reply was generated from the model\u2019s own reasoning. Nothing was retrieved from your documents or external search.',
    };
  }
  if (count >= 4) {
    return {
      id: 'retrieval-strong',
      headline: 'Grounded in retrieved sources',
      body: `The reply is grounded in ${count} retrieved sources (see list above).`,
    };
  }
  return {
    id: 'retrieval-some',
    headline: 'Partial retrieval coverage',
    body: `The reply cites ${count} retrieved source${count === 1 ? '' : 's'}; the rest came from the model\u2019s own reasoning.`,
  };
}

function modelObservation(label: string | null | undefined): TrustReasoningObservation {
  if (isCleanModel(label)) {
    return {
      id: 'model-known',
      headline: 'Model used',
      body: `Generated by ${label.trim()}.`,
    };
  }
  return {
    id: 'model-unknown',
    headline: 'Model not recorded',
    body: 'The model that generated this reply was not recorded on the message metadata.',
  };
}

function verifyObservation(): TrustReasoningObservation {
  return {
    id: 'verify',
    headline: 'Always verify',
    body: 'Retrieval tells you what the model saw, not whether it is correct. Double-check anything that affects a decision.',
  };
}

/**
 * Compute the ordered observation list for the reasoning snippet.
 * The returned array is always non-empty; length is in [2, 3].
 */
export function buildTrustBadgeReasoning(
  input: BuildTrustBadgeReasoningInput
): readonly TrustReasoningObservation[] {
  const { citationCount, modelLabel } = input;
  return [retrievalObservation(citationCount), modelObservation(modelLabel), verifyObservation()];
}
