/**
 * Chat V9 / TRUST T-TR1.4 — pure formatter for the "Copy
 * reasoning" clipboard payload.
 *
 * What we emit
 * ------------
 * A small Markdown block users can paste into a Notion page, a
 * JIRA ticket, or a Slack message to quote the Trust Badge's
 * "Why this answer?" reasoning observations verbatim:
 *
 *   ```
 *   Why this answer? (answered by GPT-4o):
 *   1. Grounded in retrieved sources — The reply is grounded in 4 retrieved sources (see list above).
 *   2. Model used — Generated by GPT-4o.
 *   3. Always verify — Retrieval tells you what the model saw, not whether it is correct. Double-check anything that affects a decision.
 *   ```
 *
 * Design notes
 * ------------
 * - Deterministic and dependency-free. Accepts the same
 *   observations `buildTrustBadgeReasoning` produces so there is
 *   no risk of the clipboard payload contradicting the popover.
 * - Rendering rules:
 *     * Header is always present; the optional `modelLabel`
 *       suffix mirrors the existing `buildTrustBadgeCitationsText`
 *       header style so both clipboard blocks read like siblings.
 *     * Each observation is rendered as
 *       `<N>. <headline> — <body>` — the em-dash separator is
 *       intentional and matches the existing citations block.
 *     * Observations with an empty `headline` OR empty `body`
 *       after trim are skipped; numbering is re-computed off
 *       output position, never input index, so a filtered row
 *       never leaves a `1., 3.` gap on the clipboard.
 *     * An empty or null input list yields a graceful
 *       "No reasoning recorded." stub under the header so
 *       nothing ever lands silently on the clipboard.
 * - The helper is orthogonal to T-TR1.2's dictionary: the caller
 *   passes the already-humanised `modelLabel`, we never re-
 *   humanise here.
 */

import type { TrustReasoningObservation } from './buildTrustBadgeReasoning';

export interface BuildReasoningTextOptions {
  /**
   * Optional humanised model label (e.g. `"GPT-4o"`). When
   * present, rendered in the header line as "(answered by
   * <label>)". Empty / whitespace / non-string values are
   * ignored.
   */
  modelLabel?: string | null;
}

function sanitiseModelLabel(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  return trimmed.length > 0 ? trimmed : null;
}

export function buildTrustBadgeReasoningText(
  observations: readonly TrustReasoningObservation[] | null | undefined,
  options: BuildReasoningTextOptions = {}
): string {
  const modelLabel = sanitiseModelLabel(options.modelLabel);
  const headerBase = 'Why this answer?';
  const header = modelLabel ? `${headerBase} (answered by ${modelLabel}):` : `${headerBase}:`;

  if (!Array.isArray(observations) || observations.length === 0) {
    return `${header}\n\nNo reasoning recorded.`;
  }

  // Renumber by output position (not input index) so a skipped
  // invalid observation never leaves a numbering gap, matching
  // `buildTrustBadgeCitationsText`'s behaviour.
  const lines: string[] = [];
  for (const obs of observations) {
    if (!obs || typeof obs !== 'object') continue;
    const headline = typeof obs.headline === 'string' ? obs.headline.trim() : '';
    const body = typeof obs.body === 'string' ? obs.body.trim() : '';
    if (!headline || !body) continue;
    lines.push(`${lines.length + 1}. ${headline} — ${body}`);
  }

  if (lines.length === 0) {
    return `${header}\n\nNo reasoning recorded.`;
  }

  return [header, '', ...lines].join('\n');
}
