import type { KpiDefinitionDto, KpiDefinitionVersionDto, KpiMeasurementDto } from './kpiApi';
import type { OkrSetDto } from './okr/okrApi';
import type { RoiCaseListItem, RoiOrgBenefitsRealizationRow } from './roi/roiApi';
import { isPublicProductionHost } from '@/utils/publicProduction';

export function shouldUseResultsVNextOwnerSampleData(
  source: { search: string; hostname: string } | undefined = typeof window === 'undefined'
    ? undefined
    : { search: window.location.search, hostname: window.location?.hostname ?? '' }
): boolean {
  if (!source || isPublicProductionHost(source.hostname)) return false;
  return new URLSearchParams(source.search).get('sampleData') === 'results-vnext';
}

const now = '2026-08-23T14:30:00.000Z';

export const RESULTS_VNEXT_SAMPLE_KPIS: KpiDefinitionDto[] = [
  {
    kpiId: 'sample-kpi-delivery',
    organizationId: 'sample-org',
    kpiCode: 'DELIVERY_ON_TIME',
    status: 'active',
    currentDefinitionVersionId: 'sample-kpi-delivery-v2',
    primaryProcessId: 'Order fulfillment',
    responsePolicyId: 'weekly-review',
    ownerUserId: 'Piotr Wiśniewski',
    rowVersion: 2,
    createdBy: 'Piotr Wiśniewski',
    createdAt: '2026-06-12T08:00:00.000Z',
    updatedAt: now,
  },
  {
    kpiId: 'sample-kpi-quality',
    organizationId: 'sample-org',
    kpiCode: 'FIRST_PASS_YIELD',
    status: 'active',
    currentDefinitionVersionId: 'sample-kpi-quality-v3',
    primaryProcessId: 'Production quality',
    responsePolicyId: 'deviation-loop',
    ownerUserId: 'Anna Kowalska',
    rowVersion: 3,
    createdBy: 'Anna Kowalska',
    createdAt: '2026-05-20T08:00:00.000Z',
    updatedAt: '2026-08-22T09:20:00.000Z',
  },
  {
    kpiId: 'sample-kpi-energy',
    organizationId: 'sample-org',
    kpiCode: 'ENERGY_INTENSITY',
    status: 'pending_approval',
    currentDefinitionVersionId: 'sample-kpi-energy-v1',
    primaryProcessId: 'Energy management',
    responsePolicyId: 'monthly-review',
    ownerUserId: 'Marek Nowak',
    rowVersion: 1,
    createdBy: 'Marek Nowak',
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-21T13:10:00.000Z',
  },
  {
    kpiId: 'sample-kpi-leadtime',
    organizationId: 'sample-org',
    kpiCode: 'ORDER_LEAD_TIME',
    status: 'draft',
    currentDefinitionVersionId: null,
    primaryProcessId: 'Sales operations',
    responsePolicyId: null,
    ownerUserId: 'Lena Meyer',
    rowVersion: 1,
    createdBy: 'Lena Meyer',
    createdAt: '2026-08-22T12:00:00.000Z',
    updatedAt: '2026-08-22T12:00:00.000Z',
  },
];

export const RESULTS_VNEXT_SAMPLE_KPI_VERSIONS: KpiDefinitionVersionDto[] = [
  {
    definitionVersionId: 'sample-kpi-delivery-v2',
    kpiId: 'sample-kpi-delivery',
    organizationId: 'sample-org',
    versionNumber: 2,
    name: 'On-time delivery',
    description: 'Share of customer orders delivered on or before the confirmed delivery date.',
    unit: '%',
    targetGeometry: 'threshold_min',
    targetValue: 95,
    targetMin: null,
    targetMax: null,
    warningLow: 92,
    warningHigh: null,
    criticalLow: 88,
    criticalHigh: null,
    binarySuccessValue: null,
    formulaText: 'Orders delivered on time / all delivered orders × 100',
    approvalStatus: 'approved',
    effectiveFrom: '2026-07-01',
    effectiveTo: null,
    createdBy: 'Piotr Wiśniewski',
    createdAt: '2026-06-20T08:00:00.000Z',
    updatedAt: '2026-06-28T10:00:00.000Z',
    submittedBy: 'Piotr Wiśniewski',
    submittedAt: '2026-06-24T10:00:00.000Z',
    approvedBy: 'Anna Kowalska',
    approvedAt: '2026-06-28T10:00:00.000Z',
    rejectedBy: null,
    rejectedAt: null,
    rejectionReason: null,
    rowVersion: 2,
  },
  {
    definitionVersionId: 'sample-kpi-quality-v3',
    kpiId: 'sample-kpi-quality',
    organizationId: 'sample-org',
    versionNumber: 3,
    name: 'First pass yield',
    description: 'Share of production units accepted without rework at the first quality gate.',
    unit: '%',
    targetGeometry: 'threshold_min',
    targetValue: 98,
    targetMin: null,
    targetMax: null,
    warningLow: 96,
    warningHigh: null,
    criticalLow: 93,
    criticalHigh: null,
    binarySuccessValue: null,
    formulaText: 'Units accepted first time / all inspected units × 100',
    approvalStatus: 'approved',
    effectiveFrom: '2026-08-01',
    effectiveTo: null,
    createdBy: 'Anna Kowalska',
    createdAt: '2026-07-12T08:00:00.000Z',
    updatedAt: '2026-07-25T10:00:00.000Z',
    submittedBy: 'Anna Kowalska',
    submittedAt: '2026-07-20T10:00:00.000Z',
    approvedBy: 'Piotr Wiśniewski',
    approvedAt: '2026-07-25T10:00:00.000Z',
    rejectedBy: null,
    rejectedAt: null,
    rejectionReason: null,
    rowVersion: 3,
  },
  {
    definitionVersionId: 'sample-kpi-energy-v1',
    kpiId: 'sample-kpi-energy',
    organizationId: 'sample-org',
    versionNumber: 1,
    name: 'Energy intensity',
    description: 'Energy consumed per finished production unit.',
    unit: 'kWh/unit',
    targetGeometry: 'threshold_max',
    targetValue: 42,
    targetMin: null,
    targetMax: null,
    warningLow: null,
    warningHigh: 45,
    criticalLow: null,
    criticalHigh: 50,
    binarySuccessValue: null,
    formulaText: 'Total production energy / accepted finished units',
    approvalStatus: 'submitted',
    effectiveFrom: null,
    effectiveTo: null,
    createdBy: 'Marek Nowak',
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-21T13:10:00.000Z',
    submittedBy: 'Marek Nowak',
    submittedAt: '2026-08-21T13:10:00.000Z',
    approvedBy: null,
    approvedAt: null,
    rejectedBy: null,
    rejectedAt: null,
    rejectionReason: null,
    rowVersion: 1,
  },
];

export const RESULTS_VNEXT_SAMPLE_KPI_MEASUREMENTS: KpiMeasurementDto[] = [
  {
    measurementId: 'sample-measurement-delivery-2026w34',
    kpiId: 'sample-kpi-delivery',
    definitionVersionId: 'sample-kpi-delivery-v2',
    organizationId: 'sample-org',
    periodStart: '2026-08-17',
    periodEnd: '2026-08-23',
    actualValue: 93.6,
    performanceStatus: 'warning',
    dataQualityStatus: 'verified',
    correctionOfMeasurementId: null,
    correctionReason: null,
    source: 'Owner review sample',
    evidenceRefs: ['sample-evidence-delivery-w34'],
    notes: 'Two late deliveries were linked to a supplier capacity constraint.',
    recordedBy: 'Anna Kowalska',
    recordedAt: now,
  },
  {
    measurementId: 'sample-measurement-quality-2026w34',
    kpiId: 'sample-kpi-quality',
    definitionVersionId: 'sample-kpi-quality-v3',
    organizationId: 'sample-org',
    periodStart: '2026-08-17',
    periodEnd: '2026-08-23',
    actualValue: 97.4,
    performanceStatus: 'warning',
    dataQualityStatus: 'verified',
    correctionOfMeasurementId: null,
    correctionReason: null,
    source: 'Owner review sample',
    evidenceRefs: ['sample-evidence-fpy-w34'],
    notes: 'Rework remains concentrated on one production cell.',
    recordedBy: 'Anna Kowalska',
    recordedAt: '2026-08-22T09:20:00.000Z',
  },
  {
    measurementId: 'sample-measurement-energy-2026-08',
    kpiId: 'sample-kpi-energy',
    definitionVersionId: 'sample-kpi-energy-v1',
    organizationId: 'sample-org',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    actualValue: 44.8,
    performanceStatus: 'warning',
    dataQualityStatus: 'estimated',
    correctionOfMeasurementId: null,
    correctionReason: null,
    source: 'Owner review sample',
    evidenceRefs: [],
    notes: 'Month-end estimate; final meter reconciliation is still pending.',
    recordedBy: 'Marek Nowak',
    recordedAt: '2026-08-21T13:10:00.000Z',
  },
];

export const RESULTS_VNEXT_SAMPLE_ROI_CASES: RoiCaseListItem[] = [
  {
    caseId: 'sample-roi-automation',
    organizationId: 'sample-org',
    initiativeId: 'sample-init-automation',
    title: 'Warehouse Automation Pilot',
    ownerUserId: 'Piotr Wiśniewski',
    status: 'benefits_realization',
    currency: 'PLN',
    granularity: 'monthly',
    analysisStart: '2026-01-01',
    analysisEnd: '2027-12-31',
    nextActionType: 'verify_actual_benefits',
    nextActionDueAt: '2026-08-30T12:00:00.000Z',
    nextReviewAt: '2026-09-05T09:00:00.000Z',
    submittedAt: '2026-02-04T10:00:00.000Z',
    approvedAt: '2026-02-12T12:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    changesRequestedAt: null,
    changesRequestedReason: null,
    archivedAt: null,
    rowVersion: 8,
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: now,
  },
  {
    caseId: 'sample-roi-energy',
    organizationId: 'sample-org',
    initiativeId: 'sample-init-energy',
    title: 'Energy Optimization Standard',
    ownerUserId: 'Lena Meyer',
    status: 'tracking',
    currency: 'PLN',
    granularity: 'monthly',
    analysisStart: '2026-03-01',
    analysisEnd: '2028-02-29',
    nextActionType: 'record_forecast',
    nextActionDueAt: '2026-09-01T10:00:00.000Z',
    nextReviewAt: '2026-09-12T09:00:00.000Z',
    submittedAt: '2026-03-10T10:00:00.000Z',
    approvedAt: '2026-03-18T12:00:00.000Z',
    rejectedAt: null,
    rejectionReason: null,
    changesRequestedAt: null,
    changesRequestedReason: null,
    archivedAt: null,
    rowVersion: 5,
    createdAt: '2026-03-02T08:00:00.000Z',
    updatedAt: '2026-08-21T11:00:00.000Z',
  },
  {
    caseId: 'sample-roi-ai',
    organizationId: 'sample-org',
    initiativeId: 'sample-init-ai',
    title: 'Procurement AI Copilot',
    ownerUserId: 'Marek Nowak',
    status: 'submitted_for_approval',
    currency: 'EUR',
    granularity: 'annual',
    analysisStart: '2027-01-01',
    analysisEnd: '2029-12-31',
    nextActionType: 'approve_case',
    nextActionDueAt: '2026-08-27T10:00:00.000Z',
    nextReviewAt: null,
    submittedAt: '2026-08-22T15:00:00.000Z',
    approvedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    changesRequestedAt: null,
    changesRequestedReason: null,
    archivedAt: null,
    rowVersion: 3,
    createdAt: '2026-08-10T08:00:00.000Z',
    updatedAt: '2026-08-22T15:00:00.000Z',
  },
];

export const RESULTS_VNEXT_SAMPLE_BENEFITS: RoiOrgBenefitsRealizationRow[] = [
  {
    caseId: 'sample-roi-automation',
    initiativeId: 'sample-init-automation',
    title: 'Warehouse Automation Pilot',
    status: 'benefits_realization',
    approvedFinancialBenefits: 200000,
    actualFinancialBenefits: 125000,
    benefitsRealizationPct: 62.5,
  },
  {
    caseId: 'sample-roi-energy',
    initiativeId: 'sample-init-energy',
    title: 'Energy Optimization Standard',
    status: 'tracking',
    approvedFinancialBenefits: 180000,
    actualFinancialBenefits: 140000,
    benefitsRealizationPct: 77.8,
  },
];

export const RESULTS_VNEXT_SAMPLE_OKR_SETS: OkrSetDto[] = [
  {
    setId: 'sample-okr-company-q3',
    organizationId: 'sample-org',
    programId: 'transformation-2026',
    cycleId: '2026-q3',
    scopeType: 'company',
    scopeId: 'sample-org',
    ownerUserId: 'Piotr Wiśniewski',
    reviewerUserId: 'Anna Kowalska',
    title: 'Company Results Q3 2026',
    status: 'active',
    submittedBy: 'Piotr Wiśniewski',
    submittedAt: '2026-06-24T10:00:00.000Z',
    approvedBy: 'Anna Kowalska',
    approvedAt: '2026-06-28T10:00:00.000Z',
    changesRequestedBy: null,
    changesRequestedAt: null,
    changesRequestedReason: null,
    currentVersion: 2,
    approvedVersion: 2,
    latestApprovedSnapshotId: 'sample-snapshot-q3',
    overallProgress: '0.70',
    overallConfidence: 'medium',
    attentionState: 'watch',
    lastCheckinAt: '2026-08-21T09:00:00.000Z',
    nextCheckinDueAt: '2026-08-28T09:00:00.000Z',
    carriedFromSetId: null,
    rowVersion: 7,
    createdBy: 'Piotr Wiśniewski',
    createdAt: '2026-06-20T08:00:00.000Z',
    updatedBy: 'Piotr Wiśniewski',
    updatedAt: now,
  },
  {
    setId: 'sample-okr-operations-q3',
    organizationId: 'sample-org',
    programId: 'operations-2026',
    cycleId: '2026-q3',
    scopeType: 'team',
    scopeId: 'operations',
    ownerUserId: 'Anna Kowalska',
    reviewerUserId: 'Piotr Wiśniewski',
    title: 'Operational Excellence Q3',
    status: 'active',
    submittedBy: 'Anna Kowalska',
    submittedAt: '2026-06-25T10:00:00.000Z',
    approvedBy: 'Piotr Wiśniewski',
    approvedAt: '2026-06-29T10:00:00.000Z',
    changesRequestedBy: null,
    changesRequestedAt: null,
    changesRequestedReason: null,
    currentVersion: 3,
    approvedVersion: 3,
    latestApprovedSnapshotId: 'sample-snapshot-ops',
    overallProgress: '0.84',
    overallConfidence: 'high',
    attentionState: 'none',
    lastCheckinAt: '2026-08-22T09:00:00.000Z',
    nextCheckinDueAt: '2026-08-29T09:00:00.000Z',
    carriedFromSetId: null,
    rowVersion: 9,
    createdBy: 'Anna Kowalska',
    createdAt: '2026-06-21T08:00:00.000Z',
    updatedBy: 'Anna Kowalska',
    updatedAt: '2026-08-22T09:00:00.000Z',
  },
  {
    setId: 'sample-okr-ai-q4',
    organizationId: 'sample-org',
    programId: 'ai-2026',
    cycleId: '2026-q4',
    scopeType: 'business_unit',
    scopeId: 'digital',
    ownerUserId: 'Marek Nowak',
    reviewerUserId: 'Piotr Wiśniewski',
    title: 'AI Adoption Q4',
    status: 'draft',
    submittedBy: null,
    submittedAt: null,
    approvedBy: null,
    approvedAt: null,
    changesRequestedBy: null,
    changesRequestedAt: null,
    changesRequestedReason: null,
    currentVersion: 1,
    approvedVersion: null,
    latestApprovedSnapshotId: null,
    overallProgress: null,
    overallConfidence: null,
    attentionState: 'none',
    lastCheckinAt: null,
    nextCheckinDueAt: null,
    carriedFromSetId: null,
    rowVersion: 1,
    createdBy: 'Marek Nowak',
    createdAt: '2026-08-20T08:00:00.000Z',
    updatedBy: null,
    updatedAt: '2026-08-20T08:00:00.000Z',
  },
];
