/**
 * RN-G4 lane `teresa` (FALA 2, 2026-08-11) — the shared, domain-agnostic
 * Teresa GOVERNANCE panel for the ResultsVNext KPI/ROI/OKR full tools.
 *
 * Walks the FULL D13 boundary path, literally, in one component:
 *   dowód/źródło → propozycja → proponowana zmiana → podgląd konsekwencji →
 *   sprawdzenie uprawnień przed wykonaniem → jawna akceptacja albo
 *   odrzucenie → autoryzowana komenda → zapis domenowy → audyt/historia.
 *
 * D13 hard boundary respected structurally, not just by convention: this
 * component NEVER calls a domain write directly. Every mutation goes
 * through the real P08 lifecycle (`teresaProposalApi.ts` →
 * `POST /api/v8/teresa/proposal*`) — `createTeresaProposal` (propose),
 * `approveTeresaProposal`/`rejectTeresaProposal` (explicit human decision),
 * `executeTeresaProposal` (the ONE call that reaches a domain command,
 * server-side, in `teresaCopilotService.ts`'s `performHandoff`). There is
 * no code path here that mutates a KPI/ROI/OKR value without that full
 * sequence, and no `window.confirm`/`window.alert`/`window.prompt` anywhere
 * — every decision is a real, focus-trapped `Modal`.
 *
 * "Teresa niedostępna" is a FIRST-CLASS state, not an afterthought: any
 * transport-level failure (network unreachable, not a domain denial) shows
 * `TeresaUnavailableBanner`, which always offers `onManualFallback` — the
 * caller's job is to make that prop open a manual editor that never touches
 * Teresa at all (ROI: `RoiPirDraftEditModal` + `updateRoiPostInvestmentReviewDraft`).
 *
 * A DOMAIN DENIAL (e.g. ROI's `DISPOSITION_ALREADY_RECORDED`/`NOT_EDITABLE`
 * guards, or a KPI `P08_KPI_VISIBILITY_STALE` check) is a DIFFERENT state
 * from "unavailable" — Teresa and the server are both reachable, but the
 * domain command itself refuses the write. `executeTeresaProposal` never
 * throws for this case (see its own header comment); this panel renders it
 * as `phase:'denied'`, never silently retries, never fabricates success.
 */
import { AlertTriangle, Check, History, Loader2, Sparkles, X } from 'lucide-react';
import React, { useCallback, useEffect, useRef, useState } from 'react';

import { Modal } from '@/components/ui/primitives';
import { MENU_1_PRIMARY_CTA } from '@/components/shared/ModuleMenu3';

import {
  approveTeresaProposal,
  createTeresaProposal,
  executeTeresaProposal,
  getTeresaAuditTrail,
  rejectTeresaProposal,
  TeresaProposalApiError,
} from './teresaProposalApi';
import {
  TeresaEvidenceBreakdown,
  type TeresaEvidenceBreakdownValue,
} from './TeresaEvidenceBreakdown';
import { TeresaUnavailableBanner } from './TeresaUnavailableBanner';
import type {
  HandoffTargetModule,
  TeresaAuditEntry,
  TeresaChatProposalEnvelope,
  TeresaHandoffContext,
  TeresaHandoffExecutionResult,
} from './teresaHandoffTypes';

type PanelPhase =
  | 'thinking' // createTeresaProposal in flight
  | 'proposal' // proposal/pending_approval — awaiting human decision
  | 'approving'
  | 'approved' // approved — awaiting explicit execute
  | 'rejecting'
  | 'rejected'
  | 'executing'
  | 'completed' // execution.success === true, domain write applied
  | 'denied' // execution.success === false — a real domain guard fired
  | 'unavailable'; // transport failure — Teresa unreachable

export interface TeresaProposalPanelProps {
  open: boolean;
  onClose: () => void;
  isPolish: boolean;
  /** Modal title, e.g. "Poproś Teresę o szkic wniosków". */
  title: string;
  targetModule: HandoffTargetModule;
  sessionId: string;
  /** One fresh key per open ATTEMPT (same convention as `newRoiIdempotencyKey`
   * elsewhere in this codebase) — regenerated by the caller each time the
   * panel is (re)opened, not on every render. */
  idempotencyKey: string;
  buildHandoffContext: () => TeresaHandoffContext;
  buildTargetPayload: () => Record<string, unknown>;
  /** What the human sees as "the proposed change" — rendered BEFORE any
   * network call, since this lane composes the draft content client-side
   * from already-visible domain data (see the ROI builder's own header
   * comment on why there is no live LLM call in this surface). */
  renderProposedChange: () => React.ReactNode;
  evidenceBreakdown: TeresaEvidenceBreakdownValue;
  evidencePointers: string[];
  /** Plain-language "what will happen on execute" — must name the EXACT
   * columns/fields that change and state explicitly what does NOT change
   * automatically (the two-gate structure). */
  consequencePreview: string;
  /** Called once with a SUCCESSFUL execution result — the only place a
   * caller should update its own domain-row state (e.g. ROI enabling its
   * pre-existing disposition action). */
  onCompleted: (execution: TeresaHandoffExecutionResult, proposal: TeresaChatProposalEnvelope | null) => void;
  /** Opens a manual editor that never calls Teresa — required reachable
   * from BOTH the unavailable banner and (optionally) as an escape hatch. */
  onManualFallback?: () => void;
}

function isTransportFailure(err: unknown): boolean {
  return err instanceof TeresaProposalApiError && err.status === 0;
}

function errorMessage(err: unknown, isPolish: boolean): string {
  if (err instanceof TeresaProposalApiError) return err.message;
  if (err instanceof Error) return err.message;
  return isPolish ? 'Nieznany błąd' : 'Unknown error';
}

export const TeresaProposalPanel: React.FC<TeresaProposalPanelProps> = ({
  open,
  onClose,
  isPolish,
  title,
  targetModule,
  sessionId,
  idempotencyKey,
  buildHandoffContext,
  buildTargetPayload,
  renderProposedChange,
  evidenceBreakdown,
  evidencePointers,
  consequencePreview,
  onCompleted,
  onManualFallback,
}) => {
  const [phase, setPhase] = useState<PanelPhase>('thinking');
  const [proposal, setProposal] = useState<TeresaChatProposalEnvelope | null>(null);
  const [execution, setExecution] = useState<TeresaHandoffExecutionResult | null>(null);
  const [errorText, setErrorText] = useState<string | null>(null);
  const [rejectReason, setRejectReason] = useState('');
  const [showRejectForm, setShowRejectForm] = useState(false);
  const [log, setLog] = useState<string[]>([]);
  const [auditTrail, setAuditTrail] = useState<TeresaAuditEntry[] | null>(null);
  const [auditLoading, setAuditLoading] = useState(false);
  const startedForKey = useRef<string | null>(null);

  const pushLog = useCallback((line: string) => {
    setLog((prev) => [...prev, line]);
  }, []);

  const startProposal = useCallback(() => {
    setPhase('thinking');
    setErrorText(null);
    setExecution(null);
    setAuditTrail(null);
    setLog([isPolish ? 'Teresa przygotowuje propozycję…' : 'Teresa is preparing a proposal…']);
    createTeresaProposal({
      sessionId,
      handoffContext: buildHandoffContext(),
      targetModule,
      targetPayload: buildTargetPayload(),
      idempotencyKey,
    })
      .then((created) => {
        setProposal(created);
        setPhase('proposal');
        pushLog(
          isPolish
            ? 'Propozycja utworzona — czeka na Twoją decyzję.'
            : 'Proposal created — awaiting your decision.'
        );
      })
      .catch((err) => {
        if (isTransportFailure(err)) {
          setPhase('unavailable');
          setErrorText(errorMessage(err, isPolish));
          return;
        }
        setPhase('unavailable');
        setErrorText(errorMessage(err, isPolish));
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId, targetModule, idempotencyKey, isPolish, pushLog]);

  useEffect(() => {
    if (!open) {
      startedForKey.current = null;
      return;
    }
    if (startedForKey.current === idempotencyKey) return;
    startedForKey.current = idempotencyKey;
    startProposal();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, idempotencyKey]);

  const handleApprove = () => {
    if (!proposal) return;
    setPhase('approving');
    approveTeresaProposal(proposal.proposalId)
      .then((updated) => {
        setProposal(updated);
        setPhase('approved');
        pushLog(
          isPolish
            ? 'Zatwierdzono. Wykonanie wymaga osobnego, jawnego kliknięcia.'
            : 'Approved. Execution still requires a separate, explicit click.'
        );
      })
      .catch((err) => {
        if (isTransportFailure(err)) {
          setPhase('unavailable');
          setErrorText(errorMessage(err, isPolish));
          return;
        }
        setPhase('proposal');
        setErrorText(errorMessage(err, isPolish));
      });
  };

  const handleReject = () => {
    if (!proposal) return;
    setPhase('rejecting');
    rejectTeresaProposal(proposal.proposalId, rejectReason.trim() || undefined)
      .then((updated) => {
        setProposal(updated);
        setPhase('rejected');
        setShowRejectForm(false);
        pushLog(
          isPolish
            ? `Odrzucono. ${rejectReason.trim() ? `Powód: ${rejectReason.trim()}` : 'Bez podanego powodu.'}`
            : `Rejected. ${rejectReason.trim() ? `Reason: ${rejectReason.trim()}` : 'No reason given.'}`
        );
      })
      .catch((err) => {
        if (isTransportFailure(err)) {
          setPhase('unavailable');
          setErrorText(errorMessage(err, isPolish));
          return;
        }
        setPhase(proposal.state === 'approved' ? 'approved' : 'proposal');
        setErrorText(errorMessage(err, isPolish));
      });
  };

  const handleExecute = () => {
    if (!proposal) return;
    setPhase('executing');
    pushLog(
      isPolish
        ? 'Sprawdzam uprawnienia i wykonuję autoryzowaną komendę…'
        : 'Checking permissions and running the authorized command…'
    );
    executeTeresaProposal(proposal.proposalId)
      .then(({ execution: result, proposal: updatedProposal }) => {
        setExecution(result);
        if (updatedProposal) setProposal(updatedProposal);
        if (result.success) {
          setPhase('completed');
          pushLog(isPolish ? 'Zapisano w domenie.' : 'Domain write applied.');
          onCompleted(result, updatedProposal);
        } else {
          setPhase('denied');
          pushLog(
            isPolish
              ? `Zablokowano: ${result.error || 'brak szczegółów'}`
              : `Blocked: ${result.error || 'no details'}`
          );
        }
      })
      .catch((err) => {
        if (isTransportFailure(err)) {
          setPhase('unavailable');
          setErrorText(errorMessage(err, isPolish));
          return;
        }
        setPhase('approved');
        setErrorText(errorMessage(err, isPolish));
      });
  };

  const loadAuditTrail = () => {
    if (!proposal) return;
    setAuditLoading(true);
    getTeresaAuditTrail(proposal.proposalId)
      .then(setAuditTrail)
      .catch((err) => setErrorText(errorMessage(err, isPolish)))
      .finally(() => setAuditLoading(false));
  };

  const busy = phase === 'thinking' || phase === 'approving' || phase === 'rejecting' || phase === 'executing';

  return (
    <Modal
      open={open}
      onClose={busy ? () => {} : onClose}
      title={title}
      size="lg"
      preventOverlayClose={busy}
      preventEscapeClose={busy}
      className="max-h-[85vh] overflow-y-auto"
    >
      <div className="space-y-4" data-testid="teresa-proposal-panel" data-phase={phase}>
        {/* Chat P1-6-style accessible streaming region — mirrors
            UnifiedChatPanel.tsx's role=log/aria-live=polite/aria-relevant
            pattern so screen readers announce each governance-state
            transition as it happens, not just the final state. */}
        <div
          role="log"
          aria-live="polite"
          aria-relevant="additions text"
          aria-label={isPolish ? 'Przebieg rozmowy z Teresą' : "Teresa's proposal log"}
          data-testid="teresa-proposal-log"
          className="max-h-24 space-y-1 overflow-y-auto rounded-lg border border-c-border bg-c-surface-raised p-2 text-[11px] text-c-text-muted"
        >
          {log.map((line, idx) => (
            <div key={idx}>{line}</div>
          ))}
        </div>

        {phase === 'unavailable' ? (
          <TeresaUnavailableBanner
            isPolish={isPolish}
            reason={errorText}
            onRetry={startProposal}
            onManualFallback={
              onManualFallback
                ? () => {
                    onManualFallback();
                    onClose();
                  }
                : undefined
            }
          />
        ) : (
          <>
            <div>
              <div className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-c-text-muted">
                {isPolish ? 'Proponowana zmiana' : 'Proposed change'}
              </div>
              <div className="rounded-lg border border-c-border bg-c-surface p-3 text-sm text-c-text">
                {renderProposedChange()}
              </div>
            </div>

            <TeresaEvidenceBreakdown
              value={evidenceBreakdown}
              evidencePointers={evidencePointers}
              isPolish={isPolish}
            />

            <div>
              <div className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-c-text-muted">
                {isPolish ? 'Podgląd konsekwencji' : 'Consequence preview'}
              </div>
              <p className="rounded-lg border border-c-border bg-c-surface-raised p-3 text-[12px] text-c-text-secondary">
                {consequencePreview}
              </p>
            </div>

            {phase === 'denied' && execution ? (
              <div
                role="alert"
                data-testid="teresa-denied-banner"
                className="flex items-start gap-2 rounded-lg border border-c-danger/30 bg-c-danger/10 p-3 text-[12px] text-c-text"
              >
                <AlertTriangle size={14} className="mt-0.5 shrink-0 text-c-danger" />
                <div>
                  <p className="font-semibold">
                    {isPolish ? 'Wykonanie zablokowane' : 'Execution blocked'}
                  </p>
                  <p>{execution.error || (isPolish ? 'Brak szczegółów.' : 'No details.')}</p>
                  <p className="mt-1 text-c-text-muted">
                    {isPolish
                      ? 'Nic nie zostało zapisane w domenie. Propozycja przeszła do stanu „odrzucona".'
                      : 'Nothing was written to the domain. The proposal moved to "rejected".'}
                  </p>
                </div>
              </div>
            ) : null}

            {phase === 'completed' && execution ? (
              <div
                role="status"
                data-testid="teresa-completed-banner"
                className="flex items-start gap-2 rounded-lg border border-c-success/30 bg-c-success/10 p-3 text-[12px] text-c-text"
              >
                <Check size={14} className="mt-0.5 shrink-0 text-c-success" />
                <div>
                  <p className="font-semibold">{isPolish ? 'Zapisano' : 'Saved'}</p>
                  <p className="text-c-text-muted">
                    {isPolish
                      ? 'Wpis audytowy: '
                      : 'Audit entry: '}
                    <span className="font-mono">{execution.audit_entry_id}</span>
                  </p>
                </div>
              </div>
            ) : null}

            {errorText ? (
              <div role="alert" className="rounded-lg border border-c-danger/30 bg-c-danger/10 p-2 text-[12px] text-c-text">
                {errorText}
              </div>
            ) : null}

            {showRejectForm ? (
              <div className="space-y-2 rounded-lg border border-c-border bg-c-surface p-3">
                <label className="block text-[11px] font-semibold uppercase tracking-wide text-c-text-muted" htmlFor="teresa-reject-reason">
                  {isPolish ? 'Powód odrzucenia (opcjonalnie)' : 'Rejection reason (optional)'}
                </label>
                <textarea
                  id="teresa-reject-reason"
                  value={rejectReason}
                  onChange={(e) => setRejectReason(e.target.value)}
                  data-testid="teresa-reject-reason"
                  className="w-full min-h-[56px] rounded-lg border border-c-border bg-c-surface px-3 py-2 text-sm text-c-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-c-focus"
                />
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={handleReject}
                    disabled={busy}
                    data-testid="teresa-reject-confirm"
                    className="inline-flex h-8 items-center gap-1.5 rounded-lg bg-c-danger px-3 text-[12px] font-medium text-white disabled:opacity-50"
                  >
                    {busy ? <Loader2 size={13} className="animate-spin" /> : <X size={13} />}
                    {isPolish ? 'Potwierdź odrzucenie' : 'Confirm rejection'}
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowRejectForm(false)}
                    disabled={busy}
                    className="inline-flex h-8 items-center rounded-lg border border-c-border px-3 text-[12px] text-c-text"
                  >
                    {isPolish ? 'Anuluj' : 'Cancel'}
                  </button>
                </div>
              </div>
            ) : null}

            {(phase === 'proposal' || phase === 'approved') && !showRejectForm ? (
              <div className="flex flex-wrap gap-2">
                {phase === 'proposal' ? (
                  <button
                    type="button"
                    onClick={handleApprove}
                    disabled={busy}
                    data-testid="teresa-approve"
                    className={`${MENU_1_PRIMARY_CTA} disabled:cursor-not-allowed disabled:opacity-50`}
                  >
                    {busy ? <Loader2 size={16} className="animate-spin" /> : <Check size={16} />}
                    <span>{isPolish ? 'Zatwierdź' : 'Approve'}</span>
                  </button>
                ) : null}
                {phase === 'approved' ? (
                  <button
                    type="button"
                    onClick={handleExecute}
                    disabled={busy}
                    data-testid="teresa-execute"
                    className={`${MENU_1_PRIMARY_CTA} disabled:cursor-not-allowed disabled:opacity-50`}
                  >
                    {busy ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
                    <span>{isPolish ? 'Wykonaj' : 'Execute'}</span>
                  </button>
                ) : null}
                <button
                  type="button"
                  onClick={() => setShowRejectForm(true)}
                  disabled={busy}
                  data-testid="teresa-reject-open"
                  className="inline-flex h-9 items-center gap-2 rounded-lg border border-c-border bg-transparent px-4 text-sm font-medium text-c-text transition-colors hover:bg-c-surface-raised disabled:opacity-50"
                >
                  <X size={16} />
                  <span>{isPolish ? 'Odrzuć' : 'Reject'}</span>
                </button>
              </div>
            ) : null}

            {phase === 'rejected' ? (
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={startProposal}
                  data-testid="teresa-ask-again"
                  className="inline-flex h-9 items-center gap-2 rounded-lg border border-c-border bg-transparent px-4 text-sm font-medium text-c-text transition-colors hover:bg-c-surface-raised"
                >
                  <Sparkles size={16} />
                  <span>{isPolish ? 'Zapytaj Teresę ponownie' : 'Ask Teresa again'}</span>
                </button>
              </div>
            ) : null}

            {proposal && (phase === 'completed' || phase === 'denied' || phase === 'rejected') ? (
              <div className="border-t border-c-border pt-3">
                <button
                  type="button"
                  onClick={loadAuditTrail}
                  disabled={auditLoading}
                  data-testid="teresa-load-audit"
                  className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-c-border bg-transparent px-3 text-[12px] font-medium text-c-text transition-colors hover:bg-c-surface-raised disabled:opacity-50"
                >
                  {auditLoading ? <Loader2 size={13} className="animate-spin" /> : <History size={13} />}
                  <span>{isPolish ? 'Zobacz ślad audytowy' : 'View audit trail'}</span>
                </button>
                {auditTrail ? (
                  <ul
                    data-testid="teresa-audit-trail"
                    className="mt-2 space-y-1 text-[11px] text-c-text-muted"
                  >
                    {auditTrail.map((entry) => (
                      <li key={entry.id} className="flex justify-between gap-2 border-b border-c-border/50 py-1">
                        <span className="font-mono">{entry.action}</span>
                        <span>{entry.actor}</span>
                        <span>{entry.from_state ?? '—'} → {entry.to_state}</span>
                        <span>{new Date(entry.timestamp).toLocaleString(isPolish ? 'pl-PL' : 'en-US')}</span>
                      </li>
                    ))}
                  </ul>
                ) : null}
              </div>
            ) : null}
          </>
        )}
      </div>
    </Modal>
  );
};

export default TeresaProposalPanel;
