import { v4 as uuidv4 } from 'uuid';

export type CanonicalStatementType = 'P&L' | 'BS' | 'CF';
export type CanonicalRequiredLevel = 'required' | 'optional' | 'computed';

export interface CanonicalLineDefinition {
  id: string;
  statementType: CanonicalStatementType;
  code: string;
  labelEn: string;
  labelPl: string;
  parentId?: string | null;
  sortOrder: number;
  aggregationLevel: number;
  requiredLevel: CanonicalRequiredLevel;
  signConvention: 'positive_normal' | 'negative_normal' | 'display_absolute';
  isTotal?: boolean;
  isSubtotal?: boolean;
  isComputed?: boolean;
  formulaJson?: Record<string, unknown> | null;
  deaggregationReady?: boolean;
}

type LineInput = Omit<CanonicalLineDefinition, 'statementType'>;

function makeLines(statementType: CanonicalStatementType, lines: LineInput[]): CanonicalLineDefinition[] {
  return lines.map((line) => ({ ...line, statementType }));
}

const PL_LINES = makeLines('P&L', [
  { id: 'fsl-pl-revenue', code: 'REVENUE', labelEn: 'Revenue', labelPl: 'Przychody', sortOrder: 10, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-pl-revenue-product', code: 'PRODUCT_REVENUE', labelEn: 'Product Revenue', labelPl: 'Przychody produktowe', parentId: 'fsl-pl-revenue', sortOrder: 11, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-pl-revenue-product-domestic', code: 'PRODUCT_REVENUE_DOMESTIC', labelEn: 'Domestic Product Revenue', labelPl: 'Przychody produktowe kraj', parentId: 'fsl-pl-revenue-product', sortOrder: 12, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-revenue-product-export', code: 'PRODUCT_REVENUE_EXPORT', labelEn: 'Export Product Revenue', labelPl: 'Przychody produktowe eksport', parentId: 'fsl-pl-revenue-product', sortOrder: 13, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-revenue-service', code: 'SERVICE_REVENUE', labelEn: 'Service Revenue', labelPl: 'Przychody usługowe', parentId: 'fsl-pl-revenue', sortOrder: 14, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-pl-revenue-service-subscription', code: 'SUBSCRIPTION_REVENUE', labelEn: 'Subscription Revenue', labelPl: 'Przychody abonamentowe', parentId: 'fsl-pl-revenue-service', sortOrder: 15, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-revenue-service-projects', code: 'PROJECT_REVENUE', labelEn: 'Project Revenue', labelPl: 'Przychody projektowe', parentId: 'fsl-pl-revenue-service', sortOrder: 16, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-revenue-other', code: 'OTHER_REVENUE', labelEn: 'Other Revenue', labelPl: 'Pozostałe przychody', parentId: 'fsl-pl-revenue', sortOrder: 17, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-cogs', code: 'COGS', labelEn: 'Cost of Goods Sold', labelPl: 'Koszt sprzedanych towarów', sortOrder: 20, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-pl-cogs-materials', code: 'MATERIALS_COGS', labelEn: 'Materials Cost', labelPl: 'Koszt materiałów', parentId: 'fsl-pl-cogs', sortOrder: 21, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-pl-cogs-materials-raw', code: 'RAW_MATERIALS_COGS', labelEn: 'Raw Materials Cost', labelPl: 'Koszt surowców', parentId: 'fsl-pl-cogs-materials', sortOrder: 22, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cogs-materials-freight', code: 'INBOUND_FREIGHT_COGS', labelEn: 'Inbound Freight', labelPl: 'Transport zakupu', parentId: 'fsl-pl-cogs-materials', sortOrder: 23, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cogs-labor', code: 'DIRECT_LABOR_COGS', labelEn: 'Direct Labor Cost', labelPl: 'Koszt robocizny bezpośredniej', parentId: 'fsl-pl-cogs', sortOrder: 24, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cogs-labor-payroll', code: 'PRODUCTION_PAYROLL_COGS', labelEn: 'Production Payroll', labelPl: 'Płace produkcyjne', parentId: 'fsl-pl-cogs-labor', sortOrder: 25, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cogs-labor-contractors', code: 'PRODUCTION_CONTRACTORS_COGS', labelEn: 'Production Contractors', labelPl: 'Usługi produkcyjne obce', parentId: 'fsl-pl-cogs-labor', sortOrder: 26, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cogs-other', code: 'OTHER_DIRECT_COSTS', labelEn: 'Other Direct Costs', labelPl: 'Pozostałe koszty bezpośrednie', parentId: 'fsl-pl-cogs', sortOrder: 27, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-gross', code: 'GROSS_PROFIT', labelEn: 'Gross Profit', labelPl: 'Marża brutto', sortOrder: 30, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isSubtotal: true, isComputed: true, formulaJson: { type: 'difference', inputs: ['REVENUE', 'COGS'] } },
  { id: 'fsl-pl-other-op-income', code: 'OTHER_OPERATING_INCOME', labelEn: 'Other Operating Income', labelPl: 'Pozostałe przychody operacyjne', sortOrder: 35, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-opex', code: 'OPEX', labelEn: 'Operating Expenses (SG&A)', labelPl: 'Koszty operacyjne (SG&A)', sortOrder: 50, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'display_absolute', isSubtotal: true, deaggregationReady: true },
  { id: 'fsl-pl-selling', code: 'SELLING_EXPENSES', labelEn: 'Selling Expenses', labelPl: 'Koszty sprzedaży', parentId: 'fsl-pl-opex', sortOrder: 40, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-pl-selling-marketing', code: 'MARKETING_EXPENSES', labelEn: 'Marketing Expenses', labelPl: 'Koszty marketingu', parentId: 'fsl-pl-selling', sortOrder: 41, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-selling-logistics', code: 'LOGISTICS_EXPENSES', labelEn: 'Logistics Expenses', labelPl: 'Koszty logistyki', parentId: 'fsl-pl-selling', sortOrder: 42, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-selling-commissions', code: 'SALES_COMMISSIONS', labelEn: 'Sales Commissions', labelPl: 'Prowizje sprzedażowe', parentId: 'fsl-pl-selling', sortOrder: 43, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-gna', code: 'GENERAL_ADMIN_EXPENSES', labelEn: 'General & Administrative Expenses', labelPl: 'Koszty ogólnego zarządu', parentId: 'fsl-pl-opex', sortOrder: 45, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-pl-gna-payroll', code: 'GNA_PAYROLL', labelEn: 'G&A Payroll', labelPl: 'Płace administracji', parentId: 'fsl-pl-gna', sortOrder: 46, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-gna-rent', code: 'GNA_RENT', labelEn: 'Office Rent', labelPl: 'Czynsz biur', parentId: 'fsl-pl-gna', sortOrder: 47, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-gna-it', code: 'GNA_IT', labelEn: 'IT & Software', labelPl: 'IT i oprogramowanie', parentId: 'fsl-pl-gna', sortOrder: 48, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-gna-external', code: 'GNA_EXTERNAL_SERVICES', labelEn: 'External Services', labelPl: 'Usługi obce', parentId: 'fsl-pl-gna', sortOrder: 49, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-other-opex', code: 'OTHER_OPERATING_EXPENSES', labelEn: 'Other Operating Expenses', labelPl: 'Pozostałe koszty operacyjne', parentId: 'fsl-pl-opex', sortOrder: 50, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-pl-other-opex-impairment', code: 'IMPAIRMENT_EXPENSE', labelEn: 'Impairment Expense', labelPl: 'Odpisy aktualizujące', parentId: 'fsl-pl-other-opex', sortOrder: 51, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-other-opex-provisions', code: 'PROVISIONS_EXPENSE', labelEn: 'Provisions Expense', labelPl: 'Koszt rezerw', parentId: 'fsl-pl-other-opex', sortOrder: 52, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-rnd', code: 'RND_EXPENSES', labelEn: 'Research & Development Expenses', labelPl: 'Koszty badań i rozwoju', parentId: 'fsl-pl-opex', sortOrder: 55, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-sga', code: 'SGA_EXPENSES', labelEn: 'Selling, General & Administrative', labelPl: 'Koszty sprzedaży i ogólnego zarządu', parentId: 'fsl-pl-opex', sortOrder: 56, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-ebitda', code: 'EBITDA', labelEn: 'EBITDA', labelPl: 'EBITDA', sortOrder: 60, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal', isSubtotal: true, isComputed: true, formulaJson: { type: 'sum', inputs: ['EBIT', 'DEPRECIATION'] } },
  { id: 'fsl-pl-depreciation', code: 'DEPRECIATION', labelEn: 'Depreciation & Amortization', labelPl: 'Amortyzacja', sortOrder: 70, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-pl-depreciation-ppe', code: 'PPE_DEPRECIATION', labelEn: 'PPE Depreciation', labelPl: 'Amortyzacja środków trwałych', parentId: 'fsl-pl-depreciation', sortOrder: 71, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-depreciation-intangibles', code: 'INTANGIBLE_AMORTIZATION', labelEn: 'Intangible Amortization', labelPl: 'Amortyzacja WNiP', parentId: 'fsl-pl-depreciation', sortOrder: 72, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-ebit', code: 'EBIT', labelEn: 'EBIT / Operating Profit', labelPl: 'EBIT / Zysk operacyjny', sortOrder: 80, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isSubtotal: true, isComputed: true },
  { id: 'fsl-pl-interest', code: 'INTEREST_EXPENSE', labelEn: 'Interest Expense', labelPl: 'Koszty odsetkowe', sortOrder: 90, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-pl-interest-bank', code: 'BANK_INTEREST_EXPENSE', labelEn: 'Bank Interest Expense', labelPl: 'Odsetki bankowe', parentId: 'fsl-pl-interest', sortOrder: 91, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-interest-lease', code: 'LEASE_INTEREST_EXPENSE', labelEn: 'Lease Interest Expense', labelPl: 'Odsetki leasingowe', parentId: 'fsl-pl-interest', sortOrder: 92, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-other-fin', code: 'OTHER_FINANCIAL_RESULT', labelEn: 'Other Financial Result', labelPl: 'Pozostałe przychody/koszty finansowe', sortOrder: 95, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-ebt', code: 'EBT', labelEn: 'Earnings Before Tax', labelPl: 'Zysk przed opodatkowaniem', sortOrder: 100, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal', isSubtotal: true, isComputed: true },
  { id: 'fsl-pl-tax', code: 'TAX_EXPENSE', labelEn: 'Income Tax Expense', labelPl: 'Podatek dochodowy', sortOrder: 110, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-pl-tax-current', code: 'CURRENT_TAX_EXPENSE', labelEn: 'Current Tax Expense', labelPl: 'Podatek bieżący', parentId: 'fsl-pl-tax', sortOrder: 111, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-tax-deferred', code: 'DEFERRED_TAX_EXPENSE', labelEn: 'Deferred Tax Expense', labelPl: 'Podatek odroczony', parentId: 'fsl-pl-tax', sortOrder: 112, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-net', code: 'NET_INCOME', labelEn: 'Net Income', labelPl: 'Zysk netto', sortOrder: 120, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isTotal: true, isComputed: true },
  { id: 'fsl-pl-net-parent', code: 'NET_INCOME_PARENT', labelEn: 'Net Income Attributable to Parent', labelPl: 'Zysk netto przypadający akcjonariuszom jednostki dominującej', sortOrder: 121, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-net-minority', code: 'NET_INCOME_MINORITY', labelEn: 'Net Income Attributable to Non-controlling Interests', labelPl: 'Zysk netto przypadający udziałom niesprawującym kontroli', sortOrder: 122, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-net-continuing', code: 'NET_INCOME_CONTINUING', labelEn: 'Net Income from Continuing Operations', labelPl: 'Zysk netto z działalności kontynuowanej', sortOrder: 123, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-other-op-result', code: 'OTHER_OPERATING_RESULT', labelEn: 'Other Operating Result', labelPl: 'Wynik na pozostałej działalności operacyjnej', sortOrder: 36, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-other-income', code: 'OTHER_INCOME', labelEn: 'Other Income', labelPl: 'Pozostałe przychody', sortOrder: 37, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-other-expense', code: 'OTHER_EXPENSE', labelEn: 'Other Expenses', labelPl: 'Pozostałe koszty', sortOrder: 38, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-equity-method-income', code: 'EQUITY_METHOD_INCOME', labelEn: 'Share of Profit of Associates', labelPl: 'Udział w zyskach jednostek stowarzyszonych', sortOrder: 96, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-fin-income', code: 'FINANCIAL_INCOME', labelEn: 'Financial Income', labelPl: 'Przychody finansowe', sortOrder: 93, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-fin-expense', code: 'FINANCIAL_EXPENSE', labelEn: 'Financial Expenses', labelPl: 'Koszty finansowe', sortOrder: 94, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-impairment-receivables', code: 'IMPAIRMENT_RECEIVABLES', labelEn: 'Impairment of Receivables', labelPl: 'Zmiana odpisów na należności', sortOrder: 53, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-oci-total', code: 'OCI_TOTAL', labelEn: 'Other Comprehensive Income', labelPl: 'Inne całkowite dochody ogółem', sortOrder: 130, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-oci-reclassifiable', code: 'OCI_RECLASSIFIABLE', labelEn: 'Items that May Be Reclassified', labelPl: 'Pozycje przeklasyfikowywalne do wyniku', sortOrder: 131, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-oci-non-reclassifiable', code: 'OCI_NON_RECLASSIFIABLE', labelEn: 'Items that Will Not Be Reclassified', labelPl: 'Pozycje nieprzeklasyfikowywalne', sortOrder: 132, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-oci-fx', code: 'OCI_FX', labelEn: 'FX Translation Differences', labelPl: 'Różnice kursowe z przeliczenia', sortOrder: 133, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-oci-hedge', code: 'OCI_HEDGE', labelEn: 'Hedging Result', labelPl: 'Wynik na zabezpieczeniach', sortOrder: 134, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-oci-actuarial', code: 'OCI_ACTUARIAL', labelEn: 'Actuarial Gains/Losses', labelPl: 'Zyski i straty aktuarialne', sortOrder: 135, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-comprehensive-income', code: 'COMPREHENSIVE_INCOME', labelEn: 'Total Comprehensive Income', labelPl: 'Całkowite dochody ogółem', sortOrder: 140, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-eps-basic', code: 'EPS_BASIC', labelEn: 'Basic Earnings Per Share', labelPl: 'Zysk na akcję podstawowy', sortOrder: 150, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-eps-diluted', code: 'EPS_DILUTED', labelEn: 'Diluted Earnings Per Share', labelPl: 'Zysk na akcję rozwodniony', sortOrder: 151, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-shares-outstanding', code: 'SHARES_OUTSTANDING', labelEn: 'Weighted Average Shares Outstanding', labelPl: 'Średnia ważona liczba akcji', sortOrder: 152, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  // Cost-by-nature P&L variant (HGB Gesamtkostenverfahren / Polish UoR wariant porównawczy)
  { id: 'fsl-pl-cbn-inventory-change', code: 'INVENTORY_CHANGE', labelEn: 'Change in Inventories of Finished Goods and WIP', labelPl: 'Zmiana stanu produktów', sortOrder: 160, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-cbn-own-work-capitalised', code: 'OWN_WORK_CAPITALISED', labelEn: 'Own Work Capitalised', labelPl: 'Koszt wytworzenia produktów na własne potrzeby jednostki', sortOrder: 161, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-cbn-materials-energy', code: 'MATERIALS_AND_ENERGY', labelEn: 'Materials and Energy', labelPl: 'Zużycie materiałów i energii', sortOrder: 162, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cbn-external-services', code: 'EXTERNAL_SERVICES', labelEn: 'External Services', labelPl: 'Usługi obce', sortOrder: 163, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cbn-taxes-fees', code: 'TAXES_AND_FEES', labelEn: 'Taxes and Fees', labelPl: 'Podatki i opłaty', sortOrder: 164, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cbn-payroll', code: 'PAYROLL_COST', labelEn: 'Payroll / Wages and Salaries', labelPl: 'Wynagrodzenia', sortOrder: 165, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cbn-social-security', code: 'SOCIAL_SECURITY', labelEn: 'Social Security and Other Benefits', labelPl: 'Ubezpieczenia społeczne i inne świadczenia', sortOrder: 166, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cbn-other-by-nature', code: 'OTHER_COSTS_BY_NATURE', labelEn: 'Other Operating Costs by Nature', labelPl: 'Pozostałe koszty rodzajowe', sortOrder: 167, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-cbn-total-by-nature', code: 'TOTAL_COSTS_BY_NATURE', labelEn: 'Total Operating Costs by Nature', labelPl: 'Koszty działalności operacyjnej razem', sortOrder: 168, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'display_absolute', isSubtotal: true },
  { id: 'fsl-pl-cbn-operating-result', code: 'OPERATING_RESULT_CBN', labelEn: 'Operating Result (Cost by Nature)', labelPl: 'Wynik na działalności operacyjnej', sortOrder: 169, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-comprehensive-income-parent', code: 'COMPREHENSIVE_INCOME_PARENT', labelEn: 'Comprehensive Income Attributable to Parent', labelPl: 'Całkowite dochody przypadające akcjonariuszom jednostki dominującej', sortOrder: 141, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-total-revenue-and-income', code: 'TOTAL_REVENUE_AND_INCOME', labelEn: 'Total Revenues and Other Income', labelPl: 'Przychody i inne dochody razem', sortOrder: 19, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal', isSubtotal: true },
  { id: 'fsl-pl-production-costs', code: 'PRODUCTION_COSTS', labelEn: 'Production and Manufacturing Expenses', labelPl: 'Koszty produkcji i wytworzenia', sortOrder: 22, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-gains-disposals', code: 'GAINS_ON_DISPOSALS', labelEn: 'Gains on Sale of Businesses and Fixed Assets', labelPl: 'Zyski ze sprzedaży przedsiębiorstw i aktywów trwałych', sortOrder: 39, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-revenue-segment', code: 'SEGMENT_REVENUE', labelEn: 'Segment Revenue', labelPl: 'Przychody segmentu', parentId: 'fsl-pl-revenue', sortOrder: 18, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-cogs-segment', code: 'SEGMENT_COGS', labelEn: 'Segment Cost of Revenue', labelPl: 'Koszty segmentu', parentId: 'fsl-pl-cogs', sortOrder: 28, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-pl-oci-derivatives', code: 'OCI_DERIVATIVES', labelEn: 'Derivative Financial Instruments (OCI)', labelPl: 'Instrumenty pochodne (OCI)', sortOrder: 136, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-oci-pension-remeasurement', code: 'OCI_PENSION_REMEASUREMENT', labelEn: 'Remeasurement of Pension Plans', labelPl: 'Przeszacowanie programów emerytalnych', sortOrder: 137, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-pl-financial-result-net', code: 'NET_FINANCIAL_RESULT', labelEn: 'Net Financial Result', labelPl: 'Wynik finansowy netto', sortOrder: 97, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal', isSubtotal: true },
  { id: 'fsl-pl-nopat', code: 'NOPAT', labelEn: 'Net Operating Profit After Tax', labelPl: 'Zysk operacyjny netto po opodatkowaniu', sortOrder: 85, aggregationLevel: 1, requiredLevel: 'computed', signConvention: 'positive_normal', isComputed: true, formulaJson: { type: 'custom', fn: 'EBIT * (1 - TAX_EXPENSE / EBT)', inputs: ['EBIT', 'TAX_EXPENSE', 'EBT'] } },
  { id: 'fsl-pl-ebt-margin', code: 'EBT_MARGIN', labelEn: 'EBT Margin', labelPl: 'Marża zysku brutto', sortOrder: 101, aggregationLevel: 1, requiredLevel: 'computed', signConvention: 'positive_normal', isComputed: true },
  { id: 'fsl-pl-effective-tax-rate', code: 'EFFECTIVE_TAX_RATE', labelEn: 'Effective Tax Rate', labelPl: 'Efektywna stopa podatkowa', sortOrder: 115, aggregationLevel: 1, requiredLevel: 'computed', signConvention: 'positive_normal', isComputed: true, formulaJson: { type: 'ratio', inputs: ['TAX_EXPENSE', 'EBT'] } },
]);

const BS_LINES = makeLines('BS', [
  { id: 'fsl-bs-current-assets', code: 'CURRENT_ASSETS', labelEn: 'Current Assets', labelPl: 'Aktywa obrotowe', sortOrder: 10, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isSubtotal: true, isComputed: true },
  { id: 'fsl-bs-cash', code: 'CASH', labelEn: 'Cash & Cash Equivalents', labelPl: 'Środki pieniężne', parentId: 'fsl-bs-current-assets', sortOrder: 11, aggregationLevel: 2, requiredLevel: 'required', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-bs-cash-operating', code: 'OPERATING_CASH', labelEn: 'Operating Cash', labelPl: 'Gotówka operacyjna', parentId: 'fsl-bs-cash', sortOrder: 12, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-cash-restricted', code: 'RESTRICTED_CASH', labelEn: 'Restricted Cash', labelPl: 'Środki zablokowane', parentId: 'fsl-bs-cash', sortOrder: 13, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-ar', code: 'AR', labelEn: 'Accounts Receivable', labelPl: 'Należności', parentId: 'fsl-bs-current-assets', sortOrder: 20, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-bs-ar-trade', code: 'TRADE_RECEIVABLES', labelEn: 'Trade Receivables', labelPl: 'Należności handlowe', parentId: 'fsl-bs-ar', sortOrder: 21, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-ar-other', code: 'OTHER_RECEIVABLES', labelEn: 'Other Receivables', labelPl: 'Pozostałe należności', parentId: 'fsl-bs-ar', sortOrder: 22, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-inventory', code: 'INVENTORY', labelEn: 'Inventory', labelPl: 'Zapasy', parentId: 'fsl-bs-current-assets', sortOrder: 30, aggregationLevel: 2, requiredLevel: 'required', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-bs-inventory-raw', code: 'RAW_MATERIALS_INVENTORY', labelEn: 'Raw Materials Inventory', labelPl: 'Materiały', parentId: 'fsl-bs-inventory', sortOrder: 31, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-inventory-wip', code: 'WORK_IN_PROGRESS_INVENTORY', labelEn: 'Work in Progress', labelPl: 'Produkcja w toku', parentId: 'fsl-bs-inventory', sortOrder: 32, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-inventory-fg', code: 'FINISHED_GOODS_INVENTORY', labelEn: 'Finished Goods', labelPl: 'Wyroby gotowe', parentId: 'fsl-bs-inventory', sortOrder: 33, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-other-current-assets', code: 'OTHER_CURRENT_ASSETS', labelEn: 'Other Current Assets', labelPl: 'Pozostałe aktywa obrotowe', parentId: 'fsl-bs-current-assets', sortOrder: 35, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-bs-other-current-assets-vat', code: 'VAT_RECEIVABLES', labelEn: 'VAT Receivables', labelPl: 'Należności VAT', parentId: 'fsl-bs-other-current-assets', sortOrder: 36, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-other-current-assets-prepaids', code: 'PREPAID_EXPENSES', labelEn: 'Short-term Prepaid Expenses', labelPl: 'Krótkoterminowe rozliczenia międzyokresowe', parentId: 'fsl-bs-other-current-assets', sortOrder: 37, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-lt-prepaids', code: 'LT_PREPAID_EXPENSES', labelEn: 'Long-term Prepaid Expenses', labelPl: 'Długoterminowe rozliczenia międzyokresowe', parentId: 'fsl-bs-fixed', sortOrder: 38, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-other-st-receivables', code: 'OTHER_ST_RECEIVABLES', labelEn: 'Other Short-term Receivables', labelPl: 'Pozostałe należności krótkoterminowe', parentId: 'fsl-bs-current-assets', sortOrder: 39, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-tax-receivables', code: 'TAX_RECEIVABLES', labelEn: 'Tax Receivables', labelPl: 'Należności podatkowe', parentId: 'fsl-bs-current-assets', sortOrder: 38, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-contract-assets', code: 'CONTRACT_ASSETS', labelEn: 'Contract Assets', labelPl: 'Aktywa kontraktowe', parentId: 'fsl-bs-current-assets', sortOrder: 39, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-st-investments', code: 'SHORT_TERM_INVESTMENTS', labelEn: 'Short-term Investments', labelPl: 'Inwestycje krótkoterminowe', parentId: 'fsl-bs-current-assets', sortOrder: 40, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-assets-held-for-sale', code: 'ASSETS_HELD_FOR_SALE', labelEn: 'Assets Held for Sale', labelPl: 'Aktywa przeznaczone do sprzedaży', sortOrder: 55, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-fixed', code: 'FIXED_ASSETS', labelEn: 'Fixed Assets', labelPl: 'Aktywa trwałe', sortOrder: 60, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isSubtotal: true, isComputed: true, deaggregationReady: true },
  { id: 'fsl-bs-ppe', code: 'PROPERTY_PLANT_EQUIPMENT', labelEn: 'Property, Plant & Equipment', labelPl: 'Rzeczowe aktywa trwałe', parentId: 'fsl-bs-fixed', sortOrder: 61, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-bs-ppe-land', code: 'PPE_LAND_BUILDINGS', labelEn: 'Land & Buildings', labelPl: 'Grunty i budynki', parentId: 'fsl-bs-ppe', sortOrder: 62, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-ppe-machinery', code: 'PPE_MACHINERY', labelEn: 'Machinery & Equipment', labelPl: 'Maszyny i urządzenia', parentId: 'fsl-bs-ppe', sortOrder: 63, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-ppe-vehicles', code: 'PPE_VEHICLES', labelEn: 'Vehicles', labelPl: 'Środki transportu', parentId: 'fsl-bs-ppe', sortOrder: 64, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-intangibles', code: 'INTANGIBLE_ASSETS', labelEn: 'Intangible Assets', labelPl: 'Wartości niematerialne', parentId: 'fsl-bs-fixed', sortOrder: 65, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-bs-intangibles-software', code: 'SOFTWARE_ASSETS', labelEn: 'Software Assets', labelPl: 'Oprogramowanie', parentId: 'fsl-bs-intangibles', sortOrder: 66, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-intangibles-goodwill', code: 'GOODWILL', labelEn: 'Goodwill', labelPl: 'Wartość firmy', parentId: 'fsl-bs-intangibles', sortOrder: 67, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-investment-property', code: 'INVESTMENT_PROPERTY', labelEn: 'Investment Property', labelPl: 'Nieruchomości inwestycyjne', parentId: 'fsl-bs-fixed', sortOrder: 68, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-rou-assets', code: 'RIGHT_OF_USE_ASSETS', labelEn: 'Right-of-Use Assets', labelPl: 'Aktywa z tytułu prawa do użytkowania', parentId: 'fsl-bs-fixed', sortOrder: 69, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-lt-receivables', code: 'LT_RECEIVABLES', labelEn: 'Long-term Receivables', labelPl: 'Należności długoterminowe', parentId: 'fsl-bs-fixed', sortOrder: 67, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-lt-financial-assets', code: 'LT_FINANCIAL_ASSETS', labelEn: 'Long-term Financial Assets', labelPl: 'Długoterminowe aktywa finansowe', parentId: 'fsl-bs-fixed', sortOrder: 67, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-equity-method-investments', code: 'EQUITY_METHOD_INVESTMENTS', labelEn: 'Equity Method Investments', labelPl: 'Inwestycje metodą praw własności', parentId: 'fsl-bs-fixed', sortOrder: 67, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-other-non-current-assets', code: 'OTHER_NON_CURRENT_ASSETS', labelEn: 'Other Non-current Assets', labelPl: 'Pozostałe aktywa trwałe', parentId: 'fsl-bs-fixed', sortOrder: 68, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-bs-other-non-current-assets-deferred-tax', code: 'DEFERRED_TAX_ASSETS', labelEn: 'Deferred Tax Assets', labelPl: 'Aktywa z tytułu podatku odroczonego', parentId: 'fsl-bs-other-non-current-assets', sortOrder: 69, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-total-assets', code: 'TOTAL_ASSETS', labelEn: 'Total Assets', labelPl: 'Aktywa ogółem', sortOrder: 70, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isTotal: true, isComputed: true },
  { id: 'fsl-bs-current-liabilities', code: 'CURRENT_LIABILITIES', labelEn: 'Current Liabilities', labelPl: 'Zobowiązania krótkoterminowe', sortOrder: 90, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'display_absolute', isSubtotal: true, isComputed: true },
  { id: 'fsl-bs-ap', code: 'AP', labelEn: 'Accounts Payable', labelPl: 'Zobowiązania handlowe', parentId: 'fsl-bs-current-liabilities', sortOrder: 91, aggregationLevel: 2, requiredLevel: 'required', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-bs-ap-trade', code: 'TRADE_PAYABLES', labelEn: 'Trade Payables', labelPl: 'Zobowiązania handlowe krajowe', parentId: 'fsl-bs-ap', sortOrder: 92, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-short-term-debt', code: 'SHORT_TERM_DEBT', labelEn: 'Short-term Debt', labelPl: 'Zobowiązania krótkoterminowe finansowe', parentId: 'fsl-bs-current-liabilities', sortOrder: 93, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-bs-short-term-debt-bank', code: 'SHORT_TERM_BANK_DEBT', labelEn: 'Short-term Bank Debt', labelPl: 'Krótkoterminowy dług bankowy', parentId: 'fsl-bs-short-term-debt', sortOrder: 94, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-short-term-debt-lease', code: 'CURRENT_LEASE_LIABILITIES', labelEn: 'Current Lease Liabilities', labelPl: 'Krótkoterminowe zobowiązania leasingowe', parentId: 'fsl-bs-short-term-debt', sortOrder: 95, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-other-current-liabilities', code: 'OTHER_CURRENT_LIABILITIES', labelEn: 'Other Current Liabilities', labelPl: 'Pozostałe zobowiązania krótkoterminowe', parentId: 'fsl-bs-current-liabilities', sortOrder: 96, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-bs-other-current-liabilities-tax', code: 'TAX_PAYABLES', labelEn: 'Tax Payables', labelPl: 'Zobowiązania podatkowe', parentId: 'fsl-bs-other-current-liabilities', sortOrder: 97, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-other-current-liabilities-accruals', code: 'ACCRUED_EXPENSES', labelEn: 'Accrued Expenses', labelPl: 'Rozliczenia międzyokresowe bierne', parentId: 'fsl-bs-other-current-liabilities', sortOrder: 98, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-total-liabilities', code: 'TOTAL_LIABILITIES', labelEn: 'Total Liabilities', labelPl: 'Zobowiązania ogółem', sortOrder: 110, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'display_absolute', isSubtotal: true, isComputed: true, deaggregationReady: true },
  { id: 'fsl-bs-long-term-debt', code: 'LONG_TERM_DEBT', labelEn: 'Long-term Debt', labelPl: 'Zobowiązania długoterminowe finansowe', parentId: 'fsl-bs-total-liabilities', sortOrder: 111, aggregationLevel: 2, requiredLevel: 'required', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-bs-long-term-debt-bank', code: 'LONG_TERM_BANK_DEBT', labelEn: 'Long-term Bank Debt', labelPl: 'Dług bankowy długoterminowy', parentId: 'fsl-bs-long-term-debt', sortOrder: 112, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-long-term-debt-lease', code: 'NON_CURRENT_LEASE_LIABILITIES', labelEn: 'Non-current Lease Liabilities', labelPl: 'Długoterminowe zobowiązania leasingowe', parentId: 'fsl-bs-long-term-debt', sortOrder: 113, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-other-non-current-liabilities', code: 'OTHER_NON_CURRENT_LIABILITIES', labelEn: 'Other Non-current Liabilities', labelPl: 'Pozostałe zobowiązania długoterminowe', parentId: 'fsl-bs-total-liabilities', sortOrder: 114, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-bs-other-non-current-liabilities-provisions', code: 'LONG_TERM_PROVISIONS', labelEn: 'Long-term Provisions', labelPl: 'Rezerwy długoterminowe', parentId: 'fsl-bs-other-non-current-liabilities', sortOrder: 115, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-other-non-current-liabilities-deferred-tax', code: 'DEFERRED_TAX_LIABILITIES', labelEn: 'Deferred Tax Liabilities', labelPl: 'Rezerwa z tytułu podatku odroczonego', parentId: 'fsl-bs-other-non-current-liabilities', sortOrder: 116, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-employee-benefits-lt', code: 'LT_EMPLOYEE_BENEFITS', labelEn: 'Long-term Employee Benefits', labelPl: 'Zobowiązania z tytułu świadczeń pracowniczych długoterminowe', parentId: 'fsl-bs-other-non-current-liabilities', sortOrder: 117, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-deferred-revenue-non-current', code: 'DEFERRED_REVENUE_NON_CURRENT', labelEn: 'Non-current Deferred Revenue', labelPl: 'Przychody przyszłych okresów długoterminowe', parentId: 'fsl-bs-other-non-current-liabilities', sortOrder: 118, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-pension-surplus', code: 'PENSION_SURPLUS', labelEn: 'Defined Benefit Pension Plan Surplus', labelPl: 'Nadwyżka programu określonych świadczeń', parentId: 'fsl-bs-fixed', sortOrder: 69, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-pension-deficit', code: 'PENSION_DEFICIT', labelEn: 'Pension Plan Deficit', labelPl: 'Niedobór programu określonych świadczeń', parentId: 'fsl-bs-other-non-current-liabilities', sortOrder: 119, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-provisions', code: 'PROVISIONS', labelEn: 'Provisions', labelPl: 'Rezerwy', parentId: 'fsl-bs-current-liabilities', sortOrder: 99, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-deferred-revenue-current', code: 'DEFERRED_REVENUE_CURRENT', labelEn: 'Current Deferred Revenue', labelPl: 'Przychody przyszłych okresów krótkoterminowe', parentId: 'fsl-bs-current-liabilities', sortOrder: 99, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-contract-liabilities', code: 'CONTRACT_LIABILITIES', labelEn: 'Contract Liabilities', labelPl: 'Zobowiązania kontraktowe', parentId: 'fsl-bs-current-liabilities', sortOrder: 99, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-employee-benefits-st', code: 'ST_EMPLOYEE_BENEFITS', labelEn: 'Short-term Employee Benefits', labelPl: 'Zobowiązania z tytułu świadczeń pracowniczych krótkoterminowe', parentId: 'fsl-bs-current-liabilities', sortOrder: 99, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-equity', code: 'TOTAL_EQUITY', labelEn: 'Total Equity', labelPl: 'Kapitał własny', sortOrder: 130, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isSubtotal: true, isComputed: true, deaggregationReady: true },
  { id: 'fsl-bs-share-capital', code: 'SHARE_CAPITAL', labelEn: 'Share Capital', labelPl: 'Kapitał podstawowy', parentId: 'fsl-bs-equity', sortOrder: 131, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-share-premium', code: 'SHARE_PREMIUM', labelEn: 'Share Premium', labelPl: 'Kapitał zapasowy', parentId: 'fsl-bs-equity', sortOrder: 132, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-retained-earnings', code: 'RETAINED_EARNINGS', labelEn: 'Retained Earnings', labelPl: 'Zyski zatrzymane', parentId: 'fsl-bs-equity', sortOrder: 133, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-retained-earnings-prior', code: 'RETAINED_EARNINGS_PRIOR', labelEn: 'Retained Earnings - Prior Years', labelPl: 'Wynik lat ubiegłych', parentId: 'fsl-bs-retained-earnings', sortOrder: 134, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-retained-earnings-current', code: 'RETAINED_EARNINGS_CURRENT', labelEn: 'Current Year Result', labelPl: 'Wynik bieżącego roku', parentId: 'fsl-bs-retained-earnings', sortOrder: 135, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-treasury-shares', code: 'TREASURY_SHARES', labelEn: 'Treasury Shares', labelPl: 'Akcje własne', parentId: 'fsl-bs-equity', sortOrder: 136, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-other-equity-reserves', code: 'OTHER_EQUITY_RESERVES', labelEn: 'Other Equity Reserves', labelPl: 'Pozostałe kapitały rezerwowe', parentId: 'fsl-bs-equity', sortOrder: 137, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-hedge-reserve', code: 'HEDGE_RESERVE', labelEn: 'Hedging Reserve', labelPl: 'Kapitał z wyceny zabezpieczeń', parentId: 'fsl-bs-equity', sortOrder: 138, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-fx-reserve', code: 'FX_TRANSLATION_RESERVE', labelEn: 'FX Translation Reserve', labelPl: 'Różnice kursowe z konsolidacji', parentId: 'fsl-bs-equity', sortOrder: 138, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-minority-interest', code: 'MINORITY_INTEREST', labelEn: 'Non-controlling Interests', labelPl: 'Udziały niesprawujące kontroli', parentId: 'fsl-bs-equity', sortOrder: 139, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-equity-parent', code: 'EQUITY_PARENT', labelEn: 'Equity Attributable to Parent', labelPl: 'Kapitał własny przypadający akcjonariuszom jednostki dominującej', parentId: 'fsl-bs-equity', sortOrder: 138, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-other-tax-payables', code: 'OTHER_TAX_PAYABLES', labelEn: 'Other Tax Payables', labelPl: 'Zobowiązania z tytułu innych podatków', parentId: 'fsl-bs-current-liabilities', sortOrder: 126, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-other-tax-receivables', code: 'OTHER_TAX_RECEIVABLES', labelEn: 'Other Tax Receivables', labelPl: 'Należności z tytułu innych podatków', parentId: 'fsl-bs-current-assets', sortOrder: 77, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-other-current-financial-assets', code: 'OTHER_CURRENT_FINANCIAL_ASSETS', labelEn: 'Other Current Financial Assets', labelPl: 'Pozostałe krótkoterminowe aktywa finansowe', parentId: 'fsl-bs-current-assets', sortOrder: 78, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-long-term-borrowings', code: 'LONG_TERM_BORROWINGS', labelEn: 'Long-term Borrowings', labelPl: 'Długoterminowe kredyty i pożyczki', parentId: 'fsl-bs-long-term-debt', sortOrder: 113, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-actuarial-reserve', code: 'ACTUARIAL_RESERVE', labelEn: 'Actuarial Remeasurement Reserve', labelPl: 'Kapitał z przeszacowania programu określonych świadczeń', parentId: 'fsl-bs-equity', sortOrder: 137, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-total-liabilities-equity', code: 'TOTAL_LIABILITIES_EQUITY', labelEn: 'Total Liabilities and Equity', labelPl: 'Pasywa ogółem', sortOrder: 140, aggregationLevel: 1, requiredLevel: 'computed', signConvention: 'positive_normal', isTotal: true, isComputed: true, formulaJson: { type: 'sum', inputs: ['TOTAL_LIABILITIES', 'TOTAL_EQUITY'] } },
  { id: 'fsl-bs-wc', code: 'WORKING_CAPITAL', labelEn: 'Working Capital', labelPl: 'Kapitał obrotowy', sortOrder: 150, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal', isComputed: true, formulaJson: { type: 'difference', inputs: ['CURRENT_ASSETS', 'CURRENT_LIABILITIES'] } },
  { id: 'fsl-bs-investments-associates', code: 'INVESTMENTS_ASSOCIATES', labelEn: 'Investments in Associates', labelPl: 'Inwestycje w jednostki stowarzyszone', parentId: 'fsl-bs-fixed', sortOrder: 67, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-current-tax-receivable', code: 'CURRENT_TAX_RECEIVABLE', labelEn: 'Current Tax Receivable', labelPl: 'Należności z tytułu podatku dochodowego', parentId: 'fsl-bs-current-assets', sortOrder: 38, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-current-portion-ltd', code: 'CURRENT_PORTION_LTD', labelEn: 'Current Maturities of Long-term Debt', labelPl: 'Bieżąca część zobowiązań długoterminowych', parentId: 'fsl-bs-current-liabilities', sortOrder: 93, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-marketable-securities', code: 'MARKETABLE_SECURITIES', labelEn: 'Marketable Securities', labelPl: 'Zbywalne papiery wartościowe', parentId: 'fsl-bs-current-assets', sortOrder: 40, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-derivative-instruments', code: 'DERIVATIVE_INSTRUMENTS', labelEn: 'Derivative Financial Instruments', labelPl: 'Instrumenty pochodne', parentId: 'fsl-bs-fixed', sortOrder: 68, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-bs-liabilities-held-for-sale', code: 'LIABILITIES_HELD_FOR_SALE', labelEn: 'Liabilities Associated with Assets Held for Sale', labelPl: 'Zobowiązania związane z aktywami przeznaczonymi do sprzedaży', parentId: 'fsl-bs-current-liabilities', sortOrder: 100, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-other-provisions', code: 'OTHER_PROVISIONS', labelEn: 'Other Provisions', labelPl: 'Pozostałe rezerwy', parentId: 'fsl-bs-current-liabilities', sortOrder: 99, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-bs-total-debt', code: 'TOTAL_DEBT', labelEn: 'Total Interest-Bearing Debt', labelPl: 'Całkowity dług oprocentowany', sortOrder: 155, aggregationLevel: 1, requiredLevel: 'computed', signConvention: 'display_absolute', isComputed: true, formulaJson: { type: 'sum', inputs: ['LONG_TERM_DEBT', 'SHORT_TERM_DEBT'] } },
  { id: 'fsl-bs-net-debt', code: 'NET_DEBT', labelEn: 'Net Debt', labelPl: 'Dług netto', sortOrder: 156, aggregationLevel: 1, requiredLevel: 'computed', signConvention: 'positive_normal', isComputed: true, formulaJson: { type: 'custom', fn: 'TOTAL_DEBT - CASH', inputs: ['TOTAL_DEBT', 'CASH'] } },
  { id: 'fsl-bs-invested-capital', code: 'INVESTED_CAPITAL', labelEn: 'Invested Capital', labelPl: 'Kapitał zainwestowany', sortOrder: 157, aggregationLevel: 1, requiredLevel: 'computed', signConvention: 'positive_normal', isComputed: true, formulaJson: { type: 'sum', inputs: ['TOTAL_EQUITY', 'NET_DEBT'] } },
  { id: 'fsl-bs-capital-employed', code: 'CAPITAL_EMPLOYED', labelEn: 'Capital Employed', labelPl: 'Kapitał zaangażowany', sortOrder: 158, aggregationLevel: 1, requiredLevel: 'computed', signConvention: 'positive_normal', isComputed: true, formulaJson: { type: 'difference', inputs: ['TOTAL_ASSETS', 'CURRENT_LIABILITIES'] } },
]);

const CF_LINES = makeLines('CF', [
  { id: 'fsl-cf-operating', code: 'OPERATING_CF', labelEn: 'Operating Cash Flow', labelPl: 'Przepływy operacyjne', sortOrder: 10, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isSubtotal: true, deaggregationReady: true },
  { id: 'fsl-cf-operating-net-income', code: 'NET_INCOME_CF', labelEn: 'Net Income in Operating Cash Flow', labelPl: 'Wynik netto w CFO', parentId: 'fsl-cf-operating', sortOrder: 11, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-depreciation', code: 'DEPRECIATION_ADDBACK', labelEn: 'Depreciation Add-back', labelPl: 'Korekta o amortyzację', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-depreciation-intangibles', code: 'DEPRECIATION_INTANGIBLES_CF', labelEn: 'Amortization of Intangible Assets (CF)', labelPl: 'Amortyzacja wartości niematerialnych', parentId: 'fsl-cf-operating-depreciation', sortOrder: 12, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-depreciation-ppe', code: 'DEPRECIATION_PPE_CF', labelEn: 'Depreciation of PPE (CF)', labelPl: 'Amortyzacja rzeczowych aktywów trwałych', parentId: 'fsl-cf-operating-depreciation', sortOrder: 12, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-depreciation-rou', code: 'DEPRECIATION_ROU_CF', labelEn: 'Depreciation of Right-of-Use Assets (CF)', labelPl: 'Amortyzacja aktywów z tytułu prawa do użytkowania', parentId: 'fsl-cf-operating-depreciation', sortOrder: 12, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-ebt', code: 'EBT_CF', labelEn: 'Profit Before Tax (CF Opening)', labelPl: 'Zysk przed opodatkowaniem', parentId: 'fsl-cf-operating', sortOrder: 10, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-adjustments', code: 'ADJUSTMENTS_CF', labelEn: 'Total Adjustments', labelPl: 'Korekty razem', parentId: 'fsl-cf-operating', sortOrder: 11, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-impairment', code: 'IMPAIRMENT_CF', labelEn: 'Impairment Charges (CF)', labelPl: 'Odpisy aktualizujące', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-gain-disposal', code: 'GAIN_DISPOSAL_CF', labelEn: 'Gain/Loss on Disposal of Assets (CF)', labelPl: 'Zyski/straty na sprzedaży aktywów', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-fv-changes', code: 'FV_CHANGES_CF', labelEn: 'Fair Value Changes (CF)', labelPl: 'Zmiany wartości godziwej', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-dividend-income', code: 'DIVIDEND_INCOME_CF', labelEn: 'Dividend Income (CF)', labelPl: 'Przychody z dywidend', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-other-adj', code: 'OTHER_ADJUSTMENTS_CF', labelEn: 'Other Adjustments (CF)', labelPl: 'Inne korekty', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-equity-method', code: 'EQUITY_METHOD_CF', labelEn: 'Share of Profit of Associates (CF)', labelPl: 'Udział w zyskach jednostek stowarzyszonych', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-interest-income', code: 'INTEREST_INCOME_CF', labelEn: 'Interest Income (CF)', labelPl: 'Przychody z odsetek', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-before-wc', code: 'CF_BEFORE_WC', labelEn: 'CF Before Working Capital Changes', labelPl: 'Przepływy przed zmianami w kapitale obrotowym', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-generated', code: 'CF_GENERATED', labelEn: 'Cash Generated from Operations', labelPl: 'Środki pieniężne wygenerowane z działalności operacyjnej', parentId: 'fsl-cf-operating', sortOrder: 16, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-change-wc', code: 'CHANGE_WORKING_CAPITAL', labelEn: 'Change in Working Capital', labelPl: 'Zmiana kapitału obrotowego', parentId: 'fsl-cf-operating', sortOrder: 13, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal', deaggregationReady: true },
  { id: 'fsl-cf-change-wc-ar', code: 'CHANGE_AR', labelEn: 'Change in Receivables', labelPl: 'Zmiana należności', parentId: 'fsl-cf-change-wc', sortOrder: 14, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-change-wc-inventory', code: 'CHANGE_INVENTORY', labelEn: 'Change in Inventory', labelPl: 'Zmiana zapasów', parentId: 'fsl-cf-change-wc', sortOrder: 15, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-change-wc-ap', code: 'CHANGE_AP', labelEn: 'Change in Payables', labelPl: 'Zmiana zobowiązań', parentId: 'fsl-cf-change-wc', sortOrder: 16, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-change-wc-provisions', code: 'CHANGE_PROVISIONS', labelEn: 'Change in Provisions', labelPl: 'Zmiana stanu rezerw', parentId: 'fsl-cf-change-wc', sortOrder: 16, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-change-wc-other', code: 'CHANGE_OTHER_WC', labelEn: 'Change in Other Working Capital', labelPl: 'Zmiana stanu pozostałych aktywów', parentId: 'fsl-cf-change-wc', sortOrder: 16, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-interest-cost', code: 'INTEREST_COST_CF', labelEn: 'Interest Cost (CF Adjustment)', labelPl: 'Koszty odsetek', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-taxes-paid', code: 'TAXES_PAID', labelEn: 'Taxes Paid', labelPl: 'Podatek zapłacony', parentId: 'fsl-cf-operating', sortOrder: 17, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-interest-paid', code: 'INTEREST_PAID', labelEn: 'Interest Paid', labelPl: 'Odsetki zapłacone', parentId: 'fsl-cf-operating', sortOrder: 18, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-investing', code: 'INVESTING_CF', labelEn: 'Investing Cash Flow', labelPl: 'Przepływy inwestycyjne', sortOrder: 30, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isSubtotal: true, deaggregationReady: true },
  { id: 'fsl-cf-capex', code: 'CAPEX', labelEn: 'Capital Expenditures', labelPl: 'Nakłady inwestycyjne', parentId: 'fsl-cf-investing', sortOrder: 31, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute', deaggregationReady: true },
  { id: 'fsl-cf-capex-maintenance', code: 'MAINTENANCE_CAPEX', labelEn: 'Maintenance Capex', labelPl: 'CAPEX odtworzeniowy', parentId: 'fsl-cf-capex', sortOrder: 32, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-capex-growth', code: 'GROWTH_CAPEX', labelEn: 'Growth Capex', labelPl: 'CAPEX rozwojowy', parentId: 'fsl-cf-capex', sortOrder: 33, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-capex-intangibles', code: 'CAPEX_INTANGIBLES', labelEn: 'Capex - Intangible Assets', labelPl: 'Wydatki na wartości niematerialne', parentId: 'fsl-cf-investing', sortOrder: 33, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-investing-disposal-proceeds', code: 'DISPOSAL_PROCEEDS', labelEn: 'Proceeds from Disposal of Assets', labelPl: 'Wpływy ze sprzedaży aktywów', parentId: 'fsl-cf-investing', sortOrder: 33, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-investing-acquisitions', code: 'ACQUISITIONS_CF', labelEn: 'Acquisitions, Net of Cash', labelPl: 'Przejęcia, netto', parentId: 'fsl-cf-investing', sortOrder: 34, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'negative_normal' },
  { id: 'fsl-cf-investing-securities', code: 'SECURITIES_CF', labelEn: 'Purchases/Sales of Investments & Securities', labelPl: 'Zakup/sprzedaż inwestycji i papierów wartościowych', parentId: 'fsl-cf-investing', sortOrder: 35, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-investing-jv', code: 'INVESTING_JV', labelEn: 'Investment in Joint Ventures', labelPl: 'Inwestycje we wspólne przedsięwzięcia', parentId: 'fsl-cf-investing', sortOrder: 35, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'negative_normal' },
  { id: 'fsl-cf-other-investing', code: 'OTHER_INVESTING_CF', labelEn: 'Other Investing Cash Flow', labelPl: 'Pozostałe przepływy inwestycyjne', parentId: 'fsl-cf-investing', sortOrder: 36, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-financing', code: 'FINANCING_CF', labelEn: 'Financing Cash Flow', labelPl: 'Przepływy finansowe', sortOrder: 50, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isSubtotal: true, deaggregationReady: true },
  { id: 'fsl-cf-debt-drawdown', code: 'DEBT_DRAWDOWN', labelEn: 'Debt Drawdown', labelPl: 'Zaciągnięcie finansowania dłużnego', parentId: 'fsl-cf-financing', sortOrder: 51, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-debt-drawdown-bank', code: 'BANK_DEBT_DRAWDOWN', labelEn: 'Bank Debt Drawdown', labelPl: 'Uruchomienie długu bankowego', parentId: 'fsl-cf-debt-drawdown', sortOrder: 52, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-debt-drawdown-lease', code: 'LEASE_DEBT_DRAWDOWN', labelEn: 'Lease Drawdown', labelPl: 'Nowe zobowiązania leasingowe', parentId: 'fsl-cf-debt-drawdown', sortOrder: 53, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-debt-repayment', code: 'DEBT_REPAYMENT', labelEn: 'Debt Repayment', labelPl: 'Spłata finansowania dłużnego', parentId: 'fsl-cf-financing', sortOrder: 54, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-debt-repayment-bank', code: 'BANK_DEBT_REPAYMENT', labelEn: 'Bank Debt Repayment', labelPl: 'Spłata długu bankowego', parentId: 'fsl-cf-debt-repayment', sortOrder: 55, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-debt-repayment-lease', code: 'LEASE_DEBT_REPAYMENT', labelEn: 'Lease Repayment', labelPl: 'Spłata leasingu', parentId: 'fsl-cf-debt-repayment', sortOrder: 56, aggregationLevel: 3, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-dividends', code: 'DIVIDENDS_PAID', labelEn: 'Dividends Paid', labelPl: 'Dywidendy wypłacone', parentId: 'fsl-cf-financing', sortOrder: 57, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'display_absolute' },
  { id: 'fsl-cf-share-issuance', code: 'SHARE_ISSUANCE', labelEn: 'Proceeds from Share Issuance', labelPl: 'Wpływy z emisji akcji', parentId: 'fsl-cf-financing', sortOrder: 58, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-other-financing', code: 'OTHER_FINANCING_CF', labelEn: 'Other Financing Cash Flow', labelPl: 'Pozostałe przepływy finansowe', parentId: 'fsl-cf-financing', sortOrder: 59, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-fcf', code: 'FREE_CASH_FLOW', labelEn: 'Free Cash Flow', labelPl: 'Wolne przepływy pieniężne', sortOrder: 60, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal', isSubtotal: true, isComputed: true, formulaJson: { type: 'sum', inputs: ['OPERATING_CF', 'CAPEX'] } },
  { id: 'fsl-cf-net-change-cash', code: 'NET_CHANGE_CASH', labelEn: 'Net Change in Cash', labelPl: 'Zmiana stanu środków pieniężnych', sortOrder: 70, aggregationLevel: 1, requiredLevel: 'required', signConvention: 'positive_normal', isTotal: true, isComputed: true },
  { id: 'fsl-cf-fx-on-cash', code: 'FX_ON_CASH', labelEn: 'FX Effect on Cash', labelPl: 'Wpływ zmian kursów walut na środki pieniężne', sortOrder: 71, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-opening-cash', code: 'OPENING_CASH', labelEn: 'Opening Cash Balance', labelPl: 'Środki pieniężne na początek okresu', sortOrder: 72, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-closing-cash', code: 'CLOSING_CASH', labelEn: 'Closing Cash Balance', labelPl: 'Środki pieniężne na koniec okresu', sortOrder: 73, aggregationLevel: 1, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-tax-refund', code: 'TAX_REFUND', labelEn: 'Tax Refund', labelPl: 'Zwrot podatku', parentId: 'fsl-cf-operating', sortOrder: 17, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-other-expenditure', code: 'OTHER_EXPENDITURE', labelEn: 'Other Expenditure', labelPl: 'Inne wydatki', sortOrder: 74, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'negative_normal' },
  { id: 'fsl-cf-other-receipts', code: 'OTHER_RECEIPTS', labelEn: 'Other Receipts', labelPl: 'Inne wpływy', sortOrder: 75, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-investing-subsidiaries', code: 'INVESTING_SUBSIDIARIES', labelEn: 'Investment in Subsidiaries', labelPl: 'Inwestycje w jednostki zależne', parentId: 'fsl-cf-investing', sortOrder: 76, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'negative_normal' },
  { id: 'fsl-cf-change-wc-restricted-cash', code: 'CHANGE_WC_RESTRICTED_CASH', labelEn: 'Change in Restricted Cash', labelPl: 'Zmiana stanu środków pieniężnych o ograniczonym dysponowaniu', parentId: 'fsl-cf-operating', sortOrder: 77, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-change-wc-prepaids', code: 'CHANGE_WC_PREPAIDS', labelEn: 'Change in Prepayments', labelPl: 'Zmiana stanu rozliczeń międzyokresowych', parentId: 'fsl-cf-operating', sortOrder: 78, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-lease-repayment', code: 'LEASE_REPAYMENT', labelEn: 'Lease Liability Repayment', labelPl: 'Spłata zobowiązań z tytułu leasingu', parentId: 'fsl-cf-financing', sortOrder: 79, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'negative_normal' },
  { id: 'fsl-cf-operating-fv-derivatives', code: 'FV_DERIVATIVES', labelEn: 'Fair Value Changes on Derivatives', labelPl: 'Zmiany wartości godziwej instrumentów pochodnych', parentId: 'fsl-cf-operating', sortOrder: 80, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-dividends-received', code: 'DIVIDENDS_RECEIVED', labelEn: 'Dividends Received', labelPl: 'Otrzymane dywidendy', parentId: 'fsl-cf-investing', sortOrder: 81, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-share-buyback', code: 'SHARE_BUYBACK', labelEn: 'Share Buyback / Treasury Shares Acquired', labelPl: 'Skup akcji własnych', parentId: 'fsl-cf-financing', sortOrder: 82, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'negative_normal' },
  { id: 'fsl-cf-operating-sbc', code: 'SBC_CF', labelEn: 'Stock-Based Compensation (CF)', labelPl: 'Wynagrodzenie w formie akcji', parentId: 'fsl-cf-operating', sortOrder: 83, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-investing-associates', code: 'INVESTING_ASSOCIATES', labelEn: 'Investment in Associates', labelPl: 'Inwestycje w jednostki stowarzyszone', parentId: 'fsl-cf-investing', sortOrder: 35, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'negative_normal' },
  { id: 'fsl-cf-investing-disposal-business', code: 'DISPOSAL_BUSINESS_PROCEEDS', labelEn: 'Proceeds from Disposal of Businesses', labelPl: 'Wpływy ze sprzedaży przedsiębiorstw', parentId: 'fsl-cf-investing', sortOrder: 34, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-investing-disposal-investments', code: 'DISPOSAL_INVESTMENTS_PROCEEDS', labelEn: 'Proceeds from Disposal of Investments', labelPl: 'Wpływy ze sprzedaży inwestycji', parentId: 'fsl-cf-investing', sortOrder: 34, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-financing-short-term-debt', code: 'SHORT_TERM_DEBT_CHANGE', labelEn: 'Net Change in Short-term Debt', labelPl: 'Zmiana netto zobowiązań krótkoterminowych', parentId: 'fsl-cf-financing', sortOrder: 53, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-financing-hybrid-bonds', code: 'HYBRID_BONDS_CF', labelEn: 'Hybrid Bonds Issued/Redeemed', labelPl: 'Obligacje hybrydowe wyemitowane/wykupione', parentId: 'fsl-cf-financing', sortOrder: 54, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-dividends-minority', code: 'DIVIDENDS_MINORITY', labelEn: 'Dividends Paid to Non-controlling Interests', labelPl: 'Dywidendy wypłacone udziałom niekontrolującym', parentId: 'fsl-cf-financing', sortOrder: 57, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'negative_normal' },
  { id: 'fsl-cf-financing-nci', code: 'NCI_TRANSACTIONS_CF', labelEn: 'Transactions with Non-controlling Interests', labelPl: 'Transakcje z udziałami niekontrolującymi', parentId: 'fsl-cf-financing', sortOrder: 58, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-operating-write-downs', code: 'WRITE_DOWNS_CF', labelEn: 'Write-downs and Write-offs (CF)', labelPl: 'Odpisy i umorzenia', parentId: 'fsl-cf-operating', sortOrder: 12, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-investing-disposal-ppe', code: 'DISPOSAL_PPE_PROCEEDS', labelEn: 'Proceeds from Disposal of Property, Plant and Equipment', labelPl: 'Wpływy ze sprzedaży rzeczowych aktywów trwałych', parentId: 'fsl-cf-investing', sortOrder: 34, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
  { id: 'fsl-cf-investing-maturity-proceeds', code: 'MATURITY_PROCEEDS', labelEn: 'Proceeds from Maturities of Investments', labelPl: 'Wpływy z zapadalności inwestycji', parentId: 'fsl-cf-investing', sortOrder: 35, aggregationLevel: 2, requiredLevel: 'optional', signConvention: 'positive_normal' },
]);

const CANONICAL_LINES: CanonicalLineDefinition[] = [...PL_LINES, ...BS_LINES, ...CF_LINES];

const LINE_BY_ID = new Map(CANONICAL_LINES.map((line) => [line.id, line]));
const LINE_BY_CODE = new Map(CANONICAL_LINES.map((line) => [line.code, line]));

export function getCanonicalLineDefinitions(): CanonicalLineDefinition[] {
  return [...CANONICAL_LINES];
}

export function getCanonicalLinesByStatementType(
  statementType: CanonicalStatementType
): CanonicalLineDefinition[] {
  return CANONICAL_LINES.filter((line) => line.statementType === statementType).sort(
    (left, right) => left.sortOrder - right.sortOrder
  );
}

export function getCanonicalLineById(id: string | null | undefined): CanonicalLineDefinition | null {
  if (!id) return null;
  return LINE_BY_ID.get(id) || null;
}

export function getCanonicalLineByCode(code: string | null | undefined): CanonicalLineDefinition | null {
  const normalized = String(code || '')
    .trim()
    .toUpperCase();
  if (!normalized) return null;
  return LINE_BY_CODE.get(normalized) || null;
}

export function getRequiredCanonicalLineIds(
  statementType: CanonicalStatementType
): string[] {
  return getCanonicalLinesByStatementType(statementType)
    .filter((line) => line.requiredLevel === 'required')
    .map((line) => line.id);
}

export function getCanonicalStatementTypeOrder(statementType: string | null | undefined): number {
  const normalized = String(statementType || '').trim().toUpperCase();
  if (normalized === 'P&L') return 1;
  if (normalized === 'BS') return 2;
  if (normalized === 'CF') return 3;
  return 9;
}

export function getCanonicalStatementTypes(): CanonicalStatementType[] {
  return ['P&L', 'BS', 'CF'];
}

export function getCanonicalLineVersionTag(): string {
  return 'finance-v2-l3';
}

export function createCanonicalVersionId(): string {
  return uuidv4();
}
