import type { OrganizationExportTableContract } from './organizationExportContract.js';

export const ORGANIZATION_EXPORT_MVP_TABLES: readonly OrganizationExportTableContract[] = [
  {
    schema: 'public',
    table: 'projects',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      organization_id: 'text',
      name: 'text',
      description: 'text',
      status: 'text',
      start_date: 'text',
      end_date: 'text',
      budget: 'real',
      currency: 'text',
      lead_id: 'text',
      priority: 'text',
      phase: 'text',
      settings: 'text',
      metadata: 'text',
      context_data: 'text',
      owner_id: 'text',
      rag_enabled: 'integer',
      created_at: 'timestamp with time zone',
      updated_at: 'timestamp with time zone',
      is_system: 'boolean',
      program_id: 'text',
      actual_end_date: 'date',
      archived_at: 'timestamp without time zone',
      archived_by: 'text',
      budget_amount: 'numeric(15,2)',
      budget_currency: 'text',
      is_closed: 'integer',
      location_id: 'text',
      pmo_standard: 'text',
      target_end_date: 'date',
      current_phase: 'text',
      health: 'text',
      progress_pct: 'real',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['organization_id'],
        parentSchema: 'public',
        parentTable: 'organizations',
        parentColumns: ['id'],
        deleteAction: 'NO ACTION',
      },
    ],
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'name',
      'description',
      'status',
      'start_date',
      'end_date',
      'budget',
      'currency',
      'lead_id',
      'priority',
      'phase',
      'settings',
      'metadata',
      'context_data',
      'owner_id',
      'rag_enabled',
      'created_at',
      'updated_at',
      'is_system',
      'program_id',
      'actual_end_date',
      'archived_at',
      'archived_by',
      'budget_amount',
      'budget_currency',
      'is_closed',
      'location_id',
      'pmo_standard',
      'target_end_date',
      'current_phase',
      'health',
      'progress_pct',
    ],
    excludedColumns: [],
    source:
      'server/src/controllers/ProjectController.ts:createProject/getProjects; projectOwnerMembershipService.ts; projects.organization_id owns project_members via project_id; organization-export-snapshot.gateway.pg.test.ts real POST/GET/JSON/CSV/SQL A-B proof',
    ownerColumn: 'organization_id',
  },
  {
    schema: 'public',
    table: 'project_members',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      project_id: 'text',
      user_id: 'text',
      project_role: 'text',
      workstream_id: 'text',
      allocation_percent: 'integer',
      permissions: 'text',
      start_date: 'text',
      end_date: 'text',
      created_at: 'timestamp with time zone',
      updated_at: 'timestamp with time zone',
      added_by_id: 'text',
      is_invoked: 'integer',
      consultant_profile: 'text',
      engagement_type: 'text',
      acting_org_id: 'text',
      role_template_id: 'text',
      normalized_project_role: 'text',
      legacy_project_role: 'text',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['project_id'],
        parentSchema: 'public',
        parentTable: 'projects',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
      {
        columns: ['user_id'],
        parentSchema: 'public',
        parentTable: 'users',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
      {
        columns: ['workstream_id'],
        parentSchema: 'public',
        parentTable: 'workstreams',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['added_by_id'],
        parentSchema: 'public',
        parentTable: 'users',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
    ],
    counterpartyColumns: [],
    projection: [
      'id',
      'project_id',
      'user_id',
      'project_role',
      'workstream_id',
      'allocation_percent',
      'permissions',
      'start_date',
      'end_date',
      'created_at',
      'updated_at',
      'added_by_id',
      'is_invoked',
      'consultant_profile',
      'engagement_type',
      'acting_org_id',
      'role_template_id',
      'normalized_project_role',
      'legacy_project_role',
    ],
    excludedColumns: [],
    source:
      'server/src/controllers/ProjectController.ts:createProject/getProjects; projectOwnerMembershipService.ts; projects.organization_id owns project_members via project_id; organization-export-snapshot.gateway.pg.test.ts real POST/GET/JSON/CSV/SQL A-B proof',
    ownerVia: {
      parentSchema: 'public',
      parentTable: 'projects',
      childColumn: 'project_id',
      parentColumn: 'id',
    },
  },
];
