import type { OrganizationExportTableContract } from './organizationExportContract.js';
export const ORGANIZATION_EXPORT_DECISION_TABLES: readonly OrganizationExportTableContract[] = [
  {
    schema: 'public',
    table: 'decisions',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      organization_id: 'text',
      project_id: 'text',
      initiative_id: 'text',
      task_id: 'text',
      title: 'text',
      type: 'text',
      decision_maker_id: 'text',
      created_by: 'text',
      status: 'text',
      options: 'text',
      criteria: 'text',
      deadline: 'timestamp without time zone',
      escalation_deadline: 'timestamp without time zone',
      selected_option: 'text',
      decision_rationale: 'text',
      decided_at: 'timestamp without time zone',
      source_type: 'text',
      source_id: 'text',
      created_at: 'timestamp without time zone',
      updated_at: 'timestamp without time zone',
      priority: 'text',
      assigned_to: 'text',
      description: 'text',
      impact: 'text',
      escalation_level: 'text',
      pmo_domain: 'text',
      required: 'text',
      decision_owner_id: 'text',
      context_type: 'text',
      context_id: 'text',
      alternatives: 'jsonb',
      risk_impact: 'jsonb',
      consequences_of_inaction: 'text',
      recommendation: 'text',
      assumptions: 'jsonb',
      version: 'integer',
      decided_by: 'text',
      escalated_to: 'text',
      ai_generated_sections: 'text',
      playbook_id: 'text',
      required_fields_status: 'text',
      workflow_status: 'text',
      idempotency_key: 'text',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['created_by'],
        parentSchema: 'public',
        parentTable: 'users',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['decision_maker_id'],
        parentSchema: 'public',
        parentTable: 'users',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['initiative_id'],
        parentSchema: 'public',
        parentTable: 'initiatives',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['organization_id'],
        parentSchema: 'public',
        parentTable: 'organizations',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
      {
        columns: ['project_id'],
        parentSchema: 'public',
        parentTable: 'projects',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['task_id'],
        parentSchema: 'public',
        parentTable: 'tasks',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
    ],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'project_id',
      'initiative_id',
      'task_id',
      'title',
      'type',
      'decision_maker_id',
      'created_by',
      'status',
      'options',
      'criteria',
      'deadline',
      'escalation_deadline',
      'selected_option',
      'decision_rationale',
      'decided_at',
      'source_type',
      'source_id',
      'created_at',
      'updated_at',
      'priority',
      'assigned_to',
      'description',
      'impact',
      'escalation_level',
      'pmo_domain',
      'required',
      'decision_owner_id',
      'context_type',
      'context_id',
      'alternatives',
      'risk_impact',
      'consequences_of_inaction',
      'recommendation',
      'assumptions',
      'version',
      'decided_by',
      'escalated_to',
      'ai_generated_sections',
      'playbook_id',
      'required_fields_status',
      'workflow_status',
      'idempotency_key',
    ],
    excludedColumns: [],
    decisionPrivacyKind: 'decision',
    source:
      'Actual cx6_swieza schema-only decision-provenance-schema.sql; DecisionController1084/1353; InterviewInsightService1884; interviewInsightFindingsService1266; source-owner matrix C6_DECISIONS_EXPORT_SOURCE_OWNER_MATRIX.md. Raw content requires explicit actor/source resolver.',
  },
  {
    schema: 'public',
    table: 'interview_insights',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      organization_id: 'text',
      title: 'text',
      prompt_type: 'text',
      source_session_ids: 'text',
      filters: 'text',
      content: 'text',
      status: 'text',
      error_message: 'text',
      source_session_count: 'integer',
      tokens_used: 'integer',
      generation_time_ms: 'integer',
      created_by: 'text',
      created_at: 'timestamp with time zone',
      updated_at: 'timestamp with time zone',
      analysis_scope_json: 'text',
      material_quality_json: 'text',
      context_mode: 'text',
      analysis_mode: 'text',
      topic_focus_json: 'text',
      generation_context_json: 'text',
      section_overrides: 'text',
      structured_content: 'jsonb',
      evidence_links: 'jsonb',
      unknowns: 'jsonb',
      counterpoints: 'jsonb',
      assumptions: 'jsonb',
      confidence_score: 'integer',
      inference_run_id: 'text',
      insight_category: 'text',
      archived_at: 'timestamp without time zone',
      archived_by: 'text',
      category: 'text',
      evidence_map_json: 'text',
      executive_summary: 'text',
      issues_json: 'text',
      missing_data_json: 'text',
      opportunities_json: 'text',
      section_completions: 'text',
      session_id: 'text',
      signals_json: 'text',
      themes_json: 'text',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['organization_id'],
        parentSchema: 'public',
        parentTable: 'organizations',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
    ],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'title',
      'prompt_type',
      'source_session_ids',
      'filters',
      'content',
      'status',
      'error_message',
      'source_session_count',
      'tokens_used',
      'generation_time_ms',
      'created_by',
      'created_at',
      'updated_at',
      'analysis_scope_json',
      'material_quality_json',
      'context_mode',
      'analysis_mode',
      'topic_focus_json',
      'generation_context_json',
      'section_overrides',
      'structured_content',
      'evidence_links',
      'unknowns',
      'counterpoints',
      'assumptions',
      'confidence_score',
      'inference_run_id',
      'insight_category',
      'archived_at',
      'archived_by',
      'category',
      'evidence_map_json',
      'executive_summary',
      'issues_json',
      'missing_data_json',
      'opportunities_json',
      'section_completions',
      'session_id',
      'signals_json',
      'themes_json',
    ],
    excludedColumns: [],
    decisionPrivacyKind: 'insight',
    source:
      'Actual cx6_swieza schema-only decision-provenance-schema.sql; DecisionController1084/1353; InterviewInsightService1884; interviewInsightFindingsService1266; source-owner matrix C6_DECISIONS_EXPORT_SOURCE_OWNER_MATRIX.md. Raw content requires explicit actor/source resolver.',
  },
  {
    schema: 'public',
    table: 'interview_insight_findings',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      organization_id: 'text',
      insight_id: 'text',
      source_section_type: 'text',
      source_section_index: 'integer',
      source_key: 'text',
      finding_statement: 'text',
      confidence_level: 'text',
      limits_text: 'text',
      limits_json: 'text',
      next_action_text: 'text',
      next_action_json: 'text',
      review_status: 'text',
      created_by: 'text',
      updated_by: 'text',
      created_at: 'timestamp without time zone',
      updated_at: 'timestamp without time zone',
      readback_status: 'text',
      readback_summary: 'text',
      readback_updated_at: 'timestamp without time zone',
    },
    primaryKey: ['id'],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'insight_id',
      'source_section_type',
      'source_section_index',
      'source_key',
      'finding_statement',
      'confidence_level',
      'limits_text',
      'limits_json',
      'next_action_text',
      'next_action_json',
      'review_status',
      'created_by',
      'updated_by',
      'created_at',
      'updated_at',
      'readback_status',
      'readback_summary',
      'readback_updated_at',
    ],
    excludedColumns: [],
    decisionPrivacyKind: 'finding',
    source:
      'Actual cx6_swieza schema-only decision-provenance-schema.sql; DecisionController1084/1353; InterviewInsightService1884; interviewInsightFindingsService1266; source-owner matrix C6_DECISIONS_EXPORT_SOURCE_OWNER_MATRIX.md. Raw content requires explicit actor/source resolver.',
  },
  {
    schema: 'public',
    table: 'interview_insight_evidence_pointers',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      organization_id: 'text',
      insight_id: 'text',
      finding_id: 'text',
      pointer_type: 'text',
      source_ref: 'text',
      source_fingerprint: 'text',
      captured_excerpt: 'text',
      captured_at: 'timestamp without time zone',
      pointer_state: 'text',
      removal_reason: 'text',
      removed_at: 'timestamp without time zone',
      duplicate_observed_count: 'integer',
      metadata_json: 'text',
      created_by: 'text',
      created_at: 'timestamp without time zone',
      updated_at: 'timestamp without time zone',
    },
    primaryKey: ['id'],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'insight_id',
      'finding_id',
      'pointer_type',
      'source_ref',
      'source_fingerprint',
      'captured_excerpt',
      'captured_at',
      'pointer_state',
      'removal_reason',
      'removed_at',
      'duplicate_observed_count',
      'metadata_json',
      'created_by',
      'created_at',
      'updated_at',
    ],
    excludedColumns: [],
    decisionPrivacyKind: 'pointer',
    source:
      'Actual cx6_swieza schema-only decision-provenance-schema.sql; DecisionController1084/1353; InterviewInsightService1884; interviewInsightFindingsService1266; source-owner matrix C6_DECISIONS_EXPORT_SOURCE_OWNER_MATRIX.md. Raw content requires explicit actor/source resolver.',
  },
  {
    schema: 'public',
    table: 'interview_insight_handoffs',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      organization_id: 'text',
      insight_id: 'text',
      finding_id: 'text',
      target_kind: 'text',
      target_id: 'text',
      target_ref_type: 'text',
      status: 'text',
      payload_json: 'text',
      operator_decision_json: 'text',
      created_by: 'text',
      created_at: 'timestamp without time zone',
      updated_at: 'timestamp without time zone',
    },
    primaryKey: ['id'],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'insight_id',
      'finding_id',
      'target_kind',
      'target_id',
      'target_ref_type',
      'status',
      'payload_json',
      'operator_decision_json',
      'created_by',
      'created_at',
      'updated_at',
    ],
    excludedColumns: [],
    decisionPrivacyKind: 'handoff',
    source:
      'Actual cx6_swieza schema-only decision-provenance-schema.sql; DecisionController1084/1353; InterviewInsightService1884; interviewInsightFindingsService1266; source-owner matrix C6_DECISIONS_EXPORT_SOURCE_OWNER_MATRIX.md. Raw content requires explicit actor/source resolver.',
  },
];
