import type { OrganizationExportTableContract } from './organizationExportContract.js';

/** Approved physical schema, not blanket content permission. */
export const ORGANIZATION_EXPORT_TASK_TABLES: readonly OrganizationExportTableContract[] = [
  {
    schema: 'public',
    table: 'tasks',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      project_id: 'text',
      organization_id: 'text',
      title: 'text',
      description: 'text',
      status: 'text',
      priority: 'text',
      assignee_id: 'text',
      reporter_id: 'text',
      due_date: 'timestamp with time zone',
      estimated_hours: 'real',
      checklist: 'text',
      attachments: 'text',
      tags: 'text',
      task_type: 'text',
      initiative_id: 'text',
      why: 'text',
      expected_outcome: 'text',
      decision_impact: 'text',
      evidence_required: 'text',
      strategic_contribution: 'text',
      roadmap_initiative_id: 'text',
      kpi_id: 'text',
      raid_item_id: 'text',
      assignees: 'text',
      progress: 'integer',
      blocked_reason: 'text',
      sla_hours: 'integer',
      sla_due_at: 'text',
      escalation_level: 'integer',
      escalated_to_id: 'text',
      last_escalated_at: 'text',
      custom_status_id: 'text',
      step_phase: 'text',
      budget_allocated: 'real',
      budget_spent: 'real',
      risk_rating: 'text',
      acceptance_criteria: 'text',
      blocking_issues: 'text',
      completed_at: 'timestamp with time zone',
      created_at: 'timestamp with time zone',
      updated_at: 'timestamp with time zone',
      idempotency_key: 'text',
      created_by: 'text',
      started_at: 'timestamp with time zone',
      backup_assignee_id: 'text',
      list_id: 'text',
      workstream_id: 'text',
      source: 'text',
      owner_id: 'text',
      requires_acceptance: 'boolean',
      acceptance_type: 'text',
      acceptor_id: 'text',
      weight: 'integer',
      weight_reason: 'text',
      blocked_by_decision_id: 'text',
      blocked_at: 'timestamp with time zone',
      custom_fields_json: 'text',
      parent_task_id: 'text',
      sort_order: 'integer',
      story_points: 'integer',
      actual_hours: 'real',
      sprint_id: 'text',
      idea_id: 'text',
      notify_on_overdue: 'integer',
      notify_on_acceptance: 'integer',
      notify_on_unassigned: 'integer',
      notify_on_blocked: 'integer',
      last_overdue_notified_at: 'text',
      last_acceptance_notified_at: 'text',
      last_unassigned_notified_at: 'text',
      last_blocked_notified_at: 'text',
      source_type: 'text',
      source_id: 'text',
      effort_estimate_hours: 'real',
      is_milestone: 'boolean',
      milestone_target_date: 'date',
      required_skills: 'text',
      risks: 'jsonb',
      alternatives: 'jsonb',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['assignee_id'],
        parentSchema: 'public',
        parentTable: 'users',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['custom_status_id'],
        parentSchema: 'public',
        parentTable: 'custom_statuses',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['organization_id'],
        parentSchema: 'public',
        parentTable: 'organizations',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
      {
        columns: ['project_id'],
        parentSchema: 'public',
        parentTable: 'projects',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
      {
        columns: ['reporter_id'],
        parentSchema: 'public',
        parentTable: 'users',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
    ],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'id',
      'project_id',
      'organization_id',
      'title',
      'description',
      'status',
      'priority',
      'assignee_id',
      'reporter_id',
      'due_date',
      'estimated_hours',
      'checklist',
      'attachments',
      'tags',
      'task_type',
      'initiative_id',
      'why',
      'expected_outcome',
      'decision_impact',
      'evidence_required',
      'strategic_contribution',
      'roadmap_initiative_id',
      'kpi_id',
      'raid_item_id',
      'assignees',
      'progress',
      'blocked_reason',
      'sla_hours',
      'sla_due_at',
      'escalation_level',
      'escalated_to_id',
      'last_escalated_at',
      'custom_status_id',
      'step_phase',
      'budget_allocated',
      'budget_spent',
      'risk_rating',
      'acceptance_criteria',
      'blocking_issues',
      'completed_at',
      'created_at',
      'updated_at',
      'idempotency_key',
      'created_by',
      'started_at',
      'backup_assignee_id',
      'list_id',
      'workstream_id',
      'source',
      'owner_id',
      'requires_acceptance',
      'acceptance_type',
      'acceptor_id',
      'weight',
      'weight_reason',
      'blocked_by_decision_id',
      'blocked_at',
      'custom_fields_json',
      'parent_task_id',
      'sort_order',
      'story_points',
      'actual_hours',
      'sprint_id',
      'idea_id',
      'notify_on_overdue',
      'notify_on_acceptance',
      'notify_on_unassigned',
      'notify_on_blocked',
      'last_overdue_notified_at',
      'last_acceptance_notified_at',
      'last_unassigned_notified_at',
      'last_blocked_notified_at',
      'source_type',
      'source_id',
      'effort_estimate_hours',
      'is_milestone',
      'milestone_target_date',
      'required_skills',
      'risks',
      'alternatives',
    ],
    excludedColumns: [],
    personalTaskPrivacy: true,
    source:
      'Actual cx6_swieza catalog canonical-business-catalog.jsonl; createPersonalTaskService.ts:127/176/185; my-work.routes.ts:1326; TaskController.ts:705/983; aiActionExecutor.ts:1211/1222. Explicit manual personal fields only; supplemental/source-derived content unresolved.',
  },
];
