import type { OrganizationExportTableContract } from './organizationExportContract.js';

// Explicit source contracts, never catalog-inferred authorization.
// Relations migration20262107 drops PK in favor of identity unique indexes.
// Catalog mismatch must fail closed until runtime measurement is available.
export const ORGANIZATION_EXPORT_CANONICAL_TABLES: readonly OrganizationExportTableContract[] = [
  {
    schema: 'public',
    table: 'ie_aggregate_state',
    category: 'EXPORT',
    columnTypes: {
      organization_id: 'text',
      aggregate_type: 'text',
      aggregate_id: 'text',
      version: 'integer',
      payload_json: 'jsonb',
      updated_at: 'timestamp with time zone',
    },
    primaryKey: ['organization_id', 'aggregate_type', 'aggregate_id'],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'organization_id',
      'aggregate_type',
      'aggregate_id',
      'version',
      'payload_json',
      'updated_at',
    ],
    excludedColumns: [],
    source:
      'postgresMaterialCommandUnitOfWork persistAggregate/appendAudit/appendOutbox/saveReceipt/claimRelation/publishInitiativeCardVersion; postgresInitiativeReader; migrations932/933 +20260930 outbox +20262107 relations. Source-derived schema only, catalog/runtime NOT_PROVEN. Payload lineage-only, explicit content unresolved.',
    canonicalLineageColumns: ['payload_json'],
  },
  {
    schema: 'public',
    table: 'ie_command_receipts',
    category: 'EXPORT',
    columnTypes: {
      organization_id: 'text',
      client_request_id: 'text',
      command_type: 'text',
      aggregate_type: 'text',
      aggregate_id: 'text',
      aggregate_version: 'integer',
      correlation_id: 'text',
      request_fingerprint: 'text',
      response_json: 'jsonb',
      created_at: 'timestamp with time zone',
    },
    primaryKey: ['organization_id', 'client_request_id'],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'organization_id',
      'client_request_id',
      'command_type',
      'aggregate_type',
      'aggregate_id',
      'aggregate_version',
      'correlation_id',
      'response_json',
      'created_at',
    ],
    excludedColumns: ['request_fingerprint'],
    source:
      'postgresMaterialCommandUnitOfWork persistAggregate/appendAudit/appendOutbox/saveReceipt/claimRelation/publishInitiativeCardVersion; postgresInitiativeReader; migrations932/933 +20260930 outbox +20262107 relations. Source-derived schema only, catalog/runtime NOT_PROVEN. Payload lineage-only, explicit content unresolved.',
    canonicalLineageColumns: ['response_json'],
  },
  {
    schema: 'public',
    table: 'ie_audit_events',
    category: 'EXPORT',
    columnTypes: {
      id: 'bigint',
      organization_id: 'text',
      actor_id: 'text',
      aggregate_type: 'text',
      aggregate_id: 'text',
      aggregate_version: 'integer',
      command_type: 'text',
      client_request_id: 'text',
      correlation_id: 'text',
      policy_id: 'text',
      policy_version: 'integer',
      payload_json: 'jsonb',
      created_at: 'timestamp with time zone',
    },
    primaryKey: ['id'],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'actor_id',
      'aggregate_type',
      'aggregate_id',
      'aggregate_version',
      'command_type',
      'client_request_id',
      'correlation_id',
      'policy_id',
      'policy_version',
      'payload_json',
      'created_at',
    ],
    excludedColumns: [],
    source:
      'postgresMaterialCommandUnitOfWork persistAggregate/appendAudit/appendOutbox/saveReceipt/claimRelation/publishInitiativeCardVersion; postgresInitiativeReader; migrations932/933 +20260930 outbox +20262107 relations. Source-derived schema only, catalog/runtime NOT_PROVEN. Payload lineage-only, explicit content unresolved.',
    canonicalLineageColumns: ['payload_json'],
  },
  {
    schema: 'public',
    table: 'ie_outbox_events',
    category: 'EXPORT',
    columnTypes: {
      id: 'bigint',
      organization_id: 'text',
      aggregate_type: 'text',
      aggregate_id: 'text',
      aggregate_version: 'integer',
      event_type: 'text',
      correlation_id: 'text',
      causation_id: 'text',
      payload_json: 'jsonb',
      attempt_count: 'integer',
      available_at: 'timestamp with time zone',
      processed_at: 'timestamp with time zone',
      last_error: 'text',
      created_at: 'timestamp with time zone',
      payload_version: 'integer',
      max_attempts: 'integer',
      processing_started_at: 'timestamp with time zone',
      dead_lettered_at: 'timestamp with time zone',
    },
    primaryKey: ['id'],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'aggregate_type',
      'aggregate_id',
      'aggregate_version',
      'event_type',
      'correlation_id',
      'causation_id',
      'payload_json',
      'attempt_count',
      'available_at',
      'processed_at',
      'created_at',
      'payload_version',
      'max_attempts',
      'processing_started_at',
      'dead_lettered_at',
    ],
    excludedColumns: ['last_error'],
    source:
      'postgresMaterialCommandUnitOfWork persistAggregate/appendAudit/appendOutbox/saveReceipt/claimRelation/publishInitiativeCardVersion; postgresInitiativeReader; migrations932/933 +20260930 outbox +20262107 relations. Source-derived schema only, catalog/runtime NOT_PROVEN. Payload lineage-only, explicit content unresolved.',
    canonicalLineageColumns: ['payload_json'],
  },
  {
    schema: 'public',
    table: 'ie_aggregate_relations',
    category: 'EXPORT',
    columnTypes: {
      organization_id: 'text',
      relation_type: 'text',
      source_type: 'text',
      source_id: 'text',
      source_version: 'integer',
      target_type: 'text',
      target_id: 'text',
      payload_json: 'jsonb',
      created_at: 'timestamp with time zone',
    },
    primaryKey: [],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'organization_id',
      'relation_type',
      'source_type',
      'source_id',
      'source_version',
      'target_type',
      'target_id',
      'payload_json',
      'created_at',
    ],
    excludedColumns: [],
    source:
      'postgresMaterialCommandUnitOfWork persistAggregate/appendAudit/appendOutbox/saveReceipt/claimRelation/publishInitiativeCardVersion; postgresInitiativeReader; migrations932/933 +20260930 outbox +20262107 relations. Source-derived schema only, catalog/runtime NOT_PROVEN. Payload lineage-only, explicit content unresolved.',
    canonicalLineageColumns: ['payload_json'],
  },
  {
    schema: 'public',
    table: 'ie_initiative_card_versions',
    category: 'EXPORT',
    columnTypes: {
      organization_id: 'text',
      initiative_id: 'text',
      card_key: 'text',
      card_version: 'integer',
      aggregate_version: 'integer',
      applicability: 'text',
      completion: 'text',
      quality: 'text',
      freshness: 'text',
      review_state: 'text',
      content_json: 'jsonb',
      evidence_refs_json: 'jsonb',
      waiver_decision_id: 'text',
      published_by: 'text',
      review_decision_id: 'text',
      reviewed_by: 'text',
      review_rationale: 'text',
      published_at: 'timestamp with time zone',
    },
    primaryKey: ['organization_id', 'initiative_id', 'card_key', 'card_version'],
    foreignKeys: [
      {
        columns: ['card_key'],
        parentSchema: 'public',
        parentTable: 'ie_initiative_card_catalog',
        parentColumns: ['card_key'],
        deleteAction: 'NO ACTION',
      },
    ],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'organization_id',
      'initiative_id',
      'card_key',
      'card_version',
      'aggregate_version',
      'applicability',
      'completion',
      'quality',
      'freshness',
      'review_state',
      'content_json',
      'evidence_refs_json',
      'waiver_decision_id',
      'published_by',
      'review_decision_id',
      'reviewed_by',
      'published_at',
    ],
    excludedColumns: ['review_rationale'],
    source:
      'postgresMaterialCommandUnitOfWork persistAggregate/appendAudit/appendOutbox/saveReceipt/claimRelation/publishInitiativeCardVersion; postgresInitiativeReader; migrations932/933 +20260930 outbox +20262107 relations. Source-derived schema only, catalog/runtime NOT_PROVEN. Payload lineage-only, explicit content unresolved.',
    canonicalLineageColumns: ['content_json', 'evidence_refs_json'],
  },
  {
    schema: 'public',
    table: 'ie_initiative_card_selection',
    category: 'EXPORT',
    columnTypes: {
      organization_id: 'text',
      initiative_id: 'text',
      card_key: 'text',
      included: 'boolean',
      position: 'integer',
      requiredness: 'text',
      waiver_decision_id: 'text',
      updated_at: 'timestamp with time zone',
    },
    primaryKey: ['organization_id', 'initiative_id', 'card_key'],
    foreignKeys: [
      {
        columns: ['card_key'],
        parentSchema: 'public',
        parentTable: 'ie_initiative_card_catalog',
        parentColumns: ['card_key'],
        deleteAction: 'NO ACTION',
      },
    ],
    ownerColumn: 'organization_id',
    counterpartyColumns: [],
    projection: [
      'organization_id',
      'initiative_id',
      'card_key',
      'included',
      'position',
      'requiredness',
      'waiver_decision_id',
      'updated_at',
    ],
    excludedColumns: [],
    source:
      'postgresMaterialCommandUnitOfWork persistAggregate/appendAudit/appendOutbox/saveReceipt/claimRelation/publishInitiativeCardVersion; postgresInitiativeReader; migrations932/933 +20260930 outbox +20262107 relations. Source-derived schema only, catalog/runtime NOT_PROVEN. Payload lineage-only, explicit content unresolved.',
  },
];
