import type { OrganizationExportTableContract } from './organizationExportContract.js';

// Explicit public ownership; assignment_members remains unresolved (no physical owner FK).
export const ORGANIZATION_EXPORT_INTERVIEW_TABLES: readonly OrganizationExportTableContract[] = [
  {
    schema: 'public',
    table: 'interview_assignments',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      organization_id: 'text',
      assignee_user_id: 'text',
      template_id: 'text',
      template_version: 'integer',
      process_ref: 'text',
      status: 'text',
      session_id: 'text',
      task_id: 'text',
      due_at: 'timestamp without time zone',
      started_at: 'timestamp without time zone',
      submitted_at: 'timestamp without time zone',
      sent_back_at: 'timestamp without time zone',
      sent_back_reason: 'text',
      created_by: 'text',
      created_at: 'timestamp without time zone',
      updated_at: 'timestamp without time zone',
      missing_items_json: 'text',
      ai_review_snapshot_json: 'text',
      ai_reviewed_at: 'timestamp without time zone',
      review_decision_memory_json: 'text',
      archived_via_session: 'boolean',
      is_anonymous: 'boolean',
      archived_at: 'timestamp without time zone',
      archived_by: 'text',
      escalate_to: 'text',
      escalated_at: 'timestamp without time zone',
      escalation_count: 'integer',
      is_active: 'integer',
      is_team_assignment: 'integer',
      last_reminder_type: 'text',
      notes: 'text',
      priority: 'text',
      project_id: 'text',
      reminder_count: 'integer',
      reminder_sent_at: 'timestamp without time zone',
      create_request_key: 'text',
      create_request_fingerprint: 'text',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['assignee_user_id'],
        parentSchema: 'public',
        parentTable: 'users',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
      {
        columns: ['created_by'],
        parentSchema: 'public',
        parentTable: 'users',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['organization_id'],
        parentSchema: 'public',
        parentTable: 'organizations',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
    ],
    ownerColumn: 'organization_id',
    interviewPrivacy: 'assignment',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'assignee_user_id',
      'template_id',
      'template_version',
      'process_ref',
      'status',
      'session_id',
      'task_id',
      'due_at',
      'started_at',
      'submitted_at',
      'sent_back_at',
      'sent_back_reason',
      'created_by',
      'created_at',
      'updated_at',
      'missing_items_json',
      'ai_review_snapshot_json',
      'ai_reviewed_at',
      'review_decision_memory_json',
      'archived_via_session',
      'is_anonymous',
      'archived_at',
      'archived_by',
      'escalate_to',
      'escalated_at',
      'escalation_count',
      'is_active',
      'is_team_assignment',
      'last_reminder_type',
      'notes',
      'priority',
      'project_id',
      'reminder_count',
      'reminder_sent_at',
      'create_request_key',
      'create_request_fingerprint',
    ],
    excludedColumns: [],
    source:
      'InterviewController createSession/createSessionFromTemplate/getQuestions D18-A; InterviewAssignmentService.create; accepted ac98 D18 recommendations wall; C6_INTERVIEW_EXPORT_SOURCE_EVIDENCE.md. Catalog cx6_swieza public; actor-conditional privacy required.',
  },
  {
    schema: 'public',
    table: 'interview_evidence',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      session_id: 'text',
      organization_id: 'text',
      question_id: 'text',
      evidence_type: 'text',
      title: 'text',
      description: 'text',
      file_path: 'text',
      file_name: 'text',
      file_size: 'integer',
      file_type: 'text',
      url: 'text',
      uploaded_by: 'text',
      created_at: 'timestamp with time zone',
      storage_backend: 'text',
      storage_key: 'text',
      file_size_bytes: 'integer',
      content_hash: 'text',
      virus_scan_status: 'text',
      virus_scan_at: 'timestamp with time zone',
      retention_until: 'timestamp with time zone',
      evidence_role: 'text',
      transcript_text: 'text',
      ingest_to_knowledge: 'boolean',
      knowledge_document_id: 'text',
      category: 'text',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['question_id'],
        parentSchema: 'public',
        parentTable: 'interview_questions',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['session_id'],
        parentSchema: 'public',
        parentTable: 'interview_sessions',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
    ],
    ownerColumn: 'organization_id',
    interviewPrivacy: 'evidence',
    counterpartyColumns: [],
    projection: [
      'id',
      'session_id',
      'organization_id',
      'question_id',
      'evidence_type',
      'title',
      'description',
      'file_path',
      'file_name',
      'file_size',
      'file_type',
      'url',
      'uploaded_by',
      'created_at',
      'storage_backend',
      'storage_key',
      'file_size_bytes',
      'content_hash',
      'virus_scan_status',
      'virus_scan_at',
      'retention_until',
      'evidence_role',
      'transcript_text',
      'ingest_to_knowledge',
      'knowledge_document_id',
      'category',
    ],
    excludedColumns: [],
    source:
      'InterviewController createSession/createSessionFromTemplate/getQuestions D18-A; InterviewAssignmentService.create; accepted ac98 D18 recommendations wall; C6_INTERVIEW_EXPORT_SOURCE_EVIDENCE.md. Catalog cx6_swieza public; actor-conditional privacy required.',
  },
  {
    schema: 'public',
    table: 'interview_notes',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      session_id: 'text',
      organization_id: 'text',
      category: 'text',
      title: 'text',
      content: 'text',
      created_by: 'text',
      created_at: 'timestamp with time zone',
      updated_at: 'timestamp with time zone',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['session_id'],
        parentSchema: 'public',
        parentTable: 'interview_sessions',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
    ],
    ownerColumn: 'organization_id',
    interviewPrivacy: 'note',
    counterpartyColumns: [],
    projection: [
      'id',
      'session_id',
      'organization_id',
      'category',
      'title',
      'content',
      'created_by',
      'created_at',
      'updated_at',
    ],
    excludedColumns: [],
    source:
      'InterviewController createSession/createSessionFromTemplate/getQuestions D18-A; InterviewAssignmentService.create; accepted ac98 D18 recommendations wall; C6_INTERVIEW_EXPORT_SOURCE_EVIDENCE.md. Catalog cx6_swieza public; actor-conditional privacy required.',
  },
  {
    schema: 'public',
    table: 'interview_questions',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      session_id: 'text',
      organization_id: 'text',
      category: 'text',
      question_text: 'text',
      answer_text: 'text',
      status: 'text',
      confidence_score: 'integer',
      answered_by: 'text',
      answered_at: 'timestamp with time zone',
      tags: 'text',
      sort_order: 'integer',
      is_template: 'boolean',
      created_at: 'timestamp with time zone',
      updated_at: 'timestamp with time zone',
      evidence_prompt: 'text',
      answered_via_distribution_id: 'text',
      allow_context_note: 'integer',
      allow_file_upload: 'integer',
      allow_url: 'integer',
      allow_voice: 'integer',
      answer_knowledge_doc_id: 'text',
      answer_mode: 'text',
      answer_options: 'text',
      answer_payload: 'text',
      answer_type: 'text',
      branching_rules: 'text',
      context_note: 'text',
      context_note_knowledge_doc_id: 'text',
      description: 'text',
      example_answer: 'text',
      expected_answer_shape: 'text',
      guidance: 'text',
      is_repeatable: 'integer',
      is_required: 'integer',
      question_config: 'text',
      source_template_question_id: 'text',
      voice_audio_evidence_id: 'text',
      voice_transcript: 'text',
      voice_transcript_status: 'text',
    },
    primaryKey: ['id'],
    foreignKeys: [
      {
        columns: ['answered_via_distribution_id'],
        parentSchema: 'public',
        parentTable: 'interview_distributions',
        parentColumns: ['id'],
        deleteAction: 'SET NULL',
      },
      {
        columns: ['session_id'],
        parentSchema: 'public',
        parentTable: 'interview_sessions',
        parentColumns: ['id'],
        deleteAction: 'CASCADE',
      },
    ],
    ownerColumn: 'organization_id',
    interviewPrivacy: 'question',
    counterpartyColumns: [],
    projection: [
      'id',
      'session_id',
      'organization_id',
      'category',
      'question_text',
      'answer_text',
      'status',
      'confidence_score',
      'answered_by',
      'answered_at',
      'tags',
      'sort_order',
      'is_template',
      'created_at',
      'updated_at',
      'evidence_prompt',
      'answered_via_distribution_id',
      'allow_context_note',
      'allow_file_upload',
      'allow_url',
      'allow_voice',
      'answer_knowledge_doc_id',
      'answer_mode',
      'answer_options',
      'answer_payload',
      'answer_type',
      'branching_rules',
      'context_note',
      'context_note_knowledge_doc_id',
      'description',
      'example_answer',
      'expected_answer_shape',
      'guidance',
      'is_repeatable',
      'is_required',
      'question_config',
      'source_template_question_id',
      'voice_audio_evidence_id',
      'voice_transcript',
      'voice_transcript_status',
    ],
    excludedColumns: [],
    source:
      'InterviewController createSession/createSessionFromTemplate/getQuestions D18-A; InterviewAssignmentService.create; accepted ac98 D18 recommendations wall; C6_INTERVIEW_EXPORT_SOURCE_EVIDENCE.md. Catalog cx6_swieza public; actor-conditional privacy required.',
  },
  {
    schema: 'public',
    table: 'interview_sessions',
    category: 'EXPORT',
    columnTypes: {
      id: 'text',
      organization_id: 'text',
      project_id: 'text',
      name: 'text',
      owner_id: 'text',
      status: 'text',
      progress_json: 'text',
      total_questions: 'integer',
      answered_questions: 'integer',
      summary_facts: 'text',
      summary_gaps: 'text',
      summary_constraints: 'text',
      summary_pain_points: 'text',
      template_id: 'text',
      template_version: 'integer',
      assignment_id: 'text',
      started_at: 'timestamp with time zone',
      completed_at: 'timestamp with time zone',
      last_activity_at: 'timestamp with time zone',
      created_at: 'timestamp with time zone',
      updated_at: 'timestamp with time zone',
      is_anonymous: 'boolean',
      anonymity_mode: 'text',
      archived_at: 'timestamp without time zone',
      archived_by: 'text',
      export_gating: 'text',
      min_cohort_size: 'integer',
      redaction_rules: 'text',
      runtime_mode_default: 'text',
      trashed_at: 'timestamp without time zone',
      trashed_by: 'text',
    },
    primaryKey: ['id'],
    foreignKeys: [],
    ownerColumn: 'organization_id',
    interviewPrivacy: 'session',
    counterpartyColumns: [],
    projection: [
      'id',
      'organization_id',
      'project_id',
      'name',
      'owner_id',
      'status',
      'progress_json',
      'total_questions',
      'answered_questions',
      'summary_facts',
      'summary_gaps',
      'summary_constraints',
      'summary_pain_points',
      'template_id',
      'template_version',
      'assignment_id',
      'started_at',
      'completed_at',
      'last_activity_at',
      'created_at',
      'updated_at',
      'is_anonymous',
      'anonymity_mode',
      'archived_at',
      'archived_by',
      'export_gating',
      'min_cohort_size',
      'redaction_rules',
      'runtime_mode_default',
      'trashed_at',
      'trashed_by',
    ],
    excludedColumns: [],
    source:
      'InterviewController createSession/createSessionFromTemplate/getQuestions D18-A; InterviewAssignmentService.create; accepted ac98 D18 recommendations wall; C6_INTERVIEW_EXPORT_SOURCE_EVIDENCE.md. Catalog cx6_swieza public; actor-conditional privacy required.',
  },
];
