import json

def get_japanese_translation(key, en_text):
    # Dictionary of manual translations for this specific app context
    translations = {
        "Dashboard": "ダッシュボード",
        "Quick Assessment": "クイック診断",
        "Full Transformation": "完全な変革 (Full Transition)",
        "Masterclass": "マスタークラス",
        "Resources": "リソース",
        "1. Expectations & Challenges": "1. 期待と課題",
        "Company Profile": "会社概要",
        "Goals & Expectations": "目標と期待",
        "Challenges Map": "課題マップ",
        "2. Assessment (DRD)": "2. アセスメント (DRD)",
        "3. Initiatives & Roadmap": "3. イニシアチブとロードマップ",
        "Initiatives List": "イニシアチブ一覧",
        "Roadmap Builder": "ロードマップビルダー",
        "4. Pilot Execution": "4. パイロット実行",
        "5. Full Rollout": "5. 本格展開",
        "6. Economics & ROI": "6. 経済性とROI",
        "7. Execution Reports": "7. 実行レポート",
        "Admin Panel": "管理パネル",
        "Users": "ユーザー",
        "Projects": "プロジェクト",
        "LLM Management": "LLM管理",
        "Knowledge Base": "ナレッジベース",
        "User Feedback": "ユーザーフィードバック",
        "Company & Expectations": "会社と期待",
        "Challenges & Profile Questions": "課題とプロファイル質問",
        "Recommendations": "推奨事項",
        "Assessment (DRD)": "アセスメント (DRD)",
        "Processes": "プロセス",
        "Digital Products": "デジタル製品",
        "Business Models": "ビジネスモデル",
        "Data Management": "データ管理",
        "Culture": "文化",
        "AI Maturity": "AI成熟度",
        "Initiatives Generator": "イニシアチブ生成",
        "Transformation Roadmap": "変革ロードマップ",
        "Execution Dashboard": "実行ダッシュボード",
        "Reports": "レポート",
        "New Conversation": "新しい会話",
        "Settings": "設定",
        "Mobile App": "モバイルアプリ",
        "Log Out": "ログアウト",
        "Start Your Quick Assessment": "クイック診断を開始",
        "Setup Your Full Account": "完全なアカウントを設定",
        "Unlock Full Transformation": "完全な変革をアンロック",
        "Enter the 6-digit access code provided by DBR77.": "DBR77から提供された6桁のアクセスコードを入力してください。",
        "Verify Code": "コードを確認",
        "We need a few details to personalize your roadmap.": "ロードマップをパーソナライズするために詳細が必要です。",
        "First Name": "名",
        "Last Name": "姓",
        "Work Email": "職場のメールアドレス",
        "Phone Number": "電話番号",
        "Company Name": "会社名",
        "Password (min. 8 chars)": "パスワード (8文字以上)",
        "Create Account & Start": "アカウントを作成して開始",
        "Already have an account?": "すでにアカウントをお持ちですか？",
        "Don't have an account?": "アカウントをお持ちでないですか？",
        "Log In": "ログイン",
        "Create one": "作成する",
        "Welcome Back!": "お帰りなさい！",
        "Sign in to continue your transformation journey.": "変革の旅を続けるにはサインインしてください。",
        "Back to Start Screen": "スタート画面に戻る",
        "Step 1 of 3 — Company & Expectations": "ステップ 1 / 3 — 会社と期待",
        "Role": "役職",
        "Industry": "業界",
        "Size": "規模",
        "Country": "国",
        "Challenges & Goals": "課題と目標",
        "Main Challenges": "主な課題",
        "Main Transformation Goal": "主な変革の目標",
        "Time Horizon": "時間枠",
        "Go to Action Proposals (Step 2)": "アクション提案へ進む (ステップ 2)",
        "Not selected yet...": "まだ選択されていません...",
        "To be defined...": "定義予定...",
        "months": "ヶ月",
        "Step 3 of 3 — Recommendations": "ステップ 3 / 3 — 推奨事項",
        "Company Snapshot": "会社スナップショット",
        "Recommended Focus Areas": "推奨される重点分野",
        "Actionable Quick Wins": "実行可能なクイックウィン",
        "Start Full Transformation Project": "完全な変革プロジェクトを開始",
        "Download Summary": "要約をダウンロード",
        "Revenue": "収益",
        "Digital Maturity": "デジタル成熟度",
        "Transformation Assistant": "変革アシスタント",
        "Step 1: Profiling": "ステップ 1: プロファイリング",
        "Type your answer...": "回答を入力...",
        "OK, let's start": "OK、始めましょう",
        "Explain process": "プロセスを説明",
        "Owner / CEO": "オーナー / CEO",
        "Plant Manager": "工場長",
        "COO": "COO",
        "Production": "生産",
        "Logistics": "物流",
        "Inefficient production processes": "非効率な生産プロセス",
        "Lack of data / visibility": "データ/可視性の欠如",
        "Too many manual tasks": "手作業が多すぎる",
        "Problems with quality": "品質の問題",
        "Low automation level": "自動化レベルが低い",
        "Data": "データ",
        "Automation": "自動化",
        "3 months": "3ヶ月",
        "6 months": "6ヶ月",
        "12 months": "12ヶ月",
        "Looks correct": "正しそうです",
        "Change something": "変更する",
        "Yes, start Full Project": "はい、完全なプロジェクトを開始します",
        "Not now": "今はしない",
        "Start Axis": "軸を開始",
        "Current Axis": "現在の軸",
        "Continue": "次へ",
        "Completed": "完了",
        "Score": "スコア",
        "Maturity Overview": "成熟度の概要",
        "Go to Initiatives Generator (Step 2)": "イニシアチブ生成へ進む (ステップ 2)",
        "Standardization & Efficiency": "標準化と効率",
        "Connectivity & UX": "接続性とUX",
        "Scalability & Revenue": "拡張性と収益",
        "Quality & Governance": "品質とガバナンス",
        "Skills & Mindset": "スキルとマインドセット",
        "Adoption & Strategy": "採用と戦略",
        "Initiative Name": "イニシアチブ名",
        "Axis": "軸",
        "Priority": "優先度",
        "Complexity": "複雑さ",
        "Status": "ステータス",
        "Notes": "メモ",
        "Actions": "アクション",
        "High": "高",
        "Medium": "中",
        "Low": "低",
        "Draft": "下書き",
        "Ready": "準備完了",
        "Archived": "アーカイブ済み",
        "Go to Transformation Roadmap (Step 3)": "変革ロードマップへ進む (ステップ 3)",
        "Quarter": "四半期",
        "Wave": "ウェーブ",
        "Workload Distribution": "ワークロード分布",
        "initiatives": "イニシアチブ",
        "Overloaded": "過負荷",
        "Go to Economics & ROI (Step 4)": "経済性とROIへ進む (ステップ 4)",
        "Est. Cost (k$)": "推定コスト (千ドル)",
        "Est. Benefit (k$/yr)": "推定利益 (千ドル/年)",
        "Total Cost": "総コスト",
        "Total Annual Benefit": "年間総利益",
        "Overall ROI": "全体ROI",
        "Payback Period": "回収期間",
        "years": "年",
        "Go to Execution Dashboard (Step 5)": "実行ダッシュボードへ進む (ステップ 5)",
        "To Do": "未着手",
        "In Progress": "進行中",
        "Blocked": "ブロック中",
        "Done": "完了",
        "Total Initiatives": "総イニシアチブ",
        "Completion Rate": "完了率",
        "Owner": "所有者",
        "Due Date": "期限",
        "Progress": "進捗",
        "Go to Final Report (Step 6)": "最終レポートへ進む (ステップ 6)",
        "Transformation Report": "変革レポート",
        "Executive Summary": "エグゼクティブサマリー",
        "Digital Maturity Profile": "デジタル成熟度プロファイル",
        "Key Initiatives": "主要イニシアチブ",
        "Economics & ROI": "経済性とROI",
        "Execution Status": "実行ステータス",
        "Maturity & Focus": "成熟度と焦点",
        "Project Economics": "プロジェクトの経済性",
        "Execution Snapshot": "実行スナップショット",
        "Export Report": "レポートをエクスポート",
        "Copy Text": "テキストをコピー",
        "Strongest Asset": "最強の資産",
        "Critical Gap": "重要なギャップ",
        "Annual Benefit": "年間利益",
        "ROI": "ROI",
        "In Prog": "進行中",
        "Block": "ブロック",
        "My Profile": "マイプロフィール",
        "Billing & Plans": "請求とプラン",
        "AI Configuration": "AI設定",
        "Notifications": "通知",
        "Integrations": "統合",
        "Regionalization": "地域化",
        "Personal Information": "個人情報",
        "Profile Photo": "プロフィール写真",
        "Change": "変更",
        "Accepts JPG, PNG (Auto-optimized)": "JPG, PNG (自動最適化)",
        "Role / Job Title": "役職 / 肩書き",
        "Email Address (Managed by Admin)": "メールアドレス (管理者が管理)",
        "Preferences": "設定",
        "Interface Theme": "インターフェーステーマ",
        "Light": "ライト",
        "Dark": "ダーク",
        "Language": "言語",
        "Save Changes": "変更を保存",
        "Saved!": "保存しました！",
        "How standardized are your core production processes?": "中核となる生産プロセスはどの程度標準化されていますか？",
        "How well are your processes measured and monitored?": "プロセスはどの程度測定・監視されていますか？",
        "To what extent are your processes digitally supported?": "プロセスはどの程度デジタルでサポートされていますか？",
        "Does your product portfolio include digital services?": "製品ポートフォリオにデジタルサービスは含まれていますか？",
        "How integrated are your products with IoT?": "製品はIoTとどの程度統合されていますか？",
        "Do you use customer usage data to improve products?": "顧客の使用データを使用して製品を改善していますか？",
        "Are you shifting from CAPEX to OPEX models?": "CAPEXからOPEXモデルに移行していますか？",
        "Do you have digital ecosystem partnerships?": "デジタルエコシステムパートナーシップを結んでいますか？",
        "How scalable is your current business model?": "現在のビジネスモデルはどの程度拡張可能ですか？",
        "Is there a single source of truth for key data?": "主要データの「信頼できる唯一の情報源」はありますか？",
        "How automated is data collection?": "データ収集はどの程度自動化されていますか？",
        "Do you use predictive analytics?": "予測分析を使用していますか？",
        "How open is the leadership to digital change?": "リーダーシップはデジタル変革に対してどの程度オープンですか？",
        "Do employees have digital skills training?": "従業員はデジタルスキルのトレーニングを受けていますか？",
        "Is innovation rewarded in the company?": "会社ではイノベーションが報われていますか？",
        "Are you piloting any AI solutions currently?": "現在AIソリューションをパイロット運用していますか？",
        "Do you have data ready for AI training?": "AIトレーニング用のデータは準備できていますか？",
        "Is there an AI strategy in place?": "AI戦略は策定されていますか？",
        "Hello {name}. I am your Transformation Assistant.\n\nIn this Quick Assessment (Free), we will go through 3 steps:\n1. Company & expectations\n2. Challenges & profile questions\n3. Recommendations & quick wins.\n\nShall we start?": "こんにちは、{name}さん。私はあなたの変革アシスタントです。\n\nこのクイック診断（無料）では、次の3つのステップを進めます：\n1. 会社と期待\n2. 課題とプロファイル質問\n3. 推奨事項とクイックウィン\n\n始めましょうか？",
        "Great. Let's start with the basics.\n\nWhat is your role in the company?": "素晴らしい。基本から始めましょう。\n\n会社でのあなたの役割は何ですか？",
        "Nice to meet you, {role}. Perspective matters.\n\nWhat industry do you operate in?": "はじめまして、{role}さん。視点は重要ですね。\n\nどの業界で事業を行っていますか？",
        "Production. Got it. What kind specifically?": "生産ですね。了解しました。具体的にはどのような種類ですか？",
        "How many employees do you have roughly?": "従業員はおおよそ何名ですか？",
        "Understood. Scale changes the available solutions.\n\nWhich country is your main operation in?": "承知しました。規模によって利用可能なソリューションが変わります。\n\n主な事業拠点はどの国ですか？",
        "Great, let's explore your current challenges to build meaningful recommendations.\n\nWhat is your main operational pain point? (Select one or type)": "では、有意義な推奨事項を作成するために、現在の課題を探っていきましょう。\n\n主な業務上の課題は何ですか？（選択または入力）",
        "Understood. Dealing with key challenges.\n\nNow, if we talk in 12 months, what would be the MAIN success statement you'd like to make?": "承知しました。主要な課題に取り組むのですね。\n\nさて、12ヶ月後に話をするとして、あなたが言いたい「主な成功の言葉」は何でしょうか？",
        "Clear goal.\n\nWhen do you need to see the first tangible results?": "明確な目標ですね。\n\n最初の具体的な成果はいつ頃確認したいですか？",
        "Perfect. We have the profile.\n\nSummary:\n- Role: {role}\n- Sector: {industry}\n- Goal: {goal}\n\nI will now generate specific ideas for you.": "完璧です。プロファイルができました。\n\n要約：\n- 役割: {role}\n- セクター: {industry}\n- 目標: {goal}\n\nこれより具体的なアイデアを生成します。",
        "Great! Please click the button on the right to view your Action Proposals.": "素晴らしい！右側のボタンをクリックして、アクション提案を表示してください。",
        "Based on your answers, here is a quick snapshot of your situation and my recommendations.": "あなたの回答に基づき、現在の状況のスナップショットと推奨事項を提示します。",
        "Your company is in the {industry} sector with a clear goal to {goal}. The main challenge is {painPoint}.": "あなたの会社は{industry}セクターに属し、{goal}という明確な目標を持っています。主な課題は{painPoint}です。",
        "I recommend focusing immediately on these areas:": "以下の分野に直ちに注力することをお勧めします：",
        "Here are some Quick Wins you can start next Monday:": "来週の月曜日から始められるクイックウィンは以下の通りです：",
        "Would you like to move to the Full Transformation Project and build a full roadmap?": "完全な変革プロジェクトに移行し、完全なロードマップを作成しますか？",
        "Welcome to the Full Digital Readiness Diagnosis (DRD). We will assess 6 key axes of your business on a scale of 1-7. This will generate your Maturity Heatmap.": "完全なデジタル準備状況診断 (DRD) へようこそ。ビジネスの6つの主要な軸を1〜7の尺度で評価し、成熟度ヒートマップを作成します。",
        "Let's assess your {axis}. How mature are you in this area?": "{axis}を評価しましょう。この分野での成熟度はどの程度ですか？",
        "Here is your digital maturity profile across 6 axes. Based on the scores, we should prioritize {weakest}.": "6つの軸にわたるデジタル成熟度プロファイルはこちらです。スコアに基づき、{weakest}を優先すべきです。",
        "Based on your maturity scores, I've generated a set of transformation initiatives. You can review and edit them in the table on the right.": "成熟度スコアに基づき、変革イニシアチブのセットを生成しました。右側の表で確認・編集できます。",
        "I have drafted a roadmap for you based on the priority and complexity of your initiatives. Foundational tasks (Data/Process) are scheduled earlier.": "イニシアチブの優先度と複雑さに基づいてロードマップの下書きを作成しました。基礎的なタスク（データ/プロセス）は早めに予定されています。",
        "Now let's estimate the costs and benefits. You don't need to be precise – ranges and best guesses are ok for now.": "コストと利益を見積もりましょう。正確である必要はありません。現時点では範囲と最善の推測で十分です。",
        "Welcome to Execution Mode. Here you can track progress, assign owners, and manage blockers. Drag or update statuses to move initiatives forward.": "実行モードへようこそ。ここでは進捗の追跡、所有者の割り当て、ブロッキング要素の管理ができます。ドラッグまたはステータス更新でイニシアチブを進めてください。",
        "{companyName} has embarked on a strategic digital transformation journey. Based on the comprehensive DRD assessment, the organization demonstrates strong maturity in {strongest} ({strongestScore}/7), while facing significant challenges in {weakest} ({weakestScore}/7).\n\nTo address these gaps, a tailored roadmap consisting of {initCount} strategic initiatives has been developed. The plan focuses on building foundational capabilities in the first 12 months before scaling advanced digital solutions.\n\nFrom an economic perspective, the transformation is projected to generate an annual benefit of ${benefit}k against a total investment of ${cost}k. This yields an attractive ROI of {roi}% with a payback period of {payback} years.": "{companyName}は戦略的なデジタル変革の旅に乗り出しました。包括的なDRD評価に基づき、組織は{strongest} ({strongestScore}/7)で高い成熟度を示していますが、{weakest} ({weakestScore}/7)では重大な課題に直面しています。\n\nこれらのギャップに対処するため、{initCount}の戦略的イニシアチブからなるカスタマイズされたロードマップが策定されました。計画は、高度なデジタルソリューションを拡大する前の最初の12ヶ月間で、基礎的な能力を構築することに焦点を当てています。\n\n経済的な観点から見ると、変革は総投資額${cost}kに対して、年間${benefit}kの利益を生み出すと予測されています。これにより、回収期間{payback}年で{roi}%という魅力的なROIが得られます。",
        "{strongest} is your strongest asset, acting as a pillar for future growth.": "{strongest}はあなたの最強の資産であり、将来の成長の柱となります。",
        "{weakest} requires immediate attention to prevent bottlenecks in scaling.": "{weakest}はスケーリングのボトルネックを防ぐために、直ちに対処する必要があります。",
        "The organization is ready for {type} transformation.": "組織は{type}変革の準備ができています。",
        "aggressive": "積極的な",
        "focused": "集中した"
    }
    return translations.get(en_text, en_text + " (JA)")

with open('scripts/full_translations.json', 'r') as f:
    data = json.load(f)

def add_recursive(obj):
    if isinstance(obj, dict):
        if 'EN' in obj:
            if 'JA' not in obj:
                obj['JA'] = get_japanese_translation("", obj['EN'])
        else:
            for k, v in obj.items():
                add_recursive(v)
    elif isinstance(obj, list):
        for item in obj:
            add_recursive(item)

add_recursive(data)

with open('scripts/full_translations.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Added Japanese to scripts/full_translations.json")
