#!/bin/bash
# Consultify Local Setup Script
# This script helps set up the local development environment

set -e

echo "=========================================="
echo "Consultify - Local Environment Setup"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check prerequisites
echo "Checking prerequisites..."

# Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js is not installed${NC}"
    echo "Please install Node.js from https://nodejs.org/"
    exit 1
fi
echo -e "${GREEN}✓${NC} Node.js $(node -v)"

# npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}❌ npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓${NC} npm $(npm -v)"

# Check Node.js version
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${YELLOW}⚠️  Warning: Node.js version should be >= 18.x${NC}"
fi

echo ""

# Create .env.local if it doesn't exist
if [ ! -f ".env.local" ]; then
    echo "Creating .env.local file..."
    cat > .env.local << 'EOF'
# Consultify Environment Variables
# Generated by setup-local.sh

# Server Configuration
NODE_ENV=development
PORT=3005
FRONTEND_URL=http://localhost:3000

# Database Configuration
DB_TYPE=sqlite
SQLITE_PATH=./server/consultify.db

# Redis Configuration
REDIS_URL=redis://localhost:6379
MOCK_REDIS=false

# JWT & Security
JWT_SECRET=supersecretkey_change_this_in_production
JWT_EXPIRES_IN=7d
REFRESH_TOKEN_EXPIRES_IN=30d

# LLM Provider - REQUIRED
# Get your Gemini API key from: https://makersuite.google.com/app/apikey
GEMINI_API_KEY=your_gemini_api_key_here

# Optional: Other LLM Providers
# OPENAI_API_KEY=sk-your_openai_api_key_here
# ANTHROPIC_API_KEY=sk-ant-your_anthropic_api_key_here
EOF
    echo -e "${GREEN}✓${NC} Created .env.local"
    echo -e "${YELLOW}⚠️  Please edit .env.local and add your GEMINI_API_KEY${NC}"
else
    echo -e "${GREEN}✓${NC} .env.local already exists"
fi

echo ""

# Install dependencies
echo "Installing dependencies..."
echo ""

# Root dependencies
if [ ! -d "node_modules" ]; then
    echo "Installing root dependencies..."
    npm install
else
    echo -e "${GREEN}✓${NC} Root dependencies already installed"
fi

# Server dependencies
if [ -f "server/package.json" ]; then
    if [ ! -d "server/node_modules" ]; then
        echo "Installing server dependencies..."
        cd server
        npm install
        cd ..
    else
        echo -e "${GREEN}✓${NC} Server dependencies already installed"
    fi
fi

echo ""

# Check for required API keys
echo "Checking configuration..."

if grep -q "GEMINI_API_KEY=your_gemini_api_key_here" .env.local 2>/dev/null || \
   grep -q "GEMINI_API_KEY=$" .env.local 2>/dev/null || \
   ! grep -q "GEMINI_API_KEY=" .env.local 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Warning: GEMINI_API_KEY not configured${NC}"
    echo "   Get your API key from: https://makersuite.google.com/app/apikey"
    echo "   Edit .env.local and add your API key"
fi

# Check database directory
if grep -q "DB_TYPE=sqlite" .env.local 2>/dev/null; then
    DB_DIR=$(grep "SQLITE_PATH" .env.local | cut -d'=' -f2 | xargs dirname)
    if [ ! -d "$DB_DIR" ]; then
        mkdir -p "$DB_DIR"
        echo -e "${GREEN}✓${NC} Created database directory: $DB_DIR"
    fi
fi

echo ""
echo "=========================================="
echo -e "${GREEN}Setup Complete!${NC}"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Edit .env.local and add your GEMINI_API_KEY"
echo "2. (Optional) Start PostgreSQL and Redis if needed"
echo "3. Run: ./start.sh or npm run dev"
echo ""
echo "For detailed instructions, see LOCAL_SETUP.md"
echo ""






