export default EconomicsService;
declare namespace EconomicsService {
    namespace VALUE_TYPES {
        let COST_REDUCTION: string;
        let REVENUE_INCREASE: string;
        let RISK_REDUCTION: string;
        let EFFICIENCY: string;
        let STRATEGIC_OPTION: string;
    }
    function setDependencies(deps: any): void;
    function createAnalysis(data: any, organizationId: any, userId: any): Promise<{
        id: any;
        name: any;
        description: any;
        status: any;
        projectId: any;
        projectName: any;
        organizationId: any;
        createdBy: any;
        createdByName: any;
        overallScore: any;
        completionPercent: any;
        axisScores: any;
        importedFrom: any;
        importDate: any;
        createdAt: any;
        updatedAt: any;
        detailedScores: any;
    } | null>;
    function getAnalysisById(id: any, organizationId: any): Promise<{
        id: any;
        name: any;
        description: any;
        status: any;
        projectId: any;
        projectName: any;
        organizationId: any;
        createdBy: any;
        createdByName: any;
        overallScore: any;
        completionPercent: any;
        axisScores: any;
        importedFrom: any;
        importDate: any;
        createdAt: any;
        updatedAt: any;
        detailedScores: any;
    } | null>;
    function getAnalyses(organizationId: any, filters?: {}): Promise<{
        analyses: {
            id: any;
            name: any;
            description: any;
            status: any;
            projectId: any;
            projectName: any;
            organizationId: any;
            createdBy: any;
            createdByName: any;
            overallScore: any;
            completionPercent: any;
            axisScores: any;
            importedFrom: any;
            importDate: any;
            createdAt: any;
            updatedAt: any;
            detailedScores: any;
        }[];
        total: any;
        page: any;
        pageSize: any;
        totalPages: number;
    }>;
    function updateAnalysis(id: any, data: any, organizationId: any): Promise<{
        id: any;
        name: any;
        description: any;
        status: any;
        projectId: any;
        projectName: any;
        organizationId: any;
        createdBy: any;
        createdByName: any;
        overallScore: any;
        completionPercent: any;
        axisScores: any;
        importedFrom: any;
        importDate: any;
        createdAt: any;
        updatedAt: any;
        detailedScores: any;
    } | null>;
    function deleteAnalysis(id: any, organizationId: any): Promise<boolean>;
    function duplicateAnalysis(id: any, newName: any, organizationId: any, userId: any): Promise<{
        id: any;
        name: any;
        description: any;
        status: any;
        projectId: any;
        projectName: any;
        organizationId: any;
        createdBy: any;
        createdByName: any;
        overallScore: any;
        completionPercent: any;
        axisScores: any;
        importedFrom: any;
        importDate: any;
        createdAt: any;
        updatedAt: any;
        detailedScores: any;
    } | null>;
    function getAxisScores(analysisId: any): Promise<any[]>;
    function updateAxisScore(analysisId: any, scoreData: any, userId: any): Promise<boolean>;
    function bulkUpdateScores(analysisId: any, scores: any, organizationId: any, userId: any): Promise<{
        id: any;
        name: any;
        description: any;
        status: any;
        projectId: any;
        projectName: any;
        organizationId: any;
        createdBy: any;
        createdByName: any;
        overallScore: any;
        completionPercent: any;
        axisScores: any;
        importedFrom: any;
        importDate: any;
        createdAt: any;
        updatedAt: any;
        detailedScores: any;
    } | null>;
    function recalculateScores(analysisId: any, organizationId: any): Promise<void>;
    function getCatalogStats(organizationId: any): Promise<{
        total: any;
        draft: any;
        inProgress: any;
        completed: any;
        avgScore: number;
        avgCompletion: number;
    }>;
    function createComparison(data: any, organizationId: any, userId: any): Promise<any>;
    function getComparison(id: any, organizationId: any): Promise<any>;
    function recordExport(analysisId: any, exportType: any, filename: any, path: any, userId: any): Promise<{
        id: string;
        analysisId: any;
        exportType: any;
        filename: any;
    }>;
    function formatAnalysis(row: any): {
        id: any;
        name: any;
        description: any;
        status: any;
        projectId: any;
        projectName: any;
        organizationId: any;
        createdBy: any;
        createdByName: any;
        overallScore: any;
        completionPercent: any;
        axisScores: any;
        importedFrom: any;
        importDate: any;
        createdAt: any;
        updatedAt: any;
        detailedScores: any;
    };
    function createValueHypothesis(data: any): Promise<any>;
    function getValueHypotheses(projectId: any, initiativeId?: null): Promise<any>;
    function validateHypothesis(id: any, userId: any): Promise<any>;
    function addFinancialAssumption(data: any): Promise<any>;
    function detectMissingValueHypotheses(projectId: any): Promise<any>;
    function linkAnalysisToInitiative(analysisId: any, initiativeId: any, organizationId: any): Promise<{
        id: any;
        name: any;
        description: any;
        status: any;
        projectId: any;
        projectName: any;
        organizationId: any;
        createdBy: any;
        createdByName: any;
        overallScore: any;
        completionPercent: any;
        axisScores: any;
        importedFrom: any;
        importDate: any;
        createdAt: any;
        updatedAt: any;
        detailedScores: any;
    } | null>;
    function getAnalysisFinancials(analysisId: any, organizationId: any): Promise<{
        id: any;
        analysisId: any;
        costs: any;
        benefits: any;
        discountRate: any;
        investmentHorizon: any;
        createdAt: any;
        updatedAt: any;
    } | null>;
    function updateAnalysisFinancials(analysisId: any, data: any, organizationId: any, userId: any): Promise<{
        id: any;
        analysisId: any;
        costs: any;
        benefits: any;
        discountRate: any;
        investmentHorizon: any;
        createdAt: any;
        updatedAt: any;
    } | null>;
    function getAnalysisBenefits(analysisId: any, organizationId: any): Promise<{
        id: any;
        analysisId: any;
        trackingPeriod: any;
        plannedBenefits: any;
        actualBenefits: any;
        variance: any;
        trackedAt: any;
        createdBy: any;
    }[]>;
    function updateAnalysisBenefits(analysisId: any, data: any, organizationId: any, userId: any): Promise<{
        id: any;
        analysisId: any;
        trackingPeriod: any;
        plannedBenefits: any;
        actualBenefits: any;
        variance: any;
        trackedAt: any;
        createdBy: any;
    }[]>;
    function getAnalysisQualityAssessment(analysisId: any, organizationId: any): Promise<{
        analysisId: any;
        forecastAccuracy: null;
        methodologyScore: number;
        documentationScore: number;
        overallScore: number;
        assessedAt: string;
        computed: boolean;
        id?: undefined;
        assessedBy?: undefined;
    } | {
        id: any;
        analysisId: any;
        forecastAccuracy: any;
        methodologyScore: any;
        documentationScore: any;
        assessedAt: any;
        assessedBy: any;
        overallScore?: undefined;
        computed?: undefined;
    } | null>;
    function getValueSummary(projectId: any): Promise<any>;
}
//# sourceMappingURL=economicsService.d.ts.map