/**
 * Report Email Service
 * 
 * Handles sending management reports via email with PDF attachments.
 * Extends base EmailService with report-specific functionality.
 * 
 * PMO Standards: ISO 21500, PMBOK 7, PRINCE2
 */

import nodemailer from 'nodemailer';
import fs from 'fs';
import path from 'path';
import db from '../database.js';
import ManagementReportsService from './managementReportsService.js';

// Lazy load PDF generator to avoid circular dependencies
let PdfGeneratorService;
const getPdfGenerator = () => {
    if (!PdfGeneratorService) {
        try {
            PdfGeneratorService = require('./pdfGeneratorService');
        } catch (e) {
            console.warn('[ReportEmail] PDF Generator not available:', e.message);
        }
    }
    return PdfGeneratorService;
};

/**
 * Email templates for different report types
 */
const EmailTemplates = {
    TEAM_MEETING: {
        subject: (report) => `Team Meeting Report - ${report.title} (${report.periodEnd})`,
        html: (report, shareUrl) => `
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
                    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                    .header { background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; padding: 30px; border-radius: 12px 12px 0 0; }
                    .content { background: #f9fafb; padding: 30px; border: 1px solid #e5e7eb; border-top: none; }
                    .footer { background: #1e293b; color: #94a3b8; padding: 20px; text-align: center; font-size: 12px; border-radius: 0 0 12px 12px; }
                    .button { display: inline-block; background: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; margin: 10px 0; }
                    .status-box { background: white; padding: 15px; border-radius: 8px; margin: 15px 0; border-left: 4px solid #6366f1; }
                    .metric { display: inline-block; margin: 10px 20px 10px 0; }
                    .metric-value { font-size: 24px; font-weight: bold; color: #1e293b; }
                    .metric-label { font-size: 12px; color: #64748b; text-transform: uppercase; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1 style="margin: 0;">📊 Team Meeting Report</h1>
                        <p style="margin: 10px 0 0 0; opacity: 0.9;">${report.title}</p>
                        <p style="margin: 5px 0 0 0; opacity: 0.8; font-size: 14px;">Period: ${report.periodStart} to ${report.periodEnd}</p>
                    </div>
                    <div class="content">
                        <p>Hello,</p>
                        <p>A new Team Meeting Report has been generated and is attached to this email.</p>
                        
                        ${report.aiNarrative ? `
                        <div class="status-box">
                            <strong>AI Summary:</strong>
                            <p style="margin: 10px 0 0 0;">${report.aiNarrative}</p>
                        </div>
                        ` : ''}
                        
                        <div class="status-box">
                            <strong>Key Metrics:</strong>
                            <div style="margin-top: 10px;">
                                <div class="metric">
                                    <div class="metric-value">${report.content?.statusSummary?.tasksCompleted || 0}</div>
                                    <div class="metric-label">Tasks Completed</div>
                                </div>
                                <div class="metric">
                                    <div class="metric-value">${report.content?.statusSummary?.tasksInProgress || 0}</div>
                                    <div class="metric-label">In Progress</div>
                                </div>
                                <div class="metric">
                                    <div class="metric-value">${report.content?.blockers?.length || 0}</div>
                                    <div class="metric-label">Blockers</div>
                                </div>
                            </div>
                        </div>
                        
                        ${shareUrl ? `
                        <p>View the full report online:</p>
                        <a href="${shareUrl}" class="button">View Full Report</a>
                        ` : ''}
                        
                        <p style="margin-top: 20px; color: #64748b; font-size: 13px;">
                            This report was automatically generated by Consultify Management Reports.<br>
                            PMO Standards: ISO 21500:2021 | PMBOK 7 | PRINCE2 (Checkpoint Report)
                        </p>
                    </div>
                    <div class="footer">
                        <p>Generated by Consultify PMO System</p>
                        <p>© ${new Date().getFullYear()} Consultify. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
        `
    },
    STEERING_COMMITTEE: {
        subject: (report) => `Steering Committee Report - ${report.title} (${report.periodEnd})`,
        html: (report, shareUrl) => `
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
                    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                    .header { background: linear-gradient(135deg, #0f172a, #1e293b); color: white; padding: 30px; border-radius: 12px 12px 0 0; }
                    .content { background: #f9fafb; padding: 30px; border: 1px solid #e5e7eb; border-top: none; }
                    .footer { background: #1e293b; color: #94a3b8; padding: 20px; text-align: center; font-size: 12px; border-radius: 0 0 12px 12px; }
                    .button { display: inline-block; background: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; margin: 10px 0; }
                    .rag-status { padding: 20px; border-radius: 8px; margin: 15px 0; text-align: center; }
                    .rag-green { background: #dcfce7; color: #166534; border: 2px solid #22c55e; }
                    .rag-amber { background: #fef3c7; color: #92400e; border: 2px solid #f59e0b; }
                    .rag-red { background: #fee2e2; color: #991b1b; border: 2px solid #ef4444; }
                    .rag-grey { background: #f1f5f9; color: #475569; border: 2px solid #94a3b8; }
                    .executive-summary { background: white; padding: 20px; border-radius: 8px; margin: 15px 0; border-left: 4px solid #0f172a; }
                    .decisions-box { background: #fef3c7; padding: 15px; border-radius: 8px; margin: 15px 0; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1 style="margin: 0;">📋 Steering Committee Report</h1>
                        <p style="margin: 10px 0 0 0; opacity: 0.9;">${report.title}</p>
                        <p style="margin: 5px 0 0 0; opacity: 0.8; font-size: 14px;">Reporting Period: ${report.periodStart} to ${report.periodEnd}</p>
                    </div>
                    <div class="content">
                        <p>Dear Steering Committee Members,</p>
                        <p>Please find attached the latest status report for your review.</p>
                        
                        ${report.content?.overallStatus ? `
                        <div class="rag-status rag-${(report.content.overallStatus.overall || 'grey').toLowerCase()}">
                            <strong style="font-size: 18px;">Overall Status: ${report.content.overallStatus.overall || 'Unknown'}</strong>
                        </div>
                        ` : ''}
                        
                        ${report.content?.executiveSummary ? `
                        <div class="executive-summary">
                            <strong>Executive Summary:</strong>
                            <p style="margin: 10px 0 0 0;">${report.content.executiveSummary}</p>
                        </div>
                        ` : ''}
                        
                        ${report.content?.decisionsRequired?.length > 0 ? `
                        <div class="decisions-box">
                            <strong>⚠️ Decisions Required: ${report.content.decisionsRequired.length}</strong>
                            <ul style="margin: 10px 0 0 0; padding-left: 20px;">
                                ${report.content.decisionsRequired.slice(0, 3).map(d => `<li>${d.title || d.description}</li>`).join('')}
                                ${report.content.decisionsRequired.length > 3 ? `<li><em>+ ${report.content.decisionsRequired.length - 3} more...</em></li>` : ''}
                            </ul>
                        </div>
                        ` : ''}
                        
                        ${shareUrl ? `
                        <p>View the full report online:</p>
                        <a href="${shareUrl}" class="button">View Full Report</a>
                        ` : ''}
                        
                        <p style="margin-top: 20px; color: #64748b; font-size: 13px;">
                            This report was automatically generated by Consultify Management Reports.<br>
                            PMO Standards: ISO 21500:2021 | PMBOK 7 | PRINCE2 (Highlight Report)
                        </p>
                    </div>
                    <div class="footer">
                        <p>Generated by Consultify PMO System</p>
                        <p>© ${new Date().getFullYear()} Consultify. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
        `
    }
};

const ReportEmailService = {
    /**
     * Get SMTP transporter configuration
     */
    getTransporter: async () => {
        const settings = await new Promise((resolve) => {
            db.all("SELECT key, value FROM settings WHERE key LIKE 'smtp_%'", [], (err, rows) => {
                if (err || !rows) return resolve({});
                const s = {};
                rows.forEach(r => s[r.key] = r.value);
                resolve(s);
            });
        });

        const smtpConfig = {
            host: settings['smtp_host'] || process.env.SMTP_HOST,
            port: parseInt(settings['smtp_port'] || process.env.SMTP_PORT || '587'),
            secure: (settings['smtp_port'] || process.env.SMTP_PORT) === '465',
            auth: {
                user: settings['smtp_user'] || process.env.SMTP_USER,
                pass: settings['smtp_pass'] || process.env.SMTP_PASS
            }
        };

        const fromAddress = settings['smtp_from'] || process.env.SMTP_FROM || '"Consultify Reports" <reports@consultify.com>';

        if (!smtpConfig.host || !smtpConfig.auth.user) {
            console.log('[ReportEmail] SMTP not configured, emails will be logged only');
            return { transporter: null, from: fromAddress };
        }

        return {
            transporter: nodemailer.createTransport(smtpConfig),
            from: fromAddress
        };
    },

    /**
     * Send a management report to recipients
     * @param {string} reportId - Report ID to send
     * @param {string[]} recipients - Array of email addresses
     * @param {object} options - Additional options
     * @returns {Promise<object>} Result with success status
     */
    sendReport: async (reportId, recipients, options = {}) => {
        if (!reportId || !recipients || recipients.length === 0) {
            throw new Error('Report ID and at least one recipient required');
        }

        console.log(`[ReportEmail] Sending report ${reportId} to ${recipients.length} recipient(s)`);

        // Get report data
        const report = await ManagementReportsService.getReport(reportId);
        if (!report) {
            throw new Error('Report not found');
        }

        // Parse content if it's a string
        if (typeof report.content === 'string') {
            try {
                report.content = JSON.parse(report.content);
            } catch (e) {
                console.warn('[ReportEmail] Could not parse report content');
            }
        }

        // Generate PDF if not exists
        let pdfPath = report.pdf_path;
        if (!pdfPath || options.regeneratePdf) {
            const pdfGenerator = getPdfGenerator();
            if (pdfGenerator && pdfGenerator.generateManagementReportPDF) {
                try {
                    pdfPath = await pdfGenerator.generateManagementReportPDF(report, options.branding || {});
                    console.log(`[ReportEmail] Generated PDF: ${pdfPath}`);
                } catch (pdfErr) {
                    console.error('[ReportEmail] PDF generation failed:', pdfErr.message);
                }
            }
        }

        // Get email template
        const template = EmailTemplates[report.report_type] || EmailTemplates.TEAM_MEETING;
        const subject = template.subject(report);
        const html = template.html(report, options.shareUrl);

        // Prepare attachments
        const attachments = [];
        if (pdfPath) {
            const absolutePath = path.isAbsolute(pdfPath) ? pdfPath : path.join(__dirname, '../../', pdfPath);
            if (fs.existsSync(absolutePath)) {
                attachments.push({
                    filename: `${report.title.replace(/[^a-zA-Z0-9]/g, '_')}_${report.period_end}.pdf`,
                    path: absolutePath,
                    contentType: 'application/pdf'
                });
            }
        }

        // Get transporter
        const { transporter, from } = await ReportEmailService.getTransporter();

        // Send to each recipient
        const results = [];
        for (const to of recipients) {
            try {
                if (transporter) {
                    await transporter.sendMail({
                        from,
                        to,
                        subject,
                        html,
                        attachments
                    });
                    console.log(`[ReportEmail] Sent to ${to}`);
                    results.push({ email: to, success: true });
                } else {
                    // Log-only mode
                    console.log(`[ReportEmail] Would send to ${to}:`);
                    console.log(`  Subject: ${subject}`);
                    console.log(`  Attachments: ${attachments.length}`);
                    results.push({ email: to, success: true, mock: true });
                }
            } catch (err) {
                console.error(`[ReportEmail] Failed to send to ${to}:`, err.message);
                results.push({ email: to, success: false, error: err.message });
            }
        }

        // Log the send action
        await ReportEmailService._logEmailSent(reportId, recipients, results);

        return {
            success: results.every(r => r.success),
            results,
            pdfPath
        };
    },

    /**
     * Send report to all saved recipients
     * @param {string} reportId - Report ID
     * @param {object} options - Options
     */
    sendToRecipients: async (reportId, options = {}) => {
        // Get recipients from database
        const recipients = await new Promise((resolve, reject) => {
            db.all(
                `SELECT u.email FROM management_report_recipients rr
                 JOIN users u ON rr.user_id = u.id
                 WHERE rr.report_id = ?`,
                [reportId],
                (err, rows) => {
                    if (err) return reject(err);
                    resolve(rows.map(r => r.email));
                }
            );
        });

        if (recipients.length === 0) {
            console.log('[ReportEmail] No recipients configured for report');
            return { success: true, results: [], message: 'No recipients configured' };
        }

        return ReportEmailService.sendReport(reportId, recipients, options);
    },

    /**
     * Schedule a report email for later
     * @param {string} reportId - Report ID
     * @param {string[]} recipients - Recipients
     * @param {Date} scheduledTime - When to send
     */
    scheduleEmail: async (reportId, recipients, scheduledTime) => {
        const scheduleId = require('uuid').v4();
        
        await new Promise((resolve, reject) => {
            db.run(
                `INSERT INTO scheduled_emails (id, report_id, recipients, scheduled_time, status)
                 VALUES (?, ?, ?, ?, 'PENDING')`,
                [scheduleId, reportId, JSON.stringify(recipients), scheduledTime.toISOString()],
                (err) => err ? reject(err) : resolve()
            );
        });

        console.log(`[ReportEmail] Scheduled email ${scheduleId} for ${scheduledTime.toISOString()}`);
        return scheduleId;
    },

    /**
     * Process scheduled emails (called by cron)
     */
    processScheduledEmails: async () => {
        const now = new Date().toISOString();
        
        const pending = await new Promise((resolve, reject) => {
            db.all(
                `SELECT * FROM scheduled_emails 
                 WHERE status = 'PENDING' AND scheduled_time <= ?`,
                [now],
                (err, rows) => err ? reject(err) : resolve(rows || [])
            );
        });

        console.log(`[ReportEmail] Processing ${pending.length} scheduled emails`);

        for (const email of pending) {
            try {
                const recipients = JSON.parse(email.recipients);
                await ReportEmailService.sendReport(email.report_id, recipients);
                
                await new Promise((resolve, reject) => {
                    db.run(
                        `UPDATE scheduled_emails SET status = 'SENT', sent_at = CURRENT_TIMESTAMP WHERE id = ?`,
                        [email.id],
                        (err) => err ? reject(err) : resolve()
                    );
                });
            } catch (err) {
                console.error(`[ReportEmail] Failed to process scheduled email ${email.id}:`, err.message);
                await new Promise((resolve) => {
                    db.run(
                        `UPDATE scheduled_emails SET status = 'FAILED', error = ? WHERE id = ?`,
                        [err.message, email.id],
                        () => resolve()
                    );
                });
            }
        }

        return pending.length;
    },

    /**
     * Log email send action for audit
     */
    _logEmailSent: async (reportId, recipients, results) => {
        const logId = require('uuid').v4();
        await new Promise((resolve) => {
            db.run(
                `INSERT INTO email_log (id, report_id, recipients, results, sent_at)
                 VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)`,
                [logId, reportId, JSON.stringify(recipients), JSON.stringify(results)],
                () => resolve()
            );
        });
    }
};

export default ReportEmailService;






