-- Canonical targets referenced by the deterministic Statement mapping taxonomy.
-- Generic taxonomy only: no document, entity, filename, or checksum-specific data.
INSERT INTO financial_statement_lines
  (id, statement_type, line_code, line_name, line_name_pl, sort_order, is_system)
VALUES
  ('fsl-pl-revenue', 'P&L', 'REVENUE', 'Revenue', 'Revenue', 1000, TRUE),
  ('fsl-pl-cogs', 'P&L', 'COGS', 'Cogs', 'Cogs', 1001, TRUE),
  ('fsl-pl-gross', 'P&L', 'GROSS', 'Gross', 'Gross', 1002, TRUE),
  ('fsl-pl-selling', 'P&L', 'SELLING', 'Selling', 'Selling', 1003, TRUE),
  ('fsl-pl-gna', 'P&L', 'GNA', 'Gna', 'Gna', 1004, TRUE),
  ('fsl-pl-opex', 'P&L', 'OPEX', 'Opex', 'Opex', 1005, TRUE),
  ('fsl-pl-ebitda', 'P&L', 'EBITDA', 'Ebitda', 'Ebitda', 1006, TRUE),
  ('fsl-pl-ebit', 'P&L', 'EBIT', 'Ebit', 'Ebit', 1007, TRUE),
  ('fsl-pl-ebt', 'P&L', 'EBT', 'Ebt', 'Ebt', 1008, TRUE),
  ('fsl-pl-net', 'P&L', 'NET', 'Net', 'Net', 1009, TRUE),
  ('fsl-pl-interest', 'P&L', 'INTEREST', 'Interest', 'Interest', 1010, TRUE),
  ('fsl-pl-depreciation', 'P&L', 'DEPRECIATION', 'Depreciation', 'Depreciation', 1011, TRUE),
  ('fsl-pl-tax', 'P&L', 'TAX', 'Tax', 'Tax', 1012, TRUE),
  ('fsl-pl-tax-deferred', 'P&L', 'TAX_DEFERRED', 'Tax Deferred', 'Tax Deferred', 1013, TRUE),
  ('fsl-pl-tax-current', 'P&L', 'TAX_CURRENT', 'Tax Current', 'Tax Current', 1014, TRUE),
  ('fsl-pl-other-income', 'P&L', 'OTHER_INCOME', 'Other Income', 'Other Income', 1015, TRUE),
  ('fsl-pl-other-expense', 'P&L', 'OTHER_EXPENSE', 'Other Expense', 'Other Expense', 1016, TRUE),
  ('fsl-bs-total-assets', 'BS', 'TOTAL_ASSETS', 'Total Assets', 'Total Assets', 1017, TRUE),
  ('fsl-bs-fixed', 'BS', 'FIXED', 'Fixed', 'Fixed', 1018, TRUE),
  ('fsl-bs-intangibles', 'BS', 'INTANGIBLES', 'Intangibles', 'Intangibles', 1019, TRUE),
  ('fsl-bs-intangibles-goodwill', 'BS', 'INTANGIBLES_GOODWILL', 'Intangibles Goodwill', 'Intangibles Goodwill', 1020, TRUE),
  ('fsl-bs-ppe', 'BS', 'PPE', 'Ppe', 'Ppe', 1021, TRUE),
  ('fsl-bs-rou-assets', 'BS', 'ROU_ASSETS', 'Rou Assets', 'Rou Assets', 1022, TRUE),
  ('fsl-bs-investment-property', 'BS', 'INVESTMENT_PROPERTY', 'Investment Property', 'Investment Property', 1023, TRUE),
  ('fsl-bs-other-non-current-assets-deferred-tax', 'BS', 'OTHER_NON_CURRENT_ASSETS_DEFERRED_TAX', 'Other Non Current Assets Deferred Tax', 'Other Non Current Assets Deferred Tax', 1024, TRUE),
  ('fsl-bs-current-assets', 'BS', 'CURRENT_ASSETS', 'Current Assets', 'Current Assets', 1025, TRUE),
  ('fsl-bs-cash', 'BS', 'CASH', 'Cash', 'Cash', 1026, TRUE),
  ('fsl-bs-inventory', 'BS', 'INVENTORY', 'Inventory', 'Inventory', 1027, TRUE),
  ('fsl-bs-ar', 'BS', 'AR', 'Ar', 'Ar', 1028, TRUE),
  ('fsl-bs-ap', 'BS', 'AP', 'Ap', 'Ap', 1029, TRUE),
  ('fsl-bs-wc', 'BS', 'WC', 'Wc', 'Wc', 1030, TRUE),
  ('fsl-bs-total-liabilities', 'BS', 'TOTAL_LIABILITIES', 'Total Liabilities', 'Total Liabilities', 1031, TRUE),
  ('fsl-bs-current-liabilities', 'BS', 'CURRENT_LIABILITIES', 'Current Liabilities', 'Current Liabilities', 1032, TRUE),
  ('fsl-bs-long-term-debt', 'BS', 'LONG_TERM_DEBT', 'Long Term Debt', 'Long Term Debt', 1033, TRUE),
  ('fsl-bs-long-term-borrowings', 'BS', 'LONG_TERM_BORROWINGS', 'Long Term Borrowings', 'Long Term Borrowings', 1034, TRUE),
  ('fsl-bs-equity', 'BS', 'EQUITY', 'Equity', 'Equity', 1035, TRUE),
  ('fsl-bs-equity-parent', 'BS', 'EQUITY_PARENT', 'Equity Parent', 'Equity Parent', 1036, TRUE),
  ('fsl-bs-share-capital', 'BS', 'SHARE_CAPITAL', 'Share Capital', 'Share Capital', 1037, TRUE),
  ('fsl-bs-retained-earnings', 'BS', 'RETAINED_EARNINGS', 'Retained Earnings', 'Retained Earnings', 1038, TRUE),
  ('fsl-bs-provisions', 'BS', 'PROVISIONS', 'Provisions', 'Provisions', 1039, TRUE),
  ('fsl-bs-other-current-assets', 'BS', 'OTHER_CURRENT_ASSETS', 'Other Current Assets', 'Other Current Assets', 1040, TRUE),
  ('fsl-bs-other-st-receivables', 'BS', 'OTHER_ST_RECEIVABLES', 'Other St Receivables', 'Other St Receivables', 1041, TRUE),
  ('fsl-bs-other-current-financial-assets', 'BS', 'OTHER_CURRENT_FINANCIAL_ASSETS', 'Other Current Financial Assets', 'Other Current Financial Assets', 1042, TRUE),
  ('fsl-bs-other-current-assets-prepaids', 'BS', 'OTHER_CURRENT_ASSETS_PREPAIDS', 'Other Current Assets Prepaids', 'Other Current Assets Prepaids', 1043, TRUE),
  ('fsl-bs-lt-prepaids', 'BS', 'LT_PREPAIDS', 'Lt Prepaids', 'Lt Prepaids', 1044, TRUE),
  ('fsl-cf-change-wc-ar', 'CF', 'CHANGE_WC_AR', 'Change Wc Ar', 'Change Wc Ar', 1045, TRUE),
  ('fsl-cf-change-wc-inventory', 'CF', 'CHANGE_WC_INVENTORY', 'Change Wc Inventory', 'Change Wc Inventory', 1046, TRUE),
  ('fsl-cf-change-wc-ap', 'CF', 'CHANGE_WC_AP', 'Change Wc Ap', 'Change Wc Ap', 1047, TRUE),
  ('fsl-cf-operating', 'CF', 'OPERATING', 'Operating', 'Operating', 1048, TRUE),
  ('fsl-cf-investing', 'CF', 'INVESTING', 'Investing', 'Investing', 1049, TRUE),
  ('fsl-cf-financing', 'CF', 'FINANCING', 'Financing', 'Financing', 1050, TRUE),
  ('fsl-cf-capex', 'CF', 'CAPEX', 'Capex', 'Capex', 1051, TRUE),
  ('fsl-cf-fcf', 'CF', 'FCF', 'Fcf', 'Fcf', 1052, TRUE),
  ('fsl-cf-change-wc-provisions', 'CF', 'CHANGE_WC_PROVISIONS', 'Change Wc Provisions', 'Change Wc Provisions', 1053, TRUE),
  ('fsl-cf-change-wc-other', 'CF', 'CHANGE_WC_OTHER', 'Change Wc Other', 'Change Wc Other', 1054, TRUE),
  ('fsl-cf-operating-depreciation', 'CF', 'OPERATING_DEPRECIATION', 'Operating Depreciation', 'Operating Depreciation', 1055, TRUE),
  ('fsl-cf-operating-interest-cost', 'CF', 'OPERATING_INTEREST_COST', 'Operating Interest Cost', 'Operating Interest Cost', 1056, TRUE),
  ('fsl-cf-net-change-cash', 'CF', 'NET_CHANGE_CASH', 'Net Change Cash', 'Net Change Cash', 1057, TRUE),
  ('fsl-cf-opening-cash', 'CF', 'OPENING_CASH', 'Opening Cash', 'Opening Cash', 1058, TRUE),
  ('fsl-cf-closing-cash', 'CF', 'CLOSING_CASH', 'Closing Cash', 'Closing Cash', 1059, TRUE),
  ('fsl-bs-lt-receivables', 'BS', 'LT_RECEIVABLES', 'Lt Receivables', 'Lt Receivables', 1060, TRUE),
  ('fsl-bs-lt-financial-assets', 'BS', 'LT_FINANCIAL_ASSETS', 'Lt Financial Assets', 'Lt Financial Assets', 1061, TRUE),
  ('fsl-bs-equity-method-investments', 'BS', 'EQUITY_METHOD_INVESTMENTS', 'Equity Method Investments', 'Equity Method Investments', 1062, TRUE),
  ('fsl-bs-tax-receivables', 'BS', 'TAX_RECEIVABLES', 'Tax Receivables', 'Tax Receivables', 1063, TRUE),
  ('fsl-bs-other-tax-receivables', 'BS', 'OTHER_TAX_RECEIVABLES', 'Other Tax Receivables', 'Other Tax Receivables', 1064, TRUE),
  ('fsl-bs-contract-assets', 'BS', 'CONTRACT_ASSETS', 'Contract Assets', 'Contract Assets', 1065, TRUE),
  ('fsl-bs-assets-held-for-sale', 'BS', 'ASSETS_HELD_FOR_SALE', 'Assets Held For Sale', 'Assets Held For Sale', 1066, TRUE),
  ('fsl-bs-treasury-shares', 'BS', 'TREASURY_SHARES', 'Treasury Shares', 'Treasury Shares', 1067, TRUE),
  ('fsl-bs-other-equity-reserves', 'BS', 'OTHER_EQUITY_RESERVES', 'Other Equity Reserves', 'Other Equity Reserves', 1068, TRUE),
  ('fsl-bs-actuarial-reserve', 'BS', 'ACTUARIAL_RESERVE', 'Actuarial Reserve', 'Actuarial Reserve', 1069, TRUE),
  ('fsl-bs-minority-interest', 'BS', 'MINORITY_INTEREST', 'Minority Interest', 'Minority Interest', 1070, TRUE),
  ('fsl-bs-hedge-reserve', 'BS', 'HEDGE_RESERVE', 'Hedge Reserve', 'Hedge Reserve', 1071, TRUE),
  ('fsl-bs-fx-reserve', 'BS', 'FX_RESERVE', 'Fx Reserve', 'Fx Reserve', 1072, TRUE),
  ('fsl-bs-employee-benefits-lt', 'BS', 'EMPLOYEE_BENEFITS_LT', 'Employee Benefits Lt', 'Employee Benefits Lt', 1073, TRUE),
  ('fsl-bs-employee-benefits-st', 'BS', 'EMPLOYEE_BENEFITS_ST', 'Employee Benefits St', 'Employee Benefits St', 1074, TRUE),
  ('fsl-bs-contract-liabilities', 'BS', 'CONTRACT_LIABILITIES', 'Contract Liabilities', 'Contract Liabilities', 1075, TRUE),
  ('fsl-bs-other-non-current-liabilities-deferred-tax', 'BS', 'OTHER_NON_CURRENT_LIABILITIES_DEFERRED_TAX', 'Other Non Current Liabilities Deferred Tax', 'Other Non Current Liabilities Deferred Tax', 1076, TRUE),
  ('fsl-bs-total-liabilities-equity', 'BS', 'TOTAL_LIABILITIES_EQUITY', 'Total Liabilities Equity', 'Total Liabilities Equity', 1077, TRUE),
  ('fsl-bs-share-premium', 'BS', 'SHARE_PREMIUM', 'Share Premium', 'Share Premium', 1078, TRUE),
  ('fsl-bs-short-term-debt', 'BS', 'SHORT_TERM_DEBT', 'Short Term Debt', 'Short Term Debt', 1079, TRUE),
  ('fsl-bs-long-term-debt-lease', 'BS', 'LONG_TERM_DEBT_LEASE', 'Long Term Debt Lease', 'Long Term Debt Lease', 1080, TRUE),
  ('fsl-bs-short-term-debt-lease', 'BS', 'SHORT_TERM_DEBT_LEASE', 'Short Term Debt Lease', 'Short Term Debt Lease', 1081, TRUE),
  ('fsl-bs-other-current-liabilities', 'BS', 'OTHER_CURRENT_LIABILITIES', 'Other Current Liabilities', 'Other Current Liabilities', 1082, TRUE),
  ('fsl-bs-other-non-current-liabilities', 'BS', 'OTHER_NON_CURRENT_LIABILITIES', 'Other Non Current Liabilities', 'Other Non Current Liabilities', 1083, TRUE),
  ('fsl-bs-other-non-current-liabilities-provisions', 'BS', 'OTHER_NON_CURRENT_LIABILITIES_PROVISIONS', 'Other Non Current Liabilities Provisions', 'Other Non Current Liabilities Provisions', 1084, TRUE),
  ('fsl-bs-other-current-liabilities-tax', 'BS', 'OTHER_CURRENT_LIABILITIES_TAX', 'Other Current Liabilities Tax', 'Other Current Liabilities Tax', 1085, TRUE),
  ('fsl-bs-other-tax-payables', 'BS', 'OTHER_TAX_PAYABLES', 'Other Tax Payables', 'Other Tax Payables', 1086, TRUE),
  ('fsl-pl-net-parent', 'P&L', 'NET_PARENT', 'Net Parent', 'Net Parent', 1087, TRUE),
  ('fsl-pl-net-minority', 'P&L', 'NET_MINORITY', 'Net Minority', 'Net Minority', 1088, TRUE),
  ('fsl-pl-net-continuing', 'P&L', 'NET_CONTINUING', 'Net Continuing', 'Net Continuing', 1089, TRUE),
  ('fsl-pl-other-op-result', 'P&L', 'OTHER_OP_RESULT', 'Other Op Result', 'Other Op Result', 1090, TRUE),
  ('fsl-pl-other-op-income', 'P&L', 'OTHER_OP_INCOME', 'Other Op Income', 'Other Op Income', 1091, TRUE),
  ('fsl-pl-equity-method-income', 'P&L', 'EQUITY_METHOD_INCOME', 'Equity Method Income', 'Equity Method Income', 1092, TRUE),
  ('fsl-pl-fin-income', 'P&L', 'FIN_INCOME', 'Fin Income', 'Fin Income', 1093, TRUE),
  ('fsl-pl-fin-expense', 'P&L', 'FIN_EXPENSE', 'Fin Expense', 'Fin Expense', 1094, TRUE),
  ('fsl-pl-impairment-receivables', 'P&L', 'IMPAIRMENT_RECEIVABLES', 'Impairment Receivables', 'Impairment Receivables', 1095, TRUE),
  ('fsl-pl-oci-total', 'P&L', 'OCI_TOTAL', 'Oci Total', 'Oci Total', 1096, TRUE),
  ('fsl-pl-oci-reclassifiable', 'P&L', 'OCI_RECLASSIFIABLE', 'Oci Reclassifiable', 'Oci Reclassifiable', 1097, TRUE),
  ('fsl-pl-oci-non-reclassifiable', 'P&L', 'OCI_NON_RECLASSIFIABLE', 'Oci Non Reclassifiable', 'Oci Non Reclassifiable', 1098, TRUE),
  ('fsl-pl-oci-fx', 'P&L', 'OCI_FX', 'Oci Fx', 'Oci Fx', 1099, TRUE),
  ('fsl-pl-oci-hedge', 'P&L', 'OCI_HEDGE', 'Oci Hedge', 'Oci Hedge', 1100, TRUE),
  ('fsl-pl-oci-actuarial', 'P&L', 'OCI_ACTUARIAL', 'Oci Actuarial', 'Oci Actuarial', 1101, TRUE),
  ('fsl-pl-comprehensive-income', 'P&L', 'COMPREHENSIVE_INCOME', 'Comprehensive Income', 'Comprehensive Income', 1102, TRUE),
  ('fsl-pl-eps-basic', 'P&L', 'EPS_BASIC', 'Eps Basic', 'Eps Basic', 1103, TRUE),
  ('fsl-pl-eps-diluted', 'P&L', 'EPS_DILUTED', 'Eps Diluted', 'Eps Diluted', 1104, TRUE),
  ('fsl-pl-shares-outstanding', 'P&L', 'SHARES_OUTSTANDING', 'Shares Outstanding', 'Shares Outstanding', 1105, TRUE),
  ('fsl-cf-operating-depreciation-intangibles', 'CF', 'OPERATING_DEPRECIATION_INTANGIBLES', 'Operating Depreciation Intangibles', 'Operating Depreciation Intangibles', 1106, TRUE),
  ('fsl-cf-operating-depreciation-ppe', 'CF', 'OPERATING_DEPRECIATION_PPE', 'Operating Depreciation Ppe', 'Operating Depreciation Ppe', 1107, TRUE),
  ('fsl-cf-operating-depreciation-rou', 'CF', 'OPERATING_DEPRECIATION_ROU', 'Operating Depreciation Rou', 'Operating Depreciation Rou', 1108, TRUE),
  ('fsl-cf-operating-ebt', 'CF', 'OPERATING_EBT', 'Operating Ebt', 'Operating Ebt', 1109, TRUE),
  ('fsl-cf-operating-adjustments', 'CF', 'OPERATING_ADJUSTMENTS', 'Operating Adjustments', 'Operating Adjustments', 1110, TRUE),
  ('fsl-cf-operating-impairment', 'CF', 'OPERATING_IMPAIRMENT', 'Operating Impairment', 'Operating Impairment', 1111, TRUE),
  ('fsl-cf-operating-gain-disposal', 'CF', 'OPERATING_GAIN_DISPOSAL', 'Operating Gain Disposal', 'Operating Gain Disposal', 1112, TRUE),
  ('fsl-cf-operating-fv-changes', 'CF', 'OPERATING_FV_CHANGES', 'Operating Fv Changes', 'Operating Fv Changes', 1113, TRUE),
  ('fsl-cf-operating-fv-derivatives', 'CF', 'OPERATING_FV_DERIVATIVES', 'Operating Fv Derivatives', 'Operating Fv Derivatives', 1114, TRUE),
  ('fsl-cf-operating-dividend-income', 'CF', 'OPERATING_DIVIDEND_INCOME', 'Operating Dividend Income', 'Operating Dividend Income', 1115, TRUE),
  ('fsl-cf-dividends-received', 'CF', 'DIVIDENDS_RECEIVED', 'Dividends Received', 'Dividends Received', 1116, TRUE),
  ('fsl-cf-operating-other-adj', 'CF', 'OPERATING_OTHER_ADJ', 'Operating Other Adj', 'Operating Other Adj', 1117, TRUE),
  ('fsl-cf-operating-equity-method', 'CF', 'OPERATING_EQUITY_METHOD', 'Operating Equity Method', 'Operating Equity Method', 1118, TRUE),
  ('fsl-cf-operating-interest-income', 'CF', 'OPERATING_INTEREST_INCOME', 'Operating Interest Income', 'Operating Interest Income', 1119, TRUE),
  ('fsl-cf-operating-before-wc', 'CF', 'OPERATING_BEFORE_WC', 'Operating Before Wc', 'Operating Before Wc', 1120, TRUE),
  ('fsl-cf-operating-generated', 'CF', 'OPERATING_GENERATED', 'Operating Generated', 'Operating Generated', 1121, TRUE),
  ('fsl-cf-capex-intangibles', 'CF', 'CAPEX_INTANGIBLES', 'Capex Intangibles', 'Capex Intangibles', 1122, TRUE),
  ('fsl-cf-investing-disposal-proceeds', 'CF', 'INVESTING_DISPOSAL_PROCEEDS', 'Investing Disposal Proceeds', 'Investing Disposal Proceeds', 1123, TRUE),
  ('fsl-cf-fx-on-cash', 'CF', 'FX_ON_CASH', 'Fx On Cash', 'Fx On Cash', 1124, TRUE),
  ('fsl-cf-tax-refund', 'CF', 'TAX_REFUND', 'Tax Refund', 'Tax Refund', 1125, TRUE),
  ('fsl-cf-dividends', 'CF', 'DIVIDENDS', 'Dividends', 'Dividends', 1126, TRUE),
  ('fsl-cf-debt-drawdown', 'CF', 'DEBT_DRAWDOWN', 'Debt Drawdown', 'Debt Drawdown', 1127, TRUE),
  ('fsl-cf-debt-repayment', 'CF', 'DEBT_REPAYMENT', 'Debt Repayment', 'Debt Repayment', 1128, TRUE),
  ('fsl-cf-lease-repayment', 'CF', 'LEASE_REPAYMENT', 'Lease Repayment', 'Lease Repayment', 1129, TRUE),
  ('fsl-cf-taxes-paid', 'CF', 'TAXES_PAID', 'Taxes Paid', 'Taxes Paid', 1130, TRUE),
  ('fsl-cf-interest-paid', 'CF', 'INTEREST_PAID', 'Interest Paid', 'Interest Paid', 1131, TRUE),
  ('fsl-cf-other-expenditure', 'CF', 'OTHER_EXPENDITURE', 'Other Expenditure', 'Other Expenditure', 1132, TRUE),
  ('fsl-cf-other-receipts', 'CF', 'OTHER_RECEIPTS', 'Other Receipts', 'Other Receipts', 1133, TRUE),
  ('fsl-cf-investing-subsidiaries', 'CF', 'INVESTING_SUBSIDIARIES', 'Investing Subsidiaries', 'Investing Subsidiaries', 1134, TRUE),
  ('fsl-cf-change-wc-restricted-cash', 'CF', 'CHANGE_WC_RESTRICTED_CASH', 'Change Wc Restricted Cash', 'Change Wc Restricted Cash', 1135, TRUE),
  ('fsl-cf-change-wc-prepaids', 'CF', 'CHANGE_WC_PREPAIDS', 'Change Wc Prepaids', 'Change Wc Prepaids', 1136, TRUE),
  ('fsl-pl-revenue-product', 'P&L', 'REVENUE_PRODUCT', 'Revenue Product', 'Revenue Product', 1137, TRUE),
  ('fsl-pl-revenue-product-domestic', 'P&L', 'REVENUE_PRODUCT_DOMESTIC', 'Revenue Product Domestic', 'Revenue Product Domestic', 1138, TRUE),
  ('fsl-pl-revenue-product-export', 'P&L', 'REVENUE_PRODUCT_EXPORT', 'Revenue Product Export', 'Revenue Product Export', 1139, TRUE),
  ('fsl-pl-revenue-service', 'P&L', 'REVENUE_SERVICE', 'Revenue Service', 'Revenue Service', 1140, TRUE),
  ('fsl-pl-revenue-service-subscription', 'P&L', 'REVENUE_SERVICE_SUBSCRIPTION', 'Revenue Service Subscription', 'Revenue Service Subscription', 1141, TRUE),
  ('fsl-pl-revenue-service-projects', 'P&L', 'REVENUE_SERVICE_PROJECTS', 'Revenue Service Projects', 'Revenue Service Projects', 1142, TRUE),
  ('fsl-pl-revenue-other', 'P&L', 'REVENUE_OTHER', 'Revenue Other', 'Revenue Other', 1143, TRUE),
  ('fsl-pl-cogs-materials', 'P&L', 'COGS_MATERIALS', 'Cogs Materials', 'Cogs Materials', 1144, TRUE),
  ('fsl-pl-cogs-materials-raw', 'P&L', 'COGS_MATERIALS_RAW', 'Cogs Materials Raw', 'Cogs Materials Raw', 1145, TRUE),
  ('fsl-pl-cogs-materials-freight', 'P&L', 'COGS_MATERIALS_FREIGHT', 'Cogs Materials Freight', 'Cogs Materials Freight', 1146, TRUE),
  ('fsl-pl-cogs-labor', 'P&L', 'COGS_LABOR', 'Cogs Labor', 'Cogs Labor', 1147, TRUE),
  ('fsl-pl-cogs-labor-payroll', 'P&L', 'COGS_LABOR_PAYROLL', 'Cogs Labor Payroll', 'Cogs Labor Payroll', 1148, TRUE),
  ('fsl-pl-cogs-labor-contractors', 'P&L', 'COGS_LABOR_CONTRACTORS', 'Cogs Labor Contractors', 'Cogs Labor Contractors', 1149, TRUE),
  ('fsl-pl-cogs-other', 'P&L', 'COGS_OTHER', 'Cogs Other', 'Cogs Other', 1150, TRUE),
  ('fsl-pl-selling-marketing', 'P&L', 'SELLING_MARKETING', 'Selling Marketing', 'Selling Marketing', 1151, TRUE),
  ('fsl-pl-selling-logistics', 'P&L', 'SELLING_LOGISTICS', 'Selling Logistics', 'Selling Logistics', 1152, TRUE),
  ('fsl-pl-selling-commissions', 'P&L', 'SELLING_COMMISSIONS', 'Selling Commissions', 'Selling Commissions', 1153, TRUE),
  ('fsl-pl-gna-payroll', 'P&L', 'GNA_PAYROLL', 'Gna Payroll', 'Gna Payroll', 1154, TRUE),
  ('fsl-pl-gna-rent', 'P&L', 'GNA_RENT', 'Gna Rent', 'Gna Rent', 1155, TRUE),
  ('fsl-pl-gna-it', 'P&L', 'GNA_IT', 'Gna It', 'Gna It', 1156, TRUE),
  ('fsl-pl-gna-external', 'P&L', 'GNA_EXTERNAL', 'Gna External', 'Gna External', 1157, TRUE),
  ('fsl-pl-other-opex', 'P&L', 'OTHER_OPEX', 'Other Opex', 'Other Opex', 1158, TRUE),
  ('fsl-pl-other-opex-impairment', 'P&L', 'OTHER_OPEX_IMPAIRMENT', 'Other Opex Impairment', 'Other Opex Impairment', 1159, TRUE),
  ('fsl-pl-other-opex-provisions', 'P&L', 'OTHER_OPEX_PROVISIONS', 'Other Opex Provisions', 'Other Opex Provisions', 1160, TRUE),
  ('fsl-pl-depreciation-ppe', 'P&L', 'DEPRECIATION_PPE', 'Depreciation Ppe', 'Depreciation Ppe', 1161, TRUE),
  ('fsl-pl-depreciation-intangibles', 'P&L', 'DEPRECIATION_INTANGIBLES', 'Depreciation Intangibles', 'Depreciation Intangibles', 1162, TRUE),
  ('fsl-pl-interest-bank', 'P&L', 'INTEREST_BANK', 'Interest Bank', 'Interest Bank', 1163, TRUE),
  ('fsl-pl-interest-lease', 'P&L', 'INTEREST_LEASE', 'Interest Lease', 'Interest Lease', 1164, TRUE),
  ('fsl-pl-other-fin', 'P&L', 'OTHER_FIN', 'Other Fin', 'Other Fin', 1165, TRUE),
  ('fsl-bs-cash-operating', 'BS', 'CASH_OPERATING', 'Cash Operating', 'Cash Operating', 1166, TRUE),
  ('fsl-bs-cash-restricted', 'BS', 'CASH_RESTRICTED', 'Cash Restricted', 'Cash Restricted', 1167, TRUE),
  ('fsl-bs-ar-trade', 'BS', 'AR_TRADE', 'Ar Trade', 'Ar Trade', 1168, TRUE),
  ('fsl-bs-ar-other', 'BS', 'AR_OTHER', 'Ar Other', 'Ar Other', 1169, TRUE),
  ('fsl-bs-inventory-raw', 'BS', 'INVENTORY_RAW', 'Inventory Raw', 'Inventory Raw', 1170, TRUE),
  ('fsl-bs-inventory-wip', 'BS', 'INVENTORY_WIP', 'Inventory Wip', 'Inventory Wip', 1171, TRUE),
  ('fsl-bs-inventory-fg', 'BS', 'INVENTORY_FG', 'Inventory Fg', 'Inventory Fg', 1172, TRUE),
  ('fsl-bs-other-current-assets-vat', 'BS', 'OTHER_CURRENT_ASSETS_VAT', 'Other Current Assets Vat', 'Other Current Assets Vat', 1173, TRUE),
  ('fsl-bs-ppe-land', 'BS', 'PPE_LAND', 'Ppe Land', 'Ppe Land', 1174, TRUE),
  ('fsl-bs-ppe-machinery', 'BS', 'PPE_MACHINERY', 'Ppe Machinery', 'Ppe Machinery', 1175, TRUE),
  ('fsl-bs-ppe-vehicles', 'BS', 'PPE_VEHICLES', 'Ppe Vehicles', 'Ppe Vehicles', 1176, TRUE),
  ('fsl-bs-intangibles-software', 'BS', 'INTANGIBLES_SOFTWARE', 'Intangibles Software', 'Intangibles Software', 1177, TRUE),
  ('fsl-bs-other-non-current-assets', 'BS', 'OTHER_NON_CURRENT_ASSETS', 'Other Non Current Assets', 'Other Non Current Assets', 1178, TRUE),
  ('fsl-bs-ap-trade', 'BS', 'AP_TRADE', 'Ap Trade', 'Ap Trade', 1179, TRUE),
  ('fsl-bs-short-term-debt-bank', 'BS', 'SHORT_TERM_DEBT_BANK', 'Short Term Debt Bank', 'Short Term Debt Bank', 1180, TRUE),
  ('fsl-bs-other-current-liabilities-accruals', 'BS', 'OTHER_CURRENT_LIABILITIES_ACCRUALS', 'Other Current Liabilities Accruals', 'Other Current Liabilities Accruals', 1181, TRUE),
  ('fsl-bs-long-term-debt-bank', 'BS', 'LONG_TERM_DEBT_BANK', 'Long Term Debt Bank', 'Long Term Debt Bank', 1182, TRUE),
  ('fsl-bs-retained-earnings-prior', 'BS', 'RETAINED_EARNINGS_PRIOR', 'Retained Earnings Prior', 'Retained Earnings Prior', 1183, TRUE),
  ('fsl-bs-retained-earnings-current', 'BS', 'RETAINED_EARNINGS_CURRENT', 'Retained Earnings Current', 'Retained Earnings Current', 1184, TRUE),
  ('fsl-pl-cbn-inventory-change', 'P&L', 'CBN_INVENTORY_CHANGE', 'Cbn Inventory Change', 'Cbn Inventory Change', 1185, TRUE),
  ('fsl-pl-cbn-own-work-capitalised', 'P&L', 'CBN_OWN_WORK_CAPITALISED', 'Cbn Own Work Capitalised', 'Cbn Own Work Capitalised', 1186, TRUE),
  ('fsl-pl-cbn-materials-energy', 'P&L', 'CBN_MATERIALS_ENERGY', 'Cbn Materials Energy', 'Cbn Materials Energy', 1187, TRUE),
  ('fsl-pl-cbn-external-services', 'P&L', 'CBN_EXTERNAL_SERVICES', 'Cbn External Services', 'Cbn External Services', 1188, TRUE),
  ('fsl-pl-cbn-taxes-fees', 'P&L', 'CBN_TAXES_FEES', 'Cbn Taxes Fees', 'Cbn Taxes Fees', 1189, TRUE),
  ('fsl-pl-cbn-payroll', 'P&L', 'CBN_PAYROLL', 'Cbn Payroll', 'Cbn Payroll', 1190, TRUE),
  ('fsl-pl-cbn-social-security', 'P&L', 'CBN_SOCIAL_SECURITY', 'Cbn Social Security', 'Cbn Social Security', 1191, TRUE),
  ('fsl-pl-cbn-other-by-nature', 'P&L', 'CBN_OTHER_BY_NATURE', 'Cbn Other By Nature', 'Cbn Other By Nature', 1192, TRUE),
  ('fsl-pl-cbn-total-by-nature', 'P&L', 'CBN_TOTAL_BY_NATURE', 'Cbn Total By Nature', 'Cbn Total By Nature', 1193, TRUE),
  ('fsl-pl-cbn-operating-result', 'P&L', 'CBN_OPERATING_RESULT', 'Cbn Operating Result', 'Cbn Operating Result', 1194, TRUE),
  ('fsl-cf-operating-net-income', 'CF', 'OPERATING_NET_INCOME', 'Operating Net Income', 'Operating Net Income', 1195, TRUE),
  ('fsl-cf-change-wc', 'CF', 'CHANGE_WC', 'Change Wc', 'Change Wc', 1196, TRUE),
  ('fsl-cf-capex-maintenance', 'CF', 'CAPEX_MAINTENANCE', 'Capex Maintenance', 'Capex Maintenance', 1197, TRUE),
  ('fsl-cf-capex-growth', 'CF', 'CAPEX_GROWTH', 'Capex Growth', 'Capex Growth', 1198, TRUE),
  ('fsl-cf-other-investing', 'CF', 'OTHER_INVESTING', 'Other Investing', 'Other Investing', 1199, TRUE),
  ('fsl-cf-debt-drawdown-bank', 'CF', 'DEBT_DRAWDOWN_BANK', 'Debt Drawdown Bank', 'Debt Drawdown Bank', 1200, TRUE),
  ('fsl-cf-debt-drawdown-lease', 'CF', 'DEBT_DRAWDOWN_LEASE', 'Debt Drawdown Lease', 'Debt Drawdown Lease', 1201, TRUE),
  ('fsl-cf-debt-repayment-bank', 'CF', 'DEBT_REPAYMENT_BANK', 'Debt Repayment Bank', 'Debt Repayment Bank', 1202, TRUE),
  ('fsl-cf-debt-repayment-lease', 'CF', 'DEBT_REPAYMENT_LEASE', 'Debt Repayment Lease', 'Debt Repayment Lease', 1203, TRUE),
  ('fsl-cf-operating-sbc', 'CF', 'OPERATING_SBC', 'Operating Sbc', 'Operating Sbc', 1204, TRUE),
  ('fsl-cf-share-buyback', 'CF', 'SHARE_BUYBACK', 'Share Buyback', 'Share Buyback', 1205, TRUE),
  ('fsl-pl-rnd', 'P&L', 'RND', 'Rnd', 'Rnd', 1206, TRUE),
  ('fsl-pl-sga', 'P&L', 'SGA', 'Sga', 'Sga', 1207, TRUE),
  ('fsl-bs-st-investments', 'BS', 'ST_INVESTMENTS', 'St Investments', 'St Investments', 1208, TRUE),
  ('fsl-bs-deferred-revenue-current', 'BS', 'DEFERRED_REVENUE_CURRENT', 'Deferred Revenue Current', 'Deferred Revenue Current', 1209, TRUE),
  ('fsl-bs-deferred-revenue-non-current', 'BS', 'DEFERRED_REVENUE_NON_CURRENT', 'Deferred Revenue Non Current', 'Deferred Revenue Non Current', 1210, TRUE),
  ('fsl-bs-pension-surplus', 'BS', 'PENSION_SURPLUS', 'Pension Surplus', 'Pension Surplus', 1211, TRUE),
  ('fsl-bs-pension-deficit', 'BS', 'PENSION_DEFICIT', 'Pension Deficit', 'Pension Deficit', 1212, TRUE),
  ('fsl-cf-investing-acquisitions', 'CF', 'INVESTING_ACQUISITIONS', 'Investing Acquisitions', 'Investing Acquisitions', 1213, TRUE),
  ('fsl-cf-investing-securities', 'CF', 'INVESTING_SECURITIES', 'Investing Securities', 'Investing Securities', 1214, TRUE),
  ('fsl-cf-investing-jv', 'CF', 'INVESTING_JV', 'Investing Jv', 'Investing Jv', 1215, TRUE),
  ('fsl-cf-share-issuance', 'CF', 'SHARE_ISSUANCE', 'Share Issuance', 'Share Issuance', 1216, TRUE),
  ('fsl-cf-other-financing', 'CF', 'OTHER_FINANCING', 'Other Financing', 'Other Financing', 1217, TRUE),
  ('fsl-pl-comprehensive-income-parent', 'P&L', 'COMPREHENSIVE_INCOME_PARENT', 'Comprehensive Income Parent', 'Comprehensive Income Parent', 1218, TRUE),
  ('fsl-pl-total-revenue-and-income', 'P&L', 'TOTAL_REVENUE_AND_INCOME', 'Total Revenue And Income', 'Total Revenue And Income', 1219, TRUE),
  ('fsl-pl-production-costs', 'P&L', 'PRODUCTION_COSTS', 'Production Costs', 'Production Costs', 1220, TRUE),
  ('fsl-pl-gains-disposals', 'P&L', 'GAINS_DISPOSALS', 'Gains Disposals', 'Gains Disposals', 1221, TRUE),
  ('fsl-pl-revenue-segment', 'P&L', 'REVENUE_SEGMENT', 'Revenue Segment', 'Revenue Segment', 1222, TRUE),
  ('fsl-pl-cogs-segment', 'P&L', 'COGS_SEGMENT', 'Cogs Segment', 'Cogs Segment', 1223, TRUE),
  ('fsl-pl-oci-derivatives', 'P&L', 'OCI_DERIVATIVES', 'Oci Derivatives', 'Oci Derivatives', 1224, TRUE),
  ('fsl-pl-oci-pension-remeasurement', 'P&L', 'OCI_PENSION_REMEASUREMENT', 'Oci Pension Remeasurement', 'Oci Pension Remeasurement', 1225, TRUE),
  ('fsl-pl-financial-result-net', 'P&L', 'FINANCIAL_RESULT_NET', 'Financial Result Net', 'Financial Result Net', 1226, TRUE),
  ('fsl-bs-investments-associates', 'BS', 'INVESTMENTS_ASSOCIATES', 'Investments Associates', 'Investments Associates', 1227, TRUE),
  ('fsl-bs-current-tax-receivable', 'BS', 'CURRENT_TAX_RECEIVABLE', 'Current Tax Receivable', 'Current Tax Receivable', 1228, TRUE),
  ('fsl-bs-current-portion-ltd', 'BS', 'CURRENT_PORTION_LTD', 'Current Portion Ltd', 'Current Portion Ltd', 1229, TRUE),
  ('fsl-bs-marketable-securities', 'BS', 'MARKETABLE_SECURITIES', 'Marketable Securities', 'Marketable Securities', 1230, TRUE),
  ('fsl-bs-derivative-instruments', 'BS', 'DERIVATIVE_INSTRUMENTS', 'Derivative Instruments', 'Derivative Instruments', 1231, TRUE),
  ('fsl-bs-liabilities-held-for-sale', 'BS', 'LIABILITIES_HELD_FOR_SALE', 'Liabilities Held For Sale', 'Liabilities Held For Sale', 1232, TRUE),
  ('fsl-bs-other-provisions', 'BS', 'OTHER_PROVISIONS', 'Other Provisions', 'Other Provisions', 1233, TRUE),
  ('fsl-cf-investing-associates', 'CF', 'INVESTING_ASSOCIATES', 'Investing Associates', 'Investing Associates', 1234, TRUE),
  ('fsl-cf-investing-disposal-business', 'CF', 'INVESTING_DISPOSAL_BUSINESS', 'Investing Disposal Business', 'Investing Disposal Business', 1235, TRUE),
  ('fsl-cf-investing-disposal-investments', 'CF', 'INVESTING_DISPOSAL_INVESTMENTS', 'Investing Disposal Investments', 'Investing Disposal Investments', 1236, TRUE),
  ('fsl-cf-financing-short-term-debt', 'CF', 'FINANCING_SHORT_TERM_DEBT', 'Financing Short Term Debt', 'Financing Short Term Debt', 1237, TRUE),
  ('fsl-cf-financing-hybrid-bonds', 'CF', 'FINANCING_HYBRID_BONDS', 'Financing Hybrid Bonds', 'Financing Hybrid Bonds', 1238, TRUE),
  ('fsl-cf-dividends-minority', 'CF', 'DIVIDENDS_MINORITY', 'Dividends Minority', 'Dividends Minority', 1239, TRUE),
  ('fsl-cf-financing-nci', 'CF', 'FINANCING_NCI', 'Financing Nci', 'Financing Nci', 1240, TRUE),
  ('fsl-cf-operating-write-downs', 'CF', 'OPERATING_WRITE_DOWNS', 'Operating Write Downs', 'Operating Write Downs', 1241, TRUE),
  ('fsl-cf-investing-disposal-ppe', 'CF', 'INVESTING_DISPOSAL_PPE', 'Investing Disposal Ppe', 'Investing Disposal Ppe', 1242, TRUE),
  ('fsl-cf-investing-maturity-proceeds', 'CF', 'INVESTING_MATURITY_PROCEEDS', 'Investing Maturity Proceeds', 'Investing Maturity Proceeds', 1243, TRUE)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM financial_statement_lines
    WHERE id = ANY (ARRAY[
      'fsl-pl-revenue',
      'fsl-pl-cogs',
      'fsl-pl-gross',
      'fsl-pl-selling',
      'fsl-pl-gna',
      'fsl-pl-opex',
      'fsl-pl-ebitda',
      'fsl-pl-ebit',
      'fsl-pl-ebt',
      'fsl-pl-net',
      'fsl-pl-interest',
      'fsl-pl-depreciation',
      'fsl-pl-tax',
      'fsl-pl-tax-deferred',
      'fsl-pl-tax-current',
      'fsl-pl-other-income',
      'fsl-pl-other-expense',
      'fsl-bs-total-assets',
      'fsl-bs-fixed',
      'fsl-bs-intangibles',
      'fsl-bs-intangibles-goodwill',
      'fsl-bs-ppe',
      'fsl-bs-rou-assets',
      'fsl-bs-investment-property',
      'fsl-bs-other-non-current-assets-deferred-tax',
      'fsl-bs-current-assets',
      'fsl-bs-cash',
      'fsl-bs-inventory',
      'fsl-bs-ar',
      'fsl-bs-ap',
      'fsl-bs-wc',
      'fsl-bs-total-liabilities',
      'fsl-bs-current-liabilities',
      'fsl-bs-long-term-debt',
      'fsl-bs-long-term-borrowings',
      'fsl-bs-equity',
      'fsl-bs-equity-parent',
      'fsl-bs-share-capital',
      'fsl-bs-retained-earnings',
      'fsl-bs-provisions',
      'fsl-bs-other-current-assets',
      'fsl-bs-other-st-receivables',
      'fsl-bs-other-current-financial-assets',
      'fsl-bs-other-current-assets-prepaids',
      'fsl-bs-lt-prepaids',
      'fsl-cf-change-wc-ar',
      'fsl-cf-change-wc-inventory',
      'fsl-cf-change-wc-ap',
      'fsl-cf-operating',
      'fsl-cf-investing',
      'fsl-cf-financing',
      'fsl-cf-capex',
      'fsl-cf-fcf',
      'fsl-cf-change-wc-provisions',
      'fsl-cf-change-wc-other',
      'fsl-cf-operating-depreciation',
      'fsl-cf-operating-interest-cost',
      'fsl-cf-net-change-cash',
      'fsl-cf-opening-cash',
      'fsl-cf-closing-cash',
      'fsl-bs-lt-receivables',
      'fsl-bs-lt-financial-assets',
      'fsl-bs-equity-method-investments',
      'fsl-bs-tax-receivables',
      'fsl-bs-other-tax-receivables',
      'fsl-bs-contract-assets',
      'fsl-bs-assets-held-for-sale',
      'fsl-bs-treasury-shares',
      'fsl-bs-other-equity-reserves',
      'fsl-bs-actuarial-reserve',
      'fsl-bs-minority-interest',
      'fsl-bs-hedge-reserve',
      'fsl-bs-fx-reserve',
      'fsl-bs-employee-benefits-lt',
      'fsl-bs-employee-benefits-st',
      'fsl-bs-contract-liabilities',
      'fsl-bs-other-non-current-liabilities-deferred-tax',
      'fsl-bs-total-liabilities-equity',
      'fsl-bs-share-premium',
      'fsl-bs-short-term-debt',
      'fsl-bs-long-term-debt-lease',
      'fsl-bs-short-term-debt-lease',
      'fsl-bs-other-current-liabilities',
      'fsl-bs-other-non-current-liabilities',
      'fsl-bs-other-non-current-liabilities-provisions',
      'fsl-bs-other-current-liabilities-tax',
      'fsl-bs-other-tax-payables',
      'fsl-pl-net-parent',
      'fsl-pl-net-minority',
      'fsl-pl-net-continuing',
      'fsl-pl-other-op-result',
      'fsl-pl-other-op-income',
      'fsl-pl-equity-method-income',
      'fsl-pl-fin-income',
      'fsl-pl-fin-expense',
      'fsl-pl-impairment-receivables',
      'fsl-pl-oci-total',
      'fsl-pl-oci-reclassifiable',
      'fsl-pl-oci-non-reclassifiable',
      'fsl-pl-oci-fx',
      'fsl-pl-oci-hedge',
      'fsl-pl-oci-actuarial',
      'fsl-pl-comprehensive-income',
      'fsl-pl-eps-basic',
      'fsl-pl-eps-diluted',
      'fsl-pl-shares-outstanding',
      'fsl-cf-operating-depreciation-intangibles',
      'fsl-cf-operating-depreciation-ppe',
      'fsl-cf-operating-depreciation-rou',
      'fsl-cf-operating-ebt',
      'fsl-cf-operating-adjustments',
      'fsl-cf-operating-impairment',
      'fsl-cf-operating-gain-disposal',
      'fsl-cf-operating-fv-changes',
      'fsl-cf-operating-fv-derivatives',
      'fsl-cf-operating-dividend-income',
      'fsl-cf-dividends-received',
      'fsl-cf-operating-other-adj',
      'fsl-cf-operating-equity-method',
      'fsl-cf-operating-interest-income',
      'fsl-cf-operating-before-wc',
      'fsl-cf-operating-generated',
      'fsl-cf-capex-intangibles',
      'fsl-cf-investing-disposal-proceeds',
      'fsl-cf-fx-on-cash',
      'fsl-cf-tax-refund',
      'fsl-cf-dividends',
      'fsl-cf-debt-drawdown',
      'fsl-cf-debt-repayment',
      'fsl-cf-lease-repayment',
      'fsl-cf-taxes-paid',
      'fsl-cf-interest-paid',
      'fsl-cf-other-expenditure',
      'fsl-cf-other-receipts',
      'fsl-cf-investing-subsidiaries',
      'fsl-cf-change-wc-restricted-cash',
      'fsl-cf-change-wc-prepaids',
      'fsl-pl-revenue-product',
      'fsl-pl-revenue-product-domestic',
      'fsl-pl-revenue-product-export',
      'fsl-pl-revenue-service',
      'fsl-pl-revenue-service-subscription',
      'fsl-pl-revenue-service-projects',
      'fsl-pl-revenue-other',
      'fsl-pl-cogs-materials',
      'fsl-pl-cogs-materials-raw',
      'fsl-pl-cogs-materials-freight',
      'fsl-pl-cogs-labor',
      'fsl-pl-cogs-labor-payroll',
      'fsl-pl-cogs-labor-contractors',
      'fsl-pl-cogs-other',
      'fsl-pl-selling-marketing',
      'fsl-pl-selling-logistics',
      'fsl-pl-selling-commissions',
      'fsl-pl-gna-payroll',
      'fsl-pl-gna-rent',
      'fsl-pl-gna-it',
      'fsl-pl-gna-external',
      'fsl-pl-other-opex',
      'fsl-pl-other-opex-impairment',
      'fsl-pl-other-opex-provisions',
      'fsl-pl-depreciation-ppe',
      'fsl-pl-depreciation-intangibles',
      'fsl-pl-interest-bank',
      'fsl-pl-interest-lease',
      'fsl-pl-other-fin',
      'fsl-bs-cash-operating',
      'fsl-bs-cash-restricted',
      'fsl-bs-ar-trade',
      'fsl-bs-ar-other',
      'fsl-bs-inventory-raw',
      'fsl-bs-inventory-wip',
      'fsl-bs-inventory-fg',
      'fsl-bs-other-current-assets-vat',
      'fsl-bs-ppe-land',
      'fsl-bs-ppe-machinery',
      'fsl-bs-ppe-vehicles',
      'fsl-bs-intangibles-software',
      'fsl-bs-other-non-current-assets',
      'fsl-bs-ap-trade',
      'fsl-bs-short-term-debt-bank',
      'fsl-bs-other-current-liabilities-accruals',
      'fsl-bs-long-term-debt-bank',
      'fsl-bs-retained-earnings-prior',
      'fsl-bs-retained-earnings-current',
      'fsl-pl-cbn-inventory-change',
      'fsl-pl-cbn-own-work-capitalised',
      'fsl-pl-cbn-materials-energy',
      'fsl-pl-cbn-external-services',
      'fsl-pl-cbn-taxes-fees',
      'fsl-pl-cbn-payroll',
      'fsl-pl-cbn-social-security',
      'fsl-pl-cbn-other-by-nature',
      'fsl-pl-cbn-total-by-nature',
      'fsl-pl-cbn-operating-result',
      'fsl-cf-operating-net-income',
      'fsl-cf-change-wc',
      'fsl-cf-capex-maintenance',
      'fsl-cf-capex-growth',
      'fsl-cf-other-investing',
      'fsl-cf-debt-drawdown-bank',
      'fsl-cf-debt-drawdown-lease',
      'fsl-cf-debt-repayment-bank',
      'fsl-cf-debt-repayment-lease',
      'fsl-cf-operating-sbc',
      'fsl-cf-share-buyback',
      'fsl-pl-rnd',
      'fsl-pl-sga',
      'fsl-bs-st-investments',
      'fsl-bs-deferred-revenue-current',
      'fsl-bs-deferred-revenue-non-current',
      'fsl-bs-pension-surplus',
      'fsl-bs-pension-deficit',
      'fsl-cf-investing-acquisitions',
      'fsl-cf-investing-securities',
      'fsl-cf-investing-jv',
      'fsl-cf-share-issuance',
      'fsl-cf-other-financing',
      'fsl-pl-comprehensive-income-parent',
      'fsl-pl-total-revenue-and-income',
      'fsl-pl-production-costs',
      'fsl-pl-gains-disposals',
      'fsl-pl-revenue-segment',
      'fsl-pl-cogs-segment',
      'fsl-pl-oci-derivatives',
      'fsl-pl-oci-pension-remeasurement',
      'fsl-pl-financial-result-net',
      'fsl-bs-investments-associates',
      'fsl-bs-current-tax-receivable',
      'fsl-bs-current-portion-ltd',
      'fsl-bs-marketable-securities',
      'fsl-bs-derivative-instruments',
      'fsl-bs-liabilities-held-for-sale',
      'fsl-bs-other-provisions',
      'fsl-cf-investing-associates',
      'fsl-cf-investing-disposal-business',
      'fsl-cf-investing-disposal-investments',
      'fsl-cf-financing-short-term-debt',
      'fsl-cf-financing-hybrid-bonds',
      'fsl-cf-dividends-minority',
      'fsl-cf-financing-nci',
      'fsl-cf-operating-write-downs',
      'fsl-cf-investing-disposal-ppe',
      'fsl-cf-investing-maturity-proceeds'
    ]::text[])
      AND (statement_type <> CASE
        WHEN id LIKE 'fsl-pl-%' THEN 'P&L'
        WHEN id LIKE 'fsl-bs-%' THEN 'BS'
        WHEN id LIKE 'fsl-cf-%' THEN 'CF'
        ELSE statement_type END
        OR COALESCE(is_system, FALSE) IS NOT TRUE
        OR organization_id IS NOT NULL)
  ) THEN
    RAISE EXCEPTION 'Finance Statement canonical mapping taxonomy collides with a foreign or incompatible definition';
  END IF;
END $$;

