import { ACCEPTANCE_NAMESPACE, stableTextId, stableUuid, type FixtureContext, type FixtureStatement } from './fixturePlan.js';

const s=(domain:string,sql:string,params:unknown[],table:string,key:string,id:string,org:string):FixtureStatement=>({domain,sql,params,verifySql:`SELECT count(*)::int count FROM ${table} WHERE ${key}=$1 AND organization_id=$2`,verifyParams:[id,org]});

export function buildGoldenChildPlan(c:FixtureContext):FixtureStatement[]{
  const kpi=stableUuid(c,'kpi'), kv=stableUuid(c,'kpi-version'), km=stableUuid(c,'kpi-measurement');
  const roi=stableUuid(c,'roi'), baseline=stableUuid(c,'roi-baseline'), pir=stableUuid(c,'roi-pir');
  const roiAssumption=stableUuid(c,'roi-assumption-adoption'), roiCostOne=stableUuid(c,'roi-cost-implementation'), roiCostRecurring=stableUuid(c,'roi-cost-governance');
  const roiBenefitOne=stableUuid(c,'roi-benefit-productivity'), roiBenefitTwo=stableUuid(c,'roi-benefit-quality'), roiDownside=stableUuid(c,'roi-scenario-downside'), roiUpside=stableUuid(c,'roi-scenario-upside'), roiRun=stableUuid(c,'roi-calculation-run');
  const program=stableUuid(c,'okr-program'), policy=stableUuid(c,'okr-policy'), cycle=stableUuid(c,'okr-cycle'), set=stableUuid(c,'okr-set'), objective=stableUuid(c,'okr-objective'), kr=stableUuid(c,'okr-kr'), occurrence=stableUuid(c,'okr-occurrence'), checkin=stableUuid(c,'okr-checkin');
  const idea=stableTextId(c,'idea'), map=stableTextId(c,'idea-map'), bc=stableTextId(c,'idea-business-case'), fc=stableTextId(c,'idea-financial-case');
  const workbook=stableTextId(c,'artifact-workbook'), workbookV=stableTextId(c,'artifact-workbook-v1'), docApproval=stableTextId(c,'document-approval');
  const deck=stableTextId(c,'artifact-presentation'), deckOrigin=stableTextId(c,'artifact-presentation-origin'), workbookOrigin=stableTextId(c,'artifact-workbook-origin');
  const deviation=stableUuid(c,'kpi-deviation'), scorecard=stableUuid(c,'kpi-scorecard'), valuation=stableTextId(c,'finance-valuation-case'), docVersion=stableTextId(c,'document-version-v1');
  const initiative=stableTextId(c,'initiative'), executionCase=stableTextId(c,'execution-case'), handoff=stableTextId(c,'handoff-package'), executionTask=stableTextId(c,'execution-task'), executionMilestone=stableTextId(c,'execution-milestone');
  const kpiPolicy=stableUuid(c,'visibility-policy-kpi'), roiPolicy=stableUuid(c,'visibility-policy-roi'), okrPolicy=stableUuid(c,'visibility-policy-okr');
  const workbookSchema={title:'Model realizacji korzyści',description:'Plan, wykonanie i dowody korzyści w jednym modelu zarządczym.',sheets:[
    {name:'Podsumowanie',purpose:'Jednokartkowy przegląd wartości i realizacji.',columns:[{key:'metric',header:'Wskaźnik',type:'text',width:34},{key:'actual',header:'Wynik',type:'number',width:18},{key:'target',header:'Cel',type:'number',width:18},{key:'status',header:'Status',type:'text',width:20}],rows:[
      {cells:{metric:{value:'Zweryfikowana realizacja korzyści'},actual:{value:0.76,style:{numberFormat:'0%'}},target:{value:0.90,style:{numberFormat:'0%'}},status:{value:'Wymaga uwagi'}}},
      {cells:{metric:{value:'NPV programu (PLN)'},actual:{value:612000,style:{numberFormat:'#,##0 "PLN"'}},target:{value:500000,style:{numberFormat:'#,##0 "PLN"'}},status:{value:'Powyżej celu'}}},
      {cells:{metric:{value:'IRR'},actual:{value:0.314,style:{numberFormat:'0.0%'}},target:{value:0.20,style:{numberFormat:'0.0%'}},status:{value:'Powyżej celu'}}},
      {cells:{metric:{value:'Okres zwrotu (miesiące)'},actual:{value:7.8},target:{value:9},status:{value:'W normie'}}}
    ],freezeRow:1,autoFilter:true,showGridLines:true},
    {name:'Dowody',purpose:'Źródła potwierdzające wartości i decyzje.',columns:[{key:'evidence',header:'Dowód',type:'text',width:38},{key:'source',header:'Źródło',type:'text',width:28},{key:'status',header:'Weryfikacja',type:'text',width:18},{key:'owner',header:'Właściciel',type:'text',width:24}],rows:[
      {cells:{evidence:{value:'Pomiar KPI 76%'},source:{value:'Results / KPI'},status:{value:'Zweryfikowany'},owner:{value:'Piotr Wiśniewski'}}},
      {cells:{evidence:{value:'Kalkulacja NPV 612 tys. PLN'},source:{value:'Results / ROI'},status:{value:'Zweryfikowana'},owner:{value:'Finance'}}},
      {cells:{evidence:{value:'Plan zamknięcia luki realizacji'},source:{value:'Execution'},status:{value:'W realizacji'},owner:{value:'Piotr Wiśniewski'}}}
    ],freezeRow:1,autoFilter:true,showGridLines:true}
  ],metadata:{marker:ACCEPTANCE_NAMESPACE,currency:'PLN',asOf:'2026-08-13'}};
  const visibility=(domain:string,resourceType:string,resourceId:string,policyId:string):FixtureStatement=>({
    domain:`${domain}-visibility`,
    sql:`INSERT INTO rvn_platform_resource_visibility (resource_type,resource_id,organization_id,visibility_mode,policy_id,owner_user_id) VALUES ($1,$2,$3,'OPEN_ORG',$4,$5) ON CONFLICT (resource_type,resource_id) DO UPDATE SET visibility_mode='OPEN_ORG',policy_id=EXCLUDED.policy_id,owner_user_id=EXCLUDED.owner_user_id WHERE rvn_platform_resource_visibility.organization_id=EXCLUDED.organization_id`,
    params:[resourceType,resourceId,c.organizationId,policyId,c.userId],
    verifySql:`SELECT count(*)::int count FROM rvn_platform_resource_visibility WHERE resource_id=$1 AND organization_id=$2 AND resource_type='${resourceType}' AND visibility_mode='OPEN_ORG'`,
    verifyParams:[resourceId,c.organizationId],
  });
  return [
    s('kpi-visibility-policy',`INSERT INTO rvn_platform_visibility_policies (policy_id,organization_id,domain,policy_version,visibility_mode,allow_narrowing_only,is_active,created_by) VALUES ($1,$2,'kpi',1,'OPEN_ORG',true,true,$3) ON CONFLICT (policy_id) DO UPDATE SET visibility_mode='OPEN_ORG',is_active=true`,[kpiPolicy,c.organizationId,c.userId],'rvn_platform_visibility_policies','policy_id',kpiPolicy,c.organizationId),
    s('roi-visibility-policy',`INSERT INTO rvn_platform_visibility_policies (policy_id,organization_id,domain,policy_version,visibility_mode,allow_narrowing_only,is_active,created_by) VALUES ($1,$2,'roi',1,'OPEN_ORG',true,true,$3) ON CONFLICT (policy_id) DO UPDATE SET visibility_mode='OPEN_ORG',is_active=true`,[roiPolicy,c.organizationId,c.userId],'rvn_platform_visibility_policies','policy_id',roiPolicy,c.organizationId),
    s('okr-visibility-policy',`INSERT INTO rvn_platform_visibility_policies (policy_id,organization_id,domain,policy_version,visibility_mode,allow_narrowing_only,is_active,created_by) VALUES ($1,$2,'okr',1,'OPEN_ORG',true,true,$3) ON CONFLICT (policy_id) DO UPDATE SET visibility_mode='OPEN_ORG',is_active=true`,[okrPolicy,c.organizationId,c.userId],'rvn_platform_visibility_policies','policy_id',okrPolicy,c.organizationId),
    s('kpi-version',`INSERT INTO rvn_kpi_definition_versions (definition_version_id,kpi_id,organization_id,version_number,name,unit,target_geometry,target_value,warning_low,critical_low,approval_status,effective_from,approved_by,approved_at,created_by) VALUES ($1,$2,$3,1,$4,'%','threshold_min',90,80,70,'approved',now(),$5,now(),$5) ON CONFLICT (definition_version_id) DO NOTHING`,[kv,kpi,c.organizationId,'Realizacja zweryfikowanych korzyści',c.userId],'rvn_kpi_definition_versions','definition_version_id',kv,c.organizationId),
    s('kpi-measurement',`INSERT INTO rvn_kpi_measurements (measurement_id,kpi_id,definition_version_id,organization_id,period_start,period_end,actual_value,performance_status,data_quality_status,source,recorded_by) VALUES ($1,$2,$3,$4,CURRENT_DATE-30,CURRENT_DATE,76,'warning','verified','acceptance_fixture',$5) ON CONFLICT (measurement_id) DO NOTHING`,[km,kpi,kv,c.organizationId,c.userId],'rvn_kpi_measurements','measurement_id',km,c.organizationId),
    s('kpi-deviation',`INSERT INTO rvn_kpi_deviation_cases (case_id,organization_id,kpi_id,trigger_measurement_id,severity,status,owner_user_id,root_cause_summary,expected_recovery_date,expected_recovery_value,created_by) VALUES ($1,$2,$3,$4,'warning','plan_required',$5,'Adopcja rozwiązania pozostaje poniżej założonego poziomu.',CURRENT_DATE+30,90,$5) ON CONFLICT (case_id) DO UPDATE SET root_cause_summary=EXCLUDED.root_cause_summary WHERE rvn_kpi_deviation_cases.organization_id=EXCLUDED.organization_id`,[deviation,c.organizationId,kpi,km,c.userId],'rvn_kpi_deviation_cases','case_id',deviation,c.organizationId),
    s('kpi-scorecard',`INSERT INTO rvn_kpi_scorecards (scorecard_id,organization_id,name,description,scope_type,scope_id,owner_user_id,review_frequency,lifecycle_status,created_by) VALUES ($1,$2,'Karta wyników transformacji',$3,'organization',$2,$4,'monthly','active',$4) ON CONFLICT (scorecard_id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description WHERE rvn_kpi_scorecards.organization_id=EXCLUDED.organization_id`,[scorecard,c.organizationId,'Miesięczny przegląd realizacji wartości programu.',c.userId],'rvn_kpi_scorecards','scorecard_id',scorecard,c.organizationId),
    visibility('kpi','kpi',kpi,kpiPolicy),
    visibility('kpi-scorecard','kpi_scorecard',scorecard,kpiPolicy),
    s('roi-baseline',`INSERT INTO rvn_roi_baselines (baseline_id,case_id,organization_id,baseline_period_start,baseline_period_end,current_measured_value,current_measured_unit,current_measured_as_of,bau_projection_method,confidence,owner_user_id,created_by) VALUES ($1,$2,$3,CURRENT_DATE-365,CURRENT_DATE,100,'index',CURRENT_DATE,'flat','high',$4,$4) ON CONFLICT (baseline_id) DO NOTHING`,[baseline,roi,c.organizationId,c.userId],'rvn_roi_baselines','baseline_id',baseline,c.organizationId),
    s('roi-assumption',`INSERT INTO rvn_roi_assumptions (assumption_id,case_id,organization_id,category,label,unit,base_value,downside_value,upside_value,confidence,evidence_ref,source,owner_user_id,sensitivity_rank,notes,created_by) VALUES ($1,$2,$3,'adoption','Adopcja nowego sposobu pracy','%',75,55,90,'medium',$4,'Zweryfikowane dane pilotażowe',$5,1,'Mierzona miesięcznie w portfelu inicjatyw.',$5) ON CONFLICT (assumption_id) DO NOTHING`,[roiAssumption,roi,c.organizationId,`${ACCEPTANCE_NAMESPACE}:roi-adoption`,c.userId],'rvn_roi_assumptions','assumption_id',roiAssumption,c.organizationId),
    s('roi-cost-implementation',`INSERT INTO rvn_roi_cost_lines (cost_line_id,case_id,organization_id,category,label,description,amount,currency,timing_type,one_time_period_date,confidence,source,owner_user_id,created_by) VALUES ($1,$2,$3,'implementation','Wdrożenie programu i integracja danych','Konfiguracja rozwiązania, migracja danych i przygotowanie zespołu.',500000,'PLN','one_time',CURRENT_DATE+14,'high','Zatwierdzony budżet programu',$4,$4) ON CONFLICT (cost_line_id) DO NOTHING`,[roiCostOne,roi,c.organizationId,c.userId],'rvn_roi_cost_lines','cost_line_id',roiCostOne,c.organizationId),
    s('roi-cost-governance',`INSERT INTO rvn_roi_cost_lines (cost_line_id,case_id,organization_id,category,label,description,amount,currency,timing_type,recurrence_start_date,recurrence_end_date,recurrence_cadence,confidence,source,owner_user_id,created_by) VALUES ($1,$2,$3,'operations','Miesięczny przegląd korzyści','Utrzymanie jakości danych, przegląd KPI i działania korygujące.',30000,'PLN','recurring',CURRENT_DATE,CURRENT_DATE+365,'monthly','high','Plan operacyjny programu',$4,$4) ON CONFLICT (cost_line_id) DO NOTHING`,[roiCostRecurring,roi,c.organizationId,c.userId],'rvn_roi_cost_lines','cost_line_id',roiCostRecurring,c.organizationId),
    s('roi-benefit-productivity',`INSERT INTO rvn_roi_benefit_lines (benefit_line_id,case_id,organization_id,category,label,description,is_financial,amount,currency,timing_type,recurrence_start_date,recurrence_end_date,recurrence_cadence,ramp_periods,confidence,source,owner_user_id,created_by) VALUES ($1,$2,$3,'productivity','Odzyskana produktywność zespołów','Mniej czasu na ręczne uzgadnianie statusów i przygotowanie raportów.',true,105000,'PLN','recurring',CURRENT_DATE,CURRENT_DATE+365,'monthly',3,'medium','Model czasu pracy i dane pilotażowe',$4,$4) ON CONFLICT (benefit_line_id) DO NOTHING`,[roiBenefitOne,roi,c.organizationId,c.userId],'rvn_roi_benefit_lines','benefit_line_id',roiBenefitOne,c.organizationId),
    s('roi-benefit-quality',`INSERT INTO rvn_roi_benefit_lines (benefit_line_id,case_id,organization_id,category,label,description,is_financial,amount,currency,timing_type,one_time_period_date,confidence,source,owner_user_id,created_by) VALUES ($1,$2,$3,'quality','Ograniczenie strat z opóźnionych decyzji','Wartość unikniętych opóźnień dzięki wcześniejszym sygnałom ryzyka.',true,420000,'PLN','one_time',CURRENT_DATE+365,'medium','Rejestr decyzji i analiza opóźnień',$4,$4) ON CONFLICT (benefit_line_id) DO NOTHING`,[roiBenefitTwo,roi,c.organizationId,c.userId],'rvn_roi_benefit_lines','benefit_line_id',roiBenefitTwo,c.organizationId),
    s('roi-scenario-downside',`INSERT INTO rvn_roi_scenarios (scenario_id,case_id,organization_id,scenario_type,label,description,created_by) VALUES ($1,$2,$3,'downside','Ostrożny','Wolniejsza adopcja i przesunięcie realizacji korzyści o jeden kwartał.',$4) ON CONFLICT (scenario_id) DO NOTHING`,[roiDownside,roi,c.organizationId,c.userId],'rvn_roi_scenarios','scenario_id',roiDownside,c.organizationId),
    s('roi-scenario-upside',`INSERT INTO rvn_roi_scenarios (scenario_id,case_id,organization_id,scenario_type,label,description,created_by) VALUES ($1,$2,$3,'upside','Przyspieszony','Szybsza adopcja i pełna realizacja korzyści od trzeciego miesiąca.',$4) ON CONFLICT (scenario_id) DO NOTHING`,[roiUpside,roi,c.organizationId,c.userId],'rvn_roi_scenarios','scenario_id',roiUpside,c.organizationId),
    s('roi-calculation-run',`INSERT INTO rvn_roi_calculation_runs (run_id,case_id,organization_id,engine_version,policy_version_stamp,status,input_snapshot,input_hash,total_costs,total_financial_benefits,simple_roi,npv,irr_pct,irr_status,payback_periods,discounted_payback_periods,benefit_cost_ratio,period_series,validation_findings,warnings,initiated_by) VALUES ($1,$2,$3,'acceptance-1.0','monthly-pln-v1','completed',$4::jsonb,$5,860000,1680000,0.9535,612000,31.4,'computed',7.8,8.6,1.9535,$6::jsonb,'[]'::jsonb,'[]'::jsonb,$7) ON CONFLICT (run_id) DO NOTHING`,[roiRun,roi,c.organizationId,JSON.stringify({marker:ACCEPTANCE_NAMESPACE,costLines:[roiCostOne,roiCostRecurring],benefitLines:[roiBenefitOne,roiBenefitTwo]}),`${ACCEPTANCE_NAMESPACE}:roi-run-v1`,JSON.stringify([{period:'M1',costs:530000,benefits:105000},{period:'M6',costs:680000,benefits:630000},{period:'M12',costs:860000,benefits:1680000}]),c.userId],'rvn_roi_calculation_runs','run_id',roiRun,c.organizationId),
    s('roi-pir',`INSERT INTO rvn_roi_post_investment_reviews (pir_id,case_id,organization_id,sequence_number,status,started_by,review_snapshot_payload,review_snapshot_hash,outcome,lessons_learned,recommendation,finalized_by,finalized_at,created_by) VALUES ($1,$2,$3,1,'finalized',$4,$5::jsonb,$6,'benefits_partially_realized',$7,$8,$4,now(),$4) ON CONFLICT (pir_id) DO NOTHING`,[pir,roi,c.organizationId,c.userId,JSON.stringify({acceptanceFixture:ACCEPTANCE_NAMESPACE}),'acceptance-fixture-v1','Benefits require verified KPI cadence.','Continue with corrective action and monthly review.'],'rvn_roi_post_investment_reviews','pir_id',pir,c.organizationId),
    visibility('roi','roi_case',roi,roiPolicy),
    s('okr-policy',`INSERT INTO okr_vnext_program_policy_versions (policy_version_id,program_id,organization_id,version_number,snapshot,published_by) VALUES ($1,$2,$3,1,$4::jsonb,$5) ON CONFLICT (policy_version_id) DO NOTHING`,[policy,program,c.organizationId,JSON.stringify({acceptanceFixture:ACCEPTANCE_NAMESPACE,scoringModel:'zero_to_one'}),c.userId],'okr_vnext_program_policy_versions','policy_version_id',policy,c.organizationId),
    s('okr-cycle',`INSERT INTO okr_vnext_cycles (cycle_id,organization_id,program_id,name,start_date,end_date,draft_open_at,submission_due_at,active_start_at,final_update_due_at,review_open_at,reflection_due_at,close_at,status,policy_version_id,created_by) VALUES ($1,$2,$3,'Cykl transformacji Q3',CURRENT_DATE-30,CURRENT_DATE+60,CURRENT_DATE-45,CURRENT_DATE-35,CURRENT_DATE-30,CURRENT_DATE+50,CURRENT_DATE+51,CURRENT_DATE+57,CURRENT_DATE+60,'active',$4,$5) ON CONFLICT (cycle_id) DO UPDATE SET name=EXCLUDED.name WHERE okr_vnext_cycles.organization_id=EXCLUDED.organization_id`,[cycle,c.organizationId,program,policy,c.userId],'okr_vnext_cycles','cycle_id',cycle,c.organizationId),
    s('okr-set',`INSERT INTO okr_vnext_sets (set_id,organization_id,program_id,cycle_id,scope_type,scope_id,owner_user_id,title,status,overall_progress,overall_confidence,attention_state,created_by) VALUES ($1,$2,$3,$4,'company',$2,$5,'Przyspieszyć realizację wartości transformacji','active',0.58,'medium','watch',$5) ON CONFLICT (set_id) DO UPDATE SET title=EXCLUDED.title WHERE okr_vnext_sets.organization_id=EXCLUDED.organization_id`,[set,c.organizationId,program,cycle,c.userId],'okr_vnext_sets','set_id',set,c.organizationId),
    s('okr-objective',`INSERT INTO okr_vnext_objectives (objective_id,set_id,organization_id,owner_user_id,title,ambition_type,status,progress,confidence,sort_order,created_by) VALUES ($1,$2,$3,$4,'Potwierdzić mierzalne rezultaty transformacji','committed','active',0.58,'medium',0,$4) ON CONFLICT (objective_id) DO UPDATE SET title=EXCLUDED.title,owner_user_id=EXCLUDED.owner_user_id,progress=EXCLUDED.progress,confidence=EXCLUDED.confidence WHERE okr_vnext_objectives.organization_id=EXCLUDED.organization_id`,[objective,set,c.organizationId,c.userId],'okr_vnext_objectives','objective_id',objective,c.organizationId),
    s('okr-kr',`INSERT INTO okr_vnext_key_results (key_result_id,objective_id,set_id,organization_id,owner_user_id,title,measurement_type,unit,baseline_value,target_value,start_value,current_value,direction,progress,progress_calc_policy_version_id,confidence,status,created_by) VALUES ($1,$2,$3,$4,$5,'Osiągnąć zweryfikowany cel realizacji korzyści','numeric','%',0,100,0,58,'increase',0.58,$6,'medium','at_risk',$5) ON CONFLICT (key_result_id) DO UPDATE SET title=EXCLUDED.title,owner_user_id=EXCLUDED.owner_user_id,current_value=EXCLUDED.current_value,progress=EXCLUDED.progress,confidence=EXCLUDED.confidence,status=EXCLUDED.status WHERE okr_vnext_key_results.organization_id=EXCLUDED.organization_id`,[kr,objective,set,c.organizationId,c.userId,policy],'okr_vnext_key_results','key_result_id',kr,c.organizationId),
    s('okr-occurrence',`INSERT INTO okr_vnext_checkin_occurrences (cadence_occurrence_id,organization_id,cycle_id,window_start,window_end) VALUES ($1,$2,$3,CURRENT_DATE-7,CURRENT_DATE) ON CONFLICT (cadence_occurrence_id) DO NOTHING`,[occurrence,c.organizationId,cycle],'okr_vnext_checkin_occurrences','cadence_occurrence_id',occurrence,c.organizationId),
    s('okr-checkin',`INSERT INTO okr_vnext_checkins (checkin_id,organization_id,key_result_id,objective_id,set_id,cadence_occurrence_id,previous_value,new_value,calculated_progress,owner_declared_status,note,submitted_by,submitted_at) VALUES ($1,$2,$3,$4,$5,$6,45,58,0.58,'at_risk','Postęp potwierdzony w miesięcznym przeglądzie korzyści.',$7,now()) ON CONFLICT (checkin_id) DO UPDATE SET note=EXCLUDED.note,new_value=EXCLUDED.new_value,calculated_progress=EXCLUDED.calculated_progress,owner_declared_status=EXCLUDED.owner_declared_status WHERE okr_vnext_checkins.organization_id=EXCLUDED.organization_id`,[checkin,c.organizationId,kr,objective,set,occurrence,c.userId],'okr_vnext_checkins','checkin_id',checkin,c.organizationId),
    visibility('okr','okr_set',set,okrPolicy),
    {domain:'kpi-current-version',sql:`INSERT INTO rvn_kpi_definitions (kpi_id,organization_id,kpi_code,status,owner_user_id,created_by,current_definition_version_id) VALUES ($1,$2,'BENEFIT-REALIZATION','draft',$3,$3,$4) ON CONFLICT (kpi_id) DO UPDATE SET kpi_code=EXCLUDED.kpi_code,current_definition_version_id=EXCLUDED.current_definition_version_id,updated_at=now() WHERE rvn_kpi_definitions.organization_id=EXCLUDED.organization_id`,params:[kpi,c.organizationId,c.userId,kv],verifySql:`SELECT count(*)::int count FROM rvn_kpi_definitions WHERE kpi_id=$1 AND organization_id=$2 AND current_definition_version_id=$3`,verifyParams:[kpi,c.organizationId,kv]},
    {domain:'okr-active-policy',sql:`INSERT INTO okr_vnext_programs (program_id,organization_id,name,status,created_by,active_policy_version_id) VALUES ($1,$2,'Rezultaty transformacji 2026','active',$3,$4) ON CONFLICT (program_id) DO UPDATE SET name=EXCLUDED.name,active_policy_version_id=EXCLUDED.active_policy_version_id,status='active',updated_at=now() WHERE okr_vnext_programs.organization_id=EXCLUDED.organization_id`,params:[program,c.organizationId,c.userId,policy],verifySql:`SELECT count(*)::int count FROM okr_vnext_programs WHERE program_id=$1 AND organization_id=$2 AND active_policy_version_id=$3 AND status='active'`,verifyParams:[program,c.organizationId,policy]},
    s('execution-initiative',`INSERT INTO ie_aggregate_state (organization_id,aggregate_type,aggregate_id,version,payload_json) VALUES ($1,'initiative',$2,1,$3::jsonb) ON CONFLICT (organization_id,aggregate_type,aggregate_id) DO UPDATE SET payload_json=EXCLUDED.payload_json,updated_at=now()`,[c.organizationId,initiative,JSON.stringify({initiativeId:initiative,title:'Poprawa realizacji korzyści programu',problem:'Realizacja korzyści pozostaje poniżej celu i wymaga skoordynowanego planu naprawczego.',proposedOutcome:'Osiągnąć i utrzymać 90% zweryfikowanej realizacji korzyści.',lifecycleState:'EXECUTING',executionState:'ACTIVE',initiativeOwnerId:c.userId,handoffPackageId:handoff})],'ie_aggregate_state','aggregate_id',initiative,c.organizationId),
    s('execution-handoff',`INSERT INTO ie_aggregate_state (organization_id,aggregate_type,aggregate_id,version,payload_json) VALUES ($1,'handoff_package',$2,1,$3::jsonb) ON CONFLICT (organization_id,aggregate_type,aggregate_id) DO UPDATE SET payload_json=EXCLUDED.payload_json,updated_at=now()`,[c.organizationId,handoff,JSON.stringify({handoffPackageId:handoff,initiativeId:initiative,executionManagerId:c.userId,snapshot:{scope:{problem:'Realizacja korzyści poniżej celu',outcome:'Osiągnąć 90% zweryfikowanych korzyści'},sourceVersions:{initiative:1},baseline:{milestones:{m1:'Zweryfikować bazę korzyści',m2:'Zamknąć lukę realizacji'}}},portfolio:{priority:'HIGH'},plan:{status:'APPROVED'},capacity:{status:'CONFIRMED'},commitmentVersions:{initiative:1}})],'ie_aggregate_state','aggregate_id',handoff,c.organizationId),
    s('execution-case',`INSERT INTO ie_aggregate_state (organization_id,aggregate_type,aggregate_id,version,payload_json) VALUES ($1,'execution_case',$2,1,$3::jsonb) ON CONFLICT (organization_id,aggregate_type,aggregate_id) DO UPDATE SET payload_json=EXCLUDED.payload_json,updated_at=now()`,[c.organizationId,executionCase,JSON.stringify({executionCaseId:executionCase,initiativeId:initiative,state:'ACTIVE',health:'AT_RISK',executionManagerId:c.userId,executionManagerName:'Piotr Wiśniewski',handoffPackageId:handoff,handoffPackageVersion:1,acceptedBaseline:{scope:{problem:'Realizacja korzyści poniżej celu',outcome:'Osiągnąć 90% zweryfikowanych korzyści'},sourceVersions:{initiative:1},baseline:{milestones:{m1:'Zweryfikować bazę korzyści',m2:'Zamknąć lukę realizacji'}}},gaps:[{id:'benefit-gap',status:'OPEN',ownerId:c.userId,dueAt:'2026-09-15'}],acceptedAt:'2026-08-13T12:00:00.000Z'})],'ie_aggregate_state','aggregate_id',executionCase,c.organizationId),
    s('execution-task',`INSERT INTO ie_aggregate_state (organization_id,aggregate_type,aggregate_id,version,payload_json) VALUES ($1,'execution_task',$2,1,$3::jsonb) ON CONFLICT (organization_id,aggregate_type,aggregate_id) DO UPDATE SET payload_json=EXCLUDED.payload_json,updated_at=now()`,[c.organizationId,executionTask,JSON.stringify({taskId:executionTask,executionCaseId:executionCase,title:'Zweryfikować bazę korzyści',status:'IN_PROGRESS',ownerId:c.userId,dueAt:'2026-08-20T16:00:00.000Z'})],'ie_aggregate_state','aggregate_id',executionTask,c.organizationId),
    s('execution-milestone',`INSERT INTO ie_aggregate_state (organization_id,aggregate_type,aggregate_id,version,payload_json) VALUES ($1,'execution_milestone',$2,1,$3::jsonb) ON CONFLICT (organization_id,aggregate_type,aggregate_id) DO UPDATE SET payload_json=EXCLUDED.payload_json,updated_at=now()`,[c.organizationId,executionMilestone,JSON.stringify({milestoneId:executionMilestone,executionCaseId:executionCase,title:'Zweryfikowana baza korzyści',status:'PLANNED',targetAt:'2026-08-31T16:00:00.000Z'})],'ie_aggregate_state','aggregate_id',executionMilestone,c.organizationId),
    {domain:'execution-relation',sql:`INSERT INTO ie_aggregate_relations (organization_id,relation_type,source_type,source_id,source_version,target_type,target_id,payload_json) VALUES ($1,'INITIATIVE_EXECUTION_CASE','initiative',$2,1,'execution_case',$3,$4::jsonb) ON CONFLICT (organization_id,relation_type,source_type,source_id) DO UPDATE SET target_id=EXCLUDED.target_id,payload_json=EXCLUDED.payload_json`,params:[c.organizationId,initiative,executionCase,JSON.stringify({marker:ACCEPTANCE_NAMESPACE})],verifySql:`SELECT count(*)::int count FROM ie_aggregate_relations WHERE source_id=$1 AND organization_id=$2 AND target_id=$3`,verifyParams:[initiative,c.organizationId,executionCase]},
    s('ideas-map',`INSERT INTO my_idea_maps (id,idea_id,user_id,organization_id,nodes_json,edges_json,version) VALUES ($1,$2,$3,$4,$5,$6,1) ON CONFLICT (user_id,idea_id) DO UPDATE SET nodes_json=EXCLUDED.nodes_json,edges_json=EXCLUDED.edges_json`,[map,idea,c.userId,c.organizationId,JSON.stringify([{id:'root',type:'idea',data:{label:'Automatyczne monitorowanie korzyści'},position:{x:0,y:0}}]),'[]'],'my_idea_maps','id',map,c.organizationId),
    s('ideas-business-case',`INSERT INTO idea_business_cases (id,idea_id,organization_id,sections_json,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$5) ON CONFLICT (idea_id) DO UPDATE SET sections_json=EXCLUDED.sections_json`,[bc,idea,c.organizationId,JSON.stringify({marker:ACCEPTANCE_NAMESPACE,decisionRequested:'Approve controlled pilot'}),c.userId],'idea_business_cases','id',bc,c.organizationId),
    s('ideas-financial-case',`INSERT INTO idea_financial_cases (id,idea_id,organization_id,case_json,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$5) ON CONFLICT (idea_id) DO UPDATE SET case_json=EXCLUDED.case_json`,[fc,idea,c.organizationId,JSON.stringify({marker:ACCEPTANCE_NAMESPACE,currency:'PLN',capex:500000,benefit:900000}),c.userId],'idea_financial_cases','id',fc,c.organizationId),
    s('artifact-workbook',`INSERT INTO generated_workbooks (id,organization_id,title,description,schema_json,sheet_count,created_by) VALUES ($1,$2,'Model realizacji korzyści',$3,$4,2,$5) ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,schema_json=EXCLUDED.schema_json,sheet_count=EXCLUDED.sheet_count WHERE generated_workbooks.organization_id=EXCLUDED.organization_id`,[workbook,c.organizationId,'Model zarządczy łączący plan, wykonanie i dowody korzyści.',JSON.stringify(workbookSchema),c.userId],'generated_workbooks','id',workbook,c.organizationId),
    s('artifact-workbook-version',`INSERT INTO generated_workbook_versions (id,workbook_id,version,schema_json_snapshot,sheet_count,created_by) VALUES ($1,$2,1,$3,2,$4) ON CONFLICT (id) DO NOTHING`,[workbookV,workbook,JSON.stringify({marker:ACCEPTANCE_NAMESPACE}),c.userId],`(SELECT gwv.id,w.organization_id FROM generated_workbook_versions gwv JOIN generated_workbooks w ON w.id=gwv.workbook_id) q`,'id',workbookV,c.organizationId),
    s('artifact-presentation-registry',`INSERT INTO v8_output_artifacts (artifact_id,organization_id,output_type,delivery_state,artifact_family,title_snapshot,owner_user_id,canonical_home,visibility_scope,created_by,is_draft) VALUES ($1,$2,'presentation','ready','presentation','Przegląd korzyści transformacji',$3,'outputs_library','organization',$3,0) ON CONFLICT (artifact_id) DO UPDATE SET delivery_state='ready',title_snapshot=EXCLUDED.title_snapshot,owner_user_id=EXCLUDED.owner_user_id,is_draft=0,last_transition_at=now()::text`,[deck,c.organizationId,c.userId],'v8_output_artifacts','artifact_id',deck,c.organizationId),
    {domain:'artifact-presentation-origin',sql:`INSERT INTO v8_artifact_origin_links (link_id,artifact_id,organization_id,origin_runtime,origin_record_id,is_primary_origin) VALUES ($1,$2,$3,'presentation',$2,1) ON CONFLICT (organization_id,origin_runtime,origin_record_id) DO UPDATE SET artifact_id=EXCLUDED.artifact_id,is_primary_origin=1`,params:[deckOrigin,deck,c.organizationId],verifySql:`SELECT count(*)::int count FROM v8_artifact_origin_links WHERE artifact_id=$1 AND organization_id=$2 AND origin_runtime='presentation' AND origin_record_id=$1 AND is_primary_origin=1`,verifyParams:[deck,c.organizationId]},
    s('artifact-workbook-registry',`INSERT INTO v8_output_artifacts (artifact_id,organization_id,output_type,delivery_state,artifact_family,title_snapshot,owner_user_id,canonical_home,visibility_scope,created_by,is_draft) VALUES ($1,$2,'sheet','ready','sheet','Model realizacji korzyści',$3,'outputs_library','organization',$3,0) ON CONFLICT (artifact_id) DO UPDATE SET delivery_state='ready',title_snapshot=EXCLUDED.title_snapshot,owner_user_id=EXCLUDED.owner_user_id,is_draft=0,last_transition_at=now()::text`,[workbook,c.organizationId,c.userId],'v8_output_artifacts','artifact_id',workbook,c.organizationId),
    {domain:'artifact-workbook-origin',sql:`INSERT INTO v8_artifact_origin_links (link_id,artifact_id,organization_id,origin_runtime,origin_record_id,is_primary_origin) VALUES ($1,$2,$3,'sheet',$2,1) ON CONFLICT (organization_id,origin_runtime,origin_record_id) DO UPDATE SET artifact_id=EXCLUDED.artifact_id,is_primary_origin=1`,params:[workbookOrigin,workbook,c.organizationId],verifySql:`SELECT count(*)::int count FROM v8_artifact_origin_links WHERE artifact_id=$1 AND organization_id=$2 AND origin_runtime='sheet' AND origin_record_id=$1 AND is_primary_origin=1`,verifyParams:[workbook,c.organizationId]},
    s('artifact-document-approval',`INSERT INTO document_approvals (approval_id,artifact_id,organization_id,status,requested_by,created_at,updated_at,payload_json) VALUES ($1,$2,$3,'pending',$4,now()::text,now()::text,$5::jsonb) ON CONFLICT (approval_id) DO NOTHING`,[docApproval,stableTextId(c,'artifact-presentation'),c.organizationId,c.userId,JSON.stringify({marker:ACCEPTANCE_NAMESPACE,fourEyes:true})],'document_approvals','approval_id',docApproval,c.organizationId),
    s('artifact-document-version',`INSERT INTO document_version_snapshots (version_id,artifact_id,organization_id,version_number,captured_at,captured_by,label,reason,status_at_capture,schema_json,origin) VALUES ($1,$2,$3,1,now()::text,$4,'Acceptance v1',$5,'draft',$6::jsonb,'manual') ON CONFLICT (version_id) DO NOTHING`,[docVersion,stableTextId(c,'artifact-presentation'),c.organizationId,c.userId,ACCEPTANCE_NAMESPACE,JSON.stringify({marker:ACCEPTANCE_NAMESPACE,blocks:[{type:'heading',text:'Owner acceptance'}]})],'document_version_snapshots','version_id',docVersion,c.organizationId),
    s('finance-valuation',`INSERT INTO finance_valuation_cases (case_id,organization_id,name,description,created_by) VALUES ($1,$2,'Wycena programu transformacji',$3,$4) ON CONFLICT (case_id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description WHERE finance_valuation_cases.organization_id=EXCLUDED.organization_id`,[valuation,c.organizationId,'Scenariusz bazowy, wzrostowy i ostrożny dla programu transformacji.',c.userId],'finance_valuation_cases','case_id',valuation,c.organizationId),
  ];
}
