import assert from 'node:assert/strict'; import fs from 'node:fs'; import {Pool} from 'pg'; import {adaptQuery} from '../database/PostgresDatabase.js';
const url=process.env.DATABASE_URL;if(!url)throw new Error('DATABASE_URL is required'); const pool=new Pool({connectionString:url});
const db={query:(q:string,p:unknown[]=[])=>pool.query(adaptQuery(q),p),get(q:string,p:unknown[],cb:any){void pool.query(adaptQuery(q),p).then(r=>cb(null,r.rows[0]??null),cb)},all(q:string,p:unknown[],cb:any){void pool.query(adaptQuery(q),p).then(r=>cb(null,r.rows),cb)},run(q:string,p:unknown[],cb:any){void pool.query(adaptQuery(q),p).then(r=>cb.call({changes:r.rowCount},null),cb)},serialize(cb:any){cb()}};(globalThis as any).__CONSULTIFY_GLOBAL_DB_INSTANCE__=db;(process as any).__CONSULTIFY_GLOBAL_DB_INSTANCE__=db;
async function main(){await pool.query('DROP SCHEMA public CASCADE;CREATE SCHEMA public');
await pool.query(`CREATE TABLE transformation_cases(transformation_case_id text primary key,organization_id text,project_id text);CREATE TABLE transformation_case_artifact_links(transformation_case_id text,organization_id text,artifact_type text,artifact_id text);CREATE TABLE project_members(project_id text,user_id text);CREATE TABLE raid_items(id text primary key,organization_id text,initiative_id text,type text,title text,description text,status text,probability text,impact text,mitigation_plan text,owner_id text,due_date text,created_at timestamptz,updated_at timestamptz);CREATE TABLE tasks(id text primary key,organization_id text,initiative_id text,title text,due_date text,status text);CREATE TABLE initiative_milestones(id text primary key,organization_id text,initiative_id text,name text,target_date text,status text);CREATE TABLE v8_calendar_items(calendar_item_id text primary key,organization_id text,source_id text,item_type text,source_system text,source_object_ref text,title text,start_at text,end_at text,all_day int,timezone text,visibility_class text,edit_authority text,recurrence_model_json text,sync_state text,etag text,created_at timestamptz,updated_at timestamptz);`);
await pool.query(fs.readFileSync(new URL('../../migrations/20260809_t01_u03_owner_backed_execution.sql',import.meta.url),'utf8'));
await pool.query(`INSERT INTO transformation_cases VALUES('case','org','project');INSERT INTO transformation_case_artifact_links VALUES('case','org','initiative','initiative');INSERT INTO project_members VALUES('project','actor');INSERT INTO tasks VALUES('task','org','initiative','Due task','2026-08-10','TODO');INSERT INTO initiative_milestones VALUES('milestone','org','initiative','Gate','2026-08-11','PLANNED')`);
const svc=await import('../services/v8/transformationMobilizationOwnerAdapterService.js'); const base={organizationId:'org',transformationCaseId:'case',initiativeId:'initiative',proposalId:'proposal',payloadDigest:'digest',actorUserId:'actor',raidItems:[{type:'risk' as const,title:'Risk',description:'Risk d',probability:'high' as const,impact:'critical' as const,ownerUserId:'actor',dueDate:'2026-08-12',response:'Mitigate'},{type:'dependency' as const,title:'External dependency',description:'Not a WBS edge',probability:'medium' as const,impact:'high' as const,ownerUserId:'actor',dueDate:'2026-08-13',response:'Escalate'}],monitoring:{cadence:'weekly' as const,timezone:'Europe/Warsaw',firstRunAt:'2026-08-08T09:00:00.000Z',ownerUserId:'actor'}};
const concurrent=await Promise.all([svc.materializeMobilizationOwners(base),svc.materializeMobilizationOwners(base)]);assert.equal(concurrent.filter(x=>!x.idempotentReplay).length,1);assert.equal((await pool.query('select count(*)::int c from transformation_mobilization_owner_receipts')).rows[0].c,1);assert.equal((await pool.query('select count(*)::int c from raid_items')).rows[0].c,2);assert.equal((await pool.query('select count(*)::int c from v8_calendar_items')).rows[0].c,2);await assert.rejects(()=>svc.materializeMobilizationOwners({...base,payloadDigest:'drift'}),/idempotency_conflict/);await assert.rejects(()=>svc.materializeMobilizationOwners({...base,proposalId:'foreign',actorUserId:'foreign'}),/authority_required/);
const workers=await Promise.all([svc.runDueMobilizationMonitoring({organizationId:'org',workerId:'w1',now:'2026-08-08T10:00:00.000Z'}),svc.runDueMobilizationMonitoring({organizationId:'org',workerId:'w2',now:'2026-08-08T10:00:00.000Z'})]);assert.equal(workers.filter(Boolean).length,1);await pool.query(`UPDATE transformation_monitoring_definitions SET next_run_at='2026-08-15T09:00:00Z',lease_owner='dead',lease_expires_at='2026-08-15T08:00:00Z'`);const restarted=await svc.runDueMobilizationMonitoring({organizationId:'org',workerId:'restart',now:'2026-08-15T10:00:00.000Z'});assert.ok(restarted);assert.equal((await pool.query('select count(*)::int c from transformation_monitoring_snapshots')).rows[0].c,2);
console.log(JSON.stringify({proof:'U03_OWNER_BACKED_EXECUTION_REALDB_GREEN',raidItems:2,wbsDependenciesUntouched:true,localCalendarProjections:2,externalInvites:0,aggregateReceipts:1,concurrentMaterializationExactlyOne:true,payloadDriftBlocked:true,tenantAuthorityBlocked:true,monitoringConcurrentExactlyOne:true,restartLeaseRecovered:true,snapshots:2,timezone:'Europe/Warsaw',cadence:'weekly'}));}
main().finally(()=>pool.end());
