/**
 * AI Editor Operation Envelope Schemas (Block C · C-S2).
 *
 * Every level handler returns a typed `operations` array plus a `diff`
 * envelope. These schemas are the canonical contract between handlers,
 * the orchestrator, MutationExecutor (C-S5+), and the frontend
 * `ProposalDiffCard` UI.
 *
 * Validation is enforced at handler exit so an LLM that returns malformed
 * JSON cannot smuggle invalid operations into `tp_schema_proposals`.
 *
 * Naming convention: `op_<level>_<verb>` so dispatchers can pattern-match.
 *
 * Cross-level invariants:
 *   - `id` is required and unique per operation within a proposal.
 *   - `dependsOn` lists other op IDs that must apply first (for column ops
 *      that reference newly-created records, etc.).
 *   - `target` carries IDs (recordId/fieldId/tableId) — never names — so the
 *      executor never has to resolve names a second time.
 *   - `before` / `after` are JSON-serialisable; absent on create-only ops.
 */

import { z } from 'zod';

// ── Common ───────────────────────────────────────────────────────────────────

const opCommon = z.object({
  id: z.string().min(1),
  dependsOn: z.array(z.string()).optional(),
});

const idTarget = z.object({
  tableId: z.string().min(1),
  recordId: z.string().min(1).optional(),
  fieldId: z.string().min(1).optional(),
});

// ── Level 1: Cell ────────────────────────────────────────────────────────────
//
// op_cell_set: Set a single cell value. Always carries before/after for diff.

export const opCellSet = opCommon.extend({
  type: z.literal('op_cell_set'),
  target: idTarget.extend({
    recordId: z.string().min(1),
    fieldId: z.string().min(1),
  }),
  before: z.unknown(),
  after: z.unknown(),
  /** Always false for AI Editor proposals; set to true ONLY when a human
   *  later edits the AI-derived value. The flag is metadata, not control. */
  manualOverride: z.literal(false).default(false),
});
export type OpCellSet = z.infer<typeof opCellSet>;

// ── Level 2: Record ──────────────────────────────────────────────────────────
//
// op_record_update: change one or more fields on a single record.
// op_record_create: insert a new record (no before).

export const opRecordUpdate = opCommon.extend({
  type: z.literal('op_record_update'),
  target: idTarget.extend({
    recordId: z.string().min(1),
  }),
  /** Field-level diffs scoped to this record. */
  fieldChanges: z
    .array(
      z.object({
        fieldId: z.string().min(1),
        before: z.unknown(),
        after: z.unknown(),
      })
    )
    .min(1),
});
export type OpRecordUpdate = z.infer<typeof opRecordUpdate>;

export const opRecordCreate = opCommon.extend({
  type: z.literal('op_record_create'),
  target: idTarget,
  data: z.record(z.string(), z.unknown()),
});
export type OpRecordCreate = z.infer<typeof opRecordCreate>;

// ── Level 3: Column (bulk over many records, one field) ──────────────────────

export const opColumnFill = opCommon.extend({
  type: z.literal('op_column_fill'),
  target: idTarget.extend({
    fieldId: z.string().min(1),
  }),
  /** Per-record fills generated by the LLM. The array length is also the
   *  hint to the UI on how many cells will mutate. */
  cells: z
    .array(
      z.object({
        recordId: z.string().min(1),
        before: z.unknown(),
        after: z.unknown(),
      })
    )
    .min(1),
});
export type OpColumnFill = z.infer<typeof opColumnFill>;

// ── Level 4: Structure (proxies to ChatToSchema pipeline) ────────────────────
//
// We mirror the existing schema-operation envelope used by ChatToSchema so
// downstream MutationExecutor can consume both flows.

export const opSchemaAddField = opCommon.extend({
  type: z.literal('op_schema_add_field'),
  target: idTarget,
  payload: z.object({
    name: z.string().min(1),
    fieldType: z.string().min(1),
    options: z.record(z.string(), z.unknown()).optional(),
  }),
});
export const opSchemaRenameField = opCommon.extend({
  type: z.literal('op_schema_rename_field'),
  target: idTarget.extend({ fieldId: z.string().min(1) }),
  payload: z.object({ from: z.string().min(1), to: z.string().min(1) }),
});
export const opSchemaRetypeField = opCommon.extend({
  type: z.literal('op_schema_retype_field'),
  target: idTarget.extend({ fieldId: z.string().min(1) }),
  payload: z.object({
    from: z.string().min(1),
    to: z.string().min(1),
    options: z.record(z.string(), z.unknown()).optional(),
  }),
});
export const opSchemaDropField = opCommon.extend({
  type: z.literal('op_schema_drop_field'),
  target: idTarget.extend({ fieldId: z.string().min(1) }),
});

export type OpSchemaAddField = z.infer<typeof opSchemaAddField>;
export type OpSchemaRenameField = z.infer<typeof opSchemaRenameField>;
export type OpSchemaRetypeField = z.infer<typeof opSchemaRetypeField>;
export type OpSchemaDropField = z.infer<typeof opSchemaDropField>;

// ── Discriminated union of all operations ────────────────────────────────────

export const aiEditorOperation = z.discriminatedUnion('type', [
  opCellSet,
  opRecordUpdate,
  opRecordCreate,
  opColumnFill,
  opSchemaAddField,
  opSchemaRenameField,
  opSchemaRetypeField,
  opSchemaDropField,
]);
export type AiEditorOperation = z.infer<typeof aiEditorOperation>;

// ── Handler output envelope ──────────────────────────────────────────────────

export const handlerOutputSchema = z.object({
  operations: z.array(aiEditorOperation),
  summary: z.string().min(1),
  warnings: z.array(z.string()).default([]),
  confidence: z.number().min(0).max(1),
});
export type HandlerOutput = z.infer<typeof handlerOutputSchema>;
