export const TEST_SCHEMA = [
  `CREATE TABLE IF NOT EXISTS organizations (
        id TEXT PRIMARY KEY,
        name TEXT,
        plan TEXT DEFAULT 'free',
        subscription_plan TEXT,
        status TEXT DEFAULT 'active',
        mfa_required INTEGER DEFAULT 0,
        mfa_grace_period_days INTEGER,
        discount_percent REAL DEFAULT 0,
        vat_number TEXT,
        domain TEXT,
        industry TEXT DEFAULT 'General',
        active_llm_provider_id TEXT,
        billing_status TEXT DEFAULT 'PENDING',
        organization_type TEXT DEFAULT 'TRIAL',
        transformation_context TEXT DEFAULT '{}',
        onboarding_status TEXT DEFAULT 'NOT_STARTED',
        onboarding_plan_snapshot TEXT,
        onboarding_plan_version INTEGER DEFAULT 0,
        onboarding_accepted_at DATETIME,
        onboarding_accept_idempotency_key TEXT,
        token_balance INTEGER DEFAULT 0,
        created_by_user_id TEXT,
        is_active INTEGER DEFAULT 1,
        ai_assertiveness_level TEXT DEFAULT 'MEDIUM',
        ai_autonomy_level TEXT DEFAULT 'SUGGEST_ONLY',
        attribution_data TEXT,
        trial_started_at DATETIME,
        trial_expires_at DATETIME,
        trial_extension_count INTEGER DEFAULT 0,
        trial_warning_sent_at DATETIME,
        trial_tokens_used INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        valid_until DATETIME,
        monthly_budget_usd REAL,
        budget_alert_threshold REAL,
        budget_period_start DATETIME,
        budget_spent_current_period REAL DEFAULT 0,
        memory_usage_mb_current REAL DEFAULT 0,
        cpu_usage_percent_current REAL DEFAULT 0,
        cpu_usage_percent_avg REAL DEFAULT 0,
        concurrent_ai_jobs_current INTEGER DEFAULT 0,
        concurrent_ai_jobs_count INTEGER DEFAULT 0
    )`,
  `CREATE TABLE IF NOT EXISTS project_memory (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        memory_type TEXT NOT NULL,
        content TEXT NOT NULL,
        title TEXT,
        importance INTEGER DEFAULT 1,
        recorded_by TEXT,
        tags TEXT,
        related_entity_type TEXT,
        related_entity_id TEXT,
        created_at TEXT DEFAULT (datetime('now')),
        updated_at TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY (recorded_by) REFERENCES users(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ai_drafts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        project_id TEXT,
        user_id TEXT NOT NULL,
        draft_type TEXT NOT NULL,
        target_entity_type TEXT,
        target_entity_id TEXT,
        target_field TEXT,
        original_content TEXT,
        suggested_content TEXT NOT NULL,
        diff_data TEXT,
        confidence_score REAL DEFAULT 0.8,
        reasoning TEXT,
        status TEXT DEFAULT 'PENDING',
        reviewed_by TEXT,
        reviewed_at TEXT,
        review_notes TEXT,
        model_used TEXT,
        prompt_id TEXT,
        tokens_used INTEGER,
        expires_at TEXT,
        created_at TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (organization_id) REFERENCES organizations(id),
        FOREIGN KEY (project_id) REFERENCES projects(id),
        FOREIGN KEY (user_id) REFERENCES users(id),
        FOREIGN KEY (reviewed_by) REFERENCES users(id)
    )`,
  `CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        email TEXT UNIQUE,
        password TEXT,
        first_name TEXT,
        last_name TEXT,
        role TEXT DEFAULT 'user',
        current_phase TEXT DEFAULT 'A',
        avatar_url TEXT,
        impersonator_id TEXT,
        status TEXT DEFAULT 'active',
        email_verified INTEGER DEFAULT 0,
        email_verification_token TEXT,
        email_verification_expires_at DATETIME,
        email_verification_sent_at DATETIME,
        mfa_enabled INTEGER DEFAULT 0,
        mfa_secret TEXT,
        mfa_sms_enabled INTEGER DEFAULT 0,
        mfa_primary_method TEXT,
        mfa_verified_at DATETIME,
        mfa_backup_codes TEXT,
        mfa_recovery_email TEXT,
        phone_number TEXT,
        phone TEXT,
        linkedin_id TEXT,
        ai_config TEXT,
        license_plan_id TEXT,
        phone_verified INTEGER DEFAULT 0,
        is_owner INTEGER DEFAULT 0,
        token_limit INTEGER DEFAULT 100000,
        token_used INTEGER DEFAULT 0,
        token_reset_at DATETIME,
        title TEXT,
        last_login DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS projects (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        goal TEXT,
        status TEXT DEFAULT 'active',
        owner_id TEXT,
        current_phase TEXT DEFAULT 'Context',
        phase_history TEXT DEFAULT '[]',
        is_closed INTEGER DEFAULT 0,
        governance_settings TEXT DEFAULT '{}',
        initiative_count INTEGER DEFAULT 0,
        assessment_count INTEGER DEFAULT 0,
        member_count INTEGER DEFAULT 0,
        document_count INTEGER DEFAULT 0,
        start_date DATETIME,
        end_date DATETIME,
        budget REAL,
        currency TEXT DEFAULT 'USD',
        lead_id TEXT,
        priority TEXT DEFAULT 'medium',
        phase TEXT DEFAULT 'planning',
        settings TEXT,
        metadata TEXT,
        context_data TEXT,
        rag_enabled INTEGER DEFAULT 1,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  // ============================================
  // Canonical project team tables (used by /api/projects/:id/members)
  // ============================================
  `CREATE TABLE IF NOT EXISTS workstreams (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        description TEXT,
        owner_id TEXT REFERENCES users(id) ON DELETE SET NULL,
        status TEXT NOT NULL DEFAULT 'ACTIVE',
        color TEXT DEFAULT '#3B82F6',
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    )`,
  `CREATE INDEX IF NOT EXISTS idx_workstreams_project ON workstreams(project_id)`,
  `CREATE TABLE IF NOT EXISTS project_members (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        project_role TEXT NOT NULL DEFAULT 'TASK_ASSIGNEE',
        workstream_id TEXT REFERENCES workstreams(id) ON DELETE SET NULL,
        allocation_percent INTEGER NOT NULL DEFAULT 100,
        permissions TEXT DEFAULT '{}',
        start_date TEXT,
        end_date TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        added_by_id TEXT REFERENCES users(id) ON DELETE SET NULL,
        is_invoked INTEGER DEFAULT 0,
        consultant_profile TEXT DEFAULT 'NONE',
        engagement_type TEXT DEFAULT 'INTERNAL',
        acting_org_id TEXT,
        UNIQUE(project_id, user_id)
    )`,
  `CREATE INDEX IF NOT EXISTS idx_project_members_project ON project_members(project_id)`,
  `CREATE INDEX IF NOT EXISTS idx_project_members_user ON project_members(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_project_members_role ON project_members(project_role)`,
  `CREATE INDEX IF NOT EXISTS idx_project_members_workstream ON project_members(workstream_id)`,
  `CREATE TABLE IF NOT EXISTS tasks (
        id TEXT PRIMARY KEY,
        project_id TEXT,
        organization_id TEXT NOT NULL,
        title TEXT NOT NULL,
        description TEXT,
        status TEXT DEFAULT 'TODO',
        priority TEXT DEFAULT 'MEDIUM',
        assignee_id TEXT,
        reporter_id TEXT,
        due_date DATETIME,
        estimated_hours REAL,
        checklist TEXT DEFAULT '[]',
        attachments TEXT DEFAULT '[]',
        tags TEXT DEFAULT '[]',
        task_type TEXT DEFAULT 'execution',
        initiative_id TEXT,
        why TEXT,
        expected_outcome TEXT,
        decision_impact TEXT,
        evidence_required TEXT,
        strategic_contribution TEXT,
        roadmap_initiative_id TEXT,
        kpi_id TEXT,
        raid_item_id TEXT,
        assignees TEXT DEFAULT '[]',
        progress INTEGER DEFAULT 0,
        blocked_reason TEXT,
        sla_hours INTEGER,
        sla_due_at TEXT,
        escalation_level INTEGER DEFAULT 0,
        escalated_to_id TEXT,
        last_escalated_at TEXT,
        custom_status_id TEXT,
        step_phase TEXT DEFAULT 'design',
        budget_allocated REAL DEFAULT 0,
        budget_spent REAL DEFAULT 0,
        risk_rating TEXT DEFAULT 'low',
        acceptance_criteria TEXT,
        blocking_issues TEXT,
        completed_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(assignee_id) REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY(reporter_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS sessions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        project_id TEXT,
        token TEXT UNIQUE,
        type TEXT,
        data TEXT,
        expires_at DATETIME,
        ip_address TEXT,
        user_agent TEXT,
        last_active_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS refresh_tokens (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        token_hash TEXT NOT NULL,
        token_family TEXT NOT NULL,
        device_info TEXT,
        ip_address TEXT,
        user_agent TEXT,
        expires_at DATETIME NOT NULL,
        revoked_at DATETIME,
        revoked_reason TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        last_used_at DATETIME,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
        id TEXT PRIMARY KEY,
        timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        user_id TEXT,
        user_email TEXT,
        ip_address TEXT,
        user_agent TEXT,
        action_type TEXT NOT NULL,
        resource_type TEXT,
        resource_id TEXT,
        before_data TEXT,
        after_data TEXT,
        risk_level TEXT,
        compliance_tags TEXT,
        request_id TEXT,
        organization_id TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS notifications (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        organization_id TEXT,
        project_id TEXT,
        initiative_id TEXT,
        task_id TEXT,
        related_id TEXT,
        type TEXT NOT NULL,
        severity TEXT DEFAULT 'INFO',
        priority TEXT DEFAULT 'medium',
        title TEXT NOT NULL,
        message TEXT,
        data TEXT,
        related_object_type TEXT,
        related_object_id TEXT,
        is_read INTEGER DEFAULT 0,
        read INTEGER DEFAULT 0,
        is_actionable INTEGER DEFAULT 0,
        action_url TEXT,
        expires_at DATETIME,
        read_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS login_history (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        ip_address TEXT,
        user_agent TEXT,
        location TEXT,
        status TEXT DEFAULT 'success',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS notification_settings (
        user_id TEXT PRIMARY KEY,
        settings TEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS teams (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        lead_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(lead_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS team_members (
        team_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        role TEXT DEFAULT 'member',
        joined_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(team_id, user_id),
        FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS invitations (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        email TEXT NOT NULL,
        role TEXT DEFAULT 'USER',
        token TEXT UNIQUE,
        token_hash TEXT UNIQUE,
        status TEXT DEFAULT 'pending',
        invited_by TEXT,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        accepted_at DATETIME,
        invitation_type TEXT DEFAULT 'ORG',
        project_id TEXT,
        role_to_assign TEXT,
        accepted_by_user_id TEXT,
        metadata TEXT DEFAULT '{}',
        resend_count INTEGER DEFAULT 0,
        last_resent_at DATETIME,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(invited_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS revoked_tokens (
        jti TEXT PRIMARY KEY,
        user_id TEXT,
        expires_at DATETIME,
        revoked_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        reason TEXT DEFAULT 'logout',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS superadmin_ai_settings (
        id TEXT PRIMARY KEY DEFAULT 'global',
        default_provider TEXT,
        fallback_chain TEXT DEFAULT '[]',
        circuit_breaker_config TEXT DEFAULT '{"failureThreshold": 5, "cooldownSeconds": 60}',
        global_token_limit INTEGER DEFAULT 10000000,
        global_rate_limit TEXT DEFAULT '{"requestsPerMinute": 60, "requestsPerHour": 1000}',
        max_context_window_size INTEGER DEFAULT 128000,
        max_tokens_per_request INTEGER DEFAULT 8192,
        pii_detection_sensitivity TEXT DEFAULT 'medium',
        require_encryption INTEGER DEFAULT 1,
        data_residency TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_by TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS organization_ai_settings (
        organization_id TEXT PRIMARY KEY,
        policy_level TEXT DEFAULT 'ADVISORY',
        max_policy_level TEXT DEFAULT 'ASSISTED',
        default_proactivity_mode TEXT DEFAULT 'BALANCED',
        active_roles TEXT DEFAULT '["ADVISOR"]',
        default_role TEXT DEFAULT 'ADVISOR',
        enabled_model_ids TEXT DEFAULT '[]',
        max_ai_calls_per_day INTEGER DEFAULT 100,
        max_tokens_per_month INTEGER DEFAULT 500000,
        monthly_budget_usd REAL DEFAULT 0,
        hard_limit_usd REAL DEFAULT 0,
        freeze_on_limit INTEGER DEFAULT 0,
        web_search_enabled INTEGER DEFAULT 1,
        artifacts_enabled INTEGER DEFAULT 1,
        thinking_steps_enabled INTEGER DEFAULT 1,
        focus_modes_enabled INTEGER DEFAULT 1,
        voice_enabled INTEGER DEFAULT 0,
        audit_all_requests INTEGER DEFAULT 0,
        audit_policy_changes INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_by TEXT,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS user_ai_settings (
        user_id TEXT PRIMARY KEY,
        response_style TEXT DEFAULT 'balanced',
        writing_tone TEXT DEFAULT 'professional',
        preferred_language TEXT DEFAULT 'auto',
        code_explanations INTEGER DEFAULT 1,
        show_sources INTEGER DEFAULT 1,
        proactivity_mode TEXT DEFAULT 'BALANCED',
        model_temperature REAL DEFAULT 0.7,
        max_tokens INTEGER DEFAULT 4096,
        top_p REAL DEFAULT 1.0,
        frequency_penalty REAL DEFAULT 0.0,
        presence_penalty REAL DEFAULT 0.0,
        system_instructions TEXT DEFAULT '',
        visible_model_ids TEXT DEFAULT '[]',
        preferred_model_id TEXT,
        enable_pii_redaction INTEGER DEFAULT 0,
        data_retention_policy TEXT DEFAULT 'standard',
        share_usage_analytics INTEGER DEFAULT 1,
        context_retention TEXT DEFAULT 'session',
        auto_suggestions INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS ai_policies (
        organization_id TEXT PRIMARY KEY,
        policy_level TEXT DEFAULT 'ADVISORY',
        internet_enabled INTEGER DEFAULT 0,
        audit_required INTEGER DEFAULT 1,
        active_roles TEXT DEFAULT '["ADVISOR","PMO_MANAGER","EXECUTOR","EDUCATOR"]',
        max_policy_level TEXT DEFAULT 'ASSISTED',
        default_ai_role TEXT DEFAULT 'ADVISOR',
        proactive_notifications INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS initiatives (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        project_id TEXT,
        name TEXT,
        title TEXT,
        description TEXT,
        summary TEXT,
        axis TEXT,
        area TEXT,
        hypothesis TEXT,
        status TEXT DEFAULT 'DRAFT',
        current_stage TEXT,
        priority TEXT DEFAULT 'MEDIUM',
        progress INTEGER DEFAULT 0,
        business_value TEXT,
        competencies_required TEXT,
        cost_capex REAL,
        cost_opex REAL,
        expected_roi REAL,
        value_driver TEXT,
        confidence_level TEXT,
        value_timing TEXT,
        social_impact TEXT,
        risk_level TEXT DEFAULT 'LOW',
        planned_start_date DATETIME,
        planned_end_date DATETIME,
        actual_start_date DATETIME,
        actual_end_date DATETIME,
        start_date DATETIME,
        pilot_end_date DATETIME,
        end_date DATETIME,
        owner_id TEXT,
        owner_business_id TEXT,
        owner_execution_id TEXT,
        sponsor_id TEXT,
        market_context TEXT,
        blocked_reason TEXT,
        problem_statement TEXT DEFAULT '',
        deliverables TEXT DEFAULT '[]',
        success_criteria TEXT DEFAULT '[]',
        scope_in TEXT DEFAULT '[]',
        scope_out TEXT DEFAULT '[]',
        key_risks TEXT DEFAULT '[]',
        report_id TEXT,
        wave_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS maturity_assessments (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        project_id TEXT NOT NULL,
        name TEXT,
        assessment_date DATE,
        planning_score REAL,
        decision_score REAL,
        execution_score REAL,
        monitoring_score REAL,
        collaboration_score REAL,
        axis_scores TEXT DEFAULT '[]',
        completed_axes TEXT DEFAULT '[]',
        overall_as_is REAL DEFAULT 0,
        overall_to_be REAL DEFAULT 0,
        overall_gap REAL DEFAULT 0,
        overall_score REAL,
        gap_analysis TEXT DEFAULT '{}',
        gap_analysis_summary TEXT,
        is_complete INTEGER DEFAULT 0,
        assessment_status TEXT DEFAULT 'IN_PROGRESS',
        finalized_at DATETIME,
        is_approved INTEGER DEFAULT 0,
        approved_at DATETIME,
        approved_by TEXT,
        updated_by TEXT,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS roadmap_waves (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        project_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        start_date TEXT,
        end_date TEXT,
        sequence_order INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );`,
  `CREATE TABLE IF NOT EXISTS change_requests (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        project_id TEXT,
        requester_id TEXT NOT NULL,
        title TEXT NOT NULL,
        description TEXT,
        reason TEXT,
        impact TEXT,
        status TEXT DEFAULT 'PENDING',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );`,
  `CREATE TABLE IF NOT EXISTS governance_policies (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        name TEXT NOT NULL,
        description TEXT,
        rules TEXT,
        is_active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );`,
  `CREATE TABLE IF NOT EXISTS project_notification_settings (
        id TEXT PRIMARY KEY,
        project_id TEXT UNIQUE NOT NULL,
        task_overdue_enabled INTEGER DEFAULT 1,
        task_due_today_enabled INTEGER DEFAULT 1,
        blocker_detected_enabled INTEGER DEFAULT 1,
        gate_ready_enabled INTEGER DEFAULT 1,
        decision_required_enabled INTEGER DEFAULT 1,
        escalation_enabled INTEGER DEFAULT 1,
        escalation_days INTEGER DEFAULT 3,
        email_notifications INTEGER DEFAULT 0,
        in_app_notifications INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS project_users (
        project_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        role TEXT DEFAULT 'member',
        assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(project_id, user_id),
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS invitation_events (
        id TEXT PRIMARY KEY,
        invitation_id TEXT NOT NULL,
        event_type TEXT NOT NULL,
        performed_by_user_id TEXT,
        ip_address TEXT,
        user_agent TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(invitation_id) REFERENCES invitations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS billing_margins (
        id TEXT PRIMARY KEY,
        source_type TEXT NOT NULL UNIQUE,
        display_name TEXT,
        base_cost_per_1k REAL DEFAULT 0,
        margin_percent REAL NOT NULL,
        min_charge REAL DEFAULT 0,
        is_active INTEGER DEFAULT 1,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS token_packages (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        tokens INTEGER NOT NULL,
        price_usd REAL NOT NULL,
        bonus_percent INTEGER DEFAULT 0,
        is_popular INTEGER DEFAULT 0,
        sort_order INTEGER DEFAULT 0,
        stripe_price_id TEXT,
        is_active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS user_token_balance (
        user_id TEXT PRIMARY KEY,
        platform_tokens INTEGER DEFAULT 0,
        platform_tokens_bonus INTEGER DEFAULT 0,
        byok_usage_tokens INTEGER DEFAULT 0,
        local_usage_tokens INTEGER DEFAULT 0,
        lifetime_purchased INTEGER DEFAULT 0,
        lifetime_used INTEGER DEFAULT 0,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS token_transactions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        organization_id TEXT,
        type TEXT NOT NULL,
        source_type TEXT,
        tokens INTEGER NOT NULL,
        cost_usd REAL DEFAULT 0,
        margin_usd REAL DEFAULT 0,
        net_revenue_usd REAL DEFAULT 0,
        stripe_payment_id TEXT,
        package_id TEXT,
        llm_provider TEXT,
        model_used TEXT,
        description TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS token_ledger (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        actor_user_id TEXT,
        actor_type TEXT,
        type TEXT,
        amount INTEGER,
        reason TEXT,
        ref_entity_type TEXT,
        ref_entity_id TEXT,
        metadata_json TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS payment_methods (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        type TEXT DEFAULT 'card',
        last_four TEXT,
        brand TEXT,
        exp_month INTEGER,
        exp_year INTEGER,
        is_default INTEGER DEFAULT 0,
        created_at TEXT DEFAULT (datetime('now')),
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS subscription_plans (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        price_monthly REAL,
        price_yearly REAL,
        currency TEXT DEFAULT 'USD',
        stripe_product_id TEXT,
        stripe_monthly_price_id TEXT,
        stripe_yearly_price_id TEXT,
        tokens_included INTEGER DEFAULT 0,
        token_limit INTEGER DEFAULT 0,
        token_overage_rate REAL DEFAULT 0,
        storage_limit_gb REAL DEFAULT 0,
        storage_overage_rate REAL DEFAULT 0,
        seats_included INTEGER DEFAULT 0,
        seat_price_monthly REAL DEFAULT 0,
        billing_model TEXT DEFAULT 'subscription',
        allow_seat_pooling INTEGER DEFAULT 0,
        max_seats INTEGER DEFAULT 0,
        features TEXT DEFAULT '[]',
        is_active INTEGER DEFAULT 1,
        memory_limit_mb REAL DEFAULT 0,
        cpu_quota_percent REAL DEFAULT 100,
        max_concurrent_ai_jobs INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS organization_seats (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        base_seats_included INTEGER DEFAULT 0,
        additional_seats_purchased INTEGER DEFAULT 0,
        total_seats_available INTEGER DEFAULT 0,
        seats_used INTEGER DEFAULT 0,
        billing_model TEXT DEFAULT 'subscription',
        seat_price_monthly REAL DEFAULT 0,
        auto_add_seats_on_invite INTEGER DEFAULT 0,
        seat_pool_enabled INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS organization_members (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'MEMBER',
        status TEXT DEFAULT 'ACTIVE',
        invited_by_user_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(invited_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
        UNIQUE(organization_id, user_id)
    )`,
  `CREATE INDEX IF NOT EXISTS idx_org_members_user ON organization_members(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_org_members_org ON organization_members(organization_id)`,
  `CREATE TABLE IF NOT EXISTS organization_billing (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL UNIQUE,
        subscription_plan_id TEXT,
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT,
        billing_email TEXT,
        billing_address TEXT,
        payment_method_last4 TEXT,
        payment_method_brand TEXT,
        current_period_start DATETIME,
        current_period_end DATETIME,
        token_limit INTEGER DEFAULT 0,
        storage_limit_gb REAL DEFAULT 0,
        status TEXT DEFAULT 'active',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(subscription_plan_id) REFERENCES subscription_plans(id)
    )`,
  `CREATE TABLE IF NOT EXISTS usage_records (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        user_id TEXT,
        type TEXT NOT NULL,
        amount INTEGER NOT NULL,
        action TEXT,
        metadata TEXT,
        recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS usage_summaries (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        period_start DATE NOT NULL,
        period_end DATE NOT NULL,
        tokens_used INTEGER DEFAULT 0,
        tokens_included INTEGER DEFAULT 0,
        tokens_overage INTEGER DEFAULT 0,
        storage_bytes_peak INTEGER DEFAULT 0,
        storage_gb_included REAL DEFAULT 0,
        storage_gb_overage REAL DEFAULT 0,
        overage_amount REAL DEFAULT 0,
        billed INTEGER DEFAULT 0,
        stripe_invoice_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(organization_id, period_start)
    )`,
  `CREATE TABLE IF NOT EXISTS invoices (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        stripe_invoice_id TEXT UNIQUE,
        invoice_number TEXT,
        subtotal REAL,
        tax_amount REAL,
        total REAL,
        amount_paid REAL,
        amount_due REAL,
        currency TEXT DEFAULT 'USD',
        status TEXT,
        due_date DATETIME,
        paid_at DATETIME,
        period_start DATE,
        period_end DATE,
        pdf_url TEXT,
        line_items TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS plan_features (
        id TEXT PRIMARY KEY,
        plan_id TEXT NOT NULL,
        feature_key TEXT NOT NULL,
        enabled INTEGER DEFAULT 1,
        limit_value INTEGER,
        FOREIGN KEY(plan_id) REFERENCES subscription_plans(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS spending_alerts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        type TEXT NOT NULL,
        threshold REAL NOT NULL,
        threshold_type TEXT DEFAULT 'absolute',
        action TEXT DEFAULT 'notify',
        notify_emails TEXT,
        is_active INTEGER DEFAULT 1,
        last_triggered_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS stripe_events (
        id TEXT PRIMARY KEY,
        event_id TEXT UNIQUE NOT NULL,
        event_type TEXT NOT NULL,
        organization_id TEXT,
        processed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        payload TEXT,
        status TEXT DEFAULT 'processed',
        error_message TEXT,
        retry_count INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS payment_attempts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        invoice_id TEXT,
        subscription_id TEXT,
        amount INTEGER NOT NULL,
        currency TEXT DEFAULT 'USD',
        status TEXT NOT NULL,
        stripe_payment_intent_id TEXT,
        stripe_charge_id TEXT,
        failure_code TEXT,
        failure_reason TEXT,
        attempt_number INTEGER DEFAULT 1,
        payment_method_id TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id),
        FOREIGN KEY (invoice_id) REFERENCES invoices(id)
    )`,
  `CREATE TABLE IF NOT EXISTS dunning_states (
        id TEXT PRIMARY KEY,
        organization_id TEXT UNIQUE NOT NULL,
        subscription_id TEXT,
        current_step INTEGER DEFAULT 0,
        max_steps INTEGER DEFAULT 4,
        last_attempt_at DATETIME,
        next_attempt_at DATETIME,
        status TEXT DEFAULT 'active',
        total_amount_due INTEGER DEFAULT 0,
        currency TEXT DEFAULT 'USD',
        emails_sent INTEGER DEFAULT 0,
        last_email_sent_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS subscription_state_history (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        subscription_id TEXT NOT NULL,
        previous_state TEXT,
        new_state TEXT NOT NULL,
        trigger_event TEXT,
        trigger_event_id TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS checkout_sessions (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        user_id TEXT,
        stripe_session_id TEXT UNIQUE NOT NULL,
        plan_id TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        mode TEXT DEFAULT 'subscription',
        success_url TEXT,
        cancel_url TEXT,
        customer_email TEXT,
        amount_total INTEGER,
        currency TEXT DEFAULT 'USD',
        expires_at DATETIME,
        completed_at DATETIME,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id),
        FOREIGN KEY (user_id) REFERENCES users(id)
    )`,
  `CREATE TABLE IF NOT EXISTS proration_records (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        subscription_id TEXT NOT NULL,
        old_plan_id TEXT NOT NULL,
        new_plan_id TEXT NOT NULL,
        proration_amount INTEGER NOT NULL,
        credit_amount INTEGER DEFAULT 0,
        charge_amount INTEGER DEFAULT 0,
        currency TEXT DEFAULT 'USD',
        effective_date DATETIME NOT NULL,
        billing_period_start DATETIME,
        billing_period_end DATETIME,
        stripe_invoice_item_id TEXT,
        status TEXT DEFAULT 'pending',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS billing_usage_events (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        subscription_id TEXT,
        metric_name TEXT NOT NULL,
        quantity REAL NOT NULL,
        unit_price REAL,
        total_amount REAL,
        currency TEXT DEFAULT 'USD',
        timestamp DATETIME NOT NULL,
        idempotency_key TEXT UNIQUE,
        stripe_usage_record_id TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS billing_credits (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        amount INTEGER NOT NULL,
        currency TEXT DEFAULT 'USD',
        reason TEXT,
        source TEXT,
        source_id TEXT,
        expires_at DATETIME,
        used_amount INTEGER DEFAULT 0,
        status TEXT DEFAULT 'active',
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS billing_email_queue (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        email_type TEXT NOT NULL,
        recipient_email TEXT NOT NULL,
        recipient_name TEXT,
        subject TEXT NOT NULL,
        template_key TEXT NOT NULL,
        template_data TEXT,
        attachments TEXT,
        status TEXT DEFAULT 'pending',
        priority INTEGER DEFAULT 5,
        scheduled_at DATETIME,
        sent_at DATETIME,
        error_message TEXT,
        retry_count INTEGER DEFAULT 0,
        max_retries INTEGER DEFAULT 3,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS billing_notification_preferences (
        id TEXT PRIMARY KEY,
        organization_id TEXT UNIQUE NOT NULL,
        invoice_created INTEGER DEFAULT 1,
        invoice_paid INTEGER DEFAULT 1,
        invoice_overdue INTEGER DEFAULT 1,
        payment_failed INTEGER DEFAULT 1,
        payment_method_expiring INTEGER DEFAULT 1,
        subscription_renewed INTEGER DEFAULT 1,
        subscription_canceled INTEGER DEFAULT 1,
        credit_note_issued INTEGER DEFAULT 1,
        usage_threshold_warning INTEGER DEFAULT 1,
        additional_recipients TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS billing_disputes (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        stripe_dispute_id TEXT UNIQUE NOT NULL,
        stripe_charge_id TEXT NOT NULL,
        amount INTEGER NOT NULL,
        currency TEXT DEFAULT 'USD',
        reason TEXT,
        status TEXT DEFAULT 'warning_needs_response',
        evidence_due_by DATETIME,
        is_charge_refundable INTEGER DEFAULT 0,
        outcome TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS billing_refunds (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        invoice_id TEXT,
        payment_attempt_id TEXT,
        stripe_refund_id TEXT UNIQUE,
        stripe_charge_id TEXT,
        amount INTEGER NOT NULL,
        currency TEXT DEFAULT 'USD',
        reason TEXT,
        status TEXT DEFAULT 'pending',
        failure_reason TEXT,
        receipt_number TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id),
        FOREIGN KEY (invoice_id) REFERENCES invoices(id)
    )`,
  `CREATE TABLE IF NOT EXISTS billing_invoices (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        amount_due REAL,
        currency TEXT DEFAULT 'USD',
        status TEXT,
        stripe_invoice_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS stage_gates (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        gate_type TEXT NOT NULL,
        from_phase TEXT,
        to_phase TEXT,
        status TEXT DEFAULT 'PENDING',
        approved_by TEXT,
        approved_at DATETIME,
        notes TEXT,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS decisions (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        project_id TEXT,
        title TEXT NOT NULL,
        description TEXT,
        -- Newer schema (DecisionController) fields
        initiative_id TEXT,
        task_id TEXT,
        type TEXT DEFAULT 'APPROVAL',
        decision_maker_id TEXT,
        deadline DATETIME,
        escalation_deadline DATETIME,
        created_by TEXT,
        priority TEXT DEFAULT 'MEDIUM',
        impact TEXT DEFAULT 'MEDIUM',
        escalation_level TEXT DEFAULT 'none',
        pmo_domain TEXT,
        required INTEGER DEFAULT 0,
        -- Legacy-compatible fields still used in some code paths
        decision_owner_id TEXT,
        related_object_type TEXT,
        related_object_id TEXT,
        due_date DATETIME,
        options TEXT,
        criteria TEXT,
        status TEXT DEFAULT 'pending',
        selected_option TEXT,
        decision_rationale TEXT,
        decided_at DATETIME,
        audit_trail TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS decision_impacts (
        id TEXT PRIMARY KEY,
        decision_id TEXT NOT NULL,
        impacted_type TEXT NOT NULL,
        impacted_id TEXT NOT NULL,
        impact_description TEXT,
        is_blocker INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(decision_id) REFERENCES decisions(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS decision_history (
        id TEXT PRIMARY KEY,
        decision_id TEXT NOT NULL,
        action TEXT,
        old_status TEXT,
        new_status TEXT,
        changed_by TEXT,
        details TEXT,
        changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(decision_id) REFERENCES decisions(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS decision_stakeholders (
        id TEXT PRIMARY KEY,
        decision_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        role TEXT DEFAULT 'informed',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(decision_id) REFERENCES decisions(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS kpi_results (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        kpi_id TEXT,
        value REAL,
        measured_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS llm_providers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        provider TEXT NOT NULL,
        description TEXT,
        api_key TEXT,
        endpoint TEXT,
        model_id TEXT,
        cost_per_1k REAL DEFAULT 0,
        input_cost_per_1k REAL DEFAULT 0,
        output_cost_per_1k REAL DEFAULT 0,
        markup_multiplier REAL DEFAULT 1.0,
        is_active INTEGER DEFAULT 1,
        is_default INTEGER DEFAULT 0,
        visibility TEXT DEFAULT 'public',
        priority INTEGER DEFAULT 0,
        last_health_check TEXT,
        health_status TEXT DEFAULT 'unknown',
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `INSERT OR IGNORE INTO superadmin_ai_settings(id) VALUES('global')`,
  `INSERT OR IGNORE INTO organizations(id, name, plan, status) VALUES('org-dbr77-system', 'DBR77 System', 'enterprise', 'active')`,
  `REPLACE INTO users(id, organization_id, email, password, first_name, last_name, role, status) VALUES('admin-001', 'org-dbr77-system', 'admin@dbr77.com', '$2b$08$fwxcIJu6Rb9YIHYuWhkd5uKPsjSr/26rEfb20ldkMlS08WpfswmYa', 'Super', 'Admin', 'SUPERADMIN', 'active')`,
  `CREATE TABLE IF NOT EXISTS organization_limits (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL UNIQUE,
        max_projects INTEGER DEFAULT 3,
        max_users INTEGER DEFAULT 5,
        max_ai_calls_per_day INTEGER DEFAULT 50,
        max_initiatives INTEGER DEFAULT 10,
        max_storage_mb REAL DEFAULT 100,
        max_total_tokens INTEGER DEFAULT 100000,
        ai_roles_enabled_json TEXT DEFAULT '["ADVISOR"]',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_project_memory (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        memory_type TEXT NOT NULL,
        content TEXT NOT NULL,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_organization_memory (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        pmo_maturity TEXT DEFAULT 'BASIC',
        cultural_tone TEXT,
        risk_appetite TEXT,
        industry_focus TEXT,
        last_updated DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS usage_counters (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        counter_date DATE NOT NULL,
        ai_calls_count INTEGER DEFAULT 0,
        projects_count INTEGER DEFAULT 0,
        users_count INTEGER DEFAULT 0,
        initiatives_count INTEGER DEFAULT 0,
        storage_used_mb REAL DEFAULT 0,
        UNIQUE(organization_id, counter_date)
    )`,
  `CREATE TABLE IF NOT EXISTS ai_partial_responses (
        id TEXT PRIMARY KEY,
        session_id TEXT UNIQUE NOT NULL,
        user_id TEXT NOT NULL,
        organization_id TEXT NOT NULL,
        content TEXT NOT NULL,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_audit_logs (
        id TEXT PRIMARY KEY,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        user_id TEXT,
        organization_id TEXT,
        project_id TEXT,
        capability TEXT,
        action_type TEXT,
        action_description TEXT,
        context_snapshot TEXT,
        data_sources_used TEXT,
        ai_role TEXT,
        policy_level TEXT,
        confidence_level TEXT,
        ai_suggestion TEXT,
        user_decision TEXT,
        user_feedback TEXT,
        ai_project_role TEXT,
        justification TEXT,
        approving_user TEXT,
        regulatory_mode INTEGER DEFAULT 0,
        reasoning_summary TEXT,
        data_used_json TEXT,
        constraints_applied_json TEXT,
        correlation_id TEXT,
        model TEXT,
        latency_ms INTEGER,
        has_screen_context INTEGER DEFAULT 0,
        screen_context_hash TEXT,
        success INTEGER DEFAULT 1,
        error_message TEXT,
        tokens_used INTEGER DEFAULT 0,
        cost_usd REAL DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_actions (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        organization_id TEXT,
        project_id TEXT,
        action_type TEXT,
        payload TEXT,
        draft_content TEXT,
        required_policy_level TEXT,
        current_policy_level TEXT,
        requires_approval INTEGER DEFAULT 0,
        status TEXT DEFAULT 'PENDING',
        approved_at DATETIME,
        approved_by TEXT,
        executed_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_user_preferences (
        user_id TEXT PRIMARY KEY,
        preferred_tone TEXT DEFAULT 'EXPERT',
        education_mode INTEGER DEFAULT 0,
        preferred_language TEXT DEFAULT 'pl',
        preferred_detail_level TEXT DEFAULT 'balanced',
        enable_proactive_nudges INTEGER DEFAULT 1,
        enable_max_mode INTEGER DEFAULT 0,
        custom_instructions TEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_system_prompts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        key TEXT UNIQUE NOT NULL,
        description TEXT,
        content TEXT NOT NULL,
        context_config TEXT DEFAULT '{}',
        is_active INTEGER DEFAULT 1,
        version INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_knowledge_embeddings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        document_id TEXT,
        chunk_index INTEGER DEFAULT 0,
        chunk_text TEXT NOT NULL,
        embedding TEXT,
        metadata TEXT DEFAULT '{}',
        source_type TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_feature_control (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        feature_key TEXT UNIQUE NOT NULL,
        is_enabled INTEGER DEFAULT 1,
        min_role TEXT DEFAULT 'USER',
        allowed_models TEXT,
        max_tokens_per_req INTEGER,
        requires_approval INTEGER DEFAULT 0,
        emergency_disable INTEGER DEFAULT 0,
        disable_reason TEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_conversations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        conversation_id TEXT UNIQUE NOT NULL,
        user_id TEXT NOT NULL,
        organization_id TEXT,
        project_id TEXT,
        title TEXT,
        messages TEXT DEFAULT '[]',
        metadata TEXT DEFAULT '{}',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  // L6.14 compatibility: "online SaaS" chat + memory tables (used by integration tests)
  `CREATE TABLE IF NOT EXISTS conversations (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        organization_id TEXT,
        title TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS conversation_messages (
        id TEXT PRIMARY KEY,
        conversation_id TEXT NOT NULL,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        metadata TEXT DEFAULT '{}',
        FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS organization_memory (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        memory_type TEXT NOT NULL,
        memory_data TEXT DEFAULT '{}',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS llm_usage_logs (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        organization_id TEXT NOT NULL,
        model TEXT,
        input_tokens INTEGER DEFAULT 0,
        output_tokens INTEGER DEFAULT 0,
        cost_usd REAL DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_cost_tracking (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        organization_id TEXT NOT NULL,
        month TEXT NOT NULL,
        total_tokens INTEGER DEFAULT 0,
        total_cost_usd REAL DEFAULT 0,
        budget_limit_usd REAL,
        last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(organization_id, month)
    )`,
  `CREATE TABLE IF NOT EXISTS access_requests(
        id TEXT PRIMARY KEY,
        email TEXT NOT NULL,
        first_name TEXT,
        last_name TEXT,
        phone TEXT,
        organization_id TEXT,
        organization_name TEXT,
        requested_role TEXT DEFAULT 'USER',
        status TEXT DEFAULT 'pending',
        request_type TEXT DEFAULT 'new_user',
        metadata TEXT,
        requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        reviewed_by TEXT,
        reviewed_at TIMESTAMP,
        rejection_reason TEXT,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(reviewed_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS circuit_breaker_state (
        id TEXT PRIMARY KEY,
        service TEXT NOT NULL,
        state TEXT DEFAULT 'CLOSED',
        failures INTEGER DEFAULT 0,
        last_failure DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS admin_audit_logs (
        id TEXT PRIMARY KEY,
        admin_id TEXT,
        action_type TEXT NOT NULL,
        metadata_json TEXT,
        risk_score INTEGER DEFAULT 0,
        risk_level TEXT DEFAULT 'low',
        status TEXT DEFAULT 'unresolved',
        resolved_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS admin_sessions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        mfa_verified INTEGER DEFAULT 0,
        is_active INTEGER DEFAULT 1,
        ip_address TEXT,
        user_agent TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        expires_at DATETIME,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS permissions (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        severity TEXT DEFAULT 'low',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS admin_approval_workflows (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        resource_type TEXT NOT NULL,
        approvers TEXT,
        status TEXT DEFAULT 'active',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS admin_approval_requests (
        id TEXT PRIMARY KEY,
        workflow_id TEXT NOT NULL,
        requester TEXT NOT NULL,
        resource TEXT,
        status TEXT DEFAULT 'pending',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(workflow_id) REFERENCES admin_approval_workflows(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS admin_dashboards (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        config TEXT,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS admin_saved_reports (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        query TEXT,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS admin_report_executions (
        id TEXT PRIMARY KEY,
        report_id TEXT NOT NULL,
        executed_by TEXT,
        status TEXT DEFAULT 'completed',
        result_url TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS system_feedback (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        type TEXT NOT NULL,
        message TEXT NOT NULL,
        rating INTEGER,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS custom_statuses (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        name TEXT NOT NULL,
        color TEXT DEFAULT '#6B7280',
        sort_order INTEGER DEFAULT 0,
        is_default INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS task_comments (
        id TEXT PRIMARY KEY,
        task_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS activity_logs (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        user_id TEXT,
        action TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id TEXT,
        entity_name TEXT,
        old_value TEXT,
        new_value TEXT,
        ip_address TEXT,
        user_agent TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS custom_prompts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        name TEXT NOT NULL,
        context TEXT NOT NULL,
        template TEXT NOT NULL,
        variables TEXT,
        is_active INTEGER DEFAULT 1,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS webhooks (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        url TEXT NOT NULL,
        events TEXT NOT NULL,
        secret TEXT NOT NULL,
        is_active INTEGER DEFAULT 1,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
        FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS ai_logs (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        action TEXT,
        model TEXT,
        input_tokens INTEGER,
        output_tokens INTEGER,
        latency_ms INTEGER,
        topic TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_ideas (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT,
        status TEXT DEFAULT 'new',
        priority TEXT DEFAULT 'medium',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_observations (
        id TEXT PRIMARY KEY,
        content TEXT NOT NULL,
        category TEXT,
        confidence_score REAL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS megatrends (
        id TEXT PRIMARY KEY,
        industry TEXT NOT NULL,
        type TEXT NOT NULL,
        label TEXT NOT NULL,
        description TEXT,
        base_impact_score REAL,
        initial_ring TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS custom_trends (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        company_id TEXT,
        industry TEXT,
        type TEXT,
        label TEXT,
        description TEXT,
        ring TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS maturity_scores (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        category TEXT NOT NULL,
        score REAL DEFAULT 0,
        measured_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS client_context (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        context_key TEXT NOT NULL,
        context_value TEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS knowledge_docs (
        id TEXT PRIMARY KEY,
        filename TEXT NOT NULL,
        filepath TEXT,
        status TEXT DEFAULT 'pending',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS knowledge_chunks (
        id TEXT PRIMARY KEY,
        doc_id TEXT NOT NULL,
        content TEXT NOT NULL,
        chunk_index INTEGER DEFAULT 0,
        embedding TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(doc_id) REFERENCES knowledge_docs(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS webhook_deliveries (
        id TEXT PRIMARY KEY,
        webhook_id TEXT NOT NULL,
        event TEXT NOT NULL,
        status TEXT DEFAULT 'sent',
        response_code INTEGER,
        response_body TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS integrations (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        type TEXT NOT NULL,
        config TEXT,
        is_active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS integration_sync_logs (
        id TEXT PRIMARY KEY,
        integration_id TEXT NOT NULL,
        status TEXT DEFAULT 'success',
        message TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(integration_id) REFERENCES integrations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS system_metrics (
        id TEXT PRIMARY KEY,
        metric_name TEXT NOT NULL,
        metric_value REAL NOT NULL,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS security_events (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        event_type TEXT NOT NULL,
        severity TEXT DEFAULT 'low',
        ip_address TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS security_incidents (
        id TEXT PRIMARY KEY,
        title TEXT,
        description TEXT,
        severity TEXT,
        type TEXT,
        status TEXT DEFAULT 'open',
        metadata_json TEXT,
        resolved_by TEXT,
        resolution_notes TEXT,
        resolved_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(resolved_by) REFERENCES users(id)
    )`,
  `CREATE TABLE IF NOT EXISTS compliance_records (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        type TEXT NOT NULL,
        status TEXT DEFAULT 'compliant',
        evidence_url TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS backup_records (
        id TEXT PRIMARY KEY,
        filename TEXT NOT NULL,
        size INTEGER DEFAULT 0,
        status TEXT DEFAULT 'completed',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS access_codes (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        code TEXT NOT NULL UNIQUE,
        role TEXT DEFAULT 'USER',
        max_uses INTEGER DEFAULT 1,
        current_uses INTEGER DEFAULT 0,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS access_code_usage (
        id TEXT PRIMARY KEY,
        code_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        used_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(code_id) REFERENCES access_codes(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS reports (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        type TEXT,
        config TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS report_blocks (
        id TEXT PRIMARY KEY,
        report_id TEXT NOT NULL,
        type TEXT NOT NULL,
        content TEXT,
        sort_order INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS report_snapshots (
        id TEXT PRIMARY KEY,
        report_id TEXT NOT NULL,
        data TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS multi_framework_assessments (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        frameworks TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS rapid_lean_assessments (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS help_events (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        event_type TEXT NOT NULL,
        context TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS organization_events (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        event_type TEXT NOT NULL,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS task_dependencies (
        id TEXT PRIMARY KEY,
        from_task_id TEXT NOT NULL,
        to_task_id TEXT NOT NULL,
        type TEXT DEFAULT 'hard',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(from_task_id) REFERENCES tasks(id) ON DELETE CASCADE,
        FOREIGN KEY(to_task_id) REFERENCES tasks(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS ai_user_memory (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        memory_type TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS ai_experiments (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        status TEXT DEFAULT 'draft',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_experiment_variants (
        id TEXT PRIMARY KEY,
        experiment_id TEXT NOT NULL,
        name TEXT NOT NULL,
        config TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(experiment_id) REFERENCES ai_experiments(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS system_config (
        config_key TEXT PRIMARY KEY,
        config_value TEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_drafts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        project_id TEXT,
        user_id TEXT NOT NULL,
        draft_type TEXT NOT NULL,
        target_entity_type TEXT,
        target_entity_id TEXT,
        target_field TEXT,
        original_content TEXT,
        suggested_content TEXT NOT NULL,
        diff_data TEXT,
        confidence_score REAL DEFAULT 0.8,
        reasoning TEXT,
        status TEXT DEFAULT 'PENDING',
        reviewed_by TEXT,
        reviewed_at DATETIME,
        review_notes TEXT,
        model_used TEXT,
        prompt_id TEXT,
        tokens_used INTEGER,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id),
        FOREIGN KEY (project_id) REFERENCES projects(id),
        FOREIGN KEY (user_id) REFERENCES users(id),
        FOREIGN KEY (reviewed_by) REFERENCES users(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ai_feedback (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        user_id TEXT,
        interaction_id TEXT,
        draft_id TEXT,
        feedback_type TEXT,
        rating INTEGER,
        comment TEXT,
        capability TEXT,
        model_used TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_learning_patterns (
        id TEXT PRIMARY KEY,
        pattern_type TEXT NOT NULL,
        pattern_data TEXT DEFAULT '{}',
        confidence_score REAL DEFAULT 0,
        occurrence_count INTEGER DEFAULT 0,
        success_count INTEGER DEFAULT 0,
        failure_count INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_instruction_suggestions (
        id TEXT PRIMARY KEY,
        suggested_instruction TEXT NOT NULL,
        category TEXT,
        reason TEXT,
        confidence_score REAL DEFAULT 0,
        status TEXT DEFAULT 'pending',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ai_user_style_profiles (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        tone TEXT,
        format_preference TEXT,
        detail_level TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS ai_style_learning_patterns (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        pattern_type TEXT NOT NULL,
        pattern_data TEXT DEFAULT '{}',
        confidence REAL DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS user_ai_profiles (
        user_id TEXT PRIMARY KEY,
        response_mode_preference TEXT DEFAULT 'standard',
        quick_length_preference TEXT DEFAULT 'short',
        standard_length_preference TEXT DEFAULT 'medium',
        deep_study_length_preference TEXT DEFAULT 'long',
        auto_detect_intent INTEGER DEFAULT 1,
        prefer_bullet_points INTEGER DEFAULT 0,
        prefer_tables INTEGER DEFAULT 0,
        prefer_action_items INTEGER DEFAULT 0,
        include_examples INTEGER DEFAULT 0,
        satisfaction_score REAL DEFAULT 0,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS system_onboarding (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        organization_id TEXT,
        context_data TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS user_api_keys (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        organization_id TEXT,
        display_name TEXT,
        name TEXT,
        key_prefix TEXT,
        key_hash TEXT,
        provider TEXT DEFAULT 'custom',
        scopes TEXT DEFAULT '[]',
        permissions TEXT DEFAULT '[]',
        is_active INTEGER DEFAULT 1,
        usage_count INTEGER DEFAULT 0,
        quota_used INTEGER DEFAULT 0,
        rate_limit INTEGER DEFAULT 1000,
        rate_limit_per_minute INTEGER,
        rate_limit_per_day INTEGER,
        last_used_at DATETIME,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS digitization_analyses (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        status TEXT DEFAULT 'draft',
        project_id TEXT,
        initiative_id TEXT,
        analysis_type TEXT DEFAULT 'financial',
        organization_id TEXT NOT NULL,
        created_by TEXT NOT NULL,
        overall_score REAL,
        completion_percent INTEGER DEFAULT 0,
        axis_scores TEXT,
        imported_from TEXT,
        import_date DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id)
    )`,
  `CREATE TABLE IF NOT EXISTS analysis_financials (
        id TEXT PRIMARY KEY,
        analysis_id TEXT NOT NULL UNIQUE,
        initiative_id TEXT,
        organization_id TEXT NOT NULL,
        initial_investment REAL DEFAULT 0,
        implementation_cost REAL DEFAULT 0,
        annual_operating_cost REAL DEFAULT 0,
        training_cost REAL DEFAULT 0,
        contingency_percent REAL DEFAULT 15,
        annual_cost_savings REAL DEFAULT 0,
        annual_revenue_increase REAL DEFAULT 0,
        productivity_gains_percent REAL DEFAULT 0,
        risk_reduction_value REAL DEFAULT 0,
        implementation_months INTEGER DEFAULT 12,
        benefit_realization_months INTEGER DEFAULT 6,
        analysis_horizon_years INTEGER DEFAULT 5,
        discount_rate REAL DEFAULT 10,
        npv REAL,
        irr REAL,
        payback_months REAL,
        roi_percent REAL,
        currency TEXT DEFAULT 'PLN',
        assumptions TEXT,
        cash_flow_projections TEXT,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        last_calculated_at DATETIME,
        FOREIGN KEY (analysis_id) REFERENCES digitization_analyses(id) ON DELETE CASCADE,
        FOREIGN KEY (initiative_id) REFERENCES initiatives(id) ON DELETE SET NULL
    )`,
  `CREATE TABLE IF NOT EXISTS analysis_financial_scenarios (
        id TEXT PRIMARY KEY,
        analysis_id TEXT NOT NULL,
        organization_id TEXT NOT NULL,
        scenario_type TEXT NOT NULL,
        name TEXT,
        assumptions TEXT,
        financial_data TEXT NOT NULL,
        metrics TEXT NOT NULL,
        is_active INTEGER DEFAULT 0,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (analysis_id) REFERENCES digitization_analyses(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS benefit_tracking (
        id TEXT PRIMARY KEY,
        analysis_id TEXT,
        initiative_id TEXT,
        organization_id TEXT,
        tracking_period TEXT,
        planned_benefits REAL DEFAULT 0,
        actual_benefits REAL DEFAULT 0,
        variance_percent REAL DEFAULT 0,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
  `INSERT OR IGNORE INTO organizations (id, name, plan, status)
    VALUES ('demo-org', 'Demo Organization', 'free', 'active')`,
  `INSERT OR IGNORE INTO users (id, organization_id, email, password, first_name, last_name, role, status)
    VALUES ('demo-user', 'demo-org', 'piotr.wisniewski@demo.com', '123456', 'Demo', 'User', 'user', 'active')`,
  `INSERT OR IGNORE INTO users (id, organization_id, email, password, first_name, last_name, role, status)
    VALUES ('e2e-user', 'demo-org', 'e2e-test@consultinity.dev', '$2b$10$xKTb1.5vZT.2ThRs/iRCLuHni43AUHaG7Hf9STKRQCudtsY1ZXxTe', 'E2E', 'User', 'user', 'active')`,
  `CREATE TABLE IF NOT EXISTS budget_expenses (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        amount REAL NOT NULL,
        category TEXT NOT NULL CHECK (category IN ('TOKENS', 'STORAGE', 'COMPUTE', 'API', 'OTHER')),
        description TEXT,
        metadata TEXT DEFAULT '{}',
        recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS user_quotas (
        user_id TEXT PRIMARY KEY,
        storage_quota_mb INTEGER,
        api_rate_limit_per_hour INTEGER,
        ai_requests_per_day INTEGER,
        max_concurrent_jobs INTEGER,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
];
