export const TEST_SCHEMA = [
    `CREATE TABLE IF NOT EXISTS audit_logs (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        organization_id TEXT,
        action TEXT NOT NULL,
        resource_type TEXT NOT NULL,
        resource_id TEXT,
        details TEXT DEFAULT '{}',
        ip_address TEXT,
        user_agent TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS assessment_workflows (
        id TEXT PRIMARY KEY,
        assessment_id TEXT,
        project_id TEXT,
        organization_id TEXT,
        status TEXT DEFAULT 'DRAFT',
        current_version INTEGER DEFAULT 1,
        created_by TEXT,
        submitted_by TEXT,
        approved_by TEXT,
        rejected_by TEXT,
        submitted_at DATETIME,
        approved_at DATETIME,
        rejected_at DATETIME,
        approval_notes TEXT,
        rejection_reason TEXT,
        axis_issues TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS assessment_reviews (
        id TEXT PRIMARY KEY,
        workflow_id TEXT,
        reviewer_id TEXT,
        reviewer_role TEXT,
        status TEXT DEFAULT 'PENDING',
        rating INTEGER,
        comments TEXT,
        axis_comments TEXT,
        recommendation TEXT,
        requested_at DATETIME,
        due_date DATETIME,
        completed_at DATETIME
    )`,
    `CREATE TABLE IF NOT EXISTS assessment_versions (
        id TEXT PRIMARY KEY,
        assessment_id TEXT,
        version INTEGER,
        assessment_data TEXT,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS assessment_axis_comments (
        id TEXT PRIMARY KEY,
        assessment_id TEXT,
        axis_id TEXT,
        user_id TEXT,
        comment TEXT,
        parent_comment_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS rapid_lean_assessments`,
    `CREATE TABLE IF NOT EXISTS rapid_lean_assessments (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        project_id TEXT,
        assessment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
        value_stream_score REAL DEFAULT 0,
        waste_elimination_score REAL DEFAULT 0,
        flow_pull_score REAL DEFAULT 0,
        quality_source_score REAL DEFAULT 0,
        continuous_improvement_score REAL DEFAULT 0,
        visual_management_score REAL DEFAULT 0,
        overall_score REAL DEFAULT 0,
        industry_benchmark REAL DEFAULT 3.3,
        ai_recommendations TEXT DEFAULT '[]',
        top_gaps TEXT DEFAULT '[]',
        questionnaire_responses TEXT DEFAULT '{}',
        drd_mapping TEXT DEFAULT '{}',
        observation_count INTEGER DEFAULT 0,
        report_generated INTEGER DEFAULT 0,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS rapid_lean_observations (
        id TEXT PRIMARY KEY,
        assessment_id TEXT,
        organization_id TEXT NOT NULL,
        project_id TEXT,
        template_id TEXT NOT NULL,
        location TEXT,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        answers TEXT DEFAULT '{}',
        photos TEXT DEFAULT '[]',
        notes TEXT,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS rapid_lean_reports (
        id TEXT PRIMARY KEY,
        assessment_id TEXT NOT NULL,
        organization_id TEXT NOT NULL,
        project_id TEXT,
        report_type TEXT DEFAULT 'detailed',
        format TEXT DEFAULT 'pdf',
        file_url TEXT,
        report_data TEXT DEFAULT '{}',
        generated_by TEXT,
        generated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS assessments`,
    `CREATE TABLE IF NOT EXISTS assessments (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        name TEXT,
        description TEXT,
        status TEXT DEFAULT 'DRAFT',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS maturity_assessments`,
    `CREATE TABLE IF NOT EXISTS maturity_assessments (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        project_id TEXT,
        name TEXT,
        assessment_date DATE,
        planning_score REAL,
        decision_score REAL,
        execution_score REAL,
        monitoring_score REAL,
        collaboration_score REAL,
        axis_scores TEXT DEFAULT '[]',
        completed_axes TEXT DEFAULT '[]',
        overall_as_is REAL DEFAULT 0,
        overall_to_be REAL DEFAULT 0,
        overall_gap REAL DEFAULT 0,
        overall_score REAL,
        gap_analysis TEXT DEFAULT '{}',
        gap_analysis_summary TEXT,
        is_complete INTEGER DEFAULT 0,
        assessment_status TEXT DEFAULT 'IN_PROGRESS',
        finalized_at DATETIME,
        is_approved INTEGER DEFAULT 0,
        approved_at DATETIME,
        approved_by TEXT,
        updated_by TEXT,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS notifications (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        organization_id TEXT,
        type TEXT,
        title TEXT,
        message TEXT,
        data TEXT,
        severity TEXT,
        read INTEGER DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS status_reports`,
    `CREATE TABLE IF NOT EXISTS status_reports (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        initiative_id TEXT,
        project_id TEXT,
        period_type TEXT DEFAULT 'WEEKLY',
        period_start DATETIME,
        period_end DATETIME,
        period_label TEXT,
        overall_status TEXT,
        overall_trend TEXT,
        sections_json TEXT,
        executive_summary TEXT,
        accomplishments TEXT,
        next_steps TEXT,
        escalations TEXT,
        risks_and_issues TEXT,
        recommendations TEXT,
        progress_percent INTEGER,
        budget_consumed_percent INTEGER,
        tasks_completed INTEGER,
        tasks_total INTEGER,
        open_risks INTEGER,
        open_issues INTEGER,
        pending_decisions INTEGER,
        generation_method TEXT,
        status TEXT DEFAULT 'DRAFT',
        summary TEXT,
        blockers TEXT,
        report_date DATETIME DEFAULT CURRENT_TIMESTAMP,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME,
        approved_by TEXT,
        approved_at DATETIME,
        published_at DATETIME
    )`,
    `DROP TABLE IF EXISTS initiatives`,
    `CREATE TABLE IF NOT EXISTS initiatives (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        project_id TEXT,
        name TEXT,
        title TEXT,
        description TEXT,
        summary TEXT,
        status TEXT DEFAULT 'DRAFT',
        priority TEXT DEFAULT 'MEDIUM',
        progress INTEGER DEFAULT 0,
        blocked_reason TEXT,
        start_date DATETIME,
        end_date DATETIME,
        owner_id TEXT,
        owner_business_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS initiative_budgets`,
    `CREATE TABLE IF NOT EXISTS initiative_budgets (
        id TEXT PRIMARY KEY,
        initiative_id TEXT NOT NULL,
        organization_id TEXT NOT NULL,
        budget_type TEXT NOT NULL DEFAULT 'COMBINED',
        planned_amount REAL DEFAULT 0,
        approved_amount REAL DEFAULT 0,
        currency TEXT DEFAULT 'PLN',
        fiscal_year INTEGER,
        contingency_percent REAL DEFAULT 10,
        contingency_amount REAL DEFAULT 0,
        notes TEXT,
        status TEXT DEFAULT 'DRAFT',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS budget_line_items`,
    `CREATE TABLE IF NOT EXISTS budget_line_items (
        id TEXT PRIMARY KEY,
        budget_id TEXT NOT NULL,
        category TEXT,
        subcategory TEXT,
        description TEXT,
        budget_type TEXT DEFAULT 'OPEX',
        planned_amount REAL DEFAULT 0,
        actual_amount REAL DEFAULT 0,
        committed_amount REAL DEFAULT 0,
        variance_amount REAL DEFAULT 0,
        variance_percent REAL DEFAULT 0,
        forecast_amount REAL DEFAULT 0,
        sort_order INTEGER DEFAULT 0,
        status TEXT DEFAULT 'PLANNED',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        email TEXT UNIQUE,
        password TEXT,
        first_name TEXT,
        last_name TEXT,
        role TEXT DEFAULT 'user',
        avatar_url TEXT,
        impersonator_id TEXT,
        status TEXT DEFAULT 'active',
        email_verified INTEGER DEFAULT 0,
        email_verification_token TEXT,
        email_verification_expires_at DATETIME,
        email_verification_sent_at DATETIME,
        mfa_enabled INTEGER DEFAULT 0,
        mfa_secret TEXT,
        mfa_sms_enabled INTEGER DEFAULT 0,
        mfa_primary_method TEXT,
        mfa_verified_at DATETIME,
        mfa_backup_codes TEXT,
        phone_number TEXT,
        phone_verified INTEGER DEFAULT 0,
        last_login DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS decisions`,
    `CREATE TABLE IF NOT EXISTS decisions (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL,
        decision_type TEXT NOT NULL,
        related_object_type TEXT NOT NULL,
        related_object_id TEXT NOT NULL,
        decision_owner_id TEXT NOT NULL,
        requested_by_id TEXT,
        status TEXT DEFAULT 'PENDING',
        required INTEGER DEFAULT 1,
        priority TEXT DEFAULT 'MEDIUM',
        due_date DATETIME,
        title TEXT NOT NULL,
        description TEXT,
        outcome TEXT,
        rationale TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        decided_at DATETIME,
        audit_trail TEXT DEFAULT '[]'
    )`,
    `CREATE TABLE IF NOT EXISTS ai_nudge_log (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        organization_id TEXT,
        nudge_id TEXT NOT NULL,
        shown_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        acted_upon INTEGER DEFAULT 0,
        action TEXT,
        acted_at DATETIME
    )`,
    `CREATE TABLE IF NOT EXISTS ai_nudge_dismissals (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        nudge_id TEXT NOT NULL,
        dismissed_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS ai_rate_limits (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        rule_name TEXT,
        applies_to TEXT DEFAULT 'all',
        limit_type TEXT DEFAULT 'per_day',
        limit_value INTEGER DEFAULT 1000,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS budget_transactions (
        id TEXT PRIMARY KEY,
        budget_id TEXT NOT NULL,
        line_item_id TEXT,
        transaction_type TEXT NOT NULL,
        amount REAL NOT NULL,
        currency TEXT DEFAULT 'PLN',
        description TEXT,
        vendor TEXT,
        invoice_number TEXT,
        transaction_date TEXT NOT NULL,
        period_month INTEGER,
        period_year INTEGER,
        cost_center TEXT,
        gl_account TEXT,
        status TEXT DEFAULT 'PENDING',
        created_by TEXT,
        approved_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS llm_providers`,
    `CREATE TABLE IF NOT EXISTS llm_providers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        provider TEXT NOT NULL,
        description TEXT,
        api_key TEXT,
        endpoint TEXT,
        model_id TEXT,
        cost_per_1k REAL DEFAULT 0,
        input_cost_per_1k REAL DEFAULT 0,
        output_cost_per_1k REAL DEFAULT 0,
        markup_multiplier REAL DEFAULT 1.0,
        is_active INTEGER DEFAULT 1,
        is_default INTEGER DEFAULT 0,
        visibility TEXT DEFAULT 'public',
        priority INTEGER DEFAULT 0,
        last_health_check TEXT,
        health_status TEXT DEFAULT 'unknown',
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
    `DROP TABLE IF EXISTS ai_learning_interactions`,
    `CREATE TABLE IF NOT EXISTS ai_learning_interactions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        organization_id TEXT,
        request_type TEXT NOT NULL,
        prompt_hash TEXT,
        response_quality REAL,
        feedback_score REAL,
        auto_feedback_score REAL,
        auto_feedback_reason TEXT,
        model TEXT,
        latency_ms INTEGER,
        token_count INTEGER,
        prompt_signature TEXT,
        response_signature TEXT,
        metadata TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS ai_learned_patterns (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL,
        request_type TEXT NOT NULL,
        pattern_type TEXT,
        pattern_key TEXT,
        pattern_data TEXT,
        successful_patterns TEXT,
        failed_patterns TEXT,
        sample_count INTEGER DEFAULT 0,
        confidence REAL DEFAULT 0,
        last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS ai_nudge_suppressions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL,
        nudge_type TEXT NOT NULL,
        suppressed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        expires_at DATETIME,
        UNIQUE(user_id, nudge_type)
    )`,
    `CREATE TABLE IF NOT EXISTS ai_ab_experiments (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        prompt_id TEXT NOT NULL,
        variants TEXT NOT NULL,
        traffic_split TEXT NOT NULL,
        min_sample_size INTEGER DEFAULT 100,
        confidence_level REAL DEFAULT 0.95,
        primary_metric TEXT DEFAULT 'user_satisfaction',
        status TEXT DEFAULT 'draft',
        stop_reason TEXT,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        started_at DATETIME,
        ended_at DATETIME
    )`,
    `CREATE TABLE IF NOT EXISTS ai_ab_assignments (
        id TEXT PRIMARY KEY,
        experiment_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        variant_index INTEGER NOT NULL,
        assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(experiment_id, user_id)
    )`,
    `CREATE TABLE IF NOT EXISTS ai_ab_outcomes (
        id TEXT PRIMARY KEY,
        experiment_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        variant_index INTEGER NOT NULL,
        metric TEXT NOT NULL,
        value REAL NOT NULL,
        recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS ai_system_prompts (
        id TEXT PRIMARY KEY,
        key TEXT UNIQUE NOT NULL,
        description TEXT,
        content TEXT NOT NULL,
        context_config TEXT DEFAULT '{}',
        is_active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS help_analytics (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        organization_id TEXT,
        search_query TEXT,
        results_count INTEGER DEFAULT 0,
        clicked_result TEXT,
        session_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS help_feedback (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        organization_id TEXT,
        content_id TEXT,
        content_type TEXT,
        rating INTEGER,
        helpful INTEGER DEFAULT 0,
        comment TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS initiative_templates (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        category TEXT,
        template_data TEXT,
        default_duration_days INTEGER DEFAULT 90,
        default_budget REAL DEFAULT 0,
        is_active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS management_report_templates (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        name TEXT NOT NULL,
        description TEXT,
        template_type TEXT,
        template_data TEXT,
        sections TEXT,
        is_active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS demo_templates (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        seed_data_json TEXT,
        template_type TEXT,
        is_active INTEGER DEFAULT 1,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS action_decisions (
        id TEXT PRIMARY KEY,
        initiative_id TEXT,
        action_id TEXT,
        decision_type TEXT,
        status TEXT DEFAULT 'PENDING',
        decided_by TEXT,
        decided_at DATETIME,
        notes TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    // Tables from auth.test.js that might be missing in setup.ts schemas
    `CREATE TABLE IF NOT EXISTS organizations (
        id TEXT PRIMARY KEY,
        name TEXT,
        plan TEXT DEFAULT 'free',
        status TEXT DEFAULT 'active',
        mfa_required INTEGER DEFAULT 0,
        mfa_grace_period_days INTEGER,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS mfa_attempts (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        attempt_type TEXT,
        success INTEGER DEFAULT 0,
        ip_address TEXT,
        user_agent TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS trusted_devices (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        device_fingerprint TEXT,
        device_name TEXT,
        last_used_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS refresh_tokens (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        token_hash TEXT,
        token_family TEXT,
        device_info TEXT,
        ip_address TEXT,
        user_agent TEXT,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        revoked_at DATETIME,
        revoked_reason TEXT
    )`,
    `CREATE TABLE IF NOT EXISTS revoked_tokens (
        jti TEXT PRIMARY KEY,
        user_id TEXT,
        expires_at DATETIME,
        reason TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS access_requests (
        id TEXT PRIMARY KEY,
        email TEXT,
        first_name TEXT,
        last_name TEXT,
        organization_id TEXT,
        organization_name TEXT,
        status TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS access_codes (
        id TEXT PRIMARY KEY,
        code TEXT UNIQUE,
        description TEXT,
        max_uses INTEGER DEFAULT 0,
        current_uses INTEGER DEFAULT 0,
        is_active INTEGER DEFAULT 1,
        expires_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS access_code_usage (
        id TEXT PRIMARY KEY,
        code_id TEXT,
        user_id TEXT,
        used_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS activity_logs (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        user_id TEXT,
        action TEXT,
        entity_type TEXT,
        entity_id TEXT,
        entity_name TEXT,
        old_value TEXT,
        new_value TEXT,
        ip_address TEXT,
        user_agent TEXT,
        correlation_id TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS projects (
        id TEXT PRIMARY KEY,
        organization_id TEXT,
        name TEXT,
        description TEXT,
        goal TEXT,
        status TEXT DEFAULT 'active',
        owner_id TEXT,
        start_date DATETIME,
        end_date DATETIME,
        created_by TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS project_members (
        id TEXT PRIMARY KEY,
        project_id TEXT,
        user_id TEXT,
        role TEXT DEFAULT 'MEMBER',
        joined_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS multi_framework_assessments (
        id TEXT PRIMARY KEY,
        project_id TEXT,
        name TEXT,
        status TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS knowledge_docs (
        id TEXT PRIMARY KEY,
        project_id TEXT,
        title TEXT,
        url TEXT,
        deleted_at DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS workstreams (
        id TEXT PRIMARY KEY,
        project_id TEXT,
        name TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS project_notification_settings (
        id TEXT PRIMARY KEY,
        project_id TEXT,
        task_overdue_enabled INTEGER DEFAULT 1,
        task_due_today_enabled INTEGER DEFAULT 1,
        blocker_detected_enabled INTEGER DEFAULT 1,
        gate_ready_enabled INTEGER DEFAULT 1,
        decision_required_enabled INTEGER DEFAULT 1,
        escalation_enabled INTEGER DEFAULT 1,
        escalation_days INTEGER DEFAULT 3,
        email_notifications INTEGER DEFAULT 0,
        in_app_notifications INTEGER DEFAULT 1,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`
];
