/**
 * V8 read-only Planning continuity bridge — org-scoped WBS snapshot, cross-initiative
 * dependencies, decision chains, and org-wide pending decision chains.
 * Namespace: /api/v8/planning (mounted by v8/index).
 *
 * @module routes/v8/planning.routes
 */

import type { Response } from 'express';
import { Router } from 'express';
import { z } from 'zod';

import type { AuthRequest } from '../../middleware/auth.middleware.js';
import { getV8Context } from '../../middleware/v8Auth.middleware.js';
import type { CreateInitiativeData } from '../../services/initiative/InitiativeDefinitionService.js';
import {
  buildInitiativeOutboundHandoffPayload,
  type InitiativeHandoffKind,
} from '../../services/initiative/initiativeLifecycleCanon.js';
import initiativeService from '../../services/initiativeService.js';
import {
  getCriticalPath,
  getCrossInitiativeDependencies,
  getDecisionChainsByInitiative,
  getDecompositionTree,
  getPendingDecisions,
  validateWBSCompleteness,
} from '../../services/v8/planningContinuityService.js';
import {
  getInitiativeBudgetItemsRead,
  getInitiativeCommentsRead,
  getInitiativeDetailRead,
  getInitiativeGateReadinessRead,
  getInitiativeGateRolesRead,
  getInitiativeHistoryRead,
  getInitiativeIntangibleAssetsRead,
  getInitiativeKpisRead,
  getInitiativeRaidRead,
  getInitiativeResourcesRead,
  getInitiativeStakeholdersRead,
  getInitiativeStatusHistoryRead,
  getInitiativeTaskDependenciesRead,
  getInitiativeToolsRead,
  getInitiativeWatchersRead,
  getPortfolioRead,
} from '../../services/v8/planningPortfolioReadService.js';
import { asyncHandler } from '../../utils/asyncHandler.js';
import * as queryHelpers from '../../utils/queryHelpers.js';

const router = Router();

/** Stable contract id for clients parsing V8 planning continuity read responses. */
export const V8_PLANNING_READ_CONTRACT = 'planning_continuity_read_v1';

function planningMeta() {
  return { version: 'v8' as const, contract: V8_PLANNING_READ_CONTRACT };
}

const initiativeIdParamSchema = z.string().trim().min(1);

const firstParam = (value: unknown): string | undefined => {
  if (typeof value === 'string') return value;
  if (Array.isArray(value) && typeof value[0] === 'string') return value[0];
  return undefined;
};

const arrayParam = (value: unknown): string[] | undefined => {
  if (typeof value === 'string') return [value];
  if (Array.isArray(value)) return value.filter((item): item is string => typeof item === 'string');
  return undefined;
};

/**
 * GET /api/v8/planning/initiatives/portfolio
 * Governed portfolio read envelope for the operator-facing list surface.
 */
router.get(
  '/initiatives/portfolio',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const portfolio = await getPortfolioRead(organizationId, {
      projectId: firstParam(req.query.projectId),
      programId: firstParam(req.query.programId),
      statuses: arrayParam(req.query.statuses) ?? firstParam(req.query.statuses),
      status: arrayParam(req.query.status) ?? firstParam(req.query.status),
      priority: arrayParam(req.query.priority) ?? firstParam(req.query.priority),
      search: firstParam(req.query.search),
    });

    return res.json({
      data: portfolio,
      meta: planningMeta(),
    });
  })
);

/**
 * GET /api/v8/planning/initiatives/:initiativeId
 * Governed initiative detail read for full-open/document flows.
 */
router.get(
  '/initiatives/:initiativeId',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const headers = req.headers || {};
    const acceptLang =
      (headers['accept-language'] as string) || (headers['Accept-Language'] as string) || 'en';
    const requestedLang = acceptLang.split(',')[0].split('-')[0].toLowerCase() || 'en';
    const supportedLangs = ['pl', 'en', 'de', 'es', 'ar', 'ja'];
    const lang = supportedLangs.includes(requestedLang) ? requestedLang : 'en';

    const initiative = await getInitiativeDetailRead(parsed.data, organizationId, lang);
    if (!initiative) {
      return res.status(404).json({ error: 'Initiative not found' });
    }

    return res.json({
      data: { initiative },
      meta: planningMeta(),
    });
  })
);

/**
 * POST /api/v8/planning/initiatives/:initiativeId/fork
 * Duplicates an existing initiative into a brand-new record (new id, generated by the
 * create path), copying the source's definition fields with a "(Fork)" title suffix.
 * Org ownership is enforced explicitly: 404 when the source does not exist anywhere,
 * 403 when it exists but belongs to another organization.
 */
router.post(
  '/initiatives/:initiativeId/fork',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    // Load without org scope first so we can distinguish "missing" (404) from
    // "belongs to another org" (403).
    const source = await initiativeService.getInitiativeById(parsed.data);
    if (!source) {
      return res.status(404).json({
        data: null,
        error: 'Initiative not found',
        code: 'INITIATIVE_NOT_FOUND',
      });
    }
    if (source.organization_id !== organizationId) {
      return res.status(403).json({
        data: null,
        error: 'Forbidden',
        code: 'INITIATIVE_FORBIDDEN',
      });
    }

    // Copy definition fields onto a fresh create payload. The create path generates the
    // new id, created_at, and updated_at; id/org aliases and progress are intentionally
    // omitted. No "forked from" marker is set: the create path does not support one and
    // the schema exposes no forkedFrom column.
    // `title` and the legacy `name` column can diverge; prefer whichever holds
    // the real label so the fork doesn't end up titled "null (Fork)".
    const sourceLabel = source.title || (source as { name?: string }).name || 'Untitled';
    const forkPayload: CreateInitiativeData = {
      organization_id: organizationId,
      project_id: source.project_id,
      title: `${sourceLabel} (Fork)`,
      axis: source.axis,
      area: source.area,
      summary: source.summary,
      hypothesis: source.hypothesis,
      status: source.status,
      current_stage: source.current_stage,
      business_value: source.business_value,
      competencies_required: source.competencies_required,
      cost_capex: source.cost_capex,
      cost_opex: source.cost_opex,
      expected_roi: source.expected_roi,
      social_impact: source.social_impact,
      start_date: source.start_date,
      pilot_end_date: source.pilot_end_date,
      end_date: source.end_date,
      due_date: source.due_date,
      owner_business_id: source.owner_business_id,
      owner_execution_id: source.owner_execution_id,
      sponsor_id: source.sponsor_id,
      market_context: source.market_context,
    };

    const initiative = await initiativeService.createInitiative(forkPayload);

    return res.json({
      data: { initiative },
      meta: planningMeta(),
    });
  })
);

/**
 * GET /api/v8/planning/initiatives/:initiativeId/task-dependencies
 * Governed initiative document dependency read for the shared dependencies canvas.
 */
router.get(
  '/initiatives/:initiativeId/task-dependencies',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const dependencies = await getInitiativeTaskDependenciesRead(parsed.data, organizationId);
    return res.json({
      data: { dependencies },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/watchers',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const watchers = await getInitiativeWatchersRead(parsed.data, organizationId);
    return res.json({
      data: { watchers },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/stakeholders',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const stakeholders = await getInitiativeStakeholdersRead(parsed.data, organizationId);
    return res.json({
      data: { stakeholders },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/gate-roles',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const roles = await getInitiativeGateRolesRead(parsed.data, organizationId);
    if (!roles) {
      return res.status(404).json({ error: 'Initiative not found' });
    }

    return res.json({
      data: { roles },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/status-history',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const history = await getInitiativeStatusHistoryRead(parsed.data, organizationId);
    return res.json({
      data: { history },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/history',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const events = await getInitiativeHistoryRead(parsed.data, organizationId);
    return res.json({
      data: { events },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/comments',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const comments = await getInitiativeCommentsRead(parsed.data, organizationId);
    return res.json({
      data: { comments },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/gate-readiness-check',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId, userId, userRole } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const readiness = await getInitiativeGateReadinessRead(
      parsed.data,
      organizationId,
      userId,
      userRole
    );
    if (!readiness) {
      return res.status(404).json({ error: 'Initiative not found' });
    }

    return res.json({
      data: { readiness },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/resources',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const resources = await getInitiativeResourcesRead(parsed.data, organizationId);
    return res.json({
      data: { resources },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/kpis',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const kpis = await getInitiativeKpisRead(parsed.data, organizationId);
    if (!kpis) {
      return res.status(404).json({ error: 'Initiative not found' });
    }

    return res.json({
      data: { kpis },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/budget-items',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const budgetItems = await getInitiativeBudgetItemsRead(parsed.data, organizationId);
    return res.json({
      data: { budgetItems },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/tools',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const tools = await getInitiativeToolsRead(parsed.data, organizationId);
    return res.json({
      data: { tools },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/intangible-assets',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const intangibleAssets = await getInitiativeIntangibleAssetsRead(parsed.data, organizationId);
    return res.json({
      data: { intangibleAssets },
      meta: planningMeta(),
    });
  })
);

router.get(
  '/initiatives/:initiativeId/raid',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const limitRaw = firstParam(req.query.limit);
    const limit = limitRaw ? Number(limitRaw) : 50;
    const items = await getInitiativeRaidRead(parsed.data, organizationId, limit);
    return res.json({
      data: { items },
      meta: planningMeta(),
    });
  })
);

/**
 * GET /api/v8/planning/initiatives/:initiativeId/snapshot
 * Aggregates decomposition tree, WBS completeness, critical-path proxy, cross-initiative
 * dependencies, and decision chains for the V8 org context.
 */
router.get(
  '/initiatives/:initiativeId/snapshot',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }
    const initiativeId = parsed.data;

    const [
      decompositionTree,
      wbsCompleteness,
      criticalPath,
      crossInitiativeDependencies,
      decisionChains,
    ] = await Promise.all([
      getDecompositionTree(initiativeId, organizationId),
      validateWBSCompleteness(initiativeId, organizationId),
      getCriticalPath(initiativeId, organizationId),
      getCrossInitiativeDependencies(initiativeId, organizationId),
      getDecisionChainsByInitiative(initiativeId, organizationId),
    ]);

    return res.json({
      data: {
        initiativeId,
        decompositionTree,
        wbsCompleteness,
        criticalPath,
        crossInitiativeDependencies,
        decisionChains,
      },
      meta: planningMeta(),
    });
  })
);

/**
 * GET /api/v8/planning/pending-decisions
 * Decision chains in the org that still have at least one pending decision entry.
 */
router.get(
  '/pending-decisions',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId } = getV8Context(req);
    const pendingDecisionChains = await getPendingDecisions(organizationId);
    return res.json({
      data: { pendingDecisionChains },
      meta: planningMeta(),
    });
  })
);

/**
 * GET /api/v8/planning/initiatives/:initiativeId/handoff
 * P11-B bounded outbound envelope for P03 / P04 / P02 (read-only; does not mutate).
 */
router.get(
  '/initiatives/:initiativeId/handoff',
  asyncHandler(async (req: AuthRequest, res: Response) => {
    const { organizationId, userId } = getV8Context(req);
    const rawId = firstParam((req.params as { initiativeId?: string }).initiativeId);
    const parsed = initiativeIdParamSchema.safeParse(rawId);
    if (!parsed.success) {
      return res.status(400).json({
        error: 'Initiative id is required',
        code: 'PLANNING_INITIATIVE_ID_INVALID',
      });
    }

    const kindRaw = String(firstParam(req.query.kind) || 'execution').toLowerCase();
    const kindParse = z.enum(['execution', 'kpi', 'calendar']).safeParse(kindRaw);
    const kind = (kindParse.success ? kindParse.data : 'execution') as InitiativeHandoffKind;

    const row = await queryHelpers.queryOne(
      `SELECT * FROM initiatives WHERE id = ? AND organization_id = ?`,
      [parsed.data, organizationId]
    );
    if (!row) {
      return res.status(404).json({ error: 'Initiative not found' });
    }

    const handoff = buildInitiativeOutboundHandoffPayload({
      initiativeRow: row as Record<string, unknown>,
      organizationId,
      handoffBy: userId,
      kind,
    });

    return res.json({
      data: { handoff },
      meta: planningMeta(),
    });
  })
);

export default router;
